(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 145,
	height: 87,
	fps: 12,
	color: "#FFFFFF",
	manifest: []
};



// symbols:



// stage content:
(lib.tn_glovesCJS = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(1,1,1).p("ALYk+QABgCgCgMQgBgNgfgMQgggMgDAEAH7l8QgPAEAAAKQAAAEAIAKIAAAAQABAHAHAcQAIAgAAAgIAAAiQAAA6gCAcQABACgBACQAAABgBABAH0lgQAIAFAJAFQAdASAjAJQAlAKAsACQAHAAAIAAQAEAAAEAAQAngBAEgOAKAGGQACgBATgUQABgBAAgBQASgUAIgiQAIgkgCACQAaiJgoihIAAgDQgOg5AGgyQABgCABgCQAyiRAEgoAICiFQAAADgBADQghBWgXBHQgHAcgFAaQgDARgBAQQgCASAAAQQAAAvABAeQAAABAAABQABAiACAPQAIA6AgAAQAgAAAMg9QAKg0AFgVQAMAoACAUQABAJAAApQAAAGgDAtQgCADgCACIADADAKXDYQAAAegDAbQgBARgCARQgGAtgLAmAIqFsQgBAEAAAEQgBASgCAZQAAAAAAABQAAAZAigIQAhgHAXgkArHmaQARAHAQAFQAEACAFABIABABQBJAXAvgGIANgDIAggOQABgBAAAAQAAAAAAABQgYA/gCBEQgBAxARAuQAsByAUB8QARB2gJBJQgJAigWACQgBgBgBAAQgggDgCgkQAAAAAAgBQAFhIggg3QggBcAUBjQADAPAEAQQAAABAAACQgGA2glgNQgQgLgSglQgpgWgmhAQgFgLgEgLQgDgFgBgFQgdhMAPhBQAShPABgEIANiYQABh1gWiSgAqnmyQgxACARAWAoPmdQAfAJgGAJAp/EdQgKgmgEguQgCgUgBgUAp+EeQAKAkAMAZ");
	this.shape.setTransform(72.8,43.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E1E1E1").s().p("AIqGWIAAgBIAEgrIAAgIQAJgOAMgfQATgwAAgeQAAgVgKgcQgNghgRAAQgRAAgZBFQgaBFgRAAQgWAAgHhDIAAgCIgBhNQAAgQACgSIAFghQAMgwAUgpQAHgOAogyQAmguAAgEQgKg5AAgZQAAgrABgKQAFgeAXgfQAlAKArACIAPAAIAJAAIgJB9QgLArgLARIgaAhQgQAWAAAPQAAAJAWAxQAYA3ADAYQAZCRAAAQQAAARgFAnQgFAlgOAYIgCACIgUAVQALgmAFgtIAEgiQACgbABgeQgfC4hSAQgApCGBQgQgLgRglQgMgZgLgkIgBgBQgKgmgEguQgCgUAAgUQAAAUACAUQgSADgSgsIgBgEQgHg2AFhEIACgEQAKgdAPgdQAIgQgDgNQgqioAiiqIAAABQBJAXAwgGIgfB9QgPBYAxBKIBgCgQARB2gIBJQgKAigWACIgCgBQgYgJAAgUQAAgPANgiQAOgiAAgRQgnhzgiAAQgSAAgQAsQgQAtAvCzIAIAfIAAADQgFArgZAAQgGAAgIgCgAqJC/IAAAAg");
	this.shape_1.setTransform(72.4,44.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#CCCCCC").s().p("AImGUIAAAAQBTgQAei4QAAAegDAbIgDAiQgGAtgLAmQgXAkghAHIgOACQgUAAAAgTgAKpEmQAFgnAAgRQAAgQgYiRQgEgYgXg1QgWgzAAgJQAAgPAQgWIAaghQALgRAKgrIAJh9QAngBAEgOQgEAogyCRIgCAEQgGAyAOA5IAAADQAoChgaCJQACgCgIAkQgIAigSAUQAOgYAFglgAItEtQAAgpgBgJQgCgUgMgoQgFAVgKA0QgMA9ggAAQggAAgIg6QgCgPgBgiQAGBDAXAAQARAAAZhFQAahFAQAAQARAAANAhQAKAcAAAVQAAAegTAwQgMAfgIAOIADgzgAq3D5IgJgWIgEgKQgdhMAPhBIAThRIANiaQABh1gWiSIAhAMIAJADQghCqApCoQADANgIAQQgPAdgKAdIgBAEQgGBEAIA2IAAAEQASAsATgDQAEAuAKAmIABABQAKAkAMAZQgpgWgmhAgApCBUQAQgsATAAQAiAAAmBzQAAARgNAiQgOAiAAAPQAAAUAZAJQgggDgCgkIAAgBQAFhIggg3QggBcAUBjQgwizAQgtgAHJASQAXhHAhhWIABgCIAAgEQACgcAAg6IAAgiQAAgggIggIgIgjIAAAAIARAKQAdASAjAJQgWAfgFAeQgCAKAAArQAAAZAKA5QAAAEglAuQgoAygHAOQgUApgNAwQAFgaAHgcgAoghmQgyhKAPhYIAfh9IANgDIAggOIABAAQgYA/gCBEQgBAxARAuQAsByAUB8g");
	this.shape_2.setTransform(72.8,44.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#A6A6A6").s().p("AKfBBIgPAAIgCgmIAAgZQADgCAgALQAfAMABANIABANQgEAOgnACIgIAAgAHuAQQgIgKAAgEQAAgIAPgFIACALIAAAAIAEAOIAAABIAEALIgRgKgAoZgYIgBgBIAEgQIAAgBIABgBQAfAIgGAKIgBABIggAOgArNgoQgRgWAxgCIABAkIghgMg");
	this.shape_3.setTransform(73.4,6.6);

	this.addChild(this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(71.5,42.5,147.7,89.1);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;