(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 94,
	height: 81,
	fps: 12,
	color: "#FFFFFF",
	manifest: []
};



// symbols:



(lib.socks = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(1,1,1).p("Ak8AcQgHgpgGgvQAPAQAiAEQAhAFAcgFQAhgFAagIQAZgJAGgRIgCBWQAAAmACAjAk0BQQgBgDAAgCQgDgSgEgdQBdAZBcguACFAHQBjAUBigQ");
	this.shape.setTransform(53.2,12.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#666666").ss(1,1,1).p("AGBkjQABgFAAgGQAGgeAEglQh5AQhagWIADBMQAAACAAACQAOCkgOB5IgLCTQgLBhANBEQAJBBBJAJQBmgLBUg0IAEgCQAlgogthEQgkgugciCQgKh3AQjHgAhKjeQABApACAjQAFA+AWDMQAOAmgtAdQguAdgXARQgXARgmAtQgYAdgyAKQgzALhIgaQhIgbAIgjQAIgjAngQQAngRBDhHQBDhIgBh2QAAhxgGgl");
	this.shape_1.setTransform(47.7,43.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#D9D9D9").s().p("AEbFHQAAgQAVAAQAWAAAAARQAAAUgRAAQgaAAAAgVgAFuFAIgCgJQAAgEAJgKQALgMAMAAQAQAAABARQAAAHgIAJQgIAKgMAAQgOAAgFgIgAC8E8IgDgNQAAgSARAAQAUAAAJAbQAAAQgSAAQgTAAgGgMgAleFAIgCgJQAAgQASAAQARAAABAQQAAARgSAAQgMAAgEgIgAkoETQAAgGAKgKQANgNAQAAQAQAAAAAMQAAAKgGAFQgGAEgXAHIABAAQgHgBgOgIgAmWEVQgGgFAAgCQAAgFAOgKIAJgGQAGAAAMAHQgCAYgaABQgBAAgGgEgAFUDxIgCgIQAAgIAIgOQAIgRAKAAQAQAAAAARQAAALgGAMQgIAPgKAAQgMAAgEgIgADGDZQgGgJAAgFQAAgQASAAQAWAAAFAaQAAAQgSAAQgMAAgJgMgAjPDKQgCgDAAgFQAAgRARAAQAOAAACARQAAAQgQAAQgLAAgEgIgAk+CyQABgJAagaIAJAAIABgBIAAgEIAPAAIAAASQgZAZgRAAIgKgDgAiYChQgKgHAAgLQAAgKAagIQAagJAAAaQAAAYgeAAQgFAAgHgFgAEjCaIgBgJQAAgFAJgKQAKgLAKAAQAOAAACASQAAAHgIAJQgIAJgKAAQgOAAgEgIgAD5BpIgBgJQAAgQAPAAQAQAAABAQQAAAQgRAAQgKAAgEgHgAj7BJIAAgLQAZgUAEAAQAAgIAJAFQAIAFAAAMQAAAWgTAAQgRAAgKgFgAC8ApIgDgNQAAgTARAAQATAAAHAbQAAASgQAAQgSAAgGgNgAiTAHQgNgHAAgLQAAgPAhgCQgFAFAKAHQAMAHAAAFQgBATgQAAQgJAAgLgIgAETgyIgCgKIAFgMQAHgMAOAAQAPAAABASQAAAZgZAAQgLAAgEgJgAj2hJQAAgMAGgEIALgFIAEgDIADABIAHACQAKAEAAAMQAAAbgRAAQgYAAAAgWgADAh8IAAgOQAAgYASAAQARAAABARQAAAhgTAAQgOAAgDgMgAiiiYQgFgHAAgGQAAgLAKgIIACAAIAIAAIAUACIAAAPQgGACgIALQgHAKgGAAQgDAAgFgIgAEpi5IgBgLQAAgVASAAQARAAABAQQAAAagUAAQgLAAgEgKgAkhjuIgNhaQAPAQAiAEQAiAFAbgFQAigFAZgIQAZgIAGgSIgBBYQg8Aeg9AAQggAAghgJgAChkDIAAgEIgDhMQBaAWB4gQQgDAlgGAeIgBALQgsAHgtAAQg2AAg2gLg");
	this.shape_2.setTransform(50.4,39.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#EEEEEE").s().p("ACzEGQgNhEALhhIALiTQAOh5gOikQBjAVBigRQgQDHAKB5QAcCAAkAuQAtBEglAoIgEABQhUA1hmALQhJgJgJhBgAE2D7QAAAVAbAAQAQAAAAgUQAAgRgVAAQgWAAAAAQgAGQDdQgJAKAAAEIADAJQAFAIAOAAQALAAAJgKQAHgJAAgHQgBgRgPAAQgNAAgLAMgADVDjIADANQAGAMATAAQASAAAAgQQgJgbgVAAQgQAAAAASgAF1CHQgHAOAAAIIABAIQAEAIAMAAQALAAAIgPQAGgMAAgLQAAgRgRAAQgJAAgJARgADcB/QAAAFAGAJQAIAMANAAQASAAAAgQQgGgagVAAQgSAAAAAQgAFGA2QgJAKAAAFIACAJQAEAIAOAAQAJAAAJgJQAHgJAAgHQgBgSgPAAQgJAAgLALgAETAUIACAJQADAHALAAQAQAAAAgQQAAgQgQAAQgQAAAAAQgADVguIADANQAGANARAAQARAAAAgSQgIgbgTAAQgQAAAAATgAEyiUIgFAMIABAKQAEAJALAAQAaAAAAgZQgCgSgOAAQgOAAgHAMgADcjWIAAAOQACAMAOAAQAUAAAAghQgCgRgQAAQgSAAAAAYgAFDkQIACALQADAKAMAAQATAAAAgaQAAgQgSAAQgSAAAAAVgAmSEXQhIgbAIgjQAIgjAngRQAngQBDhHQBDhIgBh2QAAhxgGglIgBgFIgHgvQBdAZBcguIACBJQABApACAjQAFA+AWDMQAOAmgtAdQguAdgXARQgXARgmAtQgYAdgyAKQgPADgQAAQgpAAgzgSgAlEDrIACAJQAEAIAMAAQASAAAAgRQgBgQgRAAQgSAAAAAQgAkCC3QgKAKAAAGQAOAIAGABIAAAAQAXgHAGgEQAGgFAAgKQAAgMgQAAQgQAAgNANgAlyC0QgOAJAAAFQAAACAGAFQAFAEACAAQAZgBACgYQgLgHgGAAgAi1B2QAAAFABADQAEAIALAAQAQAAAAgQQgBgRgPAAQgQAAAAARgAkjBmIAKADQASAAAZgZIAAgSIgPAAIgBAEIAAABIgJAAQgaAagCAJgAhsAxQgbAIAAAKQAAALAKAHQAHAFAGAAQAeAAAAgYQAAgTgPAAQgFAAgGACgAjDggQgEAAgYAUIAAALQAKADARAAQATAAAAgUQAAgMgJgFIgFgCQgEAAAAAFgAiEhXQAAAMAMAIQALAIAJAAQARAAABgVQAAgFgNgHQgKgHAFgFQggACAAAPgAjJiqIgLAFQgGAEAAAMQAAAWAXAAQASAAAAgbQAAgMgKgEIgIgCIgCgBIgEADgAiMjxQAAAGAFAHQAFAIAEAAQAGAAAHgKQAHgLAGgCIAAgPIgUgCIgHAAIgDAAQgKAIAAALg");
	this.shape_3.setTransform(47.7,47.3);

	this.addChild(this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-0.1,3.9,95.7,78.1);


// stage content:
(lib.tn_socksCJS = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.socks();
	this.instance.setTransform(47.3,40.5,1,1.001,0,0,0,47.3,40.5);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(47.4,44.9,94.7,77.1);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;