(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 93,
	height: 115,
	fps: 12,
	color: "#FFFFFF",
	manifest: []
};



// symbols:



// stage content:
(lib.tn_sthortsCJS = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(1,1,1).p("AGIFyQAAAEABAEQAAABAAABQAEAZAIAhQACAHACAGQALAsAAAEQAAAOgYANQgmARgaALQgYALhhAEQhPADgLgCQg/ACgfgKQgHgCgJgEAFMo1QgJgIgMAFQgPAGhAAVQg/AVhNANQhMAOikAAQiDAAgegEQhTgKgbgr");
	this.shape.setTransform(48.6,57);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#666666").ss(1,1,1).p("AFvoAQABgCAAgBQAAgCAAgDQAAgZgDgOQgEgQgCABAGSjuQgEgqgFgrQgLhdgPhgAGSjuQAYD7gGDsQAAAfgCAfQgBAZACAZAgBmzQBFgGBSgMQA7gJAqgJQAZgEATgFQBDgRAFgPAGJlDQgPgBgdgZQgIgHgRgqQgdg9AAgVAD7nXQAZAbARAuQAFAMAVBGQAQA0BDAaAhMnLQAEgHANgFQANgGAIAAQAaAAALAqAgwmwQAGAJAEAOQAFATAHAoQAPA1AQAAQAMAAAVgPQgFgFgEgFQgXgfgDgpQgCgYgCgRAh4mtQAAgUABgFQADgRAPAAQAEAAADAAQABABACAAQAJAEAGAHQAGAGADAIQAAABAAABQgJABgHAMQARgBASgBQgHgLgLgBQgBgBAAAAAlGm4QAXAGAYACQAaADB/AAQADAAADAAQgBALAAAPQAAAmgQAZQgVAWgJALQAAAOAcAAQAdAAAJhHQAGgvAMgTAmJovIgEAAQgHACgCAKQgBAGgDAWQgHAagBAIQAAABAAAAQAAAFAGAFQABABACABQAXAMAXAJQATAGASAFAmhHoQAGhtgRkMQgIiBACiOQAAgBAAgBQABgzACgzQAEhsAJhxAlrnDQgTB3gGATQgOAugdADAmyiiIACACQAfAAAZhCQAYhAAaiWAgVAcQABgGAAgFQAAgFAAgEQgIhFgag+QgWg1AAhEAAOHWQAAg7gDgqQgFhjgbjyQgSE4AIBIQADAeADAWQAEAhAEAPQgEAsg+ALQg+ALiLgEQiKgDgEgaQgDgbAKgZQABgDABgCIAcAAQApALAgAKQARAEAoAAQAzAAB0gOQA9gGAGgdAAOHWQAIADAqAQQAhANAxAAQAVAABYgOQATgGBAAAQAkAAAfgPQAcgNACgMAAlIiQgWgOgCguQABgIAAgI");
	this.shape_1.setTransform(46,57.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#D0D0D0").s().p("AhmBOIAegiQAQgYAAgkIABgbQAAgTABgGQADgRAPAAIAHABIADABQAJAEAGAGQAEgGALgGQANgGAIAAQAaAAALArQAEARACAYQADAmAYAfIAIALQgVAOgMAAQgRAAgQg1QgHglgFgTQgEgOgGgJQgHgLgJgCIgBAAIAAABQgJACgHALQgMAUgGAsQgIBIgdAAQgdAAAAgOgAgCg6QgDgJgGgGQAGAGADAJg");
	this.shape_2.setTransform(39.5,19.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#E6E6E6").s().p("Ak8H9IhJgVIgcAAQAGhtgRkMQgIiBACiOIACAAQAfAAAZhCQAYhAAaiWQAXAGAYACQAaADB/AAIAGAAIgBAaQAAAmgQAZIgeAhQAAAOAcAAQAdAAAJhHQAGgvAMgTIAjgCQAGAJAEAOQAFATAHAoQAPA1AQAAQAMAAAVgPIgJgKQgXgfgDgpQgCgYgCgRQBFgGBSgMQA7gJAqgJQAZAbARAuQAFAMAVBGQAQA0BDAaQAYD7gGDsIgCA+QgBAZACAZIAAAIIABACQADAZAJAhIADANQgCAMgcANQgfAPgkAAQhAAAgTAGQhYAOgVAAQgxAAghgNIgygSQAAg8gDgqQgFhjgbjyIABgLIAAgJQgIhFgag+QgWg1AAhEQAABEAWA1QAaA+AIBFIAAAJIgBALQgSE4AIBIIAGA0QgGAdg9AGQh0AOgzAAQgoAAgRgEgAminlIAAABQAAAFAGAFIADACQAXAMAXAJQgTB3gGATQgOAugdADQAEhsAJhxgAFdldQgIgHgRgqQgdg9AAgVQBDgRAFgPQAPBgALBdQgPgBgdgZg");
	this.shape_3.setTransform(46,57.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#D9D9D9").s().p("AkhJBQiLgDgEgbQgDgaAKgZIACgGIAcAAIBJAWQASAEAoAAQAyAAB0gPQA9gFAGgeQAEAhAEAPQgEAtg+AKQgvAJhdAAIg8gBgACNI0Qg/ABgegJQgHgCgJgFQgXgOgCgvIABgPIAyATQAiANAxAAQAUAABYgPQATgFBAAAQAkgBAfgPQAcgNACgMQAMAsAAAFQAAAOgYANIhAAcQgYALhhAEIhHABIgUAAgAm4igIADhmQAdgCAOguQAGgTATh4QATAHASAEQgaCXgXA/QgaBDgfAAgAE5k5QgVhHgFgLQgRgvgYgaIArgKQABAWAcA8QARArAIAHQAdAZAPABIAJBVQhDgagQg0gAiEmrQh/AAgagCQgYgDgXgGQgSgEgTgHQgXgIgXgMIgDgCQgGgFAAgFIAAgCQABgHAHgbIAEgcQACgKAHgCIAFABQAbAqBSALQAfADCDAAQCkAABMgNQBMgOBAgVQBAgVAOgGQANgFAJAIQADAAADAPQADAOAAAaIAAAFIgBACQgFAQhDAQIgrAKQgrAIg7AJQhSAMhFAGQgLgqgaAAQgIAAgNAGQgNAGgEAGQgGgGgJgEIgDgCIgHAAQgPAAgDARQgBAGAAATIgGAAgAhJm5IABgBQALACAHALIgjABQAHgLAJgCg");
	this.shape_4.setTransform(46.6,57.6);

	this.addChild(this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(47.9,56.3,90.4,117.7);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;