<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<!-- xxinclude('lib/lgz/dom/head.html') -->
</head>
<body ontouchstart=""  id="lgzBody" style="font-family: sans-serif" class="lgzMin" >
<script type="text/javascript" src="../lib/lgz/js/kconf.js?"></script>
<!-- build:js1 loader.js -->
@@include('rsc/dom/tail.html')
<!-- endbuild -->
</body>
</html>
