(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 200,
	height: 200,
	fps: 12,
	color: "#FFFFFF",
	manifest: []
};



// symbols:



(lib.Symbol13 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#14395A").s().p("AmMYeIgDAAIgEgOIgHgVIgTAWIgDgBIgYgIQgSgHgIgGIgCgDIACgDIAagoQAYgiAbgaQgRgIgNgLIgEgDIADgDQAIgPA9hZQA+hYA+g5QgMgKgDgQIAAgBQAAgGAEgEQALgLAGgCIgDhFIgGiIIgFhxQgFAEgHAEQgQAIgMAAQgLgCgGgEIgHgIQgHAJgcgGQgOgMgIgXQgHgYgBgKIgBgFQgYAGgkgxQgWgkAHgWQAJgRAGgBIAOgHQgghAgghKQgghKgKgqQgCgCAJgOIgEgDQgrgqABgTIAAgGQAHgIAUgBQgJgPgFgVQAAgOAJgJQAKgHAaAAQAaAAAcAEQATgzAYg6QAYg6APgeQAUgnAYgRQgSgNgTgJIgEgCIABgEQACgGATgkQASglASgTQAHgGAWgEQg8g9g/hmQg/hmgkiRQh3gvARhFQAIgfAbgSQgMhNAAhXQAChDARgxIgSgPIgPgLIAAgDIAEgZQAEgTAKgIIAEgCIAOAUQANASAHAIQAKgcA7hKQA7hLB+g7QBWgjBLgIQBKgJA0gDQA8gFAmgOQBvgxA7grQA8grAZgPIABgBIABAAQAKgFA1AmQA0AmgMCCQgOBEhHAzIgEACQATAdgPCMIgEAfQAIATgDAVIgEACQArAYAXAXQAYAXADAFIAAAAIABACIAAABQACCYgVA8QgWA8gFAAIgCABIgCABQgRABgPgCIAJAiQAXBOALAsQAMAsgNAuQgTBFhYA6QhYA6iSAeIgyAKIgDABQAPARAAAOQgBAPgHAaQgHAagDAVIgDAVIAGAMIAPAiQATAuAYA0QAYA0AaAiQAYgRAVAJQAYAbgDAaQAVgFAWAIQAGAEAAAGQABAHgHATIBLAAQAtAAAigCIA6g4QAsgqAXgRQAXgKAgAMQAgAMAIAGIgbAzQgfAKgGAPQADALAQAVQAQAUAJATQAKATgKALQgTALgggNQghgNgNgJQgQARhCgCIhaAKQhMAIg8ADIgPAQQgZAYgWgCQAcB4gZBLIAAABQgDBIgNgBQgHAigpAfQAXBJAeBoQAfBoANA+QAKA2AEBKQAEBKAAA6IABA9IgBAEIgBAAQAUAIAaAHQAZAIARACQADgJAMgOQANgOAYgDQAagCARARQAUAVgCAiIAAADIgCABQgEAEg6AUQg7AVhQAGIgDAAIgLgRIgCAUIgDABQgFAEg0gCIgEAAIAAgFIABgeQACgdAHgmQgYgBgVgOIgCgCIABgDIAUitQALhZAAgVIAAgBIgFgDQgOgFgEgOIAAgBQAAgMAYgOQgYhNgihgQghhfgPgeQgXAIhZgDIgMBfIgSCeQgJBVgEA4IAAABIAAABIgjA8IhDB3QgkBBgPAgIgCADIgEAAQgEAAgfgIQAEAQAKAJIAWAEIAXADQAFgEAUgHQAVgGAYAHQAVAIAJAWQAJAegPAdIgBACIgDABQgBABgxAHQggAEgvAAIg4gBgAmKFXQgOAFgUACQAKAyAaBNIAOiSQgFAJgLADgAl8EdIAFAMIABgNIAAgCIgGADg");
	this.shape.setTransform(61.3,156.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-0.2,0,123.1,313.5);


(lib.Symbol11 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#14395A").s().p("ADpVzQhTgPgGgDQgmgQAFgUQgGgUAmgTIgBgHQAAggAQgeQAQgeAHgIIgCg1IgKABQicAKh6glQgBAlgGAfQAHAHAMATQAMATADAVIAAAJQAbAPACAVQACAVgCACQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQiVBKh5ADQh4ADhJgXQhIgYgDgEQgZgNgHgbQgFgoATgmQAUgmAFgEQAyhABVgLQBNgHAwAnQAWATAQAYQAggFAigJQAigJAKgPIgCg4QhxgngGgGQgXgMABg2QABg2AKg5QgRgJgMgLIgLgIQgHgHAAgPQACgwAWg2QgSgIgEgNIgCgHQACgVAHgEQARgjAYhAQAYhAASg2IAUg7QANg2ACg6QABg7gEgqIgCgFQgfhMAlhOQAkhMAjgoQgDgVgBgRIgvgMIglgGQhggYhMgmQhigug6gmQg5gmgCgEQgmgtAEhLQAEhLAThAQAQg9ACgEQAPgiAJgoIgCgBIgDgCIAIgZQAKgtADglQAEhggDgKQAEgeAGgaIgKAJQgFABgJgVQgIgUA1gwQAuh5A1gtQA2gtAMAAQAHgIBHgkQBIgkB6gTQB4gTChAqQBIAUBOAnQACAAAmAYQAlAYAuAzQAXAYAUAeIgCgaQgBgCAIgIQANgIAdAHIADABIABAeIACBHQANAKAOANIAQhDIAIgeIADgBQAlgDAEATIAAABIgKAjIgZBQQAoAuAXA/QAXA/gSBPQgBAFgeA4QgdA3g4A1IACBXIABAkIgbgLIgGhaQgxAjhAgGQgvA/hDAoQgUBFgnA/QgmA/gqAyQAUA1gOAwIACABIAFAFQArAgAaApIAYAgQA+BIAuB4QAdBJALBWIgKCUQgIBqgQBeQgFCxgKB6IABABIABAEIgLBqIgCAFIgCACQgkAOgkAIIgPADQABAdAAAPQBCAVAxAAIAMgRQAxgwA+ADQA/ADAwAnQBGBDgHAtQgGAtgHACIgBACQhnA7h0AHQgkACghAAQhKAAg6gKg");
	this.shape.setTransform(66.9,140.4);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,-0.1,133.9,281.1);


(lib.Symbol10 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#14395A").s().p("AgcAmQgEgmANgWQAOgVADgBIACgDIACACQAeAagCAJIAAADIgDACQgMAHgPASIgUAUIgHAIg");
	this.shape.setTransform(3,4.9);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-0.1,0,6.1,9.7);


(lib.Symbol9 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#14395A").s().p("AhtUbIgDAAIgBgEQgCgEACgcIgEAAIgEgVIgMASIgCABQgEAChCAMQhCAMhggIIgEAAIgBgEQgBgDABgWQABgXASgYQAcgjBDAAQBpADAaAGIAIgcIgLgDIgEgCIABgDIAEhCIAIh9QAEhBAAgTQABgYAJhHIARh6Qh9gZgoguQhBgvAHgLQgHgGAGhrQgLABgPgEQAFAcgIAbIgBAAIAAABQgDAKgHAHQAUAUAGASIAAABQAFALgaAmQgSASgigCQgIADgSgfQgIAIgGAEQgZAOgXgMIgEgDIgCgBIgCgCIgBgBIgCgCIgBAAIgCgDQgHgOAFgRIACgMIgFAAQgKAJAAAgQABAgAMBJQAXB8AODHQAFCagMBCQgMBBgDAAIgBACIgBAAIgUANQgPAJgMADQghAFgegYIgCgCIABgDQAGgGAdh+QAdh/gJjDQgPiXgThMQgUhKALgcQAEgLAJgJQgggvAAgVQAGgTAwgnQAwgnAYgIQAUgDAWAGQACgXAMgQQAQgTAbgCQAYgBAbAQQAwhLAbhYQAahXAPhJQALgxAKgkQgEgIAAgEQADgSAGgPQgTgMgHgWQAFgYATgkQhdgnhlhGQhmhFhGhUQhHhUAAhSQAGhLApg3QAog2AzgnIADgJQgGgGgFgHQgFgGADgHQAEgFAJABQAMACAJgHQAJgKgHgeQgBgOAHgFQAXgNAsALQAQg9AfgtQAfgtAjgCQASAAAPAOQA2g0BHglQBHglBUABQALgIBzAtQB0AsB3C8QAVgEBKAHQBKAIA/A7IgIAlQgIAhgMAVQAHAQANAnQANAmACAdQAAATgMAHQgMAEgPgKIgXgQQgDAVgNArQgNArgeAWIgCABQgKCJheBJQhMA5hjAoQASAegBBBIAAAAIAAABQAAACgJALQAmAfAjAzQA5BdAPCSQAPCUgFB7QgFB7gDAQIAAACIgCABQgBAEgcASQgXAqhtAtIgSBkQgLBCgFA7QANAIAFANIAAABQAAAEgDADQgIAHgIgBIAAADIAAACIAAACIABAIIAAALIAAAAIAIBnQAFA/AJAyIABALIACAHIAAAAIACAHIABAFIgFABIgIACQATAbAEBOIAAAEIgEABIgZAFQgYADgeABIgEAAIgEgVIgMASIgCABQgDAChCAMQgoAHgyAAQghAAgmgDgACBS1IAIgeIgWgFIgEgBIAAgDIAAgYIABhYIAAgBIAAgQIAAgCIAAgQIAAgDIAAgnIAAgCIAAgSIABgFIAAgPIAAgGIAAgPIAAgGIAAgPIABgFIAAgVIAAAAIAAgVIABgFIAAgPIAAgHIABgNIAAgIIAAgMIABgIIAAgMIAAgHIABgSIAAgBIABgRIAAgGIABgMIAAgGIABgKIAAgHIABgJIAAgGIABgHQhGAKhGgGQgIAngLA6QgLA6gDAkQAMgBAIAGIADAHQgEAPgOAHIAHBgQAGBKAAA9QAAAWgBAOIgBAEIgEAAIgKABQAGAOAGAWQAQgDAUAAQBoADAZAGg");
	this.shape.setTransform(63.2,131);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,-0.1,126.5,262.2);


(lib.Symbol8 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#14395A").s().p("ACzPaQhZgWgqgVQgqgWgBgCIgCgCIAAgCQgBgGAAgpQAAgoAMgoQgPgEgGgEIgCgDQAJAlAAAmIgBAsIgBACIgBABQgCADgpATQgpAUhXAVQhXARgsgHQgsgIgBgDIgBAAIAAAAQgdgbgBg2QAAgzAjgcQAXgRAagHQACgEADABIACABQAlgIAdgBQAXgBAJgDIAzgaQgNgGgGgMQgCgEAAgFQAAgFACgGQAHgMAOgHIgHAAIgCgBQgQAYgWADQgcABgRgXQgDgGAAgHQAAgQAPgVQgSgOgIg3QgOgJgMgKIgBgCIAAgCIAIg1QAHguANhEQgBgaAAgcQgBg+ALg4QgRgIgOgOIgBgCIAAgCQgBgFAQgwQAQgwArgrQiAgghLg7QhKg7gDgIIAAgBQgHgTABgzQAAgsABgbQgKAQgFAgQgEAhAAAcQAAABAAABQgBAAAAABQAAAAgBABQAAAAgBAAQAAABgBAAQgBAAAAAAQgBAAAAAAQgBAAgBgBQhehKgEhCQgEhCAHgFQBPkXCEiQQCDiQBbgjQBagmA+ANQA8AMAkAdQAjAdAKANQA0gpBkAUQBjAUBeA9QBvBnAOBZQAOBYgHAGIgWgUQgTgSgLgHQAKAlAAApQgICQg5B2QgGAmgPAmQACAKg0BNQg0BNiKAzIAMBLQAHAtADAcIAAACIgBABQAAAFgbAUQAHAwAPBPIALAyQAFASAEALQAQAfAVAWQAcAbABAbQgFAcgZAlQgaAlgZAGQgKABgKgDIgCABQg+ABgYgWIgCgDIgcAGIAABMQAjAFARAbQACAGAAAFQAAAFgCAGQgHAKgNAFIAzAdQAIADAXACQA3gCA9AoQAfAdABA0QgCA4gaAcIgBAAIAAABQgCADgqAIQgOADgTAAQgmAAg5gLgAgNLRIAVAUIAMgKQgOgCgJgKIgKACgAgiKgQAcAGANAOQAQgKAWgEQABgogBgcQgoAEgmgBIgBA7gAhuKdIAEgBIAAgCIgEADg");
	this.shape.setTransform(60.4,99.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-0.1,0,121.2,199.6);


(lib.Symbol7 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#14395A").s().p("AEFWhQhXgGgfgUQgegUABgEIAAgBIgBAAIgEgUQgDgPAFgKQAOgNASAEIAAgEQgBgTAKgjQAKgjAigiIgRgvQhmAZhuAFIgGARQAjAiAIAjQAKAjgBATIAAAEQASgEANANQAFAKgCAPIgFAUIAAAAIAAABQABAEgfAUQgcAUhXAGQhgAEhngRQhogQg0gkIgCgBIAAgDIAGgmIABgEQAGgeAQgjQAPgjAdgZQAjgdAwAFQA2AIAcAhQAygdA1gDQhmgHhYgtIgDgCIABgDIAMiSQAMiGAQiWQghABgjgBQgigCgVgJQg0gegOg6QgCgYARgNQAOgJAKABQAHABALgCQALgDAPgWQg9hOgahHQgYgLgBgCIgDgBIABgDQADggAchRQAdhRAmhTQAmhUAjgmIAPgPQhZAGgvgkQgBgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAgBABAAQAAgBAAAAQABAAABgBIARgMQAPgLAFgVQAFgZgbgdIgagYQg4gxhShkQhShkgsiTQgsiTA5i+QBCi5BRhKQBRhLBCgKQBBgKARAGQAKgNA4grQA3grBdghQBegiCLAXQCNAWCsCPQAAABABAAQAAABAAAAQAAABAAAAQABABAAAAIAAABQgBADgDABIgcAJQAbATAyBTQAyBUAHCZQAAApgGAvQgYCbg6CGQg6CGgxBYQgWAngSAcQgTAdgBALQAEAgAdAQQAdAPAEAAQADABAAADIAAABQABADgIATQgIATgWAMIAvAtIATgDQAOgMAWgJIALgFIAEgCIAFgBQAjgLAWAFQAJADAFAFQAJABAJACIABAAQgFgfAfgmQAcgYAzAMIAIABIgFAGQgBABgKARQgKARgBAXIABAJQAFgTAhgUIABAAIAAgBIAFAJQgJgEgRBBQBWAqAQCEQAGA/gPBGQgQBGgpA7IABABQg+BhhLAaQhKAZgqgEQASB2AMB/QANCAABBtIgBAqIAAADIgDABIg+AbQg8AZhfAcIAHAqQAPgBAqAGQAqAGAjAWQAcghA2gIQAvgFAkAdQAdAZAPAjQAQAjAGAeIAAAEQAHAhgBAFIABADIgDABQgzAkhoAQQhUAOhPAAIgkgBg");
	this.shape.setTransform(73.3,144.2);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-0.3,0,147.2,288.6);


(lib.boy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// boy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#602B16").s().p("AAAAnQgHgRgFgKQgGgIgFgBIgFAAQADgKAJgMIAKgLIgNgDIgGAAQAKgLAJgFIAKgGQANgFABAOIACAPQgBAVAEAKQAEAKABACIgJgFIgEgDQAFAFAFAHIAEAHQgPADgFAPQgFAPABACIgFgTgAAcAMIAAAAIAAAAg");
	this.shape.setTransform(-3.9,-3.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#CCA28B").s().p("AAFAJQgEgBgEgFQgFgDgBgGIAGgDIgCADQgCABAFAGQACAEAEAAIAGACQAAABAAAAQAAABAAAAQAAAAgBAAQAAABgBAAIgDgBg");
	this.shape_1.setTransform(8.9,9.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#CCA28B").s().p("AAAgBIgCgBQACgCACAEQABADgBAAQABgDgDgBg");
	this.shape_2.setTransform(14.4,11.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#CCA28B").s().p("AgBAAQADgDABACIgDABQgBAAAAADQgCgBACgCg");
	this.shape_3.setTransform(4.3,10.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#CCA28B").s().p("AgEgBIgPABQATgIAKAGQAKAFAAACQgNgHgLABg");
	this.shape_4.setTransform(9.3,14.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AAAANQgYgDgMgKQgNgIAAgCIAAgCQABAAAAAAQAAAAAAAAQAAAAABAAQAAAAAAABIAMAKQAMAHAXADQAVABANgHQAOgEAAgCIACAAQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAAAAAQgBABgNAGQgMAHgUAAIgEAAg");
	this.shape_5.setTransform(9.3,11.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgQAHIgCgHIAAAAQAHgFAJABQABgGABgEIAEgEQAAAAAAgBQABAAAAAAQAAAAAAAAQABABAAAAIAAACIgEADQgCAEAAAGQAHABAGACQAGACAAABQAAAAAAAAQAAAAAAAAQgBAAAAAAQAAAAAAAAIgOgDQgLgEgIAEQgBABADAGQADAFAKAFIAAABIAAABIAAABQgNgGgDgHg");
	this.shape_6.setTransform(9.6,8.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgDAAQABgCACAAQAEAAAAACQgBADgDAAQgDAAAAgDg");
	this.shape_7.setTransform(1.8,4.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgHAAQABgHAHAAQAHACABAFQgCAIgHAAQgHgCAAgGg");
	this.shape_8.setTransform(2,4.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgDAAQABgCACAAQAEAAAAACQgBADgDAAQgDAAAAgDg");
	this.shape_9.setTransform(13.6,4.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgIAAQACgHAHAAQAHACAAAFQgBAIgHAAQgHgCgBgGg");
	this.shape_10.setTransform(13.5,4.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgSAFQgBgLAbgMIAMASIgkATQgCgBAAgNg");
	this.shape_11.setTransform(5.4,-3.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgSgDIAQgRQAYARgDALQgDAMgCABg");
	this.shape_12.setTransform(18.6,-2.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#602B16").s().p("ACaBcIAAAAIAAAAgACPBOQgKgNgTgRQgSgQgWgMQABABAKASQAKASgBAZIgIgTQgIgSgVgVQgWgWgmgKQADABALAQQAOAUgCAiIgMgRQgLgQgYgRQgagPgpgGQgBABgBAKQAAAMAMAQIgZgOQgXgNgQgRQgQgTARgTQgBgBANgLQANgMAfgJQAfgKA2AEIgVABQgVACgRAHIAlACQAiACAtANQAuANAjAgIgUgFQgTgDgbABIATARQASAOAUAaQAUAbAIAhIgLgOg");
	this.shape_13.setTransform(15.8,-7.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("ABXAjIgagbIgSgQQABAGAAADQgDASgCADIgBACIgCgCQgXgSgfgRIgvgcQAKARAMAPIAMAPIADADIgEgBQgjgIgXgQQgXgRgBgCQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAAAQABgBAAAAQAAAAAAAAQABAAAAAAQAAAAAAABQABABAVAQQAWAQAhAIIgQgUIgTgdIgDgEIAFADIAUALIAsAaQAXAOASANQACgGACgMQABgGgDgIIACgCIAPAPIAcAcIAQARQAGgFAGgkIAAgEIACAAIABAAQgCAZgGALQgFAMgBAAIgBABIgNgOg");
	this.shape_14.setTransform(15.3,-0.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#3A1704").s().p("ABkA1IgVgVIgagcIgNgLQAEAJgDAMIgEAOQgRgOgXgOQgZgPgUgLIgVgMQALASAMARIAOAQQgjgJgXgPQgWgQgBgCQAngYAoABQAmACAiAPQAiAOAUAOIAWAOQgDAZgFALIgGAKIAAAAg");
	this.shape_15.setTransform(15.2,-1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgHAEQgBgBAEgDQADgDAIgCIABABQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAQgHABgCACIgDAEQAAAAAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgBgCg");
	this.shape_16.setTransform(-4.7,8.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AANAFQAAgCgHgDQgGgDgMADQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAAAAAgBQAAAAABAAQANgEAIAFQAHADAAABQAAAAAAABQAAAAAAAAQAAAAAAAAQAAAAAAABIgBAAIgBAAg");
	this.shape_17.setTransform(-4.5,8.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AAEAGIgBgEQgCgCgGgDQgBgBAAAAQAAAAAAAAQAAAAAAAAQAAgBAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAAAAAQAIAEACACIACAGIgBABQgBAAAAAAQAAAAAAAAQAAgBgBAAQAAAAAAAAg");
	this.shape_18.setTransform(24.5,11.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgOADQgBAAAAAAQAAgBAAAAQAAAAAAAAQAAgBABAAIAIgCQAHgEAOAFQAAAAABAAQAAABAAAAQAAAAAAAAQAAAAAAABIgCAAQgNgEgFACQgIACAAABIgBAAIgBAAg");
	this.shape_19.setTransform(24.3,10.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#EFEFEF").s().p("AgaAqQgHgDgFgGIACACQAPAFAQgFQATgHAKgVQAHgNgCgOQgCgOgJgKQAPAIAFARQAEARgIAQQgLAVgVAIQgFACgHAAQgIAAgIgDg");
	this.shape_20.setTransform(6,3.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#EFEFEF").s().p("AgbAsQAGABAGgBQAQgFAJgQQAIgQgFgTQgGgWgSgLIgDgCQAJABAGAEQATAMAHAWQAFATgJAQQgIAQgQAEIgJABQgJAAgIgEg");
	this.shape_21.setTransform(18.3,4.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgUAsQgRgHgFgSQgFgRAIgRQALgVAVgIQAOgFAOAGQARAHAFASQAFARgIARQgLAVgVAIQgHACgFAAQgIAAgIgDg");
	this.shape_22.setTransform(5.4,3.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgVAvQgSgIgGgTQgFgSAJgSQALgWAWgIQAPgGAPAHQASAIAFASQAGASgJATQgLAWgWAHQgIADgGAAQgIAAgIgDg");
	this.shape_23.setTransform(5.5,3.2);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgPArQgUgMgGgWQgFgTAIgQQAJgQARgFQAOgDAOAIQATAMAHAWQAFATgIAQQgJAQgRAEIgJABQgJAAgKgFg");
	this.shape_24.setTransform(16.7,4.3);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AgRAtQgUgMgHgYQgFgTAJgRQAJgRATgFQAOgDAQAIQAUAMAHAYQAFAUgJARQgJARgTAEIgJABQgKAAgLgGg");
	this.shape_25.setTransform(16.7,4.2);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#D3B09C").s().p("AgGBHQATgYABgbQABgagSgUIgIgLQALgmgYgbQAYAKAQALQARALACADIAAADQgDAbgJALQgIAMgBAAIgBAAIABABQARATgCAVIAAABIgJAIQAAAAAAABQAAAAAAAAQAAAAAAAAQABABAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAQABAAAAAAIAHgHIABgBQAGgFAIgCQAHgDAIAEQAMAIgHAQQgEAKgOAGQgNAGgXgGIgCABQAAAAAAAAQAAAAAAABQAAAAABAAQAAAAAAAAQgOAQgWAJQgWAJgTADQAogIAVgYg");
	this.shape_26.setTransform(20,6.5);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#E8C8B3").s().p("AgLB7QgFgBgDgDQgCgGABgCIABgBIgBAAQgLgKgYgLIghgSQgRgKgMgMIACAAIABgCIgBgBQgYACgMgJQgMgIgDgLQgDgRANgDQAPgDAJAJQAJAKABACIACABQAAgBAAAAQAAAAAAAAQAAAAAAAAQAAgBAAAAIgEgGQgDgFgGgFQAAgWAKgRQALgQAKgJIALgJIABgBIgBgBQgNgQgDgNQgEgOABgFQAUARASAFQARAGACAAIABAAQAsgYAnAIQAqAIAdARQAdARAFAFIgBACQgDAbgIAMQgJALgBAAIgBABIABABQARASgCAWIAAABIgIAIQgBAAAAAAQAAAAAAABQAAAAAAAAQAAAAABABIACgBIAHgHIABgBQAGgEAIgDQAHgCAIAEQAMAHgHARQgEAKgOAGQgNAFgXgFQgBgBAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAIABACQgSARgZAKQgZAJgTADIgVADIgBAAIAAABQAAACgDAHQgCABgEAAIgDAAg");
	this.shape_27.setTransform(10,6.2);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgVB7QgCgCAAgFIAAgEQgLgJgXgKQgQgIgSgKQgRgLgNgNQgWAAgLgJQgLgJgDgMQgEgTAOgDQANgDAJAEQACghARgSQARgSAGgEQgOgSgDgOQgDgOABgFIAAgCIABgCIABACQASAQASAHIAVAGQAugZAqAKQAsAJAdASQAdASACADIAAAAIAAABIAAADQgDAZgIAMQgHAMgDACQAQATgCAVQANgKARAGQANAIgIASQgEALgNAHQgNAHgXgFQgPAPgYAKQgYAJgVADIgaAFQgBAEgDAGQgFAEgHAAQgGgBgCgFg");
	this.shape_28.setTransform(10,6);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#3A1704").s().p("AA6CMIhTgIIhUgHIgogEQgMhDgMgWQgLgWgCABIAAgBIgBAAQgLAEgIAEQAGgPAIgKIAKgNIABgCIgCAAQgMgBgJACQAOgbAOgPIAPgOIABgBIgBgBQgOgKgOgIIgSgJQASgVAGABIARAaIAMARIABABIABgBQArgrArgHQArgIAWADIATABQATABAUgCQAPgEAKAAQgMAJgEAHIgFAJIAAAAIABABQAvAIAcASQAbASANARQANAQADAHQgPgEgPgCIgQgCIgEgBIADADQAhAiAOAjQAOAkABAMQgNgHgLgDIgLgDIgDgBIAEAMIAEAMQgmAIgUATQgVAUgCAHIgngDg");
	this.shape_29.setTransform(12.1,-3.9);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AiZB9IAAgCQgKg/gLgXQgMgXgDgBIgOAGIgGADIgEACIABgDQAFgOAIgKIALgRIgNAAIgHABIgDABIACgDQAMgYAOgPQAMgPAGgDQgRgMgOgIIgQgHIgBgBIABgBQAKgPAIgFIAJgDIACAAIAAABIAPAWIAOAUQApgpAtgJQAtgHAWACIASABQAUACATgEQAMgCAJgBIAKgBIAEAAIgDADQgWAQgBAIQA7ANAcAUQAdAVAJASQAIARAAABIAAADIgCgBQgLgFgOgCIgUgDQArAuALAkQAKAlgBACIAAADIgDgBQgLgIgKgDQgKgDgEgBIAEANIAEAKIgDAAQguAMgSATQgSAUAAADIAAABg");
	this.shape_30.setTransform(12.3,-4.1);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("Ag8AtIgBAAIAFgWQAEgUAIgWQAHgYAJgOIACgBIgJATQgIAVgPA/QArASAhgHQAjgHAGgFQgEgkgLgfIgMgiQACACAMAgQAMAfAEAkIAAABIgBABIgTAGQgRAGgaABIgEAAQgaAAgdgOg");
	this.shape_31.setTransform(9.4,23.8);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#DAF79A").s().p("AgGAAQAAgFAGAAQAGAAACAFQgCAGgGAAQgGAAAAgGg");
	this.shape_32.setTransform(12.3,20.4);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgHAAQABgHAGgBQAIABAAAHQAAAIgIABQgGgBgBgIg");
	this.shape_33.setTransform(12.3,20.4);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#4D6809").s().p("AgCACIAAAAIACgFIADACIgBAFIgEgCg");
	this.shape_34.setTransform(5.4,21.6);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#5A7C12").s().p("AgsAAIAAAAIACgHQAcAKAagDQAcgCADgBIAAgBIACAEIAAAAQgCACgaAFIgPABQgTAAgbgIg");
	this.shape_35.setTransform(9.6,22);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#9AB749").s().p("AgeAZIAEgVIAMgpIABAAIAFACQgGAcAOAXQALASAUAEIgHAAQgYAAgegNg");
	this.shape_36.setTransform(6.4,25.9);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#9AB749").s().p("AgDANIgBgBQAEgOAFgLIgFAbIgDgBg");
	this.shape_37.setTransform(5.8,19.5);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#C3E565").s().p("AgJgaIAHgDIABgBQAHAeAEAeIgIAAQgCgegJgag");
	this.shape_38.setTransform(14.5,25.4);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#B1D366").s().p("Ag8AZIAEgVIAMgpIABAAQAlAOAZgFQAagFACgCIABAAQAJAdAEAeIgSAHQgSAGgaABIgDAAQgbAAgdgNg");
	this.shape_39.setTransform(9.4,25.9);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#C3E565").s().p("AgBAIIgEgYIACABIAJAfIgBAAIgFABIgBgJg");
	this.shape_40.setTransform(13.3,19.5);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#B1D366").s().p("AgpAPIgBAAQAGgRAIgLQAAgDASgGQAQgHAZAQIAMAgIgBAAQgDABgbAFIgMABQgUgBgVgKg");
	this.shape_41.setTransform(9.6,19.3);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("Ag8AyIAFgVQAEgUAIgWQAIgYAIgPQABgCASgGQAQgHAZAQIAMAiQALAeAFAkIgSAHQgSAGgaABIgDAAQgbAAgdgNg");
	this.shape_42.setTransform(9.4,23.4);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#B1D366").s().p("Ag8ANQABgHANgPQANgRAjgCQAEgCAVAGQAWAGAMAiQgIAFgkAGQgIACgJAAQgaAAgigQg");
	this.shape_43.setTransform(9.7,19.2);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#000000").s().p("Ag9APIgBgBIAAAAQAAgBAEgLQAGgJAOgLQAOgLAaAAQAEgDAWAGQAXAGANAlIAAAAIgBABIgUAHQgSAGgbAAIgCAAQgbAAgegQg");
	this.shape_44.setTransform(9.6,19.2);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#000000").s().p("AgGABQgBgBAHAAIAEAAIADABQgLgBgCABg");
	this.shape_45.setTransform(9.3,31.5);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#000000").s().p("AgFAGQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAAAAAgBQAKgGgBgDQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAAAAAIABABIgCAFQgCADgFAEIgBAAIgBgBg");
	this.shape_46.setTransform(5.4,30.4);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#000000").s().p("AAFAHQgFgDgDgEIgDgEQAAgBAAAAQAAAAAAAAQAAgBAAAAQAAAAAAAAIACAAIADAFQACADAGADIAAABIgBABIgBAAg");
	this.shape_47.setTransform(13.2,30.4);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#384C01").s().p("AACAYIAAgMIAAgJIgDAAIgBAKIgBALQgIACglgEQgBgBgDgNQgCgLABgQIAAgEQAJADAfAEQAdAEAmgMIgBAWQgCANgDAKIgTADIgMABIgPgBg");
	this.shape_48.setTransform(9.3,31.1);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#000000").s().p("AABAaIgBAAIAAgJIAAgLIAAAAIgBALIgCAKIgBAAQgCACgsgDIgBAAIAAgBIgDgTQgCgOAAgQIAAgCIACAAQACADAhAFQAfAFArgNIACgBIgBACIgCAUQgCAPgDAOIAAAAIgBABIgRADIgKAAQgKAAgKgCg");
	this.shape_49.setTransform(9.4,31);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#F7D9C9").s().p("AAUArQAAgDgHgIQgGgJgHgJIAAgBQgFgUgGgPIgHgSIgCAAIAFgCIAHASQAFAPADAVIAAAAIAOATQAGAJABADIAAAAg");
	this.shape_50.setTransform(16.8,25.4);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#E8C8B3").s().p("AAJAlIgJgHIgGAGQgGAGgEABIgBgBIgBgDQACgKAKgMIAAgCIgDgNIgHgVIgGgRQACgEAHgCIAHASQAFAPACAVIAAAAIABAAIAOATQAGAJAAADIAAAAIAAAAQgDAAgKgGg");
	this.shape_51.setTransform(16.6,25.4);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#E8C8B3").s().p("AgEAIQgBgBADgHQACgCAAgFIAFAFQgBADgEAEQgBADgDAAg");
	this.shape_52.setTransform(16.7,29.7);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#E8C8B3").s().p("AgDAEQAEgEADgEIABABIgEAHIAAAAIgDABIgBgBg");
	this.shape_53.setTransform(16,29.2);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#000000").s().p("AgJAAQgBAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAgBIACAAQAGACAEgBIAHgBQABAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAAAQAAAAAAAAQgBAAAAAAQAAAAgHACIgDAAQgEAAgFgCg");
	this.shape_54.setTransform(6.6,35.4);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#E8C8B3").s().p("AgEAIIABgPIAIgBIgBAIIAAAIIgEABIgEgBg");
	this.shape_55.setTransform(6.6,34.4);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#000000").s().p("AgGAKIAAAAIAAgBIAAgKIAAgHIAAgBIAOgBIgBAVIgBAAIgHAAQgEAAgBgBg");
	this.shape_56.setTransform(6.6,34.4);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#000000").s().p("AgCACIgHgCQgBAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAABAAIAHABQAEABAGgCQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQgGACgFAAIgCAAg");
	this.shape_57.setTransform(11.3,35.4);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#E8C8B3").s().p("AgDAIIgBgIIAAgIIAIABIABAPIgEABIgEgBg");
	this.shape_58.setTransform(11.3,34.4);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#000000").s().p("AgGALIAAAAIgBgVIAOABIAAABIAAAHIAAAKIAAABIAAAAQgBABgFAAIgHAAg");
	this.shape_59.setTransform(11.4,34.4);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#D0DBA9").s().p("AgKAHQACgFACgBIACgBIgCAAQgDgBgBgDQACgGAOgBIAEAAQgNABgBAGQAAADADABIABAAIgBABQgCABgBAFQABAEAIABQgMAAgDgFg");
	this.shape_60.setTransform(10.6,35.7);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#E5EFCA").s().p("AgSAHQACgFACgBIACgBIgCAAQgDgBgBgDQACgGAQgBIAIAAQAGAAACACIAAAAQgCAIgBAAIgCABIADAAQADAAABACQgBAFgRAFIgEAAQgLAAgDgFg");
	this.shape_61.setTransform(11.4,35.7);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#000000").s().p("AgMAOQgHgCgBgEIAAgCQABgEAEgCQgEAAgBgEIAAgBQABgHATgCIAIAAQAHABADACIABADQgCAFgCADQAEAAACADQAAADgHADQgHAEgHABIgEABIgIgBg");
	this.shape_62.setTransform(11.4,35.7);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#D6E0B1").s().p("AAGAHQgBgFgCgBIgCgBIACAAQACgBABgDQgBgGgPgBIAFAAQAOABACAGQgBADgDABIgCAAIACABQACABACAFQgDAFgMAAQAJgBABgEg");
	this.shape_63.setTransform(7.4,35.7);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#E5EFCA").s().p("AAAAMQgQgFgCgFQACgCAEAAIACAAIgCgBQgBAAgDgIIABAAQACgCAFAAIAJAAQAQABABAGQAAADgDABIgBAAIABABQADABAAAFQgCAFgLAAIgFAAg");
	this.shape_64.setTransform(6.5,35.7);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#000000").s().p("AAAAOQgGgBgHgEQgHgDAAgDQACgDAFgBQgDgCgCgFIAAAAIABgDQADgCAHgBIAIAAQATACABAHIAAABQgBAEgEAAQAEACABAEIAAACQgBAEgHACIgIABIgFgBg");
	this.shape_65.setTransform(6.5,35.7);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#53593D").s().p("AgTAPIgBgLQgBgJAIgGQALgFAJADIANAFIABABQgFgCgJgCQgHgBgIAEQgJAGABAJIABAJIgEgBg");
	this.shape_66.setTransform(1.9,38.3);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#383D24").s().p("AAAgCIARAAIgBAFIggAAQAJgCAHgDg");
	this.shape_67.setTransform(6.5,39.9);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#42492F").s().p("AgnANIgCgLQgBgJAJgGQAKgFALADIAMAFQACABABAJQAAADACACQACADAJABIAaABIgBAGQgIABgbAAQgaAAgTgEg");
	this.shape_68.setTransform(4,38.5);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#596331").s().p("AgHALQAJgIgCgOIADAAQADACACAQIgBAEIgOAAg");
	this.shape_69.setTransform(7.4,38.1);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#67723F").s().p("AgOAKQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQgBgIgDgCQAFgCAFgGQAHACARACQADAAACAQIgBAFIgLAAQgUAAgCgDg");
	this.shape_70.setTransform(6.3,37.9);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#000000").s().p("AgIAVQgUgBgNgDIgBAAIAAgBQgBgCgBgLQgBgKAKgHQALgGALADQAMADABADQAEgCAGgHIABAAIABAAIAIACQAJACAJAAIABAAIAAAAQABAAADAIQADAIgDATIAAABIgBAAIgRABIgRAAIgQAAg");
	this.shape_71.setTransform(4,38.4);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#53593D").s().p("AAOAFQABgIgJgHQgMgFgNAFQAFgCAKgCQAHgCAJAEQAIAHgBAIIgBAMIgGABIACgLg");
	this.shape_72.setTransform(16.2,38.3);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#383D24").s().p("AgIADIgBgFIAJAAQAEADAGACIgSAAg");
	this.shape_73.setTransform(10.8,39.9);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#42492F").s().p("AgoAQIgBgGIAagBQAIgBADgDQACgCAAgDQABgJABgBIANgFQALgDAKAFQAIAGAAAJQgBAIgBADQgUAEgZAAQgbAAgIgBg");
	this.shape_74.setTransform(14,38.5);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#67723F").s().p("AgLANQgIgKAFgLQAPgCAGgCIAKAIQgCACgBAIIgBAEQgDADgQAAIgFAAg");
	this.shape_75.setTransform(11.9,37.9);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#596331").s().p("AgDALIAAgEQABgQACgCIABAAQgCAMAFAKIgHAAg");
	this.shape_76.setTransform(10.1,38.1);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#67723F").s().p("AgTANIAAgFQACgQADAAQAQgCAIgCQAFAGAFACQgDACgBAIQAAABAAAAQAAABAAAAQAAABAAAAQgBAAAAABQgCADgVAAIgLAAg");
	this.shape_77.setTransform(11.7,37.9);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#000000").s().p("AgXAVIgSgBIgBAAIAAgBQgDgTADgIQADgIABAAIAAAAIABAAQAKAAAIgCIAIgCIABAAIABAAQAGAHADACQACgDAMgDQALgDALAGQAKAHgBAKQgBALgBACIAAABIgBAAQgNADgUABIgQAAIgQAAg");
	this.shape_78.setTransform(13.9,38.4);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#000000").s().p("AgFAwQgBgBADgHQgFACgEgCIgDABQgBAAAAAAQgBAAgBAAQAAAAAAAAQgBgBAAAAIgCgEQABgGAEgIIAHgKIgHgZIgIgbIAAAAIAAAAIAEgFQADgDAFgBIABAAIAAABIAGARQAFAQADAYIAPASQAHAIAAAEIgBACQgFACgLgHQgFANgFAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAAAAAgBg");
	this.shape_79.setTransform(16.6,25.8);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#000000").s().p("AgFAAQgHgFAAgBIAIAGQAEAEALAAIACACIgCACQgLgBgFgHg");
	this.shape_80.setTransform(-0.6,27.6);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#D3B09C").s().p("AgTAwIgCgBIABAAQADgCACgHIADgLIABgEIABAEIABABIgBAAIgCALQgDAHgDACIgBAAIAAAAgAAAArIAAgBQACgDAAgFQAAgEgCgEIAAgBIAAgBIAFgDQADgEAAgMIAAgFIAAAAIAIgMIAQgVIAJgNIgBgBQABAAAAAAQABABAAAAQABABAAAAQAAAAAAABIgJAMIgPAWIgIAKIAAAAIABAGQgBAMgEAEQgDAEgBgBIgCABIACABQACAFAAAEQgBAEgBADIgDACIAAgCgAgrAfIAAgBQAIgCAMgGIADgCIgBADIgOAHIgGABIgCAAgAgdALIgDgBIABAAIACABgAglgFIAAgBIACACIgCgBg");
	this.shape_81.setTransform(0.7,25.8);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#E8C8B3").s().p("AgUAxQgDgCABgHQABgIACgHIABgDIgDACIgOAGQgGADgCgBIAAgBQABgDAEgFIAKgIIACgCIgDgBQgJgDgDgKQAAgBABAAQAAgBAAgBQAAAAAAgBQAAAAAAAAQACgBADACIAKAEIAHAAIABAAIAAAAQASgIACACIABAAIAAAAIAOgVIAPgVQALACgBACIgJAMIgPAWIgIAKIAAAAIAAAHQAAAMgEADIgEAEIgCABIABABQACAEAAAEQAAAFgBADIgDACQgBgCgGgPIgCgEIgBAEIgDALQgCAGgDADIgBAAIgBAAg");
	this.shape_82.setTransform(0.7,25.7);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#000000").s().p("AgVAzQgEgCAAgHQABgJADgIIgNAHQgHADgDgCIgBgCQABgEAFgGIAJgIQgKgEgDgKIAAgBQAAgEACgCQADgBAFADIAHADIAIACQARgIAEABIAOgVIAOgVIABgBIAAAAQAKABACADIACADIAAABIgJALIgQAWIgJALIABALQgBAIgHAGIACAKQAAAFgCAEQgCADgDAAQAAAAgDgHIgFgMIgEAMQgCAHgDADIgCABIgCgBg");
	this.shape_83.setTransform(0.6,25.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_83},{t:this.shape_82},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(50));

	// Layer 2
	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#000000").s().p("AgIgFIgBgCIAEAAQAEgBABgBIAEgCIAEACIgGgOIAHgDIAAAEIgEAxIgFAAQgFgWgDgKgAgCgDIACAQIACgLIABgGIgFABg");
	this.shape_84.setTransform(-87,9.4);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#000000").s().p("AhnGbIgDAAIgCgGIgDADIgCAAQgIgDgGgDIgCgDIABgCIAGgJIAMgPIgFgEIgCgCIABgDIASgaQAPgWAQgQQgCgDgBgDQAAgDACgCIAEgDIgBgUIgCgiIAAgXQgFACgEAAIgFgCIgBgBQgEACgGgCQgFgEgCgGIgCgJQgIAAgIgNQgFgHAAgGIABgEQADgGACAAIABgBIgQgkQgIgSgCgLIAAAAIABgEQgMgLAAgGIABgCQABgEAEAAQgCgDAAgEQAAgGADgCQAEgDAGAAIAOABIALgcIAJgUQAEgIAGgFIgGgEIgDgBIAAgEIAGgLQAFgKAFgGIAEgCQgPgQgPgaQgQgZgJgkQgdgMACgRIAAgEQACgIAHgFQgDgVAAgVQAAgPAFgOIgFgEIgEgDIAAgDQACgNAFgCIADgCIABACIAGAJQAXgpArgSQAogOAbAAIAJgBQANgBAKgEQAogSAPgNIALgHIABgBIABAAIAHABQAFADAHAFQAKAIACAZIgBANQgEASgTAPQACAHAAAMIgBAYIgBADIAAAFIABAHIAAADQAKAGAGAGIAHAHIAAABIAAABIABAKQgBAjgGAOQgFAOgBAAIgBABIgCAAIgFAAIABAGIAFAQQAFAQABAMQAAAGgCAGQgGAUgYAPQgYAQglAHIgKADQACADAAADQAAAEgDAIIgCALIgBAFIACACIAEAIIAKAYQAGAMAGAJQAIgDAFADQAGAFAAAIQAGgBAFACQACACAAADIAAABIAAADIASAAIARAAIAQgQIARgOQAGgDAIADQAIACAFADIACABIgJARIgBAAIgHAEIAEAHQAHAJACAIQAAACgDADQgFADgIgCQgHgDgHgEQgFAFgQgBIgXADIgjACIgDAEQgGAFgFABQADAPAAAMQAAAMgDAKIAAAEQgBAOgEACQgCAIgJAIIAOAvQAHAaADAQQAEATABAaIAAAkIAAACQANAFAGABQACgIANgCQAIgBAFAFQAGAGAAAJIAAACIgBACIgCABIgQAGQgQAGgVABIgCABIgDAAQgCACgNgBIgEAAIAAgEIABgHQAAgHACgJQgHgBgEgDIgBgCIAAgCIAFgtIADgbQgFgCgBgGQABgFAFgDIgPgsQgGgWgEgHQgGABgTAAIgEAaIgEAoIgDAiIAAABIgBABIgJAPIgRAfIgNAaIgCACIgDAAIgEgBIABAAIAFABIAEABQAGgFAOACQAHADACAHQADAJgEAJIgBABIgCAAIgNADIgTABIgRgBgAhoGQIACAGQAoAAAGgDQACgDAAgEIAAgFQgCgFgFgCQgFgBgFABIgGADIgBAAIgNgCIAAAAQgDgCgCgGIgBgEIAFABIAHACIAOgZIARgeIAJgRIADglIAFgqIADgXIAAgDIADAAQAXABAFgCIACAAIABABQACAGAGASIAMAjIAGAUIABACIgCABQgGAEABAAQAAABABAAQAAAAAAABQABAAAAABQABAAABAAIABABIABABIAAACIgDAeIgFArQAEADAGAAIADAAIgBADQgDARABAHQAIAAADgBIABgGIAAgFIADAFIADAFQATgBAOgFIARgGIAAgBQAAgHgEgEQgDgEgGABQgKADgBAFIgBACIgCAAQgKgBgOgFIgGgDIAFgCIAAgCIgBgkQAAgZgEgTQgDgQgIgbIgOgvIAAgCIABgBQAKgHACgIIAAgBIAAAAQACAAACgNIAAgEIAAgBQADgJAAgMQAAgMgEgRIgBgDIAEAAQAEABAGgGIAFgFIABAAIAkgCIAXgDIAAAAQAQAAAEgEIABgBIABABQASAKAFgDIAAgCQgBgGgGgHQgGgIAAgCQADgGAIgCIAFgKQgMgHgIADIgOAMIgSARIAAABIgCAAIgUAAIgUAAIgEAAIACgDIABgFIAAgBQgDgCgHABIgDABIAAgDQABgGgFgGQgFgBgEADIgCABIgCgCQgGgJgHgOIgLgZIgFgLIgBAAIABgGIACgMIADgLIgEgHIgDgDIATgEQAjgHAXgOQAYgPAFgSQACgJgBgIQgBgJgEgLIgDgJIgCgIIgDgNIAEABIAHAAQACgCAEgNQAFgOAAgeIAAgJIgGgHQgGgGgLgGIgEgCIAEgCIAAgCIgBgGIgBgBIACgJIABgXQAAgPgCgEIgBgCIACgCIAAAAQATgNACgQIACgNQAAgPgIgKQgMgMgFAAIgLAHQgQAOgoASQgLAEgOABIgJABQgaAAgnANQgqASgXAqIgCAEIgCgCIgIgKIgCAJIAEAEIADADIACABIgBABQgFAPAAAPQAAAWADAUIABACIgCABQgGAEgCAHIAAADQgBAOAaAKIABABIABABQAJAmAQAaQARAaAPAQIADADIgKADQgEAEgEAIIgGAMIAJAFIADACIgDACQgHAGgEAIIgKAVIgLAdIgBACIgCAAQgSgDgDADQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAABIACAGIADAFIgGABIgCABIAAAAQAAAEAKAKIADADIgCACIgBACQAEAQAXAxIABADIgDABIgDACIgCADIAAACQAAAEAEAHQAHALAGgBIACAAIABADIACAJQACAFADADQADAAADgBIAAgBIABAAQABAAAAAAQABAAAAABQABAAAAAAQAAABAAAAIAAABIAEABIAGgCIAGgFIAEBaIgBABIgEADIAAABQAAABADADIACACIgCACQgPAOgPAVIgUAdIAHAEIAEABIgDADQgGAFgGAIIgIALQADACAIACIAEgEIADgEIABAGg");
	this.shape_85.setTransform(-76.4,-0.4);

	this.instance = new lib.Symbol13("synched",0);
	this.instance.setTransform(-92.5,-41.4,0.261,0.261);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#000000").s().p("AAWBJQgHgCgZgBIgJABIgCABIgBgDIgDgJIgCgCIAGgBIAAgIIgBgkIgDgWIAAgBIACgBIADgEIAAgBIgDAAIgDAAIAAgDIAEgYIAFgZIAAgDIADAAQARACARgDIAEgBIgBAEIAAADIAAAEIAAAFIgBAEIAAAFIAAAEIAAADIAAADIAAADIgBAEIAAAIIAAAEIAAAEIAAAFIAAAGIAAAEIAAALIgBAEIAAAGIAAAIIAAACIAAAXIAAAFIAEABIADAAIgDAOgAAUBEIABgDIgEgBIgCgBIAAgFIAAgEIAAgXIAAgFIAAgEIAAgGIAAgFIAAgDIAAgCIAAgDIAAgDIAAgBIAAgCIAAgGIAAgHIAAgCIAAgDIAAgCIABgDIAAgSIAAgEIABgHIAAgCIAAgFIAAgCIAAgCQgPACgOgBIgFAWQgDANAAAKQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAIAAAAIACADIAAAAQAAAEgFAEIACAXIABAiIgBAKIAAACIgCABIABAEIAIAAQAVAAAJACg");
	this.shape_86.setTransform(78.6,29.6);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#000000").s().p("AgcFYIgCgBIgBgCIAAgFIAAgCIgBAAIAAgBIAAAAIgBABIgTADQgRAEgagCIgDgBIAAgDIgBgHQABgHAFgHQAIgKATAAQAXABAJABIABgCIgBAAIgCgBIAAgDIABgTIACggIABgVIACgXIAFggQgggGgKgMQgOgJgBgGQgBAFgFAGQgGAGgKgBIAAAAQgCAAgFgGIgCACQgIAEgHgEIgBgBIgBgBIgBAAIAAgBIAAAAIAAAAIADAYQAGAhADA0IABAUQAAAegDANQgDAMgBABIAAABIgBAAQgFAEgIADQgJACgKgIIgCgBIABgDIAIgbQAGgaABgqIgBgWQgDgngGgUQgDgOAAgHIABgHIADgFQgIgLAAgGQACgHAOgLQANgKAGgCQAEgBAGABQABgFACgEQAFgFAIgBQAGgBAHAEQAMgTAGgWQAHgWAEgRIAFgWIgBgDQAAgDACgFQgGgFAAgEQgCAAAHgPQgZgLgagSQgagSgSgWQgRgVgBgVIAAgCQABgVAMgPQALgPAMgJIAAAAIgCgDIgBgDIAAgCQADgEADABIAEAAQABAAgBgJQgBgFADgCQAEgEANACQAEgMAGgLQAHgKAHgEIAAgDQgBgLAEgGQAEgHABAAIACgCIACACQAJAHAAADIAAADIgCABIgLALQAFAAADADQAkghAkABQADgCAfALQAeAMAgAxQAIgBATACQASADAQAPIABABIgBABIgCAKQgBAIgEAGIAGAOQADAKAAAIQAAAHgEACQgHABgGgFQgBAHgDAKQgEAJgHAFQgDAkgZAUQgSAOgaAKQAEAHAAANIAAAEIAAABIgCACQAKAJAIALQANAVAFAfQAEAhAAAfQAAAWgBAPIgBARIAAABIgBABIgIAGQgGALgcAMIgEAZQgDAQgBAPQAEADAAADIAAABQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAIgEACIAAAFIADAbQABAQACANIAAADIABABIAAACIABAEIgDABQAFAIABARIAAADIgEABIgHABIgOABIgDAAIAAgBIgBAAIgBABIgSAEQgLACgLAAIgUgBgAgcFEIABAFIACAAIgBADIAAAEIAAADQAXABAOgCQARgDACgBIAEgFIADgEIAAAEIABAFIASgCQgBgSgFgHIgBgDIAEgBIAAgBIgBgCIAAgCIgEgeIgCgbIAAgDIAAgGIACgBIADAAIgEgEIgBgBIAAgBIAEghIAFgaIABgCIABAAQAbgMAGgKIAAgBIABAAIAHgFIABgRIABgkQAAgfgEggQgEgegNgUQgIgMgLgJIgCgBIAEgFIAAgDQgBgOgEgGIgBgDIADgBQAagKATgPQAXgSADgjIAAgBIACgBQAHgFADgKIAEgPIABgGIAFAEQAFAEAEAAQAAAAAAgBQABAAAAgBQAAAAAAgBQAAgBAAAAQAAgHgDgKIgGgOIAAgCIAAgBQADgDACgHIACgLQgQgOgSgCQgTgCgEABIgCABIgBgCQgegwgegLQgdgMgDACQgigBgkAhIgCACIgCgCQgDgDgDAAQgDAAgDACIgBAAQgNAKgHAaIgBACIgCAAQgQgCAAACIAAACQACAJgDAEQgEADgEgBIgBAAIABABIACADIABABIgBAEIgBABQgMAIgKAOQgLAOgCAUIAAACQABAUASAVQARAVAaARQAaASAYAKIADACIgBACQgHAOABABQAAABAGAFIABACIAAABIgDAIIABACIAAABIAAABIgFAWQgEARgHAYQgHAXgNAUIgBACIgCgBQgIgEgEAAQgGAAgEAFQgCADgBAFIAAADIgDAAQgGgCgEABQgFACgMAJQgLAKgDAEQAAAEAIAMIABACIgBABIgDAFIgBAFIAEAUQAFAUAEAnIAAAXQAAAngGAaQgGAagDAFQAHAFAHgBIALgGIADgNQACgMABgbIgBgVQgDg0gGggIgEgcQAAgJAEgDIABgBIAFAAIgBAGQgBAEABACIAAABIABAAIABABIABABQAEACAGgDIADgDIADgDIABAEQADAGACAAQAHAAAEgEQAGgHgBgDQgBgEgFgFIgCgBIACgCIACgEQABgEAAgFIAAgEIgBgEIAEABIAGABIADgBIAAADQgCAcACABQgCACAQALIABABQAJALAgAHIACAAIAAACIgHA5IgBATIgBAfIgCAVIACAAIACABIgDAMIgCAAQgHgCgbgBQgQAAgHAJQgFAHAAAGIABACQAWACARgDIATgDIADgFIADgFIABAFgAhUCDIAAgJIAAgMIgBAAIABACQAAAGgCAFIgCADIAEAFIAAAAgAhLk/IAAABIAKgKQAAgDgEgDQgFADgBAMg");
	this.shape_87.setTransform(77.5,5.2);

	this.instance_1 = new lib.Symbol10("synched",0);
	this.instance_1.setTransform(69.6,-28.7,0.261,0.261);
	this.instance_1.alpha = 0.699;

	this.instance_2 = new lib.Symbol9("synched",0);
	this.instance_2.setTransform(61,-29,0.261,0.261);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#000000").s().p("AA8FvIgXgFQgMgEABgHIAAgBIAAgBQgBgFAJgGIAAgBQABgIADgHIAGgLIAAgKQghADgkgJIgBANQAGAGACAMIAAABQAJAHgBAHIAAAEIgCACQgoAUggABQggAAgTgGQgTgGgBgBQgIgEgCgIQgBgMAFgKIAHgMQAOgSAXgCQAVgCAOAKIAJALQAWgEADgEIAAgFIAAgHQgbgJgDgCQgCAAgCgEQgDgEAAgNQAAgJACgRIgGgFIgDgCQgDgDAAgEIAAgBIAAgBQABgMAFgMQgDgCgCgEIgBgDIAAgBQABgFACgCIALgZIALgfIAFgPQAEgTAAgSIgBgSIAAAAQgFgJAAgJQABgRAIgNQAIgPAHgIIAAgHIgHgCIgEgBIgFgBIgFgBQgXgFgWgLQgagMgPgKIgQgLQgKgMAAgTQABgVAFgTIAFgRIAGgRIgBgBIACgIIAEgVIAAgQIAAgLIAAgBIABgJIAAgBQgDgBgCgGIAAgBQAAgIAMgLQAMgfAOgMQAOgMAEAAQADgDATgJQATgKAggEQAegFAqALQAUAFAUAKQABAAAKAHQAKAGAMANIAGAIIADgDQAEgDAJACIADABIAAANIABAOIACADIAEgOIACgJIACgBQANgBABAHIABABIgFAOIgFAQQAUAXAAAbQAAAIgCAJIgIAPQgIAPgOAOIAAASIABARIgNgFIAAgIIgBgNQgNAHgNgBQgNARgQAJQgJAegaAhQACAGAAAHIgBALIABABQAKAIAIAMIADAEIADAEQATAWAKAcQAIAVADAVIgBAIIgDAnQgCAYgDAUQgCAwgCAeIAAABIgCAcIgBACIgBABIABAAIgCABQgJAEgKACIgBAAIgBAAIAAAGIAAACQAPAEALAAIADgDQANgNASAAQARABANALIAAAAQAUATgCANQgCANgCAAIgBABQgcAQgeACIgSAAQgUAAgQgCgAAyE5IgBABIgFAJQgFAHAAAIIABADIgCABQgHADAAAFIAAAAQgCACAJAFIAXAFQAWADAdgBQAegCAbgPQABgBACgKQABgKgRgRQgMgKgPAAQgQgBgLAMIgEAFIgCAAQgMAAgTgGIgBAAIAAgCIAAgEIgBgHIAAgDIAGgBIABAAQAJgCAIgEIACgNIABgOIAAAAIAAgBIAEhOIAAgBQADgUACgYIADgmIAAgEIAAgEQgCgUgIgVQgJgagTgWIgGgIQgIgMgJgHIgCgBIgCgBIABgCIABgMQAAgHgDgFIgBgCIACgBQAbgiAJgdIAAgBIABgBQAPgJAOgRIABgBIABAAQAOACAOgJIAEgDIAAAMIABAOIACABIAAgRIAAgMIAAgBQAPgOAHgOIAIgPQACgIAAgIQAAgYgTgXIgBgBIAEgPIAFgPQAAgDgHAAIgDANIgCALIgCAEIgLgJIAAgMIAAgOQgHgBgBABIgBABIABAIIAAAIIgFgIIgLgOQgMgNgJgGIgKgGQgUgKgTgFQgqgLgdAFQggAFgSAJQgTAJgBACIAAAAIgBAAQgDABgNALQgOALgLAfIAAAAIgBABQgMALABAEIAAAAIABADIAEgEIADgDIgBAIIgDAOIAAABIAAALIAAAQIgEAWIgBAFIABAAIgBACQgCAMgEAIIgFARQgFAQgBAWQAAARAIAKIAQAKQAPAKAZAMQAWALAXAFIAEABIAFABIAOAEIABABIABAKIAAABIgBABQgHAIgIAOQgIANAAAQQAAAIADAHIABACIAAABIABASQAAATgEATIgGAQIgLAfIgKAaIgBAAIgBAEIAAACQABACAEACIACABIgBACQgGAQAAAJIAAABIAAAEIADACIAHAFIACABIAAACQgDASAAAKQAAAOAEABIAfAMIACAAIAAASIAAAAQgDAFgJACIgTAEIgBAAIgBgBQgFgGgEgEQgMgKgTACQgVACgNAQIgGAKQgFAKACAKQABAFAGADQAAABATAGQASAGAfgBQAfAAAmgTIAAgCQABgFgHgFIgCgBIAAgDQgBgJgHgHIgBgBIAAgBIACgSIAAgDIADABQAlAKAigDIAFgBg");
	this.shape_88.setTransform(41,5.2);

	this.instance_3 = new lib.Symbol11("synched",0);
	this.instance_3.setTransform(23.6,-31.4,0.261,0.261);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#000000").s().p("ABEF7QgYgCgIgFQgJgGAAgCIAAgBIgCgIQAAgDACgCQACgEAFAAQgBgMAPgTIgDgJQgcAHgXABIAAABQANATgBAMQAFAAACAEQACACAAADIgCAJIAAAAIAAAAQAAACgJAGQgGAFgYACQgZABgcgFQgbgEgOgKIgCgBIAAgCIACgKIAAABIABgDIgBABQACgJAEgJQAFgKAHgHQALgIANACQANABAJAJQAEgDAGgCQgTgDgQgJIgCgBIAAgCIADglIAHhJQgSABgMgEQgGgEgGgGQgFgIgCgHQAAgIAFgEQAFgDADAAIABAAQADABAEgFQgNgRgIgUIgGgDIgCgBIAAgDQABgIAHgVQAIgVAKgWQAKgWAJgJQgVAAgKgJQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAgBIACgDIAEgCQADgDABgEIABgCQAAgEgGgGIgGgGQgMgLgSgTQgRgUgOgcQgNgdgBgkQgBgYAJgbQARgwAVgUQAVgUASgDQARgEAGACQAEgFAOgLQAPgKAXgIQAZgKAkAGQAlAGAuAmIABADIAAABQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAIgDABQAJAIALAWQAMAVABAkIAAABIgCAXQgGApgPAjQgQAjgNAXIgJAQIgGALQABAHAGADIAJAEQAAAAABAAQAAABABAAQAAABAAAAQAAABAAABIAAAAIgBAFQgCAFgFAEIAJAJIADgBIAJgFIAEgCIABAAIACgBIgBAAQAKgDAGACIAFACIABAAQAAgIAIgJQAIgHAPADIAGACIgEAFIgEAGIAFgDIACgBIAEAGIgCABQgCAAgDANQAWALAEAiIAAAKQABAcgRAeIAAAAIgBACQgPAYgSAIQgTAIgOgBQALBNAAAuIAAAGIAAAGIAAACIgCABIgQAHQgPAGgYAHIABAHIAPABQAJACAJAFQAIgJANgBQAOgCAKAIQAIAHAEAKQAEAJACAJIgBgBIABADIAAgBIACAKIAAACIgCABQgOAKgbAEQgXAEgVAAIgJAAgAAfFgIAAADIABAHQAAABAHAFQAIAEAVACQAYABAbgEQAagFANgIIgBgJIAAgBQgDgSgOgOQgIgGgLABQgMABgIAJIgCABIgCgBQgIgFgLgCIgOgBIgCAAIgDgQIACAAQAXgHAPgGIASgIIAAgFIAAgFQAAgugLhPIgBgDIADAAQANABASgHQARgHAPgVIgBgBIACgCQASgdgBgcIAAgJQgEgigVgIIgCgBIAAgCIADgKIgCADIgEAJIgCgMQABgKAEgFQgKgCgGAFQgHAJABAHIAAADIgJgBIgBgBIgCgBQgFgBgIACIgBABIgBAAIgDABIgJAGIgBAAIgHABIgQgPIAEgCQAHgFABgGQgEgBgHgEQgGgFgBgIQAAgEAHgKIAJgPQANgXAPgjQAPgjAGgoIACgWIAAgBQgCgmgNgWQgMgVgIgFIgDgDIAEgBIAGgCQgsgkgkgFQghgGgYAJQgYAIgOALIgRAOIgBABIgCAAQgDgCgRADQgQADgVATQgVATgRAvQgIAbAAAXQABAjANAcQAOAbARATQARAUALAKIAHAGQAHAHAAAHIAAADQgEAJgGADQAKAHAWgBIAHAAIgEAEIgFAFQgIAIgKAVQgJAVgIAVQgHAUgCAJIAHADIAAABQAJAVAOARIABACIgBABQgHAKgGgCIgBAAIgEACQgEADABAEQADAOAMAHQAGADAJAAIAQAAIADAAIAAADIgHBGIgEApQAVALAbACIAAAFQgNABgMAHIgCABIgCgBQgIgIgMgCQgLgBgIAGQgOAOgDASIAAABIgBAJQANAIAbAFQAaAEAYgBQAVgCAFgEQAIgFAAgBIABgHIAAgDQgBgBgFAAIgDABIAAgEQABgFgBgIQgCgJgJgJIgBgBIADgHIACAAQAXgBAegHIACgBIAGAQIgBABQgJAJgCAJQgDAIABAFIAAAEIgDgBIgCAAQgBAAgBAAQAAAAgBAAQAAABgBAAQAAAAAAAAg");
	this.shape_89.setTransform(-51.2,3.6);

	this.instance_4 = new lib.Symbol7("synched",0);
	this.instance_4.setTransform(-70.4,-34.1,0.261,0.261);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#000000").s().p("AgJgCIAJgDIAAACIAEACIAGABIgJAFg");
	this.shape_90.setTransform(-20.3,35.4);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f("#000000").s().p("AAAAMQAAgCgKgDIgCAAIABgSIACAAIATgBIADAAIAAACIAAAQIAAACIgCABQgGABgDACIgCABgAgGgGIAAAJQAFABACADIAGgDIABgFIAAgGIgOABg");
	this.shape_91.setTransform(-20.2,33.3);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#000000").s().p("AAuEEQgYgGgLgGQgLgFAAgBIAAgBIgBgCIAAgBQgGAGglAKQgXAEgMgCIgNgDIAAAAIgBAAQgIgIAAgPQAAgPAKgIQAFgEAIgDQAAAAABAAQAAAAABgBQAAAAAAAAQABAAAAABQAKgDAHAAIAIgBIAJgEIgCgDIgBgDIgEABQgJAAgFgIIgBgEQAAgEAEgGQgFgEgCgMIgGgFIgBgBIAAgCIACgOIAGgeIgBgHIAAgHQAAgRACgMIgGgFIgCgCIABgCQgBgBAEgLQAEgMAJgLQgggKgTgNQgSgPgBgCIAAgBIgCgIIgBACQgBAAAAAAQgBABAAAAQgBAAAAgBQgBAAgBAAQgZgVgBgSQgBgSACgBQAUhIAigmQAjgnAZgKQAsgUAhAiQAQgKAaAGQAaAGAXAPIAAAAQAdAbAEAYQAFAYgDADIgCADIgCgCIgIgHIACAOQgBASgFATQgFASgHAOQgBAKgEAKQABACgOAUQgNAUgkANIADAUIACARIAAABIAAABIgHAHIAFAfIACAHIABAGIADAHQADAIAGAFQAIAIAAAJQgBAHgHALQgHAKgJACIgFAAIgBAAIgNgBQgHgBgEgEIgDABIAAAIIAAAHQAKADADAHIABAEIgBAEIgCACIAJAGIAHABQAPgBARALQAJAJAAAOIAAABQAAAPgIAIIAAAAIAAABIgBAAQgBABgLACIgIABQgKAAgQgDgAAEDLIADABIgBADQgEAMAAALIABAIQACAFAqAMQAVAEAKgCIAMgDQAGgGAAgNIAAgBQAAgMgHgHQgPgJgOAAIgJgCIgSgKIAFgCQABgBAAAAQABAAAAgBQABAAAAAAQAAgBAAAAIABgBIgBgCQgEgGgHgBIgCgBIAAgYIALgCIABACQAEAEAQABIABgBIABABIAEAAQAFgCAGgIQAHgJABgHIAAgBQgBgFgGgGQgGgGgEgJIgDgIIgBgGIgCgHIgFghIgBgCIACgBQAFgDABgCIgDgTIgDgTIAAgCIACgBQAjgMANgTQAOgUgBgCQAEgJACgLIAAAAQAGgOAFgRQAFgSAAgSQAAgKgCgKIgCgGIAGADIAKAIIAAgBQAAgJgGgTQgGgSgWgUQgagQgYgFQgZgEgMAJIgCACIgDgDQgFgIgSgJQgQgJggANQgYAJgiAmQgiAmgTBHQgBABgBAJQAAAHAFALQAEALAOALIACgPQABgIADgEIAFgHIgBAbQABARABAAQABADATAOQATAPAgAHIAFABIgEADQgKAKgEALIgEAOIAHAFIABABIAAACQgDANAAARIABAPIgFAcIgDAPIAGAEIABABIAAABQACANAFADIABACIgBACQgEAFAAADIABACQADAEAGAAQACABAGgHIABgBIACABIABgBIACAFQgDACgBACIgBACIAAABQABACADACIAEACIgRAJIgJACQgIAAgJACIgBAAIgBAAQgHACgFAEQgIAHAAAMQAAAMAHAHQABABAKABQALACAWgFQAogLADgEIABgLQAAgJgDgJIAEgDIAEACg");
	this.shape_92.setTransform(-20.3,16.2);

	this.instance_5 = new lib.Symbol8("synched",0);
	this.instance_5.setTransform(-36.1,-9.8,0.261,0.261);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_5},{t:this.shape_92},{t:this.shape_91},{t:this.shape_90},{t:this.instance_4},{t:this.shape_89},{t:this.instance_3},{t:this.shape_88},{t:this.instance_2},{t:this.instance_1},{t:this.shape_87},{t:this.shape_86},{t:this.instance},{t:this.shape_85},{t:this.shape_84}]}).wait(50));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-92.8,-41.6,187.1,84.2);


// stage content:
(lib.brotherCJS = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.boy();
	this.instance.setTransform(100,100.8);

	// Layer 8
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,255,255,0)").s().p("AvnPnIAA/OIfOAAIAAfOg");
	this.shape.setTransform(100,100);

	this.addChild(this.shape,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(100,100,200,200);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;