(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 200,
	height: 200,
	fps: 12,
	color: "#FFFFFF",
	manifest: []
};



// symbols:



(lib.Symbol13 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#14395A").s().p("AmMYeIgDAAIgEgOIgHgVIgTAWIgDgBIgYgIQgSgHgIgGIgCgDIACgDIAagoQAYgiAbgaQgRgIgNgLIgEgDIADgDQAIgPA9hZQA+hYA+g5QgMgKgDgQIAAgBQAAgGAEgEQALgLAGgCIgDhFIgGiIIgFhxQgFAEgHAEQgQAIgMAAQgLgCgGgEIgHgIQgHAJgcgGQgOgMgIgXQgHgYgBgKIgBgFQgYAGgkgxQgWgkAHgWQAJgRAGgBIAOgHQgghAgghKQgghKgKgqQgCgCAJgOIgEgDQgrgqABgTIAAgGQAHgIAUgBQgJgPgFgVQAAgOAJgJQAKgHAaAAQAaAAAcAEQATgzAYg6QAYg6APgeQAUgnAYgRQgSgNgTgJIgEgCIABgEQACgGATgkQASglASgTQAHgGAWgEQg8g9g/hmQg/hmgkiRQh3gvARhFQAIgfAbgSQgMhNAAhXQAChDARgxIgSgPIgPgLIAAgDIAEgZQAEgTAKgIIAEgCIAOAUQANASAHAIQAKgcA7hKQA7hLB+g7QBWgjBLgIQBKgJA0gDQA8gFAmgOQBvgxA7grQA8grAZgPIABgBIABAAQAKgFA1AmQA0AmgMCCQgOBEhHAzIgEACQATAdgPCMIgEAfQAIATgDAVIgEACQArAYAXAXQAYAXADAFIAAAAIABACIAAABQACCYgVA8QgWA8gFAAIgCABIgCABQgRABgPgCIAJAiQAXBOALAsQAMAsgNAuQgTBFhYA6QhYA6iSAeIgyAKIgDABQAPARAAAOQgBAPgHAaQgHAagDAVIgDAVIAGAMIAPAiQATAuAYA0QAYA0AaAiQAYgRAVAJQAYAbgDAaQAVgFAWAIQAGAEAAAGQABAHgHATIBLAAQAtAAAigCIA6g4QAsgqAXgRQAXgKAgAMQAgAMAIAGIgbAzQgfAKgGAPQADALAQAVQAQAUAJATQAKATgKALQgTALgggNQghgNgNgJQgQARhCgCIhaAKQhMAIg8ADIgPAQQgZAYgWgCQAcB4gZBLIAAABQgDBIgNgBQgHAigpAfQAXBJAeBoQAfBoANA+QAKA2AEBKQAEBKAAA6IABA9IgBAEIgBAAQAUAIAaAHQAZAIARACQADgJAMgOQANgOAYgDQAagCARARQAUAVgCAiIAAADIgCABQgEAEg6AUQg7AVhQAGIgDAAIgLgRIgCAUIgDABQgFAEg0gCIgEAAIAAgFIABgeQACgdAHgmQgYgBgVgOIgCgCIABgDIAUitQALhZAAgVIAAgBIgFgDQgOgFgEgOIAAgBQAAgMAYgOQgYhNgihgQghhfgPgeQgXAIhZgDIgMBfIgSCeQgJBVgEA4IAAABIAAABIgjA8IhDB3QgkBBgPAgIgCADIgEAAQgEAAgfgIQAEAQAKAJIAWAEIAXADQAFgEAUgHQAVgGAYAHQAVAIAJAWQAJAegPAdIgBACIgDABQgBABgxAHQggAEgvAAIg4gBgAmKFXQgOAFgUACQAKAyAaBNIAOiSQgFAJgLADgAl8EdIAFAMIABgNIAAgCIgGADg");
	this.shape.setTransform(61.3,156.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-0.2,0,123.1,313.5);


(lib.Symbol12 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#14395A").s().p("AgeRxIhEgCIgEAAIAAgEQgLhpARgXQgOgHgDgLIgBgGQAFgQANgIQgNgHgFgOIABgGQAEgTAugMIAAgSQgVgBgSgFIgEgBIgCgiIgDgoIgBAAIgGAqIgFAkIgEABQgCABg5ACIAAARQAuAMAEATIACAGQgGAPgNAIQANAGAFAQIAAAGQgDALgPAHQARAXgLBpIAAAEIgEAAIhEACQg7AChKgDQhKgDgzgMIgCgBIgBgCQgEgHgEgsQgDgrAmgeQApgUArAMQAsALANAJQAJgFATgQQgPgKgBgKQAHgRATgFQgLgHgHgTIAAgCQAAgEAEgEQAOgLAfgBIAAgQQgcgCgggEIgEAAIgBgEIgKhBQgJg9ABg8IgSgJIgDgBIAThUQARhIAbhXIhDBcIgqA4QADAKgBAgQgBAhgdAYQAIATABARQgBAUgIANQgIAOgKAAQgJgCgLgYQgMgYgIgWQgEASgIAbQgIAbgNAJQgHAFgHgDQgRgIABgaQAFgkALgdQgVANgdANQgdANgMgJQgDgCAAgGIAAgBQADgQAVgUIAjgfQgpgSgKgsIAAgDQAAgRAJgFQALgGASAMQAJAFATAGQATAGAMACQBCggAWAEQAIgOAigyIA4hUIgMgHIgEgBIABgEQgBgGAcg1QAcg1BRgoIhjgwQg+gehDgoQhDgogxg1QhVABgrghQgqgjgJgqQgQhJA2gWQAwgLAjAZQAAgTACgRQglirgkhAQgjhAgKgEQgcAIgZAMIgbANIgMAGIAEgMQASg0AeguQAdgtAPgTQgagBgZACIgcADIgKABIAEgIQAxhhAzg4QAyg4ATgNQg9gsg3gdIg8geIgFgCIADgFQAog5AfgQQAggRADACIAEAAIACACIA6BWIA1BNQCfigCrgeQCrgfBUALIBNACQBLAHBJgMQAsgJAjgCIAmgDIASgBIgPAKQhSBAgFAeQDiAtBtBQQBuBQAhBCQAiBDgDAFIADALIgLgFIgUgIIABACQgggMgigHQg4gJgegCQClC0AoCMQAoCMgHAKIACALIgKgGQgqgagmgNQgmgOgSgDIAQAxIANAmIgGABQhxAahDAsQhDArgeAnIAAACQAvgoBDAYQAxAfgdBDQgRApgzAaQgyAbhXgTQg2A5hVAiQhUAhhOAQQA9AlAiBwIABAEIgEACIgQAGQAWA4AgCYQAfAkAaAhQAaAgACARQAAAFgDACQgWAIgqgeQgSAygcAFQgJAAgCgFQgDgGANgbQgVAIgNgHQgHAEgGABQgHBJgNA6IgBADIgDABQgLAEhJAHIAAAQQAdABAOALQAEAEAAAEIAAACQgGAUgKAKQASADAGAPQAAAKgQAKQATAQAJAFQANgJAsgLQAsgMAoAUQAmAegDAsQgEArgEAHIgBACIgCABQgzAMhKADQgxACgrAAIgngBgAB8JvIADgDIgIgaIAFAdg");
	this.shape.setTransform(82.1,113.8);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,164.2,227.7);


(lib.Symbol11 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#14395A").s().p("ADpVzQhTgPgGgDQgmgQAFgUQgGgUAmgTIgBgHQAAggAQgeQAQgeAHgIIgCg1IgKABQicAKh6glQgBAlgGAfQAHAHAMATQAMATADAVIAAAJQAbAPACAVQACAVgCACQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQiVBKh5ADQh4ADhJgXQhIgYgDgEQgZgNgHgbQgFgoATgmQAUgmAFgEQAyhABVgLQBNgHAwAnQAWATAQAYQAggFAigJQAigJAKgPIgCg4QhxgngGgGQgXgMABg2QABg2AKg5QgRgJgMgLIgLgIQgHgHAAgPQACgwAWg2QgSgIgEgNIgCgHQACgVAHgEQARgjAYhAQAYhAASg2IAUg7QANg2ACg6QABg7gEgqIgCgFQgfhMAlhOQAkhMAjgoQgDgVgBgRIgvgMIglgGQhggYhMgmQhigug6gmQg5gmgCgEQgmgtAEhLQAEhLAThAQAQg9ACgEQAPgiAJgoIgCgBIgDgCIAIgZQAKgtADglQAEhggDgKQAEgeAGgaIgKAJQgFABgJgVQgIgUA1gwQAuh5A1gtQA2gtAMAAQAHgIBHgkQBIgkB6gTQB4gTChAqQBIAUBOAnQACAAAmAYQAlAYAuAzQAXAYAUAeIgCgaQgBgCAIgIQANgIAdAHIADABIABAeIACBHQANAKAOANIAQhDIAIgeIADgBQAlgDAEATIAAABIgKAjIgZBQQAoAuAXA/QAXA/gSBPQgBAFgeA4QgdA3g4A1IACBXIABAkIgbgLIgGhaQgxAjhAgGQgvA/hDAoQgUBFgnA/QgmA/gqAyQAUA1gOAwIACABIAFAFQArAgAaApIAYAgQA+BIAuB4QAdBJALBWIgKCUQgIBqgQBeQgFCxgKB6IABABIABAEIgLBqIgCAFIgCACQgkAOgkAIIgPADQABAdAAAPQBCAVAxAAIAMgRQAxgwA+ADQA/ADAwAnQBGBDgHAtQgGAtgHACIgBACQhnA7h0AHQgkACghAAQhKAAg6gKg");
	this.shape.setTransform(66.9,140.4);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,-0.1,133.9,281.1);


(lib.Symbol8 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#14395A").s().p("ACzPaQhZgWgqgVQgqgWgBgCIgCgCIAAgCQgBgGAAgpQAAgoAMgoQgPgEgGgEIgCgDQAJAlAAAmIgBAsIgBACIgBABQgCADgpATQgpAUhXAVQhXARgsgHQgsgIgBgDIgBAAIAAAAQgdgbgBg2QAAgzAjgcQAXgRAagHQACgEADABIACABQAlgIAdgBQAXgBAJgDIAzgaQgNgGgGgMQgCgEAAgFQAAgFACgGQAHgMAOgHIgHAAIgCgBQgQAYgWADQgcABgRgXQgDgGAAgHQAAgQAPgVQgSgOgIg3QgOgJgMgKIgBgCIAAgCIAIg1QAHguANhEQgBgaAAgcQgBg+ALg4QgRgIgOgOIgBgCIAAgCQgBgFAQgwQAQgwArgrQiAgghLg7QhKg7gDgIIAAgBQgHgTABgzQAAgsABgbQgKAQgFAgQgEAhAAAcQAAABAAABQgBAAAAABQAAAAgBABQAAAAgBAAQAAABgBAAQgBAAAAAAQgBAAAAAAQgBAAgBgBQhehKgEhCQgEhCAHgFQBPkXCEiQQCDiQBbgjQBagmA+ANQA8AMAkAdQAjAdAKANQA0gpBkAUQBjAUBeA9QBvBnAOBZQAOBYgHAGIgWgUQgTgSgLgHQAKAlAAApQgICQg5B2QgGAmgPAmQACAKg0BNQg0BNiKAzIAMBLQAHAtADAcIAAACIgBABQAAAFgbAUQAHAwAPBPIALAyQAFASAEALQAQAfAVAWQAcAbABAbQgFAcgZAlQgaAlgZAGQgKABgKgDIgCABQg+ABgYgWIgCgDIgcAGIAABMQAjAFARAbQACAGAAAFQAAAFgCAGQgHAKgNAFIAzAdQAIADAXACQA3gCA9AoQAfAdABA0QgCA4gaAcIgBAAIAAABQgCADgqAIQgOADgTAAQgmAAg5gLgAgNLRIAVAUIAMgKQgOgCgJgKIgKACgAgiKgQAcAGANAOQAQgKAWgEQABgogBgcQgoAEgmgBIgBA7gAhuKdIAEgBIAAgCIgEADg");
	this.shape.setTransform(60.4,99.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-0.1,0,121.2,199.6);


(lib.Symbol7 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#14395A").s().p("AEFWhQhXgGgfgUQgegUABgEIAAgBIgBAAIgEgUQgDgPAFgKQAOgNASAEIAAgEQgBgTAKgjQAKgjAigiIgRgvQhmAZhuAFIgGARQAjAiAIAjQAKAjgBATIAAAEQASgEANANQAFAKgCAPIgFAUIAAAAIAAABQABAEgfAUQgcAUhXAGQhgAEhngRQhogQg0gkIgCgBIAAgDIAGgmIABgEQAGgeAQgjQAPgjAdgZQAjgdAwAFQA2AIAcAhQAygdA1gDQhmgHhYgtIgDgCIABgDIAMiSQAMiGAQiWQghABgjgBQgigCgVgJQg0gegOg6QgCgYARgNQAOgJAKABQAHABALgCQALgDAPgWQg9hOgahHQgYgLgBgCIgDgBIABgDQADggAchRQAdhRAmhTQAmhUAjgmIAPgPQhZAGgvgkQgBgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAgBABAAQAAgBAAAAQABAAABgBIARgMQAPgLAFgVQAFgZgbgdIgagYQg4gxhShkQhShkgsiTQgsiTA5i+QBCi5BRhKQBRhLBCgKQBBgKARAGQAKgNA4grQA3grBdghQBegiCLAXQCNAWCsCPQAAABABAAQAAABAAAAQAAABAAAAQABABAAAAIAAABQgBADgDABIgcAJQAbATAyBTQAyBUAHCZQAAApgGAvQgYCbg6CGQg6CGgxBYQgWAngSAcQgTAdgBALQAEAgAdAQQAdAPAEAAQADABAAADIAAABQABADgIATQgIATgWAMIAvAtIATgDQAOgMAWgJIALgFIAEgCIAFgBQAjgLAWAFQAJADAFAFQAJABAJACIABAAQgFgfAfgmQAcgYAzAMIAIABIgFAGQgBABgKARQgKARgBAXIABAJQAFgTAhgUIABAAIAAgBIAFAJQgJgEgRBBQBWAqAQCEQAGA/gPBGQgQBGgpA7IABABQg+BhhLAaQhKAZgqgEQASB2AMB/QANCAABBtIgBAqIAAADIgDABIg+AbQg8AZhfAcIAHAqQAPgBAqAGQAqAGAjAWQAcghA2gIQAvgFAkAdQAdAZAPAjQAQAjAGAeIAAAEQAHAhgBAFIABADIgDABQgzAkhoAQQhUAOhPAAIgkgBg");
	this.shape.setTransform(73.3,144.2);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-0.3,0,147.2,288.6);


(lib.grandfather = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 7
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AA8FvIgXgFQgMgEABgHIAAgBIAAgBQgBgFAJgGIAAgBQABgIADgHIAGgLIAAgKQghADgkgJIgBANQAGAGACAMIAAABQAJAHgBAHIAAAEIgCACQgoAUggABQggAAgTgGQgTgGgBgBQgIgEgCgIQgBgMAFgKIAHgMQAOgSAXgCQAVgCAOAKIAJALQAWgEADgEIAAgFIAAgHQgbgJgDgCQgCAAgCgEQgDgEAAgNQAAgJACgRIgGgFIgDgCQgDgDAAgEIAAgBIAAgBQABgMAFgMQgDgCgCgEIgBgDIAAgBQABgFACgCIALgZIALgfIAFgPQAEgTAAgSIgBgSIAAAAQgFgJAAgJQABgRAIgNQAIgPAHgIIAAgHIgHgCIgEgBIgFgBIgFgBQgXgFgWgLQgagMgPgKIgQgLQgKgMAAgTQABgVAFgTIAFgRIAGgRIgBgBIACgIIAEgVIAAgQIAAgLIAAgBIABgJIAAgBQgDgBgCgGIAAgBQAAgIAMgLQAMgfAOgMQAOgMAEAAQADgDATgJQATgKAggEQAegFAqALQAUAFAUAKQABAAAKAHQAKAGAMANIAGAIIADgDQAEgDAJACIADABIAAANIABAOIACADIAEgOIACgJIACgBQANgBABAHIABABIgFAOIgFAQQAUAXAAAbQAAAIgCAJIgIAPQgIAPgOAOIAAASIABARIgNgFIAAgIIgBgNQgNAHgNgBQgNARgQAJQgJAegaAhQACAGAAAHIgBALIABABQAKAIAIAMIADAEIADAEQATAWAKAcQAIAVADAVIgBAIIgDAnQgCAYgDAUQgCAwgCAeIAAABIgCAcIgBACIgBABIABAAIgCABQgJAEgKACIgBAAIgBAAIAAAGIAAACQAPAEALAAIADgDQANgNASAAQARABANALIAAAAQAUATgCANQgCANgCAAIgBABQgcAQgeACIgSAAQgUAAgQgCgAAyE5IgBABIgFAJQgFAHAAAIIABADIgCABQgHADAAAFIAAAAQgCACAJAFIAXAFQAWADAdgBQAegCAbgPQABgBACgKQABgKgRgRQgMgKgPAAQgQgBgLAMIgEAFIgCAAQgMAAgTgGIgBAAIAAgCIAAgEIgBgHIAAgDIAGgBIABAAQAJgCAIgEIACgNIABgOIAAAAIAAgBIAEhOIAAgBQADgUACgYIADgmIAAgEIAAgEQgCgUgIgVQgJgagTgWIgGgIQgIgMgJgHIgCgBIgCgBIABgCIABgMQAAgHgDgFIgBgCIACgBQAbgiAJgdIAAgBIABgBQAPgJAOgRIABgBIABAAQAOACAOgJIAEgDIAAAMIABAOIACABIAAgRIAAgMIAAgBQAPgOAHgOIAIgPQACgIAAgIQAAgYgTgXIgBgBIAEgPIAFgPQAAgDgHAAIgDANIgCALIgCAEIgLgJIAAgMIAAgOQgHgBgBABIgBABIABAIIAAAIIgFgIIgLgOQgMgNgJgGIgKgGQgUgKgTgFQgqgLgdAFQggAFgSAJQgTAJgBACIAAAAIgBAAQgDABgNALQgOALgLAfIAAAAIgBABQgMALABAEIAAAAIABADIAEgEIADgDIgBAIIgDAOIAAABIAAALIAAAQIgEAWIgBAFIABAAIgBACQgCAMgEAIIgFARQgFAQgBAWQAAARAIAKIAQAKQAPAKAZAMQAWALAXAFIAEABIAFABIAOAEIABABIABAKIAAABIgBABQgHAIgIAOQgIANAAAQQAAAIADAHIABACIAAABIABASQAAATgEATIgGAQIgLAfIgKAaIgBAAIgBAEIAAACQABACAEACIACABIgBACQgGAQAAAJIAAABIAAAEIADACIAHAFIACABIAAACQgDASAAAKQAAAOAEABIAfAMIACAAIAAASIAAAAQgDAFgJACIgTAEIgBAAIgBgBQgFgGgEgEQgMgKgTACQgVACgNAQIgGAKQgFAKACAKQABAFAGADQAAABATAGQASAGAfgBQAfAAAmgTIAAgCQABgFgHgFIgCgBIAAgDQgBgJgHgHIgBgBIAAgBIACgSIAAgDIADABQAlAKAigDIAFgBg");
	this.shape.setTransform(41,5.2);

	this.instance = new lib.Symbol11("synched",0);
	this.instance.setTransform(23.6,-31.4,0.261,0.261);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgGErIgSAAIgDAAIgBgEIgBgQQAAgLACgFQgDgCgBgDIAAgCQABgEACgDQgDgCAAgDIABgDQABgFALgEIAAAAIgIgCIgCAAIAAABIgDAAIgNABQALAEABAFIABADQAAADgDADQACACABAEIAAACQgBADgDACQACAFAAALIgBAQIgBAEIgDAAIgSAAIgjAAQgTgBgOgDIgCgBIAAgBQgCgCAAgNQgBgMALgJQAKgFAMACQALADAFACIADgCQgCgCgBgDQABgFAEgCQgCgCAAgDIAAgBIABgEQADgDAGgBIgLgBIgDAAIAAgDIgDgPQgCgPAAgQIAAgBIgEgCIgCgBIAAgCIAEgRIAIggIgMAQIgGAJIAAAHQAAANgHAGIACAJQAAAGgDAEQgDAFgEAAQgEAAgGgNQgDALgFAEQgDACgDgBQgFgBgBgLIADgLQgPAIgHgEIgBgEIAAgBQACgHALgJQgJgGgCgLIAAgBQABgHADgBQADgCAHAEQAFADAJABQAPgHAGAAIALgQIANgTIgBAAIgCgCIAAgDQAAgBAGgNQAHgOATgLIgIgEIgNgGQgQgIgRgKQgSgLgNgNQgWAAgMgIQgLgJgDgMQgFgWARgGQAKgDAKAFIAAgFQgIglgIgRQgHgSgGgFIgMAFIgHADIgJAFIADgJQAEgMAHgKIALgRIgPABIgIABIADgHQAMgXAMgOQAMgOAHgGQgPgKgOgHIgOgHIgEgCIACgEQALgQAJgEQAJgEABAAIACAAIACACIANAUIAOAUQArgqAtgHQAsgIAVADIASABQAUACASgDIAVgEIAKAAIAPgBIgNAIQgQAMgEAIQA3AMAdAUQAcAUAKARQAKASAAAEIADAJIgEgCIgEgCIAAABIgGgDIgRgEIgPgDQAlAqALAiQALAigBAJIACAJIgIgFQgSgKgMgDIAEANIADAJIgEAAQgsALgSASQAKgCAKAEQAOAJgIATQgFALgOAIQgNAHgXgFQgOAOgUAIQgUAJgUAEQAPANAHAYIABADIgDACIgCAAQAFAQAIAkIAFAGQARATAAAHQAAABAAABQAAAAAAABQAAAAgBABQAAAAAAAAQgEAEgOgIQgFAMgIABQgDAAgCgCIgBgCIACgFQgDABgCgBIgBAAQgCASgDAPIgBADIgCAAIgRADQAGAAACADIABAEIAAABQAAADgCADQAEABABAFQAAADgDACIADACQAFgCALgDQAMgCAKAFQALAJgBAMQAAANgCACIAAABIgCABQgOADgTABIgZABIgIgBgAgZDQIABAIIAAAJIAJACIADAAIAAAJIgCABQgLADgBADIAAABIADACIAEADIgEADIgDAEIAAAAQAAABABAAQAAABAAAAQABABAAAAQABAAABAAIACACIgBACQgCADgBANIABAPIAiAAQAbAAAUgEIABgLQABgLgIgGQgKgFgMADIgNAFIgBAAIgBAAIgIgGIgDgCIADgCIADgDIgDgCIgFgCIADgDQACgCABgEIAAgBQABgBgJgBIgDAAIAAgJIADAAIATgDQADgPACgSIAAgCIACAAIADgBIACgBIABABIAEgBIAIgBIgDAFIgCAGQAFgBAFgLIAAgEIAEACQANAIAAgCQAAgDgFgHIgLgNIgGgGIAAgBQgJgogFgOIgBgDIAFgCQgGgYgRgMIgFgDIAGgCQAUgEAWgIQAWgJANgPIABgBIACABQAVAEAMgGQANgGAEgKQAHgPgLgGQgMgGgPAKIgEADIAAgHIABAAQAIgLASgLQARgMAdgHIgEgOIgEgKIAFABQALACAXAMQAAgMgMgiQgMghglgoIgFgFIAHAAIAWADIAMAEIAAgBIAEABIAFACQgBgMgagcQgbgdhMgQIgDgBIABgDQACgHASgQQgKABgQADQgTADgUgCIgTgBQgUgCgsAHQgtAIgqAqIgCACIgCgDIgNgTIgPgXQgGgBgTAWIATAJQANAHAOAKIACACIgCACQgGAEgMAOQgMAOgNAXIATgBIAFAAIgDAFIgKAPQgIALgFAMQAIgEALgDIACgBIABACQATATAMA9IAAAAIgBAPIgDgDQgKgGgKADQgMAEAEARQACALALAIQALAHAUAAIABAAIABABQANANARAKQARAKARAIIAeAPIgFADQgSAIgHAMQgIAMAAAFIAEACIgBACIgPAXIgLAQIgBABIgBAAQgHAAgPAHIAAABIgBAAIgJgCIgIgEQgBAAgBgBQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAAAABQgBAAAAABQAAAAAAAAQAAABAAAAIAAABQADAKAJAEIAEACIgFADQgNALAAAEIAAAAQAAADAUgLIAHgDIgDAJQgDAHAAAGQgBAFADACIACgBQACgBABgGIADgJIADgLIAEAKIADAIIAEAGIACgCQACgDAAgEQAAgEgCgEIgBgCIACgCQAHgEAAgMIAAgGIgBgCIAdgoIAFADIgLAlIgFAYIAFACIAAACIAAAEQAAANACANIADARIAIABIAGABIADAAIAAAJIgDAAQgLABABABIAAABIADAEIADAEIgDACIgFADIADADIADACIgDACIgIAGIgBAAIgBAAIgNgFQgLgDgKAFQgJAHABAKIABALQAUAEAbAAIAkAAIABgPQgBgNgCgDIgBgCIACgCQABAAABAAQAAAAABgBQAAAAAAgBQABAAAAgBIAAAAQAAgBgBAAQAAgBAAAAQAAAAgBgBQAAAAgBgBIgDgCIADgDIADgDIAAgBQgBgDgKgDIgDgBIAAgJIADAAIAOgBIACgKIABgIgAC6i4IAAAAIAAAAgAC6i4IAAAAIAAAAg");
	this.shape_1.setTransform(12.2,10.6);

	this.instance_1 = new lib.Symbol12("synched",0);
	this.instance_1.setTransform(-9.2,-19.1,0.261,0.261);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgIgFIgBgCIAEAAQAEgBABgBIAEgCIAEACIgGgOIAHgDIAAAEIgEAxIgFAAQgFgWgDgKgAgCgDIACAQIACgLIABgGIgFABg");
	this.shape_2.setTransform(-87,9.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AhnGbIgDAAIgCgGIgDADIgCAAQgIgDgGgDIgCgDIABgCIAGgJIAMgPIgFgEIgCgCIABgDIASgaQAPgWAQgQQgCgDgBgDQAAgDACgCIAEgDIgBgUIgCgiIAAgXQgFACgEAAIgFgCIgBgBQgEACgGgCQgFgEgCgGIgCgJQgIAAgIgNQgFgHAAgGIABgEQADgGACAAIABgBIgQgkQgIgSgCgLIAAAAIABgEQgMgLAAgGIABgCQABgEAEAAQgCgDAAgEQAAgGADgCQAEgDAGAAIAOABIALgcIAJgUQAEgIAGgFIgGgEIgDgBIAAgEIAGgLQAFgKAFgGIAEgCQgPgQgPgaQgQgZgJgkQgdgMACgRIAAgEQACgIAHgFQgDgVAAgVQAAgPAFgOIgFgEIgEgDIAAgDQACgNAFgCIADgCIABACIAGAJQAXgpArgSQAogOAbAAIAJgBQANgBAKgEQAogSAPgNIALgHIABgBIABAAIAHABQAFADAHAFQAKAIACAZIgBANQgEASgTAPQACAHAAAMIgBAYIgBADIAAAFIABAHIAAADQAKAGAGAGIAHAHIAAABIAAABIABAKQgBAjgGAOQgFAOgBAAIgBABIgCAAIgFAAIABAGIAFAQQAFAQABAMQAAAGgCAGQgGAUgYAPQgYAQglAHIgKADQACADAAADQAAAEgDAIIgCALIgBAFIACACIAEAIIAKAYQAGAMAGAJQAIgDAFADQAGAFAAAIQAGgBAFACQACACAAADIAAABIAAADIASAAIARAAIAQgQIARgOQAGgDAIADQAIACAFADIACABIgJARIgBAAIgHAEIAEAHQAHAJACAIQAAACgDADQgFADgIgCQgHgDgHgEQgFAFgQgBIgXADIgjACIgDAEQgGAFgFABQADAPAAAMQAAAMgDAKIAAAEQgBAOgEACQgCAIgJAIIAOAvQAHAaADAQQAEATABAaIAAAkIAAACQANAFAGABQACgIANgCQAIgBAFAFQAGAGAAAJIAAACIgBACIgCABIgQAGQgQAGgVABIgCABIgDAAQgCACgNgBIgEAAIAAgEIABgHQAAgHACgJQgHgBgEgDIgBgCIAAgCIAFgtIADgbQgFgCgBgGQABgFAFgDIgPgsQgGgWgEgHQgGABgTAAIgEAaIgEAoIgDAiIAAABIgBABIgJAPIgRAfIgNAaIgCACIgDAAIgEgBIABAAIAFABIAEABQAGgFAOACQAHADACAHQADAJgEAJIgBABIgCAAIgNADIgTABIgRgBgAhoGQIACAGQAoAAAGgDQACgDAAgEIAAgFQgCgFgFgCQgFgBgFABIgGADIgBAAIgNgCIAAAAQgDgCgCgGIgBgEIAFABIAHACIAOgZIARgeIAJgRIADglIAFgqIADgXIAAgDIADAAQAXABAFgCIACAAIABABQACAGAGASIAMAjIAGAUIABACIgCABQgGAEABAAQAAABABAAQAAAAAAABQABAAAAABQABAAABAAIABABIABABIAAACIgDAeIgFArQAEADAGAAIADAAIgBADQgDARABAHQAIAAADgBIABgGIAAgFIADAFIADAFQATgBAOgFIARgGIAAgBQAAgHgEgEQgDgEgGABQgKADgBAFIgBACIgCAAQgKgBgOgFIgGgDIAFgCIAAgCIgBgkQAAgZgEgTQgDgQgIgbIgOgvIAAgCIABgBQAKgHACgIIAAgBIAAAAQACAAACgNIAAgEIAAgBQADgJAAgMQAAgMgEgRIgBgDIAEAAQAEABAGgGIAFgFIABAAIAkgCIAXgDIAAAAQAQAAAEgEIABgBIABABQASAKAFgDIAAgCQgBgGgGgHQgGgIAAgCQADgGAIgCIAFgKQgMgHgIADIgOAMIgSARIAAABIgCAAIgUAAIgUAAIgEAAIACgDIABgFIAAgBQgDgCgHABIgDABIAAgDQABgGgFgGQgFgBgEADIgCABIgCgCQgGgJgHgOIgLgZIgFgLIgBAAIABgGIACgMIADgLIgEgHIgDgDIATgEQAjgHAXgOQAYgPAFgSQACgJgBgIQgBgJgEgLIgDgJIgCgIIgDgNIAEABIAHAAQACgCAEgNQAFgOAAgeIAAgJIgGgHQgGgGgLgGIgEgCIAEgCIAAgCIgBgGIgBgBIACgJIABgXQAAgPgCgEIgBgCIACgCIAAAAQATgNACgQIACgNQAAgPgIgKQgMgMgFAAIgLAHQgQAOgoASQgLAEgOABIgJABQgaAAgnANQgqASgXAqIgCAEIgCgCIgIgKIgCAJIAEAEIADADIACABIgBABQgFAPAAAPQAAAWADAUIABACIgCABQgGAEgCAHIAAADQgBAOAaAKIABABIABABQAJAmAQAaQARAaAPAQIADADIgKADQgEAEgEAIIgGAMIAJAFIADACIgDACQgHAGgEAIIgKAVIgLAdIgBACIgCAAQgSgDgDADQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAABIACAGIADAFIgGABIgCABIAAAAQAAAEAKAKIADADIgCACIgBACQAEAQAXAxIABADIgDABIgDACIgCADIAAACQAAAEAEAHQAHALAGgBIACAAIABADIACAJQACAFADADQADAAADgBIAAgBIABAAQABAAAAAAQABAAAAABQABAAAAAAQAAABAAAAIAAABIAEABIAGgCIAGgFIAEBaIgBABIgEADIAAABQAAABADADIACACIgCACQgPAOgPAVIgUAdIAHAEIAEABIgDADQgGAFgGAIIgIALQADACAIACIAEgEIADgEIABAGg");
	this.shape_3.setTransform(-76.4,-0.4);

	this.instance_2 = new lib.Symbol13("synched",0);
	this.instance_2.setTransform(-92.5,-41.4,0.261,0.261);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("ABEF7QgYgCgIgFQgJgGAAgCIAAgBIgCgIQAAgDACgCQACgEAFAAQgBgMAPgTIgDgJQgcAHgXABIAAABQANATgBAMQAFAAACAEQACACAAADIgCAJIAAAAIAAAAQAAACgJAGQgGAFgYACQgZABgcgFQgbgEgOgKIgCgBIAAgCIACgKIAAABIABgDIgBABQACgJAEgJQAFgKAHgHQALgIANACQANABAJAJQAEgDAGgCQgTgDgQgJIgCgBIAAgCIADglIAHhJQgSABgMgEQgGgEgGgGQgFgIgCgHQAAgIAFgEQAFgDADAAIABAAQADABAEgFQgNgRgIgUIgGgDIgCgBIAAgDQABgIAHgVQAIgVAKgWQAKgWAJgJQgVAAgKgJQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAgBIACgDIAEgCQADgDABgEIABgCQAAgEgGgGIgGgGQgMgLgSgTQgRgUgOgcQgNgdgBgkQgBgYAJgbQARgwAVgUQAVgUASgDQARgEAGACQAEgFAOgLQAPgKAXgIQAZgKAkAGQAlAGAuAmIABADIAAABQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAIgDABQAJAIALAWQAMAVABAkIAAABIgCAXQgGApgPAjQgQAjgNAXIgJAQIgGALQABAHAGADIAJAEQAAAAABAAQAAABABAAQAAABAAAAQAAABAAABIAAAAIgBAFQgCAFgFAEIAJAJIADgBIAJgFIAEgCIABAAIACgBIgBAAQAKgDAGACIAFACIABAAQAAgIAIgJQAIgHAPADIAGACIgEAFIgEAGIAFgDIACgBIAEAGIgCABQgCAAgDANQAWALAEAiIAAAKQABAcgRAeIAAAAIgBACQgPAYgSAIQgTAIgOgBQALBNAAAuIAAAGIAAAGIAAACIgCABIgQAHQgPAGgYAHIABAHIAPABQAJACAJAFQAIgJANgBQAOgCAKAIQAIAHAEAKQAEAJACAJIgBgBIABADIAAgBIACAKIAAACIgCABQgOAKgbAEQgXAEgVAAIgJAAgAAfFgIAAADIABAHQAAABAHAFQAIAEAVACQAYABAbgEQAagFANgIIgBgJIAAgBQgDgSgOgOQgIgGgLABQgMABgIAJIgCABIgCgBQgIgFgLgCIgOgBIgCAAIgDgQIACAAQAXgHAPgGIASgIIAAgFIAAgFQAAgugLhPIgBgDIADAAQANABASgHQARgHAPgVIgBgBIACgCQASgdgBgcIAAgJQgEgigVgIIgCgBIAAgCIADgKIgCADIgEAJIgCgMQABgKAEgFQgKgCgGAFQgHAJABAHIAAADIgJgBIgBgBIgCgBQgFgBgIACIgBABIgBAAIgDABIgJAGIgBAAIgHABIgQgPIAEgCQAHgFABgGQgEgBgHgEQgGgFgBgIQAAgEAHgKIAJgPQANgXAPgjQAPgjAGgoIACgWIAAgBQgCgmgNgWQgMgVgIgFIgDgDIAEgBIAGgCQgsgkgkgFQghgGgYAJQgYAIgOALIgRAOIgBABIgCAAQgDgCgRADQgQADgVATQgVATgRAvQgIAbAAAXQABAjANAcQAOAbARATQARAUALAKIAHAGQAHAHAAAHIAAADQgEAJgGADQAKAHAWgBIAHAAIgEAEIgFAFQgIAIgKAVQgJAVgIAVQgHAUgCAJIAHADIAAABQAJAVAOARIABACIgBABQgHAKgGgCIgBAAIgEACQgEADABAEQADAOAMAHQAGADAJAAIAQAAIADAAIAAADIgHBGIgEApQAVALAbACIAAAFQgNABgMAHIgCABIgCgBQgIgIgMgCQgLgBgIAGQgOAOgDASIAAABIgBAJQANAIAbAFQAaAEAYgBQAVgCAFgEQAIgFAAgBIABgHIAAgDQgBgBgFAAIgDABIAAgEQABgFgBgIQgCgJgJgJIgBgBIADgHIACAAQAXgBAegHIACgBIAGAQIgBABQgJAJgCAJQgDAIABAFIAAAEIgDgBIgCAAQgBAAgBAAQAAAAgBAAQAAABgBAAQAAAAAAAAg");
	this.shape_4.setTransform(-51.2,3.6);

	this.instance_3 = new lib.Symbol7("synched",0);
	this.instance_3.setTransform(-70.4,-34.1,0.261,0.261);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgJgCIAJgDIAAACIAEACIAGABIgJAFg");
	this.shape_5.setTransform(-20.3,35.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AAAAMQAAgCgKgDIgCAAIABgSIACAAIATgBIADAAIAAACIAAAQIAAACIgCABQgGABgDACIgCABgAgGgGIAAAJQAFABACADIAGgDIABgFIAAgGIgOABg");
	this.shape_6.setTransform(-20.2,33.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AAuEEQgYgGgLgGQgLgFAAgBIAAgBIgBgCIAAgBQgGAGglAKQgXAEgMgCIgNgDIAAAAIgBAAQgIgIAAgPQAAgPAKgIQAFgEAIgDQAAAAABAAQAAAAABgBQAAAAAAAAQABAAAAABQAKgDAHAAIAIgBIAJgEIgCgDIgBgDIgEABQgJAAgFgIIgBgEQAAgEAEgGQgFgEgCgMIgGgFIgBgBIAAgCIACgOIAGgeIgBgHIAAgHQAAgRACgMIgGgFIgCgCIABgCQgBgBAEgLQAEgMAJgLQgggKgTgNQgSgPgBgCIAAgBIgCgIIgBACQgBAAAAAAQgBABAAAAQgBAAAAgBQgBAAgBAAQgZgVgBgSQgBgSACgBQAUhIAigmQAjgnAZgKQAsgUAhAiQAQgKAaAGQAaAGAXAPIAAAAQAdAbAEAYQAFAYgDADIgCADIgCgCIgIgHIACAOQgBASgFATQgFASgHAOQgBAKgEAKQABACgOAUQgNAUgkANIADAUIACARIAAABIAAABIgHAHIAFAfIACAHIABAGIADAHQADAIAGAFQAIAIAAAJQgBAHgHALQgHAKgJACIgFAAIgBAAIgNgBQgHgBgEgEIgDABIAAAIIAAAHQAKADADAHIABAEIgBAEIgCACIAJAGIAHABQAPgBARALQAJAJAAAOIAAABQAAAPgIAIIAAAAIAAABIgBAAQgBABgLACIgIABQgKAAgQgDgAAEDLIADABIgBADQgEAMAAALIABAIQACAFAqAMQAVAEAKgCIAMgDQAGgGAAgNIAAgBQAAgMgHgHQgPgJgOAAIgJgCIgSgKIAFgCQABgBAAAAQABAAAAgBQABAAAAAAQAAgBAAAAIABgBIgBgCQgEgGgHgBIgCgBIAAgYIALgCIABACQAEAEAQABIABgBIABABIAEAAQAFgCAGgIQAHgJABgHIAAgBQgBgFgGgGQgGgGgEgJIgDgIIgBgGIgCgHIgFghIgBgCIACgBQAFgDABgCIgDgTIgDgTIAAgCIACgBQAjgMANgTQAOgUgBgCQAEgJACgLIAAAAQAGgOAFgRQAFgSAAgSQAAgKgCgKIgCgGIAGADIAKAIIAAgBQAAgJgGgTQgGgSgWgUQgagQgYgFQgZgEgMAJIgCACIgDgDQgFgIgSgJQgQgJggANQgYAJgiAmQgiAmgTBHQgBABgBAJQAAAHAFALQAEALAOALIACgPQABgIADgEIAFgHIgBAbQABARABAAQABADATAOQATAPAgAHIAFABIgEADQgKAKgEALIgEAOIAHAFIABABIAAACQgDANAAARIABAPIgFAcIgDAPIAGAEIABABIAAABQACANAFADIABACIgBACQgEAFAAADIABACQADAEAGAAQACABAGgHIABgBIACABIABgBIACAFQgDACgBACIgBACIAAABQABACADACIAEACIgRAJIgJACQgIAAgJACIgBAAIgBAAQgHACgFAEQgIAHAAAMQAAAMAHAHQABABAKABQALACAWgFQAogLADgEIABgLQAAgJgDgJIAEgDIAEACg");
	this.shape_7.setTransform(-20.3,16.2);

	this.instance_4 = new lib.Symbol8("synched",0);
	this.instance_4.setTransform(-36.1,-9.8,0.261,0.261);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_4},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.instance_3},{t:this.shape_4},{t:this.instance_2},{t:this.shape_3},{t:this.shape_2},{t:this.instance_1},{t:this.shape_1},{t:this.instance},{t:this.shape}]}).wait(50));

	// grandfather
	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#D9F7FC").s().p("AgMAQQAJgKABgGIACgKIACgJQAHACAEAIIgWAdIgDgEg");
	this.shape_8.setTransform(71.6,-17.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#B3F1FF").s().p("AgQAAQACgTAOgCQAPACACATQgCAVgPABQgOgBgCgVg");
	this.shape_9.setTransform(71.6,-17);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#72B7DD").s().p("AgSAAQABgWARgCQARACACAWQgCAXgRACQgRgCgBgXg");
	this.shape_10.setTransform(71.6,-17);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#494949").s().p("AgEAGQACgKACgCQAEADABACIgJAIIAAgBg");
	this.shape_11.setTransform(70.3,-27.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#2D2C2B").s().p("AgGAJQgBgJADgFIAEgGIAAAAIAAAAQAIAHgBACIABABIgBABIgHAFIgEAFIgCACg");
	this.shape_12.setTransform(70.3,-27.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#494949").s().p("AgEgBQABgCADgDQADACACAKIAAABIgJgIg");
	this.shape_13.setTransform(76.7,-27.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#2D2C2B").s().p("AAFAKIgFgFIgGgFIgBgBIABgBQgBgCAHgHIAAAAIAAAAIAFAGQADAFgBAJIAAADg");
	this.shape_14.setTransform(76.6,-27.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#BA8954").s().p("AgKAIIAFgIQAFgGAKgDIABAAIAAAAIgBABQgDAAgGAEQgEAEgGAKIAAAAg");
	this.shape_15.setTransform(63,-12.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAAAAIAAgBIAAABIAAACg");
	this.shape_16.setTransform(67.2,-20.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgCAAQABgEABAAQADAAAAAEQAAAFgDAAQgBAAgBgFg");
	this.shape_17.setTransform(67.3,-20.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAAAAIAAAAIAAAAIAAABg");
	this.shape_18.setTransform(73.2,-19.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgCAAQABgEABAAQADAAAAAEQAAAFgDAAQgBAAgBgFg");
	this.shape_19.setTransform(73.3,-19.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FCF7F0").s().p("AgFASQAMgSAAgWIAFADIAAAEQgDAigUAEIAGgFg");
	this.shape_20.setTransform(76.7,-18.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgOAlQgKgLABgWQABgOAFgNQAGgNAHgGQACAHAFAOQAIAPAOAGIgBAEQgDAlgVACQgIAAgGgGg");
	this.shape_21.setTransform(75.5,-20.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#CC9B66").s().p("AADASQgBgUgIgRIADADQAJANABAXIgEgCg");
	this.shape_22.setTransform(77.2,-22.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#DDAF78").s().p("AgGAAQgGgOAAgFQACgBADAAQAFAAADAFQALANACAXQgOgHgGgOg");
	this.shape_23.setTransform(76.6,-22.7);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#BA8954").s().p("AAAATIAAAAIAAgMQABgKgCgPIABAAIABALQACAIgCASg");
	this.shape_24.setTransform(78.9,-6.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#CC9B66").s().p("AgDgDIAAAAQADAAAEADIAAAAIgEAEIgDgHg");
	this.shape_25.setTransform(70.5,-25.2);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FCF7F0").s().p("AAFAFQAEgSgHgTIAEgEQAJAPgEAWQgFAfgSAFQAMgMAFgUg");
	this.shape_26.setTransform(70.5,-21.2);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#DDAF78").s().p("AAHgMQAFAAAEAFIAAAAIgLAIQgIAIgMAEQAKgXAMgCg");
	this.shape_27.setTransform(69.3,-24.4);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgQAgQgJgKAEgVQABgGADgJIAAAAQAOgFAIgHIAMgKQAIAPgDAWQgGAigVACQgHAAgEgFg");
	this.shape_28.setTransform(69.4,-21.2);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#BA8954").s().p("AABAVIABgOQAAgKgFgSIAAgBQABABACAMQAFAKgBAVIAAABg");
	this.shape_29.setTransform(77.8,-7.1);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#BA8954").s().p("AgHABIABAAIAEAAQADAAAGgDIABAAIgBABQABABgFACIgDABQgCAAgFgCg");
	this.shape_30.setTransform(70.1,-6);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#BA8954").s().p("AgRgDIgBAAIABgBIAKAEQAHADANgDIAGAAIgBAAQgBABgKADIgEABQgHAAgNgIg");
	this.shape_31.setTransform(68.9,-6.6);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#494949").s().p("AgDAEIAAgBIACgDQABgBADgCIABAAQgCABgDAGg");
	this.shape_32.setTransform(64.2,-11);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#494949").s().p("AACAIIgBgFQgBgEgDgGIABgBIACAFQADADABAHIgDABg");
	this.shape_33.setTransform(70.1,-10);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#606363").s().p("AAKAVQgDAAgEgDQAHAAAFgBIAFgBQAGgBAIACIAGABIABgCIgCgMQgCgIgLgKIAGADQAIAEADAGQAEAFABAEIACAMIgBACIgGgBQgIgCgFABIgFABIgJABIgGgBgAgcALIgEgDIAJgBIAIgCQAGAAAEAEIgIABQgFACgEAAIgGgBgAgoAGIgJgBIABgDQAFAAACACIABACgAgJgSIgBgBIgDgCIAGACIgBABg");
	this.shape_34.setTransform(67.7,-11.3);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#777777").s().p("AArAVQgIgCgFABIgFABQgIACgHgBQgFgCgEgFQgCgFgFgBIgHACQgIACgHgCIgEgDQgCgCgGAAIgJgBQABgEAHgIQAFgJALgEQALgEANAJIABABIAAAAIAKgCQAKAAAMAFQAIAEADAGQAEAFABAEIACAMIgBACIgGgBg");
	this.shape_35.setTransform(67.7,-11.3);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#494949").s().p("AArAYIgPgCIgFABQgHACgHgBQgGgCgDgFQgCgFgDAAIgIABQgIADgHgCIgGgEQgDgCgFgBIgJAAIgBAAIAAgBQAAgCAHgKQAGgLANgGQAMgDAOAKIALgCQAKgBANAGQALAGAEAKQAEALAAAHQAAABAAAAQAAABAAAAQgBABAAAAQAAAAgBABIgBAAIgHgBg");
	this.shape_36.setTransform(67.7,-11.3);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#704C2C").s().p("AgFAdQgJgGgEgLQgFgLAAgIQgBgNAHgFQALgGANAFQAOAFADACQAAAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAAAIgCABIgOgFQgLgEgKAGQgGAEAAAMQAAASAQAMQAAABAAAAQAAAAAAAAQAAABAAAAQAAAAAAAAIgBABIgBAAg");
	this.shape_37.setTransform(67.1,-14.9);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#DDAF78").s().p("AgFAdQgJgGgEgLQgFgLAAgIQgBgNAHgFQALgGANAFQAOAFADACQAAAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAAAIgCABIgJAKQgJAIgFALQgHAKAFAEQAAABAAAAQAAAAAAAAQAAABAAAAQAAAAAAAAIgBABIgBAAg");
	this.shape_38.setTransform(67.1,-14.9);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#4C2000").s().p("AgFAGIgOgSQAFgDAMAAQAKAAAMAOIgGAJQgEAIgFAAQgEAAgGgKg");
	this.shape_39.setTransform(67.1,-8.8);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#351901").s().p("AgJAEQgKgLgCgFIgBgBIACAAQABgCAOgCQAMgCAQARIAAAAIAAABIgGAJQgEAJgHABQgGgBgJgNg");
	this.shape_40.setTransform(67.1,-8.8);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#18607F").s().p("AASASIgkgiQgBAAAAAAQAAAAAAgBQAAAAAAAAQAAAAABgBQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAABAAIAjAiQAAABABAAQAAAAAAAAQAAABAAAAQgBAAAAAAIAAABIgBgBg");
	this.shape_41.setTransform(75,-13.7);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#D9F7FC").s().p("AgIAJQAIgFAAgGIgCAAQACgGADgEQAFAEAAAIIgNANIgDgEg");
	this.shape_42.setTransform(65.7,-18.3);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#B3F1FF").s().p("AgIAAQABgOAHgBQAIABABAOQgBAPgIABQgHgBgBgPg");
	this.shape_43.setTransform(65.7,-18.3);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#72B7DD").s().p("AgLAAQABgQAKgBQALABABAQQgBARgLACQgKgCgBgRg");
	this.shape_44.setTransform(65.7,-18.3);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#704C2C").s().p("AgRAlQgJgLADgVQADgRAJgPQAJgPAJgBQAFAAAEAGQAGAGACANQACAMgCALQgHAkgVACQgIAAgFgGg");
	this.shape_45.setTransform(69.4,-21.5);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#704C2C").s().p("AgPAoQgLgMABgXQABgSAIgQQAIgQAKgBQAGAAAFAFQAGAIAEANQADANAAAMQgBATgIALQgHAMgKAAQgJAAgGgHg");
	this.shape_46.setTransform(75.4,-20.4);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#000000").s().p("AAFABQgHgBgCABQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAQACgCAJACIAAABIAAABIgBgBg");
	this.shape_47.setTransform(90,-15.3);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#000000").s().p("AgKAIQAAgCAFgGQAFgIAKgBQABAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABIgBABQgKAAgDAGIgFAJIgBABQgBAAAAgBQAAAAAAAAQAAAAAAAAQAAAAAAgBg");
	this.shape_48.setTransform(89.7,-15.1);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#000000").s().p("AgLAUQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIACgBIAKABQAHAAAKgKQAKgLgGgIQgHgJgNAEQgKAFgHALIgGALIgBABQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAABAAQAAgCAGgKQAHgMALgGQAPgEAIAKQAHALgLAMQgKAKgJAAIgGABIgFgBg");
	this.shape_49.setTransform(89.4,-14.9);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#DDAF78").s().p("AgLAUQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIgFgDIgGgDQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAABAAQAAgCAGgKQAHgMALgGQAPgEAIAKQAHALgLAMQgKAKgJAAIgGABIgFgBg");
	this.shape_50.setTransform(89.4,-14.9);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#7F7D7A").s().p("AgEACIgBgBIABgBQADgBADAAIAEAAIAAABQgIAAgBACg");
	this.shape_51.setTransform(89,-20.6);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#494949").s().p("AABADIgDgFIAAAAQAFACAAABIgCACg");
	this.shape_52.setTransform(92.6,-18);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#7F7D7A").s().p("AgJAhIAHgMIABgCIABABQACAFAHAAQAAAAAAAAQABAAAAgBQAAAAABgBQAAgBAAgBQABgEAAgIIgCgOIgBgBIABAAQAIgIABgHIAAgEQgHgNgLgGQANADALALIAAAFQABAHgGAIIgBABIABABQAHAOABAMQAAABAAABQAAAAAAABQAAAAgBABQAAAAAAAAQgHABgFgDIgCgCIAAADIgDALQgDAKgHAHQAAgHgJgJgAgZgrIgCgFIACAAIABAFg");
	this.shape_53.setTransform(90.8,-16.6);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#999999").s().p("AgEAfIgSgLQgKgFgCgDQgBgBAEgKIAEgHIgBgBQgEgHgBgEIAGgHIALgLIABgBIgCgEIgEgHQAHgBAOADQARADAOAOIABAEQAAAHgFAJIgBAAIABABQAHAOABAMQAAABAAABQAAAAAAABQgBAAAAABQAAAAgBAAQgGABgFgEIgCgBIAAACQAAACgDAKQgDAKgIAHQgBgHgJgLg");
	this.shape_54.setTransform(90.1,-16.6);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#494949").s().p("AAFAxIgCgHQgDgGgFgGIgSgKQgPgJAAgCIAAgBQAAgDAFgHIAEgHQgIgHgBgEIAAgBIADgDIASgQIgEgHIgCgGIABAAQACgBAUABQATABASARIgBAJQgDAJgDAGIAGAMQADAKAAAHQAAAGgDABQgDABgEgCIgGgEIgEAQQgDALgIAGIgCABg");
	this.shape_55.setTransform(90,-16.3);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#CC9E6A").s().p("AgtCDQgVgCglgWQAVAKAMABQAfABAigLQAggLAagTQAbgVAAgpQgBgngbg0QgXgogYgPQAQAFATAQQATAPASAgQAbA0AAAnQABApgbAVQgaATgiALQgcAKgbAAIgIAAg");
	this.shape_56.setTransform(79.9,-14.9);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#DDAF78").s().p("AgECGQgTgCghgSQghgTgcgaQgbgaAAgaQACgWAPgQQAQgQAPgKIAOgLIAGgIQAMgSAagXQAagYAkgBQADgCAeAMQAeAMAeAyQAcA1AAAnQABApgbAVQgaATgiALQggAKgbAAIgEAAg");
	this.shape_57.setTransform(75.8,-15.2);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#704C2C").s().p("AgECJQgUgBgigTQgigTgcgbQgbgbgBgbQADgXAPgRQAQgQAQgKIANgLIAHgIQAIgLAOgQQAPgQAVgNQAUgMAYAAQADgCAfAMQAfANAgA0QAcA2AAAoQAAAqgcAVQgaAUgjALQgfAKgcAAIgFAAg");
	this.shape_58.setTransform(75.9,-15.1);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#999999").s().p("AgRAFIABAAQAEABADgDQAEgDgCgIIAAgCQAEgDAGACQAIABAGACQgBAEgIAFIgPAMQgCAAgIgIg");
	this.shape_59.setTransform(66.4,-20.5);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#494949").s().p("AgHAPQgCABgKgKIAAgDQAAAAAAAAQABgBAAAAQAAAAABAAQAAAAABAAQADABADgCQACgBgCgIQAAgEACgBQAFgDAJACIAOAEIABAAIAAABQgCAGgLAHIgNALIgBABg");
	this.shape_60.setTransform(66.4,-20.4);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#876F5C").s().p("AgDABIgPAAQASgJAHACQAJACACAEIABAHQgLgGgLAAg");
	this.shape_61.setTransform(74.3,10.4);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#CC9E6A").s().p("AgIACQAEgCAAAAIgQACQgJABgFgBIgBgCIABAAQADABALgBIASgEQABACAGACQAJAFAWgHIAAABQgDABgMADQgFACgGAAQgJAAgJgDg");
	this.shape_62.setTransform(74.1,19.9);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#DDAF78").s().p("AgIAUIAEgCQABAAAAAAQAAAAAAgBQABAAAAAAQAAAAgBAAIgBgBIgQADQgJACgFgCIgBgBQABgGAGgIQAHgHAIgFQABgBAAAAQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAAAgBAAQAAAAAAAAQAAAAgBAAIgGAFQgMgKABgEIAAgBQAMADAHgCIAFgBQACABALAGIAXANIADACQADAEABAJQgDADgMAEQgFABgGAAQgJAAgJgCg");
	this.shape_63.setTransform(74.1,18.1);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#000000").s().p("AgNAVIAAgBQgOAEgIgCQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBgBAAAAQACgLAOgMQgPgNAEgEQAAgBABAAQAAgBAAAAQABAAAAAAQABAAAAAAQALADAGgCIAGAAQAEABAOAIIAUAKIAEAEQADAEAAALIAAABIAAAAQgBACgOAFQgFACgIAAQgKAAgNgEg");
	this.shape_64.setTransform(74.1,18.1);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#000000").s().p("AAFAQQgBgOgEgHQgFgJAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBQAAAAABAAQAAAAAAAAQAAgBABAAQAAAAAAABQAAAAABAAIAFAKQAFAIAAAOIgBACIgBgCg");
	this.shape_65.setTransform(77.3,18.5);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#AD9787").s().p("AgPAaIgEgDQAHAAAEgCIACgBIAPgGQAIgEAAgPQAAgRgKgEQAHABADAJQADAKAAAKQAAALgFADQgMAGgDAAIgBABQgDACgFAAIgGgBg");
	this.shape_66.setTransform(78.5,18.1);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#E8D8CD").s().p("AgTAAQALgOALgCQAOgEAFAOIACAGIgBgBQgFgPgOAFQgLACgMALQgEAJABAHQgDgIAGgKg");
	this.shape_67.setTransform(78,17);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#C6B2A3").s().p("AgLAbQgGgEgEgLIAAgBIgCgHQgBgGAEgHQAMgOALgCQAOgEAFAOQADAKgBAJQAAAMgEADQgMAFgFABIgCAAQgBACgFAAIgGAAg");
	this.shape_68.setTransform(78,18);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#000000").s().p("AgMAdQgIgEgEgNIAAAAIgCgJQgBgGAFgIQAMgPANgCQAGgCAGACQAGACADAKQADAJAAALQAAANgHAEQgMAFgFABIgBAAQgCADgFAAIgHgBg");
	this.shape_69.setTransform(78.1,18);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#000000").s().p("AgIgBQAAgBAAgBQgBAAAAgBQAAAAAAgBQAAAAABAAQACgDAQAGIgIgBIgIAAIAFAFIADAFQgIgHgCgBg");
	this.shape_70.setTransform(83.7,12.1);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#998370").s().p("AABAHQgIgHgBgCQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQACgDAQAFIABACIgGABQgEABADAEIAAABIgBABIgBAAg");
	this.shape_71.setTransform(83.7,12.2);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#000000").s().p("AgVBGIgBgLQgCgLgHgFIgCAAIACgCIAZgSQANgMADgFIAAgSIAAgjQgBgSgCgGIABgCQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAQACAHAAASIABAkIAAARIAAABQgEAGgOAMIgXARQAFAFADAHQACAIAAAFIAOgPIAWgZIAMgNIABgQIABgfIgBghQAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAAVIAAAlQAAARgCAGIAAAAIg1A7g");
	this.shape_72.setTransform(82.4,11.3);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#000000").s().p("AABATQgCgOAAgKIAAgNIABgBIAAABIAAANQAAAKACAOQABABgBAAIgBAAIAAgBg");
	this.shape_73.setTransform(77.2,0);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#000000").s().p("AAAAUIAAgBQACgPgCgKIgBgMIABgBIAAABIABAMQACAKgCAPIAAABIgBAAg");
	this.shape_74.setTransform(78.9,-0.2);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#000000").s().p("AAAATQACgSgCgIIgBgLIAAgBIABABQAAAAABAKQACAJgDASIAAABIAAgBg");
	this.shape_75.setTransform(80,-0.5);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#000000").s().p("AAAAUQAAAAAAgBQACgOgCgKIgBgNIAAgBIABABIABANQACAKgCAOIAAABIgBAAg");
	this.shape_76.setTransform(81.3,-0.8);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#000000").s().p("AABASQACgRgDgIIgCgKIAAgBQABAAAAABQABAAABAKQADAIgBARIgBABIgBgBg");
	this.shape_77.setTransform(82.2,-1.2);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#000000").s().p("AADAVQgHgUACgJQABgLABAAIAAgBIAAABQAAAAgBALQgBAJAGATIAAABIgBAAIAAAAg");
	this.shape_78.setTransform(75.6,0.1);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#000000").s().p("AAAAUQgDgTACgJQABgLABAAQAAgBABAAIAAABQgBAAgBALQgCAJAEATIgBABIAAAAIgBgBg");
	this.shape_79.setTransform(74.2,0);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#000000").s().p("Ag3AIIAAgBIABgBQA8AGAZgKQAZgJgBgCIABAAIAAABQABACgaAJQgQAHgfAAQgRAAgWgCg");
	this.shape_80.setTransform(78.2,-0.5);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#000000").s().p("Ag4ADIAAAAIABgBQA1AJAcgJQAdgHABgCQABgBAAABIAAABQgBACgeAHQgPAFgTAAQgVAAgbgFg");
	this.shape_81.setTransform(77.8,-1.6);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#664E3C").s().p("AABATQgCgOAAgKIAAgNIABgBIAAABIAAANQAAAKACAOQABABgBAAIgBAAIAAgBg");
	this.shape_82.setTransform(77.2,0);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#664E3C").s().p("AAAAUIAAgBQACgPgCgKIgBgMIABgBIAAABIABAMQACAKgCAPIAAABIgBAAg");
	this.shape_83.setTransform(78.9,-0.2);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#664E3C").s().p("AAAATQACgSgCgIIgBgLIAAgBIABABQAAAAABAKQACAJgDASIAAABIAAgBg");
	this.shape_84.setTransform(80,-0.5);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#664E3C").s().p("AAAAUQAAAAAAgBQACgOgCgKIgBgNIAAgBIABABIABANQACAKgCAOIAAABIgBAAg");
	this.shape_85.setTransform(81.3,-0.8);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#664E3C").s().p("AABASQACgRgDgIIgCgKIAAgBQABAAAAABQABAAABAKQADAIgBARIgBABIgBgBg");
	this.shape_86.setTransform(82.2,-1.2);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#664E3C").s().p("AADAVQgHgUACgJQABgLABAAIAAgBIAAABQAAAAgBALQgBAJAGATIAAABIgBAAIAAAAg");
	this.shape_87.setTransform(75.6,0.1);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#664E3C").s().p("AAAAUQgDgTACgJQABgLABAAQAAgBABAAIAAABQgBAAgBALQgCAJAEATIgBABIAAAAIgBgBg");
	this.shape_88.setTransform(74.2,0);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#664E3C").s().p("Ag3AIIAAgBIABgBQA8AGAZgKQAZgJgBgCIABAAIAAABQABACgaAJQgQAHgfAAQgRAAgWgCg");
	this.shape_89.setTransform(78.2,-0.5);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#664E3C").s().p("Ag4ADIAAAAIABgBQA1AJAcgJQAdgHABgCQABgBAAABIAAABQgBACgeAHQgPAFgTAAQgVAAgbgFg");
	this.shape_90.setTransform(77.8,-1.6);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f("#5B4536").s().p("AgcALIgVgBIAAgBQA8ABAUgKQAUgIgCgBIABgBIAAAEQgOAKgYADQgTAEgRAAIgEAAg");
	this.shape_91.setTransform(78.7,-0.2);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#5B4536").s().p("AgyAHIAAAAIgDgEIACAAQACACAgABQAgABAmgOIAAAAQABACgZAHQgSAGgeAAIgfgBg");
	this.shape_92.setTransform(77.4,-0.9);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f("#775F4D").s().p("AgkAaQgMgCgDgDIgCgDIADgJIAAgBIgBgBQgEgEgCgDIADgFIAEgKQAGADAbABQAaACAqgQIAEAIQADAGAAALIAAACQAAABgMAIQgLAHgjAGQgQACgLAAIgJAAg");
	this.shape_93.setTransform(77.9,-0.7);

	this.shape_94 = new cjs.Shape();
	this.shape_94.graphics.f("#000000").s().p("AgkAcQgNgBgDgEQgEgEABgBQAAgFACgEQgFgDgCgGIAEgIIAEgJIABgBIABAAQABACAcADQAaACAtgRIABAAIABAAIAFAJQAEAIgBANIAAABQABABgLAIQgLAJgnAGQgOACgLAAIgLgBg");
	this.shape_94.setTransform(77.8,-0.7);

	this.shape_95 = new cjs.Shape();
	this.shape_95.graphics.f("#000000").s().p("AgZAGIgBAAIABgBQAaABAMgGQANgEgBgBIABAAIAAABQAAACgMADQgKAFgVAAIgIAAg");
	this.shape_95.setTransform(78.8,11.2);

	this.shape_96 = new cjs.Shape();
	this.shape_96.graphics.f("#000000").s().p("AgYAKQAAgBAAAAQAAAAAAAAQAAAAAAAAQAAAAABAAQARgJAOgEIARgFIAAABIAAABIgRAFQgNACgSAKIAAAAIgBAAg");
	this.shape_96.setTransform(78.8,10.3);

	this.shape_97 = new cjs.Shape();
	this.shape_97.graphics.f("#000000").s().p("AgVAJIAAgBQABgCANgGQALgGASgCIAAABIAAABQgRABgLAFIgOAJIgBAAg");
	this.shape_97.setTransform(79,8.6);

	this.shape_98 = new cjs.Shape();
	this.shape_98.graphics.f("#000000").s().p("AgTAGIAAgBQAOgGALgCIAOgCIAAAAIAAABIgOACQgLACgNAGIgBAAIAAAAg");
	this.shape_98.setTransform(79.1,7.2);

	this.shape_99 = new cjs.Shape();
	this.shape_99.graphics.f("#000000").s().p("AgSAEQAAgBABAAIAMgDQAKgDANAAIABAAIgBABQgNAAgJACIgNAEIgBAAg");
	this.shape_99.setTransform(78.9,5.4);

	this.shape_100 = new cjs.Shape();
	this.shape_100.graphics.f("#000000").s().p("AgRADIAAgBQAMgCAKgBIAMgBIABAAIgBABIgMABQgJAAgMADIgBAAg");
	this.shape_100.setTransform(78.6,3.5);

	this.shape_101 = new cjs.Shape();
	this.shape_101.graphics.f("#000000").s().p("AgEA5IgBAAQAOgtgGggQgFgigCgCIAAgBIABABQADACAEAiQAGAggOAtIAAABIAAgBg");
	this.shape_101.setTransform(77.9,7.4);

	this.shape_102 = new cjs.Shape();
	this.shape_102.graphics.f("#000000").s().p("AADA5QAFgqgHghQgFgjgBgDIAAgBIABABIAGAlQAHAigEAqIgBABIgBgBg");
	this.shape_102.setTransform(79.4,7.1);

	this.shape_103 = new cjs.Shape();
	this.shape_103.graphics.f("#5B4536").s().p("AgVA4QASgBAIgQQALgYgDgWQgCgZgHgYQAFAJAGAWQAGAXAAAeIAAARQgBACgLAFQgIAFgMAAIgKgBg");
	this.shape_103.setTransform(79.1,7.4);

	this.shape_104 = new cjs.Shape();
	this.shape_104.graphics.f("#775F4D").s().p("AgaA3QADgFAFgQQAFgQABgVQAAgXgLgZIAQgDIAQgDQADAFAHAXQAHAYABAiIgBARQgBADgOAGQgHADgIAAQgKAAgMgDg");
	this.shape_104.setTransform(78.5,7.3);

	this.shape_105 = new cjs.Shape();
	this.shape_105.graphics.f("#000000").s().p("AgFBAIABgGIgFAAIgCAFIgBAAIAAgBQACgDAAgCIgHgBQAAADgDAEIgBAAIAAgBQACgDAAgDIgGgBQgBACgDADIgBAAIAAAAIADgGIAAAAIgCgBIABgBIAHgRQAGgQABgWQACgYgNgcIAAgBIABgBIAQgCIATgFIAAAAIABABQACABAJAfQAKAegDAsIAAABIAAAAIAAAIIgBABIAAgBIAAgHIgDADQABABgBAIIgBAAIAAgBIAAgIIgGADIABAIIgBABIAAgBIgBgHIgFADIAAAGIAAABIgBgBQAAgGgBAAIgHACQABACgBAFIgBAAIgBAAQACgFgBgCIgGABIgBAGIgBABIAAgBg");
	this.shape_105.setTransform(78.4,7.6);

	this.shape_106 = new cjs.Shape();
	this.shape_106.graphics.f("#876F5C").s().p("AgFA/IABgFIgFAAIgCAFIgBAAIAAgBQACgDAAgCIgHgBQAAADgDAEIgBAAIAAgBQACgDAAgDIgGgCQgBADgDAEIgBAAIAAgBIADgGIAAAAIgCgBIABgBIAHgRQAGgPABgXQACgZgNgaIAAgCIABAAIAQgEIATgDIAAAAIABABQACABAJAeQAKAegDAsIAAABIAAAAIAAAIIgBABIAAgBIAAgHIgDACQABADgBAGIgBABIAAgBIAAgIIgGAEIABAIIgBAAIAAAAIgBgIIgFACIAAAHIAAABIgBgBQAAgGgBgBIgHACQABADgBAFIgBAAIgBgBQACgEgBgDIgGACIgBAGIgBAAIAAgBg");
	this.shape_106.setTransform(79.1,7.8);

	this.shape_107 = new cjs.Shape();
	this.shape_107.graphics.f("#000000").s().p("AgjB2QgjgDgLgKQgKgKAAgCIgBgQQAAgQAHgXIACgIIAPgyIAKgqIABgBQABABgEASIgKAnIgKAkIgDAIQgHAXABAPIABAQQgBABAKAJQAKAJAiAEQAlACAWgGQAXgGADgCIADgIIADgGIAAgCIACABQAFAGACAGQAKgBAGgDIAHgFIABgRIABgkQAAgegEgfQgFgggMgUQgYgfgWgGQgWgFgBABIAAgBQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAAAAAAAQABgCAXAGQAWAFAZAgQAPAZAEAmQAEAlgCAgIgCAkIAAABIAAAAQAAABgHAFQgHAEgLABIgBAAIAAgBIgHgKQgDAIgBAEIAAABIgBAAQAAABgXAHQgRAFgaAAIgVgBg");
	this.shape_107.setTransform(78.5,9.8);

	this.shape_108 = new cjs.Shape();
	this.shape_108.graphics.f("#6B503C").s().p("AgvAZIgPgCQgLgNgEgPQARAEAlABQAxACAYgJQAZgMADgGIgBAaIgHAFQgGAEgLABIgDgGIgFgFIAAAAIAAAAIgDAFIgCAIQgCACgXAGQgPAFgcAAIgTgBg");
	this.shape_108.setTransform(79.6,19);

	this.shape_109 = new cjs.Shape();
	this.shape_109.graphics.f("#5B412F").s().p("AgKAGQgIgGABgBIgBgRQADADATAFQAEAQALANQgVgFgIgIg");
	this.shape_109.setTransform(71.3,19.4);

	this.shape_110 = new cjs.Shape();
	this.shape_110.graphics.f("#AF9887").s().p("AgMAxQAAgOAGgVIAGgYIAOgvIgNBBQgFAkAOAOQgXgIABgBg");
	this.shape_110.setTransform(70.7,12.2);

	this.shape_111 = new cjs.Shape();
	this.shape_111.graphics.f("#6B503C").s().p("AgjAZQgggDgMgKQgLgJABgCIgBgOQADACASAFQASAFAoABQAxACAYgJQAZgMADgGIgBAaIgHAFQgFAEgMABIgDgGIgEgFIgBAAIgDAFQgCAFAAADQgCACgXAGQgRAFgaAAIgTgBg");
	this.shape_111.setTransform(78.4,19);

	this.shape_112 = new cjs.Shape();
	this.shape_112.graphics.f("#876F5C").s().p("AAJAEQACgrgNgqIACAFQAPAZAEAoQADAngCAgIgBAAQAAABgKAHQgJAIgUAGQAcggABgug");
	this.shape_112.setTransform(85.4,10);

	this.shape_113 = new cjs.Shape();
	this.shape_113.graphics.f("#998370").s().p("AgGBcQgtgEgRgGIgQgGQAAgOAGgVIAIgaIANgoQAFgVABgNQAAgIADgKQAKAKAQADQAYAIAUgJQAUgJAQgSQAHAHAHAIQAOArgBArQgBAtgfAhQgRAGgZAAIgRgBg");
	this.shape_113.setTransform(77.9,9.5);

	this.shape_114 = new cjs.Shape();
	this.shape_114.graphics.f("#876F5C").s().p("AgbAWQgPgDgLgKQADgMAMgLQAQgNAWACQABgBAQADQAQADAVAQQgRAQgUAJQgKAFgKAAQgLAAgNgEg");
	this.shape_114.setTransform(78.3,0.7);

	this.shape_115 = new cjs.Shape();
	this.shape_115.graphics.f("#998370").s().p("AgLBnQgugEgRgGQgQgFAAgBQABgOAFgVIAIgaIANgoQAGgVABgNQAAgJADgMQADgMAKgKQARgNAXACQABgBAWAFQAXAGAYAfQAPAZADAnQAEApgCAgIgBAAQABACgYAOQgWALgsAAIgLAAg");
	this.shape_115.setTransform(78.4,8.4);

	this.shape_116 = new cjs.Shape();
	this.shape_116.graphics.f("#000000").s().p("AgjB1QghgEgLgJQgLgKABgBIgBgPQAAgPAGgZIAIgaIANgoQAGgVABgNQAAgJAFgMQAEgLAKgKQAQgOAVACQABgBAWAFQAXAGAYAfQAPAYADAnQAEAmgBAgIgCAiIgGAFQgHAEgLABIgDgFQgCgFgDgCIAAAAIAAAAIgDAGIgCAIQgCACgXAGQgSAFgaAAIgSAAg");
	this.shape_116.setTransform(78.4,9.8);

	this.shape_117 = new cjs.Shape();
	this.shape_117.graphics.f("#000000").s().p("AgNBIIgBgBIAAgBIAAgbIABg4QABggACgUQAAAAAAAAQAAAAAAAAQABgBAAAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAAAQAAAAAAABIgBApIgCAwIAAAlIAAAHQAOADAFgDQgDgRgCgZIgCgbIAAgBIACABIAEgBIgFgFIAAAAIAAgBQACgUAEgVIAEgXIACgBIABABIgFAXIgFApQADACABAEIgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAIADAfQABAYADAPIABABIgCABIgHABIgDAAIgNgBg");
	this.shape_117.setTransform(81.9,28.8);

	this.shape_118 = new cjs.Shape();
	this.shape_118.graphics.f("#775F51").s().p("AgLABIgBAAIAAgCQALABANgCIABACIAAABIgBAAIgIACIgEAAQgEAAgHgCg");
	this.shape_118.setTransform(81.8,35.8);

	this.shape_119 = new cjs.Shape();
	this.shape_119.graphics.f("#3F2C20").s().p("AgBBFIgNgBIAAgkIABgxIADgsIACgBQAAAAAAABQAAAAAAAAQAAAAAAAAQAAABAAAAIAJgEIANgEIABABIgFAXIgFApQADACABACIgBACQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAIACAbIAEAkQgFACgFAAIgBAAg");
	this.shape_119.setTransform(81.9,28.4);

	this.shape_120 = new cjs.Shape();
	this.shape_120.graphics.f("#000000").s().p("AgNBIIgBgBIAAgBIAAgbIABg4QABggACgUQAAAAAAAAQAAAAAAAAQABgBAAAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAAAQAAAAAAABIAJgEIANgEIABABIgFAXIgFApQADACABAEIgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAIADAfQABAYADAPIABABIgCABIgHABIgDAAIgNgBg");
	this.shape_120.setTransform(81.9,28.8);

	this.shape_121 = new cjs.Shape();
	this.shape_121.graphics.f("#3F2C20").s().p("AgnAPQgfgGgIgJIAkAAQAbABAagCQAdgEANgNIAKAFQAHADAJgCQgDAGgNAHQgNAKgfAGQgMACgLAAQgSAAgRgEg");
	this.shape_121.setTransform(78.9,20.6);

	this.shape_122 = new cjs.Shape();
	this.shape_122.graphics.f("#000000").s().p("AgsASQgggIgGgKIAAgDIACABIAeACQAbAAAdgDQAggDANgOIABgBIABAAIAKAFQAIAEAJgEIADgBIgBADQABACgMAMQgMAMgnAIQgOACgMAAQgUAAgSgEg");
	this.shape_122.setTransform(78.9,20.6);

	this.shape_123 = new cjs.Shape();
	this.shape_123.graphics.f("#281409").s().p("AgIAAIARgCIAAADQgFACgLAAIgBgDg");
	this.shape_123.setTransform(82.2,38.5);

	this.shape_124 = new cjs.Shape();
	this.shape_124.graphics.f("#281409").s().p("AgdADIAAgDIAAAAIAVAAIAmgCIgCACIgTACQgJABgLAAIgSAAg");
	this.shape_124.setTransform(77.7,39);

	this.shape_125 = new cjs.Shape();
	this.shape_125.graphics.f("#594739").s().p("AgkAEQAHgGAQAAQAfABACABIABAAIAAgBIACgEIABgHIAFAAIAFgBQAEADADAPIgSAEIgBgDIgDAEQgTADgSAAIgWABQAAgFAEgFg");
	this.shape_125.setTransform(78.9,37.3);

	this.shape_126 = new cjs.Shape();
	this.shape_126.graphics.f("#000000").s().p("AgqATIgBAAIAAgBIAAgHQAAgGAFgFQAHgIASAAQAZAAAHACIACgLIABgBIANgBIABABIAEAIQAEAIAAANIAAABIgBAAIgHABIgOACIgBAAIgBgGIgDAFIAAAAIgRAEQgKACgNAAIgTgBg");
	this.shape_126.setTransform(78.9,37.6);

	this.shape_127 = new cjs.Shape();
	this.shape_127.graphics.f("#491E01").s().p("AgIAAIARgCIAAADQgFABgLABIgBgDg");
	this.shape_127.setTransform(75.4,38);

	this.shape_128 = new cjs.Shape();
	this.shape_128.graphics.f("#000000").s().p("AgPAXQgHgFADgGIABgGIAAgQIAAgMQAAAAAAAAQABgBAAAAQAAAAAAAAQAAAAABAAIABABIAAANIgBAQIgBAFQgCAGAFADQAFACAFgDQAEgBABgSIAAgBIABAAIAHAAQAGAAADgEQAAgBABAAQAAAAAAAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAAAQAAAAAAABQgDAEgGABIgIABIAAABQgCAQgFACQgDACgDAAQgDAAgDgBg");
	this.shape_128.setTransform(66.3,18.1);

	this.shape_129 = new cjs.Shape();
	this.shape_129.graphics.f("#CC9E6A").s().p("AgQAPIgDgDQAEABAEgDQAHgCABgOIAAgBQADAAAEgBQAFgCACgGIAEACIAFACQAAAAAAAAQAAAAAAAAQAAAAAAABQAAAAAAAAQgCAHgGABIgJAAIAAACQgCAOgEACQgEACgDAAQgDAAgDgCg");
	this.shape_129.setTransform(66.4,18.8);

	this.shape_130 = new cjs.Shape();
	this.shape_130.graphics.f("#DDAF78").s().p("AgPAXQgHgFADgGIABgGIAAgQIAAgMQAAAAAAAAQABgBAAAAQAAAAAAAAQAAAAABAAIABABIAQAJIATAIQABAAAAAAQAAABAAAAQAAAAAAAAQAAAAAAABQgDAEgGABIgIABIAAABQgCAQgFACQgDACgDAAQgDAAgDgBg");
	this.shape_130.setTransform(66.3,18.1);

	this.shape_131 = new cjs.Shape();
	this.shape_131.graphics.f("#543621").s().p("AggBrQADgFAFgaQAGgaABgnIgBgVQgDgogGgUQgDgMAAgIIABgFQADgHAKgEQAKgFAJACQAKACAJAHQAJAHACAFQABADgGAIIgCACIgIgOQgHgKgIgEQgGgCgHAEQgHAEgEAGQgCAFAFAeQAFAgACAkQABAigCAaQgCAagFAMIgCABQgGAAgFgEg");
	this.shape_131.setTransform(65.3,28);

	this.shape_132 = new cjs.Shape();
	this.shape_132.graphics.f("#381D0B").s().p("AgLBDQACgagBghQgCgkgFggQgFgbACgHQACgFAHgEQAGgEAFADQAHADAGAJIAJANQgDACgEgBQgCABgEgJQgCgMgKAAQgFgBgEADQgFACAAAMIADAcQAHAgADAyIAAAUQAAAbgCAMIgDAOIgJAFQAFgOACgZg");
	this.shape_132.setTransform(65.5,28.4);

	this.shape_133 = new cjs.Shape();
	this.shape_133.graphics.f("#000000").s().p("AgiBsIgBAAIABgBQABgCAIghQAHghgCgxQgEgngFgUQgFgTADgIQADgIALgFQALgEAJABQALACAJAIQAKAHACAHIAAAAQACADgHAKQgFAFgJgBIgDgCQgDgCgBgGQgCgKgIAAQgEgBgEACQgDACAAAKQAAAIADATQAGAhADAyQAAAogBARQgDARgBAAIAAABIgGADIgHADIgCAAQgHAAgHgFg");
	this.shape_133.setTransform(65.3,28);

	this.shape_134 = new cjs.Shape();
	this.shape_134.graphics.f("#CC9E6A").s().p("AgKAXQgKgBgGgHQAEADAFAAQACABAPgBQAPAAAFgKQABgFAAgDQAAgNgJgJQAPAJAAAQIgBAIQgFAKgQACIgMAAIgDAAg");
	this.shape_134.setTransform(65.6,16.3);

	this.shape_135 = new cjs.Shape();
	this.shape_135.graphics.f("#DDAF78").s().p("AgFAZQgNgBgHgLQgGgLgBgCQACgDAMgKQALgKAGgCQADAAAGABIAFACQATAJAAASQAAAEgBAEQgFAKgPACIgMABIgEgBg");
	this.shape_135.setTransform(65.1,16.1);

	this.shape_136 = new cjs.Shape();
	this.shape_136.graphics.f("#000000").s().p("AgFAcQgOgCgIgLQgHgMAAgDQACgFAMgKQANgKAGgCQADgBAGACIAHACQAMAFAFALQAFAKgDAMQgGAMgQABIgPABIgCAAg");
	this.shape_136.setTransform(65,16.1);

	this.shape_137 = new cjs.Shape();
	this.shape_137.graphics.f("#AD9787").s().p("AgKAPQAGABAEgFQACgEAAgGQABgDgCgCQgCgGgNgIQAJAAAGAHQAKAHADAEIABAFQgBAGgEAEQgDAEgGAAQgDAAgIgEg");
	this.shape_137.setTransform(69,14);

	this.shape_138 = new cjs.Shape();
	this.shape_138.graphics.f("#C6B2A3").s().p("AgEAPIgIgFQgGgGgCgEIAAgDQAAgGADgFQADgEAGAAQAIAAAIAHQAJAHADAEQABAAAAAFQAAAGgEAEQgDAEgGAAQgGAAgGgEg");
	this.shape_138.setTransform(68.3,14);

	this.shape_139 = new cjs.Shape();
	this.shape_139.graphics.f("#000000").s().p("AgFASIgIgHQgHgFgCgGQgBgJAEgGQAEgFAHgBQAIAAAKAIQAKAIADAEQABABAAAGQgBAGgEAFQgCAEgHABIgCAAQgGAAgHgEg");
	this.shape_139.setTransform(68.2,14);

	this.shape_140 = new cjs.Shape();
	this.shape_140.graphics.f("#998370").s().p("AgWBJIgGgFQAOgUAIgYQAGgYADgTIAIgdQAMgaAGAAIAAABQgBAIgHAZIgRA4IgRA7QgFAAgEgCg");
	this.shape_140.setTransform(71.6,5.8);

	this.shape_141 = new cjs.Shape();
	this.shape_141.graphics.f("#000000").s().p("AgYBKIgGgFIgBgBIABAAQAOgUAIgZQAHgXACgUIAIgcQAHgSAGgGQAGgGABABIABAAQACgCgBANQgCANgRA2IgOA0IgIAYIAAABIgBAAQgHAAgGgEg");
	this.shape_141.setTransform(71.5,5.8);

	this.shape_142 = new cjs.Shape();
	this.shape_142.graphics.f("#775F51").s().p("AgJAAIAAgBQAFABAOAAIAAACIgFAAQgFAAgJgCg");
	this.shape_142.setTransform(75.3,35.3);

	this.shape_143 = new cjs.Shape();
	this.shape_143.graphics.f("#3F2C20").s().p("AgMA/IADglIACgbIABgRIADgbIADgSQAGgBAGADIgFAaIgFAfIAAACIACAAIAFAAIgFACIAAABIAAAAIACAXIACAmIAAACIgIAAQgJAAgDgBg");
	this.shape_143.setTransform(75.5,28.4);

	this.shape_144 = new cjs.Shape();
	this.shape_144.graphics.f("#000000").s().p("AgNBEIgBgBIAAgBIABgRIACggIABgUIACgUIAEgdIACgQIAAgBIABAAIAFAAQAGABAFADIAAAAIAAABIgEAXQgFAUgBANQAEAAACABIABACQgBAEgEABIABAYIACAjIAAAKIAAABIgCAAIgHAAQgGAAgIgCg");
	this.shape_144.setTransform(75.6,28.7);

	this.shape_145 = new cjs.Shape();
	this.shape_145.graphics.f("#281409").s().p("AgdADIAAgDIAAAAIAVAAIAmgCIgCACIgTACQgJABgLAAIgSAAg");
	this.shape_145.setTransform(71,38.5);

	this.shape_146 = new cjs.Shape();
	this.shape_146.graphics.f("#594739").s().p("AgkAEQAHgGAQAAQAfABACABIABAAIAAgBIACgEIABgHIAFAAIAFgBQAEADADAPIgSAEIgBgDIgDAEQgTADgSAAIgWABQAAgFAEgFg");
	this.shape_146.setTransform(72.1,36.7);

	this.shape_147 = new cjs.Shape();
	this.shape_147.graphics.f("#000000").s().p("AgqATIgBAAIAAgBIAAgHQAAgGAFgFQAHgIASAAQAZAAAHACIACgLIABgBIANgBIABABIAEAIQAEAIAAANIAAABIgBAAIgHABIgOACIgBAAIgBgGIgDAFIAAAAIgRAEQgKACgNAAIgTgBg");
	this.shape_147.setTransform(72.2,37.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_147},{t:this.shape_146},{t:this.shape_145},{t:this.shape_144},{t:this.shape_143},{t:this.shape_142},{t:this.shape_141},{t:this.shape_140},{t:this.shape_139},{t:this.shape_138},{t:this.shape_137},{t:this.shape_136},{t:this.shape_135},{t:this.shape_134},{t:this.shape_133},{t:this.shape_132},{t:this.shape_131},{t:this.shape_130},{t:this.shape_129},{t:this.shape_128},{t:this.shape_127},{t:this.shape_126},{t:this.shape_125},{t:this.shape_124},{t:this.shape_123},{t:this.shape_122},{t:this.shape_121},{t:this.shape_120},{t:this.shape_119},{t:this.shape_118},{t:this.shape_117},{t:this.shape_116},{t:this.shape_115},{t:this.shape_114},{t:this.shape_113},{t:this.shape_112},{t:this.shape_111},{t:this.shape_110},{t:this.shape_109},{t:this.shape_108},{t:this.shape_107},{t:this.shape_106},{t:this.shape_105},{t:this.shape_104},{t:this.shape_103},{t:this.shape_102},{t:this.shape_101},{t:this.shape_100},{t:this.shape_99},{t:this.shape_98},{t:this.shape_97},{t:this.shape_96},{t:this.shape_95},{t:this.shape_94},{t:this.shape_93},{t:this.shape_92},{t:this.shape_91},{t:this.shape_90},{t:this.shape_89},{t:this.shape_88},{t:this.shape_87},{t:this.shape_86},{t:this.shape_85},{t:this.shape_84},{t:this.shape_83},{t:this.shape_82},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8}]}).wait(50));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-92.8,-41.6,186.8,84.2);


// stage content:
(lib.grandfatherCJS = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.grandfather();
	this.instance.setTransform(100,100.8);

	// Layer 8
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,255,255,0)").s().p("AvnPnIAA/OIfOAAIAAfOg");
	this.shape.setTransform(100,100);

	this.addChild(this.shape,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(100,100,200,200);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;