(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 200,
	height: 200,
	fps: 12,
	color: "#FFFFFF",
	manifest: []
};



// symbols:



(lib.Symbol13 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#14395A").s().p("AmMYeIgDAAIgEgOIgHgVIgTAWIgDgBIgYgIQgSgHgIgGIgCgDIACgDIAagoQAYgiAbgaQgRgIgNgLIgEgDIADgDQAIgPA9hZQA+hYA+g5QgMgKgDgQIAAgBQAAgGAEgEQALgLAGgCIgDhFIgGiIIgFhxQgFAEgHAEQgQAIgMAAQgLgCgGgEIgHgIQgHAJgcgGQgOgMgIgXQgHgYgBgKIgBgFQgYAGgkgxQgWgkAHgWQAJgRAGgBIAOgHQgghAgghKQgghKgKgqQgCgCAJgOIgEgDQgrgqABgTIAAgGQAHgIAUgBQgJgPgFgVQAAgOAJgJQAKgHAaAAQAaAAAcAEQATgzAYg6QAYg6APgeQAUgnAYgRQgSgNgTgJIgEgCIABgEQACgGATgkQASglASgTQAHgGAWgEQg8g9g/hmQg/hmgkiRQh3gvARhFQAIgfAbgSQgMhNAAhXQAChDARgxIgSgPIgPgLIAAgDIAEgZQAEgTAKgIIAEgCIAOAUQANASAHAIQAKgcA7hKQA7hLB+g7QBWgjBLgIQBKgJA0gDQA8gFAmgOQBvgxA7grQA8grAZgPIABgBIABAAQAKgFA1AmQA0AmgMCCQgOBEhHAzIgEACQATAdgPCMIgEAfQAIATgDAVIgEACQArAYAXAXQAYAXADAFIAAAAIABACIAAABQACCYgVA8QgWA8gFAAIgCABIgCABQgRABgPgCIAJAiQAXBOALAsQAMAsgNAuQgTBFhYA6QhYA6iSAeIgyAKIgDABQAPARAAAOQgBAPgHAaQgHAagDAVIgDAVIAGAMIAPAiQATAuAYA0QAYA0AaAiQAYgRAVAJQAYAbgDAaQAVgFAWAIQAGAEAAAGQABAHgHATIBLAAQAtAAAigCIA6g4QAsgqAXgRQAXgKAgAMQAgAMAIAGIgbAzQgfAKgGAPQADALAQAVQAQAUAJATQAKATgKALQgTALgggNQghgNgNgJQgQARhCgCIhaAKQhMAIg8ADIgPAQQgZAYgWgCQAcB4gZBLIAAABQgDBIgNgBQgHAigpAfQAXBJAeBoQAfBoANA+QAKA2AEBKQAEBKAAA6IABA9IgBAEIgBAAQAUAIAaAHQAZAIARACQADgJAMgOQANgOAYgDQAagCARARQAUAVgCAiIAAADIgCABQgEAEg6AUQg7AVhQAGIgDAAIgLgRIgCAUIgDABQgFAEg0gCIgEAAIAAgFIABgeQACgdAHgmQgYgBgVgOIgCgCIABgDIAUitQALhZAAgVIAAgBIgFgDQgOgFgEgOIAAgBQAAgMAYgOQgYhNgihgQghhfgPgeQgXAIhZgDIgMBfIgSCeQgJBVgEA4IAAABIAAABIgjA8IhDB3QgkBBgPAgIgCADIgEAAQgEAAgfgIQAEAQAKAJIAWAEIAXADQAFgEAUgHQAVgGAYAHQAVAIAJAWQAJAegPAdIgBACIgDABQgBABgxAHQggAEgvAAIg4gBgAmKFXQgOAFgUACQAKAyAaBNIAOiSQgFAJgLADgAl8EdIAFAMIABgNIAAgCIgGADg");
	this.shape.setTransform(61.3,156.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-0.2,0,123.1,313.5);


(lib.Symbol12 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#14395A").s().p("AgeRxIhEgCIgEAAIAAgEQgLhpARgXQgOgHgDgLIgBgGQAFgQANgIQgNgHgFgOIABgGQAEgTAugMIAAgSQgVgBgSgFIgEgBIgCgiIgDgoIgBAAIgGAqIgFAkIgEABQgCABg5ACIAAARQAuAMAEATIACAGQgGAPgNAIQANAGAFAQIAAAGQgDALgPAHQARAXgLBpIAAAEIgEAAIhEACQg7AChKgDQhKgDgzgMIgCgBIgBgCQgEgHgEgsQgDgrAmgeQApgUArAMQAsALANAJQAJgFATgQQgPgKgBgKQAHgRATgFQgLgHgHgTIAAgCQAAgEAEgEQAOgLAfgBIAAgQQgcgCgggEIgEAAIgBgEIgKhBQgJg9ABg8IgSgJIgDgBIAThUQARhIAbhXIhDBcIgqA4QADAKgBAgQgBAhgdAYQAIATABARQgBAUgIANQgIAOgKAAQgJgCgLgYQgMgYgIgWQgEASgIAbQgIAbgNAJQgHAFgHgDQgRgIABgaQAFgkALgdQgVANgdANQgdANgMgJQgDgCAAgGIAAgBQADgQAVgUIAjgfQgpgSgKgsIAAgDQAAgRAJgFQALgGASAMQAJAFATAGQATAGAMACQBCggAWAEQAIgOAigyIA4hUIgMgHIgEgBIABgEQgBgGAcg1QAcg1BRgoIhjgwQg+gehDgoQhDgogxg1QhVABgrghQgqgjgJgqQgQhJA2gWQAwgLAjAZQAAgTACgRQglirgkhAQgjhAgKgEQgcAIgZAMIgbANIgMAGIAEgMQASg0AeguQAdgtAPgTQgagBgZACIgcADIgKABIAEgIQAxhhAzg4QAyg4ATgNQg9gsg3gdIg8geIgFgCIADgFQAog5AfgQQAggRADACIAEAAIACACIA6BWIA1BNQCfigCrgeQCrgfBUALIBNACQBLAHBJgMQAsgJAjgCIAmgDIASgBIgPAKQhSBAgFAeQDiAtBtBQQBuBQAhBCQAiBDgDAFIADALIgLgFIgUgIIABACQgggMgigHQg4gJgegCQClC0AoCMQAoCMgHAKIACALIgKgGQgqgagmgNQgmgOgSgDIAQAxIANAmIgGABQhxAahDAsQhDArgeAnIAAACQAvgoBDAYQAxAfgdBDQgRApgzAaQgyAbhXgTQg2A5hVAiQhUAhhOAQQA9AlAiBwIABAEIgEACIgQAGQAWA4AgCYQAfAkAaAhQAaAgACARQAAAFgDACQgWAIgqgeQgSAygcAFQgJAAgCgFQgDgGANgbQgVAIgNgHQgHAEgGABQgHBJgNA6IgBADIgDABQgLAEhJAHIAAAQQAdABAOALQAEAEAAAEIAAACQgGAUgKAKQASADAGAPQAAAKgQAKQATAQAJAFQANgJAsgLQAsgMAoAUQAmAegDAsQgEArgEAHIgBACIgCABQgzAMhKADQgxACgrAAIgngBgAB8JvIADgDIgIgaIAFAdg");
	this.shape.setTransform(82.1,113.8);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,164.2,227.7);


(lib.Symbol10 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#14395A").s().p("AgcAmQgEgmANgWQAOgVADgBIACgDIACACQAeAagCAJIAAADIgDACQgMAHgPASIgUAUIgHAIg");
	this.shape.setTransform(3,4.9);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-0.1,0,6.1,9.7);


(lib.Symbol9 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#14395A").s().p("AhtUbIgDAAIgBgEQgCgEACgcIgEAAIgEgVIgMASIgCABQgEAChCAMQhCAMhggIIgEAAIgBgEQgBgDABgWQABgXASgYQAcgjBDAAQBpADAaAGIAIgcIgLgDIgEgCIABgDIAEhCIAIh9QAEhBAAgTQABgYAJhHIARh6Qh9gZgoguQhBgvAHgLQgHgGAGhrQgLABgPgEQAFAcgIAbIgBAAIAAABQgDAKgHAHQAUAUAGASIAAABQAFALgaAmQgSASgigCQgIADgSgfQgIAIgGAEQgZAOgXgMIgEgDIgCgBIgCgCIgBgBIgCgCIgBAAIgCgDQgHgOAFgRIACgMIgFAAQgKAJAAAgQABAgAMBJQAXB8AODHQAFCagMBCQgMBBgDAAIgBACIgBAAIgUANQgPAJgMADQghAFgegYIgCgCIABgDQAGgGAdh+QAdh/gJjDQgPiXgThMQgUhKALgcQAEgLAJgJQgggvAAgVQAGgTAwgnQAwgnAYgIQAUgDAWAGQACgXAMgQQAQgTAbgCQAYgBAbAQQAwhLAbhYQAahXAPhJQALgxAKgkQgEgIAAgEQADgSAGgPQgTgMgHgWQAFgYATgkQhdgnhlhGQhmhFhGhUQhHhUAAhSQAGhLApg3QAog2AzgnIADgJQgGgGgFgHQgFgGADgHQAEgFAJABQAMACAJgHQAJgKgHgeQgBgOAHgFQAXgNAsALQAQg9AfgtQAfgtAjgCQASAAAPAOQA2g0BHglQBHglBUABQALgIBzAtQB0AsB3C8QAVgEBKAHQBKAIA/A7IgIAlQgIAhgMAVQAHAQANAnQANAmACAdQAAATgMAHQgMAEgPgKIgXgQQgDAVgNArQgNArgeAWIgCABQgKCJheBJQhMA5hjAoQASAegBBBIAAAAIAAABQAAACgJALQAmAfAjAzQA5BdAPCSQAPCUgFB7QgFB7gDAQIAAACIgCABQgBAEgcASQgXAqhtAtIgSBkQgLBCgFA7QANAIAFANIAAABQAAAEgDADQgIAHgIgBIAAADIAAACIAAACIABAIIAAALIAAAAIAIBnQAFA/AJAyIABALIACAHIAAAAIACAHIABAFIgFABIgIACQATAbAEBOIAAAEIgEABIgZAFQgYADgeABIgEAAIgEgVIgMASIgCABQgDAChCAMQgoAHgyAAQghAAgmgDgACBS1IAIgeIgWgFIgEgBIAAgDIAAgYIABhYIAAgBIAAgQIAAgCIAAgQIAAgDIAAgnIAAgCIAAgSIABgFIAAgPIAAgGIAAgPIAAgGIAAgPIABgFIAAgVIAAAAIAAgVIABgFIAAgPIAAgHIABgNIAAgIIAAgMIABgIIAAgMIAAgHIABgSIAAgBIABgRIAAgGIABgMIAAgGIABgKIAAgHIABgJIAAgGIABgHQhGAKhGgGQgIAngLA6QgLA6gDAkQAMgBAIAGIADAHQgEAPgOAHIAHBgQAGBKAAA9QAAAWgBAOIgBAEIgEAAIgKABQAGAOAGAWQAQgDAUAAQBoADAZAGg");
	this.shape.setTransform(63.2,131);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,-0.1,126.5,262.2);


(lib.Symbol8 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#14395A").s().p("ACzPaQhZgWgqgVQgqgWgBgCIgCgCIAAgCQgBgGAAgpQAAgoAMgoQgPgEgGgEIgCgDQAJAlAAAmIgBAsIgBACIgBABQgCADgpATQgpAUhXAVQhXARgsgHQgsgIgBgDIgBAAIAAAAQgdgbgBg2QAAgzAjgcQAXgRAagHQACgEADABIACABQAlgIAdgBQAXgBAJgDIAzgaQgNgGgGgMQgCgEAAgFQAAgFACgGQAHgMAOgHIgHAAIgCgBQgQAYgWADQgcABgRgXQgDgGAAgHQAAgQAPgVQgSgOgIg3QgOgJgMgKIgBgCIAAgCIAIg1QAHguANhEQgBgaAAgcQgBg+ALg4QgRgIgOgOIgBgCIAAgCQgBgFAQgwQAQgwArgrQiAgghLg7QhKg7gDgIIAAgBQgHgTABgzQAAgsABgbQgKAQgFAgQgEAhAAAcQAAABAAABQgBAAAAABQAAAAgBABQAAAAgBAAQAAABgBAAQgBAAAAAAQgBAAAAAAQgBAAgBgBQhehKgEhCQgEhCAHgFQBPkXCEiQQCDiQBbgjQBagmA+ANQA8AMAkAdQAjAdAKANQA0gpBkAUQBjAUBeA9QBvBnAOBZQAOBYgHAGIgWgUQgTgSgLgHQAKAlAAApQgICQg5B2QgGAmgPAmQACAKg0BNQg0BNiKAzIAMBLQAHAtADAcIAAACIgBABQAAAFgbAUQAHAwAPBPIALAyQAFASAEALQAQAfAVAWQAcAbABAbQgFAcgZAlQgaAlgZAGQgKABgKgDIgCABQg+ABgYgWIgCgDIgcAGIAABMQAjAFARAbQACAGAAAFQAAAFgCAGQgHAKgNAFIAzAdQAIADAXACQA3gCA9AoQAfAdABA0QgCA4gaAcIgBAAIAAABQgCADgqAIQgOADgTAAQgmAAg5gLgAgNLRIAVAUIAMgKQgOgCgJgKIgKACgAgiKgQAcAGANAOQAQgKAWgEQABgogBgcQgoAEgmgBIgBA7gAhuKdIAEgBIAAgCIgEADg");
	this.shape.setTransform(60.4,99.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-0.1,0,121.2,199.6);


(lib.Symbol7 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#14395A").s().p("AEFWhQhXgGgfgUQgegUABgEIAAgBIgBAAIgEgUQgDgPAFgKQAOgNASAEIAAgEQgBgTAKgjQAKgjAigiIgRgvQhmAZhuAFIgGARQAjAiAIAjQAKAjgBATIAAAEQASgEANANQAFAKgCAPIgFAUIAAAAIAAABQABAEgfAUQgcAUhXAGQhgAEhngRQhogQg0gkIgCgBIAAgDIAGgmIABgEQAGgeAQgjQAPgjAdgZQAjgdAwAFQA2AIAcAhQAygdA1gDQhmgHhYgtIgDgCIABgDIAMiSQAMiGAQiWQghABgjgBQgigCgVgJQg0gegOg6QgCgYARgNQAOgJAKABQAHABALgCQALgDAPgWQg9hOgahHQgYgLgBgCIgDgBIABgDQADggAchRQAdhRAmhTQAmhUAjgmIAPgPQhZAGgvgkQgBgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAgBABAAQAAgBAAAAQABAAABgBIARgMQAPgLAFgVQAFgZgbgdIgagYQg4gxhShkQhShkgsiTQgsiTA5i+QBCi5BRhKQBRhLBCgKQBBgKARAGQAKgNA4grQA3grBdghQBegiCLAXQCNAWCsCPQAAABABAAQAAABAAAAQAAABAAAAQABABAAAAIAAABQgBADgDABIgcAJQAbATAyBTQAyBUAHCZQAAApgGAvQgYCbg6CGQg6CGgxBYQgWAngSAcQgTAdgBALQAEAgAdAQQAdAPAEAAQADABAAADIAAABQABADgIATQgIATgWAMIAvAtIATgDQAOgMAWgJIALgFIAEgCIAFgBQAjgLAWAFQAJADAFAFQAJABAJACIABAAQgFgfAfgmQAcgYAzAMIAIABIgFAGQgBABgKARQgKARgBAXIABAJQAFgTAhgUIABAAIAAgBIAFAJQgJgEgRBBQBWAqAQCEQAGA/gPBGQgQBGgpA7IABABQg+BhhLAaQhKAZgqgEQASB2AMB/QANCAABBtIgBAqIAAADIgDABIg+AbQg8AZhfAcIAHAqQAPgBAqAGQAqAGAjAWQAcghA2gIQAvgFAkAdQAdAZAPAjQAQAjAGAeIAAAEQAHAhgBAFIABADIgDABQgzAkhoAQQhUAOhPAAIgkgBg");
	this.shape.setTransform(73.3,144.2);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-0.3,0,147.2,288.6);


(lib.grandmother = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// grandmother
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E9FDFF").s().p("AgJAAIAPgEQAEACABACIgUAFQgBgCABgDg");
	this.shape.setTransform(30.9,-12.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#72B7DD").s().p("AgGALQgKgIAGgJQAIgKAJAGQAFAEABAFQABAEgDAEQgFAGgGAAQgCAAgEgCgAgHgEQgFAGAIAHQAGAFAHgIQACgEAAgCQgBgFgEgCQgEgCgCAAQgDAAgEAFg");
	this.shape_1.setTransform(30.9,-12.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#B3F1FF").s().p("AgGAKQgIgHAFgJQAHgIAIAFQAJAHgFAIQgFAGgFAAQgCAAgEgCg");
	this.shape_2.setTransform(30.9,-12);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#8C6235").s().p("AAAAAIgCgDQAEABABACIAAAEQgBgDgCgBg");
	this.shape_3.setTransform(29.3,-8.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#8C6235").s().p("AggAuQgBAAAAAAQgBgBAAAAQAAgBAAAAQAAgBABAAQAGgFALgMQAFgEACgEQgSgDgIgHQgBgBgBAAQAAgBAAAAQAAgBgBAAQAAgBABgBQABgDAIgDIAMgEQAKgIAGgPIADgQIAAAHQgBAHgCAIQgFAKgHAHQAFAAAEACIgFAAIgIABIgMAEQgGABgBACIACACQAJAIAPADIAPADQgGABgGgBIgKAKIgOAOQABABAQgCIAfgDIAVgBIgQADIgbADIgYADIgCAAIgCgBg");
	this.shape_4.setTransform(29.8,-11.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#D8A76C").s().p("AgJAJIAJgIQABgGgKgCQgMgDACgIIABADQADADAJACIAPACQANACgBAGQgNgDgIAJQgDAGgLAHQAAgFAFgFg");
	this.shape_5.setTransform(28.3,-9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#E9FDFF").s().p("AgJAAIAPgEQAEADABABIgUAGQgBgEABgCg");
	this.shape_6.setTransform(27.3,-13.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#72B7DD").s().p("AgGALQgKgIAGgJQAIgKAJAGQAFAEABAFQABAEgDAEQgFAGgGAAQgCAAgEgCgAgHgEQgFAGAIAHQAGAFAHgIQACgEAAgCQgBgFgEgCQgEgCgCAAQgDAAgEAFg");
	this.shape_7.setTransform(27.3,-13.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#B3F1FF").s().p("AgGAKQgIgHAFgJQAHgIAIAFQAJAHgFAIQgFAGgFAAQgCAAgEgCg");
	this.shape_8.setTransform(27.3,-13);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#63550D").s().p("AgUAAQAHgGANgBQAKgCASAOIgSgFQgPgFgWAOIAHgJg");
	this.shape_9.setTransform(54,36.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#63550D").s().p("AgWAAQAKgGANgBQAPgCARAOQgEgDgQgCQgRgGgcAOIAKgIg");
	this.shape_10.setTransform(29.3,36.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#8C6235").s().p("AgMAAQgRgCAAgBQAHADAPAAIAYACIANABIgNABQgRAAgMgEg");
	this.shape_11.setTransform(35.3,-23.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#8C6235").s().p("AgVACQgYgFgDgCQAnALAegBIAcgBQgVACgRAAQgSAAgOgEg");
	this.shape_12.setTransform(35.6,-24.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#892116").s().p("AgPAAQAOgHARABQgIANgIAAQgIgBgHgGg");
	this.shape_13.setTransform(30.6,-5.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#706801").s().p("AgNBpIABgCIAQAFQAVhEgDgoQgDgqgQgZQgNgZgRgVQAMAJASAeQAUAdAFAtIgEAuIgGAuQgDATgEADQgVgEgDgFg");
	this.shape_14.setTransform(48.3,14.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#493D03").s().p("AgDBzQgKgDgCgEIAAgBQACgBAJgXQAIgXAFghQAFgfgNghIAAgBIgBgMQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAAAAAAAIABAFIABAEIACAEQAHAQABARQABAngMAiQgJAigEAGQADAEAWAEQADgDAEgTIAGgtIAEgwQgEgjgPgbQgNgagOgPIgPgOIgBgBIABgBQAAAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAIAPAPQAOAPANAbQAQAbAFAjIgDAmQgCAbgEAYQgEAZgGAEIgBAAIgQgEg");
	this.shape_15.setTransform(48.2,14.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#878002").s().p("AAABzQgLgDgCgEIAKgZQAIgYAFgiQAFgggNgfIgBgMIgfhDIAPAPQAOANANAbQAPAbAEAkIgCAdQgCAbgFAdQgEAcgFAEIgNgDg");
	this.shape_16.setTransform(48.2,14.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#704C2C").s().p("AgCAFIAAgCQADgDABgFQAAAAAAABQAAAAAAAAQAAAAABAAQAAAAAAAAIgBADQgBAEgBACIgBABIgBgBg");
	this.shape_17.setTransform(47.9,30.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#704C2C").s().p("AgGAEQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAAAAAAAQACACAJgIQAAgBAAAAQABAAAAAAQAAAAAAAAQABAAAAABIAAABIgHAEIgEADIgCgBg");
	this.shape_18.setTransform(45.9,30.5);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#704C2C").s().p("AgDAKQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIADgGIADgHIgCgCQAAAAAAAAQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAEABABADIgBACIgEAHIgBAGIgBAAIgBAAg");
	this.shape_19.setTransform(44.9,28.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#EAC18B").s().p("AAAgIQAFAEgCAAIgDAHIgDAGg");
	this.shape_20.setTransform(44.9,28.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#704C2C").s().p("AgNAbQgFACgFgDIgBgFQAAgEADgHQgCgDgCgHQgBgHAEgDIADgBIADgBIADgCIAOgEIADgGIADgFIAAAAQAHgEAHAHIAAABIAAADQAAAHAEAIQABABABAGQAAAFgHANIgDAEQgCACgGABQgCADgGADIgDABQgFAAgGgFgAgMAaQAIAHAFgDQAGgEABgBIABAAQAEgBAEgEIADgFQAGgLgBgEQgBgFgBAAIAAgBQgEgIgBgIIAAgDQgGgEgDACIgFAFIgDAFIgBABQgXAGACACQgCACAAAGIADALIABAAIgBABQgCAGAAAEIABACQAEADADgBIABgBIABABg");
	this.shape_21.setTransform(46.7,28.1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#EAC18B").s().p("AgOAaQgBABgGgBQgGgCAFgNIgCgKQgCgGAEgFQgDgBAZgHIAHgLIAEgBQAEAAAEAEIAAAHQABAGADAGQABAAABAFQACAEgHANIgDAFQgEAEgFABIgHAFIgDABQgGAAgGgFg");
	this.shape_22.setTransform(46.8,28.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#66421F").s().p("AgJAIQgCgIATgNIACAOIgHAEIgJAJQgCAAgBgGg");
	this.shape_23.setTransform(26.4,-22.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#704C2C").s().p("AAHACQgCgCgFAAIgHAAIgBAAIAAgBQADgBAFAAQAHABACACIgBACIgBgBg");
	this.shape_24.setTransform(49.5,-11.5);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#704C2C").s().p("AgKAHIAFgHQAFgGAJgCQABAAAAAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAAAAAQgKADgDAEIgEAHIgCABQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBg");
	this.shape_25.setTransform(49.2,-12);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgEAKIADgTQAFACABAHQAAAIgIACg");
	this.shape_26.setTransform(26,-15.3);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AgEAAIgBgJIABAAQAIAAACAJQAAAIgHACIgDgKg");
	this.shape_27.setTransform(35.6,-15.3);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#C1AE02").s().p("AAHAbQgjgEgZgKQgZgJgBgCQgCABgCgJIABgQQAEgFAFgBQgFAcAfALQAfAMAmgBQAoAAAWgHIAAACQgeAMgdAAIgSgCg");
	this.shape_28.setTransform(41.3,32.4);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFED48").s().p("AAfASQgGgTgLgCQgLgBgHAIIgLAMIgBACIgBgDQgGgVgLgCQgKAAgHAIIgIAHIgCACIAAgDQgGgUgIgCIgEAAIAAgEIADAAQAJADAFAUIABADIACgDIAIgHQAHgIAKABQAKACAGAVIABADIACgDIAKgLQAIgIALAAQALACAGAUIAAADIACgDQABgCAKgLQAKgKAMgBQAJAAAGAJIAAABQgHgHgHAAQgNACgJAJIgMAOIgCACg");
	this.shape_29.setTransform(41.9,31.6);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#493D03").s().p("AAHAdQgkgEgZgJIgbgLQgIgCADgZIAAgBQAIgIAIACQAJACAGAWIAKgLQAHgGAJABQAMACAGAVQAEgEAHgIQAJgHAKABQAMACAGATQAEgFAKgJQAJgJAMgBQAJAAAHALIAAABIgCAZIgCACQgdALgdAAIgTgCgAg2AOQAZAKAjAEQAlAFAogPIABgOIACgLQgGgJgIAAQgNABgKAMIgLALIgCABIgBgBQgFgUgLgCQgLAAgIAKQgKAHAAACIgCABIgBgBQgGgVgLgCQgJgBgIAIIgIAJIgBABIgBgBQgFgWgJgDQgGgBgHAHIAAAQQABAJADgBQABACAZAJg");
	this.shape_30.setTransform(41.4,32.3);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#DDCD00").s().p("AAFAdQgjgFgZgJQgZgKgBgCQgEgBgBgGQgBgIACgLQAHgIAIACQAIACAGAXIAIgJQAIgIAKAAQALABAHAXIAKgJQAHgKAMAAQAMgBAHAXIAJgJQAIgKAMgFQALgFALAOIgEAbQgfAMgdAAIgSgBg");
	this.shape_31.setTransform(41.5,32.4);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#493D03").s().p("AAGACQgIgDgCgCQgYAEABgBIgBgBIACgBQgCACAYgFIABAAIAIAFQAKAEANgBQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIgBABQgNAAgJgEg");
	this.shape_32.setTransform(41,12.7);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#493D03").s().p("AgFgCIABgCIABABQABABAHAEQAAAAABABQAAAAAAAAQAAAAAAAAQAAABAAAAIgCABQgIgFgBgCg");
	this.shape_33.setTransform(48,9.9);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#8C6235").s().p("AgDAAQADgCAJADIgFgBQgFgBgHADQAAgBAFgBg");
	this.shape_34.setTransform(30.7,-2.9);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#704C2C").s().p("AgJAXQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAAAAAQAMgCAHgGIAGgHQAHgMgDgHQgDgFgFgCIgFgBQgQAAgIAIQgGAKACACIgBABIgCgBQgCgDAHgLQAIgIAQABIAIAAQAGABADAFQAEALgKAOIgGAHQgGAGgNACIgBgBg");
	this.shape_35.setTransform(48.9,-11.6);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#EAC18B").s().p("AgWgBQgBgBAEgKQAEgJAWgBQADAAAJAFQAJAGgKASIgHAIQgGAGgNACg");
	this.shape_36.setTransform(49,-11.6);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#8C6235").s().p("AgCAAQACgKAHgEQgEAEgJAZIAEgPg");
	this.shape_37.setTransform(25.6,-7.7);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#8C6235").s().p("AAEAIQgLgDgLgOIAKAJQAJAHARADIAAAAIgOgCg");
	this.shape_38.setTransform(38,-10.2);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#8C6235").s().p("AARAJQgQgTgfgRQAEAAAUAMQATAMASAfIgOgTg");
	this.shape_39.setTransform(37.2,-6.6);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#8C6235").s().p("AgOAGQgHgGgDgFIAAgBIABgBIAbgDIATgDIABABIABACQgLAXgOABQgHAAgHgIgAADgHIgXACQADAFAGAFQAGAGAFAAQALgBAKgTIgSACg");
	this.shape_40.setTransform(30.4,-5.8);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#4F2F15").s().p("AgNAFQgHgGgCgFIAagCIATgDQgKAXgNAAQgGAAgHgHg");
	this.shape_41.setTransform(30.5,-5.8);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#72B7DD").s().p("AgKAkIgBgBIACgGQAEgVAAgLIAAgPIACgRIAAgBIADgBQAHACADAMQADAMgBAOQgFAhgNACIgEgCgAgDgTIAAASQgBAPgEATIACABQAGABADgKQAGgKACgOQABgNgDgKQgEgLgFgBIAAAAIgDAPg");
	this.shape_42.setTransform(26.4,-17.5);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AgHAkQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQAEgUABgPIAAgRIADgRIACAAQAGABADALQAEAKgCAOQgBAPgGAKQgEAKgGAAIgBAAg");
	this.shape_43.setTransform(26.4,-17.5);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#72B7DD").s().p("AAAAoQgKgKgFgcQgDgQADgNQACgMAIgCQADAAACACQAKAHAEAaIACAHQAFAlgOAEIgBAAQgDAAgDgCgAgOgZQgCANADAQQAFAaAJAIQAEADADgBQANgHgHgiQgFgbgJgJQgEgCgDAAQgGACgBAMg");
	this.shape_44.setTransform(36.5,-15.6);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AgFAfQgGgMgDgRQgDgPADgNQACgMAHgBQAFgBAGALQAGALADARQADAQgDALQgCANgHACIAAAAQgGAAgFgKg");
	this.shape_45.setTransform(36.5,-15.5);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#66421F").s().p("AgCAGIgHgGQgCgFABgEIACgEQAEgCAGAJIAJAJIAAALQgIgBgFgHg");
	this.shape_46.setTransform(37.4,-20.9);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFD6A4").s().p("AAgCFQARgSARgbQAQgaACgcIAAgGQgCgUgQgOIgGgHQgFgHgCgKIABgHIAAAAIAFgOQAEgNAAgRQAAgcgigZIAJgBQAjAZgBAcQABASgFAMIgFAOIAAAAIAAAHQABAKAGAHIAGAIQAQANABAVIAAAFQgBAcgRAbQgQAagSATIgUAUIgJABQADgCARgTgAgziAQgUgBgNgIQgGgEgDgHIAIgFQACAJAJAGQALAHAQACQARACASgBIgWABIgRgBg");
	this.shape_47.setTransform(39.4,-12.8);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#D8A76C").s().p("AAxCOIgJgCQgqgMgbgTQgbgSgBgCQgHgJgBgPQgBgUAFgRIAFgUQAJgVACgZIABgcQAFghAKgTQALgTAKgIQgLAPgJAbQgJAagDAcQgDAcAIASQgdAkAGAaQAFAZAXARQAYARAaAKIAvASIgSgEg");
	this.shape_48.setTransform(30.5,-12.7);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#704C2C").s().p("AAgCdIgBgBQgIgFgSgFIgSgFQgtgMgcgRQgdgSgCgCQgKgMABgUQACgUAFgQIAGgTQAIgVABgYIAAgaQAJg2AUgTQATgTADABIABAAIABABQABAKAJAFQAPAKAaAAQAYAAAWgEIAXgEIABAAQATAMAIAPQAIAOAAAOQABATgEANQgEAMgBACIAAAGQABAKAHAGIAHAHQAPAOAAAWIgBAJQgCAdgPAaQgRAagQARIgTAUIgGACIgGACgAhNiFQgRATgHAwIgCAbQgBAZgJAWIgGATQgEASAAAUQABAOAIAJQABACAbATQAbATAsAMIAUAEQASAEAJAGIAKgBIAKgBIAVgUQARgSARgbQAQgbACgbIAAgGQgCgVgQgNIgGgIQgGgGgBgLIAAgHQACgBAEgNQAEgMgBgSQABgcgjgZIgaAEQgWAEgXgBQgZAAgQgKQgIgFgCgKQgHACgRATg");
	this.shape_49.setTransform(36.2,-12.7);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#EAC18B").s().p("AAECSIgUgEQgtgNgbgSQgbgTAAgCQgKgMAAgTQABgTAEgPIAFgRQAJgVABgZIACgbQAJg3AUgSQATgSACABQAFAVAeADQAbAEAdgFIAfgFQAcATAFAXQAFAXgGARQgFARgBAAQgBANAGAJIAIAJQAWAUgFAcQgEAcgSAaQgRAZgQARIgRARIgWACQgIgGgTgEg");
	this.shape_50.setTransform(36.3,-12.8);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#B4C0D3").s().p("ABZBSQAKgVAFgPIAEgQQAFgUgCgPQgDgdgNgSQgOgTgMgJIgOgJQgsgVghgBQgkgBgZAJQgZAIgLAHIABgBQADgDAYgLQAYgMAogCQAmgCAzAYQACAAAMAJQANAJANATQAOASADAdQACAPgFAUIgFASQgFARgMAWQgMAWgUAPQARgQAKgUg");
	this.shape_51.setTransform(42.9,-19.2);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#566984").s().p("AAiB+IgggWQgcgWgjghQhahYAjg7IAAAAQABgCAYgLQAXgMApgCQAngDA1AZQADAAARANQASAOAPAbQAOAbgJApIgIAaQgJAYgTAZQgUAZggAHIgBAAgAgXh7QgoACgYALQgZALgCADQgLATACAUQAEAfAXAeQAXAfAdAaQAeAaAWARIAbATQAhgGASgZQASgZAIgYIAIgaQAEgSgBgRQgDgcgOgTQgNgSgNgJIgOgJQgvgWgkAAIgGAAg");
	this.shape_52.setTransform(42.5,-18.6);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#91A3BF").s().p("AAEBnQgcgVgkgiQgjgigUglQgTgmAUgkQAAgBAYgMQAXgMAqgCQAngDA1AZQACAAARAMQARANAOAbQANAbgJApQABACgIAYQgIAYgSAZQgTAaghAGIgggWg");
	this.shape_53.setTransform(42.5,-18.6);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#B4C0D3").s().p("AABA5IAJgSIADgHQADgLgBgKQgCgRgKgOQgHgOgKgIIgBgFIgEgJQALAHALAQQAOAQADAWQABAKgDAMIgEAKQgEAJgIALg");
	this.shape_54.setTransform(55.9,-17.9);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#677D99").s().p("AgSATIACgMIAFgbQAAAUAIAFQAGAHAQgBQgLAKgOAAIgMgCg");
	this.shape_55.setTransform(52.9,-11.8);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#798DAA").s().p("AgZBGIAEgXIAIgvIAIgvIAFgXIADAEIAEAJQAEARgEASQgGASgBAOQAAARALAMQAHAFAIADQgIAMgNAHQgHAFgLAAQgGAAgGgBg");
	this.shape_56.setTransform(53.6,-16.9);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#566984").s().p("AglBIQAAAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAZiPIABgBIABAAIAPALQAOALANAVQAMAUgGAbQAAACgJAQQgJAQgRAOQgKAJgPAAQgGAAgIgCgAgOguIgJAuIgIAvIgEAXQAYAFANgNQAPgNAHgQIAIgRQACgLAAgIQgFgdgRgRQgPgRgHgEIgEAYg");
	this.shape_57.setTransform(54.5,-16.9);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#91A3BF").s().p("AgjBHIAZiPQABAAAMALQAOALALAUQAMAUgGAaIgHASQgIAQgPANQgKAKgPAAIgOgCg");
	this.shape_58.setTransform(54.4,-17);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#493D03").s().p("AgeAdQgIgFgCgNIgBgPIAAgBQA8gjARAQQAHAJgBAMIgDANQgJAQgMACQgKAAgGgFIgIgIQgMAPgIAAIgEgBgAAMgZQgPACgkAUIABAHQAAAIACAHQACAHAFACQAHACAPgRIABgBIABABIAFAHQAHAGALAAQAKgBAIgPIAEgLQACgMgIgJQgDgEgKAAIgJABg");
	this.shape_59.setTransform(41,1.8);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#C1AE02").s().p("AgdASQgFgCgCgHQgCgHAAgGIgBgJIABAAIAAADQAAAIADAFQACAHAEACQAIACAOgPIABgCIABACIAGAFQAHAFAKAAQALgBAIgMIADgNQAAAIgCAFIgCAEQgIAPgLABQgKAAgHgGIgFgHIgBgBIgCABQgMAPgHAAIgCAAg");
	this.shape_60.setTransform(41,2.8);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#DDCD00").s().p("AgfAcQgHgGgBgOIgBgNQAzgcAQAGQAQAFgCAQQgCAOgCACQgKARgKgBQgLAAgGgGIgHgHQgNAQgHAAIgEgBg");
	this.shape_61.setTransform(41,1.9);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#706801").s().p("AALBiQAEg4ADhPIgEgfQgEgbgKgdQgMgdgVgKIALAFQAWAOAFAVQAHAVgBACIAAABQASAgADA1QADAlgBAmQgCAmgCAbIgEAgIgUAGIAFhCg");
	this.shape_62.setTransform(47,18.3);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#706801").s().p("AgJB/IgOgHQgEgBAAgIQgBgLACgPIAFgcQAMg0AGgnIAEgsIAAgCIgCgOIgEgLQgDgGgBgGQAAgLAEgKQAAARAHAXQAIAXATAAQgYAigFAsQgGAuAGAnQAHAnATAMQgXgGgMgGg");
	this.shape_63.setTransform(35.7,20.6);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#493D03").s().p("AAFCpQgkgEgagJIgagLQgGgDAAgOQAAgOADgPIAEgVQAMgzAGgnIAHgsQAAgEgEgIIgGgOQgHgQAGgRQAGgRAJgMIALgOQAsgUAdARQAWAPAIAVQAHAVAAADQATAhACA3QACAjgCAnIgDBCIgDAfIgBABQgeALgdAAIgSgBgAgoicQgEADgLASQgMASgBAWQABAGADAGIAEALQAEAJAAAGIAAABIgGAsQgGAogMAzQgDANgCAPQgCAPABALQAAAIAEACQABABAZAKQAYAJAkAFQAlAEAngPIAEgfQACgbACgmQABgmgDglQgDg2gSgfIAAgBQABgCgHgVQgHgVgWgPQgNgHgRAAQgRAAgXAKg");
	this.shape_64.setTransform(41.6,18.4);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#878002").s().p("AADCoQgkgEgZgKQgZgKgBgBQgFgDABgQQABgQACgOIADgQQANg0AFgoIAGgrQAAgFgEgKIgEgLQgHgQAGgSQAHgRAJgMIAJgMQAugTAYAPQAYAPAHAWQAHAWAAACQAPAaAEAqQAFApgBAsQgBAsgDAeIgEAfQgfAMgeAAIgRgBg");
	this.shape_65.setTransform(41.7,18.4);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#878002").s().p("AgRBGIAAgBQAAgFABAAIABAAIAKgbIAJggIAGgPQADgOABgPQAAgPgBgLIgBgLIAFAHIAAAGQABALAAAPQgBAPgDAPIgGAPIgJAgIgKAaIgCAFIAAABQABACAEADQgJgEAAgDg");
	this.shape_66.setTransform(33.8,16.6);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#493D03").s().p("AgYBFIAAgBQAAgGACgBIALgaIALgfIADgNQADgOABgQQAAgQgBgLIgCgPIABgCIACABQATAVgBAmQgBAlgIAgQgIAhgCAEIgCABQgXgHgFgIgAAJhCQABALgBAPQAAAOgEAPIgFAPIgJAgIgLAbIgCAEIABACQAAACAGAEQAFADAOADQADgIAIglQAIgkgCgkQgBgZgMgQIABALg");
	this.shape_67.setTransform(34.2,16.8);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#706801").s().p("AgWBFQgBgHACAAIALgbIAKghIAEgNQAGgagCgVIgCgYQATAWgBAnQgCAlgIAgIgJAjQgbgGAAgIg");
	this.shape_68.setTransform(34.2,16.8);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#704C2C").s().p("AgDANQgDgDAAgFQgBgFACgGIACgHQAAAAABAAQAAgBAAAAQAAAAAAAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAAAQAAABAAAAQgCAEgCAHQgCAFACAFQAAAAABABQAAAAAAAAQAAABABAAQAAAAAAAAIABAAQAAABAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAAAABgBQAAAAAAgBQABgBAAgBQACgEgBgKIACgBQAAAAAAAAQABAAAAAAQAAAAAAAAQAAABAAAAQABASgHADIgBAAQAAAAAAAAQgBAAgBgBQAAAAAAAAQgBAAAAgBg");
	this.shape_69.setTransform(33.5,25.9);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#EAC18B").s().p("AgBAMQgGgDACgJIAEgNIAHAHQAAATgEAAIgCABQAAAAAAgBQAAAAAAAAQgBAAAAAAQAAAAAAgBg");
	this.shape_70.setTransform(33.4,25.9);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#704C2C").s().p("AgEAWIgHgFQgEgHAFgOQAFgPADgEIABgBQAGgBAFAGIAEAGIAAABIgDAMIgCAPQABAIgFACIgDAAQgCAAgEgDgAgIgCQgEAIAAAHIACADQACACAGADQADADADgCQADgBAAgGIABgOIADgNIgEgGQgDgEgEAAQgFAJgDALg");
	this.shape_71.setTransform(33.1,25.8);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#EAC18B").s().p("AAAAXQgKgFgBgCQgEgHAHgOIAHgSQAGgBAEAFIAEAGQgCAFgBAKIgCANQAAAJgGAAIgCgBg");
	this.shape_72.setTransform(33,25.9);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#282203").s().p("AgsARQgTgGAAgBQgGgDgBgGIgBgBQABgMAGgKQgEAXAYAKQAYAJAggDQAigDAagOIAAADQgmASgfABIgDABQgbAAgRgGg");
	this.shape_73.setTransform(32.1,39.5);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#231D01").s().p("AgtAfQgTgGgBgBQgHgDgBgHQgCgLAFgIIAHgLQANgRAWgCQAUgCALAKQALALAFAMIAHAPIASgEIASgDIACgDIAAgBIABAAQAIAEABAFIAAAHIgBABQgmATggABIgDAAQgcAAgRgGgAgcghQgVADgMAQIgGAKQgFAIABAJQACAGAFADIATAHQATAGAdgBQAfgBAmgSIAAgDQAAgFgGgEIgCADIgBAAIgmAIIgBAAIgBgBIgFgNQgFgNgMgMQgIgIgPAAIgGAAg");
	this.shape_74.setTransform(32.1,38.3);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#3F3706").s().p("AgtAeIgTgHQgMgKAGgNQAGgOACgBQAOgRAUgCQAUgCAKAKQANAMAFAOIAFANIAngJIABgDQAIADAAAFIAAAGQgnATgfABIgDAAQgcAAgRgFg");
	this.shape_75.setTransform(32.1,38.3);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#704C2C").s().p("AgLAfIgGgMQgFgLgGgFIgBgBIAAgBIABAAIAUgCQAJgCAEgFIgBgLIAAgLIAAgBIACAAIAQAFIABABIAAAKQAAAIgCAHIAFAFQADAFABAGQAAAEgDADIAAABIglAIIgBgBgAAHgRIABAKIgBAAQgDAGgKABIgSADQAFAGAEAIIAGAMIARgEIASgEQACgCgBgDQgBgGgDgFIgEgFIgBAAIAAAAIACgNIAAgLIgGgCIgHgCIAAALg");
	this.shape_76.setTransform(35.8,36.5);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#EAC18B").s().p("AgQATQgGgLgGgGIARgCQAMgBAFgGIgBgXIAQAFIAAAKIgCAPQACAAAFAIQAFAIgFAHIgkAIIgGgMg");
	this.shape_77.setTransform(35.8,36.5);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#282203").s().p("AgnAUQgWgEgBgBQgIgDABgDIAAgBIABgCQA4AUAlgOQAngMgBgVQAGAJABAHQgBAJgCABQgbAPgeACIgRAAQgRAAgPgCg");
	this.shape_78.setTransform(51.2,39.6);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#231D01").s().p("AgnAgQgWgDgBgBQgKgFABgFQgCgFALgGIABABIABAAQACAGAGABIAYACIARAAIAAgGQgBgOAFgJIAHgKQAKgNARABQAQABANAKQASASgCAJQgCAMgBABIgBAAQgaAQgfABIgRABQgTAAgOgDgAhFASIAAABQgBADAIADIAXAFQAWADAbgBQAegCAbgPQACgBABgLQAAgJgQgPQgMgJgPgBQgPgBgMAMQAAABgFAKQgGAJADASIAAACIgGAAIgngCQgGgCgDgGQgGACgBAGg");
	this.shape_79.setTransform(51.2,38.6);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#3F3706").s().p("AgnAfIgXgEQgGgCgBgDIgBgEQABgHAIgCQACAGAHACIALAAIAVACIALAAQgDgTAGgJQAFgLABgBQALgMAPABQAQAAANAKQASARgCAKQgCALgBAAQgbAQgeABIgQAAQgTAAgPgCg");
	this.shape_80.setTransform(51.1,38.6);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#704C2C").s().p("AgGAgIgTgCQgIgCgCgGIAAgDQAAgJAEgIIAGgHIgBgNIAAgLIABgCQAJgCAEABIAEABIAAABQACACAAAFIAAAMQAPAGAMAAIAOgBIABABIAAABQgLAOgEALIgDALIgBABIgHABIgQgCgAgXgcIAAAMIABALIgBABIgFAGQgFAIAAAIIABADQACAFAGACIARACQAOABAIAAQAAgIARgaQgKABgZgGIgGgCIAAgNIgBgGIgDgBIgKACg");
	this.shape_81.setTransform(48.4,37.4);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#EAC18B").s().p("AgGAfIgSgCQgOgGAGgOQAGgMADgCIgBgYQAJgDADABIAEABQABAEAAAIIAAAIQAQAGANAAIANAAQgLAOgEALIgDALIgFAAIgSgBg");
	this.shape_82.setTransform(48.4,37.4);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#FFD6A4").s().p("AgFBYIgBgcIgEg8IgEg6IgBgcIABgBQABgBAGABIABASIABAfIAAAQIACABIADgPIAGgcIAEgPQAGgBABADIgHAUIgKAjIgFATIAAAVIACAtIAAAZIgCAAg");
	this.shape_83.setTransform(55.5,-16.9);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#704C2C").s().p("AgHBZIgLiwIACgCQADgDAIACIABABIAAAXIABAiIAGgeIAFgUIABgBQAJAAABAEIAAABIgGATIgLAkIgEAUIABAXIABAvIAAAZg");
	this.shape_84.setTransform(55.4,-16.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_84},{t:this.shape_83},{t:this.shape_82},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(50));

	// Layer 2
	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#000000").s().p("AgIgFIgBgCIAEAAQAEgBABgBIAEgCIAEACIgGgOIAHgDIAAAEIgEAxIgFAAQgFgWgDgKgAgCgDIACAQIACgLIABgGIgFABg");
	this.shape_85.setTransform(-87,9.4);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#000000").s().p("AhnGbIgDAAIgCgGIgDADIgCAAQgIgDgGgDIgCgDIABgCIAGgJIAMgPIgFgEIgCgCIABgDIASgaQAPgWAQgQQgCgDgBgDQAAgDACgCIAEgDIgBgUIgCgiIAAgXQgFACgEAAIgFgCIgBgBQgEACgGgCQgFgEgCgGIgCgJQgIAAgIgNQgFgHAAgGIABgEQADgGACAAIABgBIgQgkQgIgSgCgLIAAAAIABgEQgMgLAAgGIABgCQABgEAEAAQgCgDAAgEQAAgGADgCQAEgDAGAAIAOABIALgcIAJgUQAEgIAGgFIgGgEIgDgBIAAgEIAGgLQAFgKAFgGIAEgCQgPgQgPgaQgQgZgJgkQgdgMACgRIAAgEQACgIAHgFQgDgVAAgVQAAgPAFgOIgFgEIgEgDIAAgDQACgNAFgCIADgCIABACIAGAJQAXgpArgSQAogOAbAAIAJgBQANgBAKgEQAogSAPgNIALgHIABgBIABAAIAHABQAFADAHAFQAKAIACAZIgBANQgEASgTAPQACAHAAAMIgBAYIgBADIAAAFIABAHIAAADQAKAGAGAGIAHAHIAAABIAAABIABAKQgBAjgGAOQgFAOgBAAIgBABIgCAAIgFAAIABAGIAFAQQAFAQABAMQAAAGgCAGQgGAUgYAPQgYAQglAHIgKADQACADAAADQAAAEgDAIIgCALIgBAFIACACIAEAIIAKAYQAGAMAGAJQAIgDAFADQAGAFAAAIQAGgBAFACQACACAAADIAAABIAAADIASAAIARAAIAQgQIARgOQAGgDAIADQAIACAFADIACABIgJARIgBAAIgHAEIAEAHQAHAJACAIQAAACgDADQgFADgIgCQgHgDgHgEQgFAFgQgBIgXADIgjACIgDAEQgGAFgFABQADAPAAAMQAAAMgDAKIAAAEQgBAOgEACQgCAIgJAIIAOAvQAHAaADAQQAEATABAaIAAAkIAAACQANAFAGABQACgIANgCQAIgBAFAFQAGAGAAAJIAAACIgBACIgCABIgQAGQgQAGgVABIgCABIgDAAQgCACgNgBIgEAAIAAgEIABgHQAAgHACgJQgHgBgEgDIgBgCIAAgCIAFgtIADgbQgFgCgBgGQABgFAFgDIgPgsQgGgWgEgHQgGABgTAAIgEAaIgEAoIgDAiIAAABIgBABIgJAPIgRAfIgNAaIgCACIgDAAIgEgBIABAAIAFABIAEABQAGgFAOACQAHADACAHQADAJgEAJIgBABIgCAAIgNADIgTABIgRgBgAhoGQIACAGQAoAAAGgDQACgDAAgEIAAgFQgCgFgFgCQgFgBgFABIgGADIgBAAIgNgCIAAAAQgDgCgCgGIgBgEIAFABIAHACIAOgZIARgeIAJgRIADglIAFgqIADgXIAAgDIADAAQAXABAFgCIACAAIABABQACAGAGASIAMAjIAGAUIABACIgCABQgGAEABAAQAAABABAAQAAAAAAABQABAAAAABQABAAABAAIABABIABABIAAACIgDAeIgFArQAEADAGAAIADAAIgBADQgDARABAHQAIAAADgBIABgGIAAgFIADAFIADAFQATgBAOgFIARgGIAAgBQAAgHgEgEQgDgEgGABQgKADgBAFIgBACIgCAAQgKgBgOgFIgGgDIAFgCIAAgCIgBgkQAAgZgEgTQgDgQgIgbIgOgvIAAgCIABgBQAKgHACgIIAAgBIAAAAQACAAACgNIAAgEIAAgBQADgJAAgMQAAgMgEgRIgBgDIAEAAQAEABAGgGIAFgFIABAAIAkgCIAXgDIAAAAQAQAAAEgEIABgBIABABQASAKAFgDIAAgCQgBgGgGgHQgGgIAAgCQADgGAIgCIAFgKQgMgHgIADIgOAMIgSARIAAABIgCAAIgUAAIgUAAIgEAAIACgDIABgFIAAgBQgDgCgHABIgDABIAAgDQABgGgFgGQgFgBgEADIgCABIgCgCQgGgJgHgOIgLgZIgFgLIgBAAIABgGIACgMIADgLIgEgHIgDgDIATgEQAjgHAXgOQAYgPAFgSQACgJgBgIQgBgJgEgLIgDgJIgCgIIgDgNIAEABIAHAAQACgCAEgNQAFgOAAgeIAAgJIgGgHQgGgGgLgGIgEgCIAEgCIAAgCIgBgGIgBgBIACgJIABgXQAAgPgCgEIgBgCIACgCIAAAAQATgNACgQIACgNQAAgPgIgKQgMgMgFAAIgLAHQgQAOgoASQgLAEgOABIgJABQgaAAgnANQgqASgXAqIgCAEIgCgCIgIgKIgCAJIAEAEIADADIACABIgBABQgFAPAAAPQAAAWADAUIABACIgCABQgGAEgCAHIAAADQgBAOAaAKIABABIABABQAJAmAQAaQARAaAPAQIADADIgKADQgEAEgEAIIgGAMIAJAFIADACIgDACQgHAGgEAIIgKAVIgLAdIgBACIgCAAQgSgDgDADQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAABIACAGIADAFIgGABIgCABIAAAAQAAAEAKAKIADADIgCACIgBACQAEAQAXAxIABADIgDABIgDACIgCADIAAACQAAAEAEAHQAHALAGgBIACAAIABADIACAJQACAFADADQADAAADgBIAAgBIABAAQABAAAAAAQABAAAAABQABAAAAAAQAAABAAAAIAAABIAEABIAGgCIAGgFIAEBaIgBABIgEADIAAABQAAABADADIACACIgCACQgPAOgPAVIgUAdIAHAEIAEABIgDADQgGAFgGAIIgIALQADACAIACIAEgEIADgEIABAGg");
	this.shape_86.setTransform(-76.4,-0.4);

	this.instance = new lib.Symbol13("synched",0);
	this.instance.setTransform(-92.5,-41.4,0.261,0.261);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#000000").s().p("AAWBJQgHgCgZgBIgJABIgCABIgBgDIgDgJIgCgCIAGgBIAAgIIgBgkIgDgWIAAgBIACgBIADgEIAAgBIgDAAIgDAAIAAgDIAEgYIAFgZIAAgDIADAAQARACARgDIAEgBIgBAEIAAADIAAAEIAAAFIgBAEIAAAFIAAAEIAAADIAAADIAAADIgBAEIAAAIIAAAEIAAAEIAAAFIAAAGIAAAEIAAALIgBAEIAAAGIAAAIIAAACIAAAXIAAAFIAEABIADAAIgDAOgAAUBEIABgDIgEgBIgCgBIAAgFIAAgEIAAgXIAAgFIAAgEIAAgGIAAgFIAAgDIAAgCIAAgDIAAgDIAAgBIAAgCIAAgGIAAgHIAAgCIAAgDIAAgCIABgDIAAgSIAAgEIABgHIAAgCIAAgFIAAgCIAAgCQgPACgOgBIgFAWQgDANAAAKQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAIAAAAIACADIAAAAQAAAEgFAEIACAXIABAiIgBAKIAAACIgCABIABAEIAIAAQAVAAAJACg");
	this.shape_87.setTransform(78.6,29.6);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#000000").s().p("AgcFYIgCgBIgBgCIAAgFIAAgCIgBAAIAAgBIAAAAIgBABIgTADQgRAEgagCIgDgBIAAgDIgBgHQABgHAFgHQAIgKATAAQAXABAJABIABgCIgBAAIgCgBIAAgDIABgTIACggIABgVIACgXIAFggQgggGgKgMQgOgJgBgGQgBAFgFAGQgGAGgKgBIAAAAQgCAAgFgGIgCACQgIAEgHgEIgBgBIgBgBIgBAAIAAgBIAAAAIAAAAIADAYQAGAhADA0IABAUQAAAegDANQgDAMgBABIAAABIgBAAQgFAEgIADQgJACgKgIIgCgBIABgDIAIgbQAGgaABgqIgBgWQgDgngGgUQgDgOAAgHIABgHIADgFQgIgLAAgGQACgHAOgLQANgKAGgCQAEgBAGABQABgFACgEQAFgFAIgBQAGgBAHAEQAMgTAGgWQAHgWAEgRIAFgWIgBgDQAAgDACgFQgGgFAAgEQgCAAAHgPQgZgLgagSQgagSgSgWQgRgVgBgVIAAgCQABgVAMgPQALgPAMgJIAAAAIgCgDIgBgDIAAgCQADgEADABIAEAAQABAAgBgJQgBgFADgCQAEgEANACQAEgMAGgLQAHgKAHgEIAAgDQgBgLAEgGQAEgHABAAIACgCIACACQAJAHAAADIAAADIgCABIgLALQAFAAADADQAkghAkABQADgCAfALQAeAMAgAxQAIgBATACQASADAQAPIABABIgBABIgCAKQgBAIgEAGIAGAOQADAKAAAIQAAAHgEACQgHABgGgFQgBAHgDAKQgEAJgHAFQgDAkgZAUQgSAOgaAKQAEAHAAANIAAAEIAAABIgCACQAKAJAIALQANAVAFAfQAEAhAAAfQAAAWgBAPIgBARIAAABIgBABIgIAGQgGALgcAMIgEAZQgDAQgBAPQAEADAAADIAAABQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAIgEACIAAAFIADAbQABAQACANIAAADIABABIAAACIABAEIgDABQAFAIABARIAAADIgEABIgHABIgOABIgDAAIAAgBIgBAAIgBABIgSAEQgLACgLAAIgUgBgAgcFEIABAFIACAAIgBADIAAAEIAAADQAXABAOgCQARgDACgBIAEgFIADgEIAAAEIABAFIASgCQgBgSgFgHIgBgDIAEgBIAAgBIgBgCIAAgCIgEgeIgCgbIAAgDIAAgGIACgBIADAAIgEgEIgBgBIAAgBIAEghIAFgaIABgCIABAAQAbgMAGgKIAAgBIABAAIAHgFIABgRIABgkQAAgfgEggQgEgegNgUQgIgMgLgJIgCgBIAEgFIAAgDQgBgOgEgGIgBgDIADgBQAagKATgPQAXgSADgjIAAgBIACgBQAHgFADgKIAEgPIABgGIAFAEQAFAEAEAAQAAAAAAgBQABAAAAgBQAAAAAAgBQAAgBAAAAQAAgHgDgKIgGgOIAAgCIAAgBQADgDACgHIACgLQgQgOgSgCQgTgCgEABIgCABIgBgCQgegwgegLQgdgMgDACQgigBgkAhIgCACIgCgCQgDgDgDAAQgDAAgDACIgBAAQgNAKgHAaIgBACIgCAAQgQgCAAACIAAACQACAJgDAEQgEADgEgBIgBAAIABABIACADIABABIgBAEIgBABQgMAIgKAOQgLAOgCAUIAAACQABAUASAVQARAVAaARQAaASAYAKIADACIgBACQgHAOABABQAAABAGAFIABACIAAABIgDAIIABACIAAABIAAABIgFAWQgEARgHAYQgHAXgNAUIgBACIgCgBQgIgEgEAAQgGAAgEAFQgCADgBAFIAAADIgDAAQgGgCgEABQgFACgMAJQgLAKgDAEQAAAEAIAMIABACIgBABIgDAFIgBAFIAEAUQAFAUAEAnIAAAXQAAAngGAaQgGAagDAFQAHAFAHgBIALgGIADgNQACgMABgbIgBgVQgDg0gGggIgEgcQAAgJAEgDIABgBIAFAAIgBAGQgBAEABACIAAABIABAAIABABIABABQAEACAGgDIADgDIADgDIABAEQADAGACAAQAHAAAEgEQAGgHgBgDQgBgEgFgFIgCgBIACgCIACgEQABgEAAgFIAAgEIgBgEIAEABIAGABIADgBIAAADQgCAcACABQgCACAQALIABABQAJALAgAHIACAAIAAACIgHA5IgBATIgBAfIgCAVIACAAIACABIgDAMIgCAAQgHgCgbgBQgQAAgHAJQgFAHAAAGIABACQAWACARgDIATgDIADgFIADgFIABAFgAhUCDIAAgJIAAgMIgBAAIABACQAAAGgCAFIgCADIAEAFIAAAAgAhLk/IAAABIAKgKQAAgDgEgDQgFADgBAMg");
	this.shape_88.setTransform(77.5,5.2);

	this.instance_1 = new lib.Symbol10("synched",0);
	this.instance_1.setTransform(69.6,-28.7,0.261,0.261);
	this.instance_1.alpha = 0.699;

	this.instance_2 = new lib.Symbol9("synched",0);
	this.instance_2.setTransform(61,-29,0.261,0.261);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#000000").s().p("ABEF7QgYgCgIgFQgJgGAAgCIAAgBIgCgIQAAgDACgCQACgEAFAAQgBgMAPgTIgDgJQgcAHgXABIAAABQANATgBAMQAFAAACAEQACACAAADIgCAJIAAAAIAAAAQAAACgJAGQgGAFgYACQgZABgcgFQgbgEgOgKIgCgBIAAgCIACgKIAAABIABgDIgBABQACgJAEgJQAFgKAHgHQALgIANACQANABAJAJQAEgDAGgCQgTgDgQgJIgCgBIAAgCIADglIAHhJQgSABgMgEQgGgEgGgGQgFgIgCgHQAAgIAFgEQAFgDADAAIABAAQADABAEgFQgNgRgIgUIgGgDIgCgBIAAgDQABgIAHgVQAIgVAKgWQAKgWAJgJQgVAAgKgJQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAgBIACgDIAEgCQADgDABgEIABgCQAAgEgGgGIgGgGQgMgLgSgTQgRgUgOgcQgNgdgBgkQgBgYAJgbQARgwAVgUQAVgUASgDQARgEAGACQAEgFAOgLQAPgKAXgIQAZgKAkAGQAlAGAuAmIABADIAAABQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAIgDABQAJAIALAWQAMAVABAkIAAABIgCAXQgGApgPAjQgQAjgNAXIgJAQIgGALQABAHAGADIAJAEQAAAAABAAQAAABABAAQAAABAAAAQAAABAAABIAAAAIgBAFQgCAFgFAEIAJAJIADgBIAJgFIAEgCIABAAIACgBIgBAAQAKgDAGACIAFACIABAAQAAgIAIgJQAIgHAPADIAGACIgEAFIgEAGIAFgDIACgBIAEAGIgCABQgCAAgDANQAWALAEAiIAAAKQABAcgRAeIAAAAIgBACQgPAYgSAIQgTAIgOgBQALBNAAAuIAAAGIAAAGIAAACIgCABIgQAHQgPAGgYAHIABAHIAPABQAJACAJAFQAIgJANgBQAOgCAKAIQAIAHAEAKQAEAJACAJIgBgBIABADIAAgBIACAKIAAACIgCABQgOAKgbAEQgXAEgVAAIgJAAgAAfFgIAAADIABAHQAAABAHAFQAIAEAVACQAYABAbgEQAagFANgIIgBgJIAAgBQgDgSgOgOQgIgGgLABQgMABgIAJIgCABIgCgBQgIgFgLgCIgOgBIgCAAIgDgQIACAAQAXgHAPgGIASgIIAAgFIAAgFQAAgugLhPIgBgDIADAAQANABASgHQARgHAPgVIgBgBIACgCQASgdgBgcIAAgJQgEgigVgIIgCgBIAAgCIADgKIgCADIgEAJIgCgMQABgKAEgFQgKgCgGAFQgHAJABAHIAAADIgJgBIgBgBIgCgBQgFgBgIACIgBABIgBAAIgDABIgJAGIgBAAIgHABIgQgPIAEgCQAHgFABgGQgEgBgHgEQgGgFgBgIQAAgEAHgKIAJgPQANgXAPgjQAPgjAGgoIACgWIAAgBQgCgmgNgWQgMgVgIgFIgDgDIAEgBIAGgCQgsgkgkgFQghgGgYAJQgYAIgOALIgRAOIgBABIgCAAQgDgCgRADQgQADgVATQgVATgRAvQgIAbAAAXQABAjANAcQAOAbARATQARAUALAKIAHAGQAHAHAAAHIAAADQgEAJgGADQAKAHAWgBIAHAAIgEAEIgFAFQgIAIgKAVQgJAVgIAVQgHAUgCAJIAHADIAAABQAJAVAOARIABACIgBABQgHAKgGgCIgBAAIgEACQgEADABAEQADAOAMAHQAGADAJAAIAQAAIADAAIAAADIgHBGIgEApQAVALAbACIAAAFQgNABgMAHIgCABIgCgBQgIgIgMgCQgLgBgIAGQgOAOgDASIAAABIgBAJQANAIAbAFQAaAEAYgBQAVgCAFgEQAIgFAAgBIABgHIAAgDQgBgBgFAAIgDABIAAgEQABgFgBgIQgCgJgJgJIgBgBIADgHIACAAQAXgBAegHIACgBIAGAQIgBABQgJAJgCAJQgDAIABAFIAAAEIgDgBIgCAAQgBAAgBAAQAAAAgBAAQAAABgBAAQAAAAAAAAg");
	this.shape_89.setTransform(-51.2,3.6);

	this.instance_3 = new lib.Symbol7("synched",0);
	this.instance_3.setTransform(-70.4,-34.1,0.261,0.261);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#000000").s().p("AgJgCIAJgDIAAACIAEACIAGABIgJAFg");
	this.shape_90.setTransform(-20.3,35.4);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f("#000000").s().p("AAAAMQAAgCgKgDIgCAAIABgSIACAAIATgBIADAAIAAACIAAAQIAAACIgCABQgGABgDACIgCABgAgGgGIAAAJQAFABACADIAGgDIABgFIAAgGIgOABg");
	this.shape_91.setTransform(-20.2,33.3);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#000000").s().p("AAuEEQgYgGgLgGQgLgFAAgBIAAgBIgBgCIAAgBQgGAGglAKQgXAEgMgCIgNgDIAAAAIgBAAQgIgIAAgPQAAgPAKgIQAFgEAIgDQAAAAABAAQAAAAABgBQAAAAAAAAQABAAAAABQAKgDAHAAIAIgBIAJgEIgCgDIgBgDIgEABQgJAAgFgIIgBgEQAAgEAEgGQgFgEgCgMIgGgFIgBgBIAAgCIACgOIAGgeIgBgHIAAgHQAAgRACgMIgGgFIgCgCIABgCQgBgBAEgLQAEgMAJgLQgggKgTgNQgSgPgBgCIAAgBIgCgIIgBACQgBAAAAAAQgBABAAAAQgBAAAAgBQgBAAgBAAQgZgVgBgSQgBgSACgBQAUhIAigmQAjgnAZgKQAsgUAhAiQAQgKAaAGQAaAGAXAPIAAAAQAdAbAEAYQAFAYgDADIgCADIgCgCIgIgHIACAOQgBASgFATQgFASgHAOQgBAKgEAKQABACgOAUQgNAUgkANIADAUIACARIAAABIAAABIgHAHIAFAfIACAHIABAGIADAHQADAIAGAFQAIAIAAAJQgBAHgHALQgHAKgJACIgFAAIgBAAIgNgBQgHgBgEgEIgDABIAAAIIAAAHQAKADADAHIABAEIgBAEIgCACIAJAGIAHABQAPgBARALQAJAJAAAOIAAABQAAAPgIAIIAAAAIAAABIgBAAQgBABgLACIgIABQgKAAgQgDgAAEDLIADABIgBADQgEAMAAALIABAIQACAFAqAMQAVAEAKgCIAMgDQAGgGAAgNIAAgBQAAgMgHgHQgPgJgOAAIgJgCIgSgKIAFgCQABgBAAAAQABAAAAgBQABAAAAAAQAAgBAAAAIABgBIgBgCQgEgGgHgBIgCgBIAAgYIALgCIABACQAEAEAQABIABgBIABABIAEAAQAFgCAGgIQAHgJABgHIAAgBQgBgFgGgGQgGgGgEgJIgDgIIgBgGIgCgHIgFghIgBgCIACgBQAFgDABgCIgDgTIgDgTIAAgCIACgBQAjgMANgTQAOgUgBgCQAEgJACgLIAAAAQAGgOAFgRQAFgSAAgSQAAgKgCgKIgCgGIAGADIAKAIIAAgBQAAgJgGgTQgGgSgWgUQgagQgYgFQgZgEgMAJIgCACIgDgDQgFgIgSgJQgQgJggANQgYAJgiAmQgiAmgTBHQgBABgBAJQAAAHAFALQAEALAOALIACgPQABgIADgEIAFgHIgBAbQABARABAAQABADATAOQATAPAgAHIAFABIgEADQgKAKgEALIgEAOIAHAFIABABIAAACQgDANAAARIABAPIgFAcIgDAPIAGAEIABABIAAABQACANAFADIABACIgBACQgEAFAAADIABACQADAEAGAAQACABAGgHIABgBIACABIABgBIACAFQgDACgBACIgBACIAAABQABACADACIAEACIgRAJIgJACQgIAAgJACIgBAAIgBAAQgHACgFAEQgIAHAAAMQAAAMAHAHQABABAKABQALACAWgFQAogLADgEIABgLQAAgJgDgJIAEgDIAEACg");
	this.shape_92.setTransform(-20.3,16.2);

	this.instance_4 = new lib.Symbol8("synched",0);
	this.instance_4.setTransform(-36.1,-9.8,0.261,0.261);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f("#000000").s().p("AgGErIgSAAIgDAAIgBgEIgBgQQAAgLACgFQgDgCgBgDIAAgCQABgEACgDQgDgCAAgDIABgDQABgFALgEIAAAAIgIgCIgCAAIAAABIgDAAIgNABQALAEABAFIABADQAAADgDADQACACABAEIAAACQgBADgDACQACAFAAALIgBAQIgBAEIgDAAIgSAAIgjAAQgTgBgOgDIgCgBIAAgBQgCgCAAgNQgBgMALgJQAKgFAMACQALADAFACIADgCQgCgCgBgDQABgFAEgCQgCgCAAgDIAAgBIABgEQADgDAGgBIgLgBIgDAAIAAgDIgDgPQgCgPAAgQIAAgBIgEgCIgCgBIAAgCIAEgRIAIggIgMAQIgGAJIAAAHQAAANgHAGIACAJQAAAGgDAEQgDAFgEAAQgEAAgGgNQgDALgFAEQgDACgDgBQgFgBgBgLIADgLQgPAIgHgEIgBgEIAAgBQACgHALgJQgJgGgCgLIAAgBQABgHADgBQADgCAHAEQAFADAJABQAPgHAGAAIALgQIANgTIgBAAIgCgCIAAgDQAAgBAGgNQAHgOATgLIgIgEIgNgGQgQgIgRgKQgSgLgNgNQgWAAgMgIQgLgJgDgMQgFgWARgGQAKgDAKAFIAAgFQgIglgIgRQgHgSgGgFIgMAFIgHADIgJAFIADgJQAEgMAHgKIALgRIgPABIgIABIADgHQAMgXAMgOQAMgOAHgGQgPgKgOgHIgOgHIgEgCIACgEQALgQAJgEQAJgEABAAIACAAIACACIANAUIAOAUQArgqAtgHQAsgIAVADIASABQAUACASgDIAVgEIAKAAIAPgBIgNAIQgQAMgEAIQA3AMAdAUQAcAUAKARQAKASAAAEIADAJIgEgCIgEgCIAAABIgGgDIgRgEIgPgDQAlAqALAiQALAigBAJIACAJIgIgFQgSgKgMgDIAEANIADAJIgEAAQgsALgSASQAKgCAKAEQAOAJgIATQgFALgOAIQgNAHgXgFQgOAOgUAIQgUAJgUAEQAPANAHAYIABADIgDACIgCAAQAFAQAIAkIAFAGQARATAAAHQAAABAAABQAAAAAAABQAAAAgBABQAAAAAAAAQgEAEgOgIQgFAMgIABQgDAAgCgCIgBgCIACgFQgDABgCgBIgBAAQgCASgDAPIgBADIgCAAIgRADQAGAAACADIABAEIAAABQAAADgCADQAEABABAFQAAADgDACIADACQAFgCALgDQAMgCAKAFQALAJgBAMQAAANgCACIAAABIgCABQgOADgTABIgZABIgIgBgAgZDQIABAIIAAAJIAJACIADAAIAAAJIgCABQgLADgBADIAAABIADACIAEADIgEADIgDAEIAAAAQAAABABAAQAAABAAAAQABABAAAAQABAAABAAIACACIgBACQgCADgBANIABAPIAiAAQAbAAAUgEIABgLQABgLgIgGQgKgFgMADIgNAFIgBAAIgBAAIgIgGIgDgCIADgCIADgDIgDgCIgFgCIADgDQACgCABgEIAAgBQABgBgJgBIgDAAIAAgJIADAAIATgDQADgPACgSIAAgCIACAAIADgBIACgBIABABIAEgBIAIgBIgDAFIgCAGQAFgBAFgLIAAgEIAEACQANAIAAgCQAAgDgFgHIgLgNIgGgGIAAgBQgJgogFgOIgBgDIAFgCQgGgYgRgMIgFgDIAGgCQAUgEAWgIQAWgJANgPIABgBIACABQAVAEAMgGQANgGAEgKQAHgPgLgGQgMgGgPAKIgEADIAAgHIABAAQAIgLASgLQARgMAdgHIgEgOIgEgKIAFABQALACAXAMQAAgMgMgiQgMghglgoIgFgFIAHAAIAWADIAMAEIAAgBIAEABIAFACQgBgMgagcQgbgdhMgQIgDgBIABgDQACgHASgQQgKABgQADQgTADgUgCIgTgBQgUgCgsAHQgtAIgqAqIgCACIgCgDIgNgTIgPgXQgGgBgTAWIATAJQANAHAOAKIACACIgCACQgGAEgMAOQgMAOgNAXIATgBIAFAAIgDAFIgKAPQgIALgFAMQAIgEALgDIACgBIABACQATATAMA9IAAAAIgBAPIgDgDQgKgGgKADQgMAEAEARQACALALAIQALAHAUAAIABAAIABABQANANARAKQARAKARAIIAeAPIgFADQgSAIgHAMQgIAMAAAFIAEACIgBACIgPAXIgLAQIgBABIgBAAQgHAAgPAHIAAABIgBAAIgJgCIgIgEQgBAAgBgBQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAAAABQgBAAAAABQAAAAAAAAQAAABAAAAIAAABQADAKAJAEIAEACIgFADQgNALAAAEIAAAAQAAADAUgLIAHgDIgDAJQgDAHAAAGQgBAFADACIACgBQACgBABgGIADgJIADgLIAEAKIADAIIAEAGIACgCQACgDAAgEQAAgEgCgEIgBgCIACgCQAHgEAAgMIAAgGIgBgCIAdgoIAFADIgLAlIgFAYIAFACIAAACIAAAEQAAANACANIADARIAIABIAGABIADAAIAAAJIgDAAQgLABABABIAAABIADAEIADAEIgDACIgFADIADADIADACIgDACIgIAGIgBAAIgBAAIgNgFQgLgDgKAFQgJAHABAKIABALQAUAEAbAAIAkAAIABgPQgBgNgCgDIgBgCIACgCQABAAABAAQAAAAABgBQAAAAAAgBQABAAAAgBIAAAAQAAgBgBAAQAAgBAAAAQAAAAgBgBQAAAAgBgBIgDgCIADgDIADgDIAAgBQgBgDgKgDIgDgBIAAgJIADAAIAOgBIACgKIABgIgAC6i4IAAAAIAAAAgAC6i4IAAAAIAAAAg");
	this.shape_93.setTransform(12.2,10.6);

	this.instance_5 = new lib.Symbol12("synched",0);
	this.instance_5.setTransform(-9.2,-19.1,0.261,0.261);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_5},{t:this.shape_93},{t:this.instance_4},{t:this.shape_92},{t:this.shape_91},{t:this.shape_90},{t:this.instance_3},{t:this.shape_89},{t:this.instance_2},{t:this.instance_1},{t:this.shape_88},{t:this.shape_87},{t:this.instance},{t:this.shape_86},{t:this.shape_85}]}).wait(50));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-92.8,-41.6,187.1,84.2);


// stage content:
(lib.grandmotherCJS = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.grandmother();
	this.instance.setTransform(100,100.8);

	// Layer 8
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,255,255,0)").s().p("AvnPnIAA/OIfOAAIAAfOg");
	this.shape.setTransform(100,100);

	this.addChild(this.shape,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(100,100,200,200);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;