(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 200,
	height: 200,
	fps: 12,
	color: "#FFFFFF",
	manifest: []
};



// symbols:



(lib.Symbol16 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#14395A").s().p("AnXGrQglgBgXgKQg0gegOg6QgCgYARgNQANgJAKABQAHABAMgCQALgDAPgXQAHgLAVgYQArgzBHhQQBHhPBgg5QBgg7BxAIQAFgCAhglIAzg6QgKg1ATgdQAcgeAWAAIAdgEQAbgBAjgGQAPgMAVgJIALgFIAEgCIAGgBQAigLAXAFQAJADAFAFQAJABAJACIAAAAQgEgfAfgmQAcgYAzALIAIACIgFAGQgCABgJARQgKARgBAXIABAJQAFgTAhgUIAAAAIAAgBIAGAJQgKgEgQBBQBWAqAPCGQAJBWggBbQgfBehRA4QiABLh1APQh1APgWgEQgJANgzAgQgxAghYAHQhcAEgwANQgwANgDAEQgDAFgOAJQgOAKgRgCQgLgBgdABIgqABIgeAAg");
	this.shape.setTransform(59.9,42.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,-0.1,119.8,85.6);


(lib.Symbol13 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#14395A").s().p("AmMYeIgDAAIgEgOIgHgVIgTAWIgDgBIgYgIQgSgHgIgGIgCgDIACgDIAagoQAYgiAbgaQgRgIgNgLIgEgDIADgDQAIgPA9hZQA+hYA+g5QgMgKgDgQIAAgBQAAgGAEgEQALgLAGgCIgDhFIgGiIIgFhxQgFAEgHAEQgQAIgMAAQgLgCgGgEIgHgIQgHAJgcgGQgOgMgIgXQgHgYgBgKIgBgFQgYAGgkgxQgWgkAHgWQAJgRAGgBIAOgHQgghAgghKQgghKgKgqQgCgCAJgOIgEgDQgrgqABgTIAAgGQAHgIAUgBQgJgPgFgVQAAgOAJgJQAKgHAaAAQAaAAAcAEQATgzAYg6QAYg6APgeQAUgnAYgRQgSgNgTgJIgEgCIABgEQACgGATgkQASglASgTQAHgGAWgEQg8g9g/hmQg/hmgkiRQh3gvARhFQAIgfAbgSQgMhNAAhXQAChDARgxIgSgPIgPgLIAAgDIAEgZQAEgTAKgIIAEgCIAOAUQANASAHAIQAKgcA7hKQA7hLB+g7QBWgjBLgIQBKgJA0gDQA8gFAmgOQBvgxA7grQA8grAZgPIABgBIABAAQAKgFA1AmQA0AmgMCCQgOBEhHAzIgEACQATAdgPCMIgEAfQAIATgDAVIgEACQArAYAXAXQAYAXADAFIAAAAIABACIAAABQACCYgVA8QgWA8gFAAIgCABIgCABQgRABgPgCIAJAiQAXBOALAsQAMAsgNAuQgTBFhYA6QhYA6iSAeIgyAKIgDABQAPARAAAOQgBAPgHAaQgHAagDAVIgDAVIAGAMIAPAiQATAuAYA0QAYA0AaAiQAYgRAVAJQAYAbgDAaQAVgFAWAIQAGAEAAAGQABAHgHATIBLAAQAtAAAigCIA6g4QAsgqAXgRQAXgKAgAMQAgAMAIAGIgbAzQgfAKgGAPQADALAQAVQAQAUAJATQAKATgKALQgTALgggNQghgNgNgJQgQARhCgCIhaAKQhMAIg8ADIgPAQQgZAYgWgCQAcB4gZBLIAAABQgDBIgNgBQgHAigpAfQAXBJAeBoQAfBoANA+QAKA2AEBKQAEBKAAA6IABA9IgBAEIgBAAQAUAIAaAHQAZAIARACQADgJAMgOQANgOAYgDQAagCARARQAUAVgCAiIAAADIgCABQgEAEg6AUQg7AVhQAGIgDAAIgLgRIgCAUIgDABQgFAEg0gCIgEAAIAAgFIABgeQACgdAHgmQgYgBgVgOIgCgCIABgDIAUitQALhZAAgVIAAgBIgFgDQgOgFgEgOIAAgBQAAgMAYgOQgYhNgihgQghhfgPgeQgXAIhZgDIgMBfIgSCeQgJBVgEA4IAAABIAAABIgjA8IhDB3QgkBBgPAgIgCADIgEAAQgEAAgfgIQAEAQAKAJIAWAEIAXADQAFgEAUgHQAVgGAYAHQAVAIAJAWQAJAegPAdIgBACIgDABQgBABgxAHQggAEgvAAIg4gBgAmKFXQgOAFgUACQAKAyAaBNIAOiSQgFAJgLADgAl8EdIAFAMIABgNIAAgCIgGADg");
	this.shape.setTransform(61.3,156.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-0.2,0,123.1,313.5);


(lib.Symbol12 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#14395A").s().p("AgeRxIhEgCIgEAAIAAgEQgLhpARgXQgOgHgDgLIgBgGQAFgQANgIQgNgHgFgOIABgGQAEgTAugMIAAgSQgVgBgSgFIgEgBIgCgiIgDgoIgBAAIgGAqIgFAkIgEABQgCABg5ACIAAARQAuAMAEATIACAGQgGAPgNAIQANAGAFAQIAAAGQgDALgPAHQARAXgLBpIAAAEIgEAAIhEACQg7AChKgDQhKgDgzgMIgCgBIgBgCQgEgHgEgsQgDgrAmgeQApgUArAMQAsALANAJQAJgFATgQQgPgKgBgKQAHgRATgFQgLgHgHgTIAAgCQAAgEAEgEQAOgLAfgBIAAgQQgcgCgggEIgEAAIgBgEIgKhBQgJg9ABg8IgSgJIgDgBIAThUQARhIAbhXIhDBcIgqA4QADAKgBAgQgBAhgdAYQAIATABARQgBAUgIANQgIAOgKAAQgJgCgLgYQgMgYgIgWQgEASgIAbQgIAbgNAJQgHAFgHgDQgRgIABgaQAFgkALgdQgVANgdANQgdANgMgJQgDgCAAgGIAAgBQADgQAVgUIAjgfQgpgSgKgsIAAgDQAAgRAJgFQALgGASAMQAJAFATAGQATAGAMACQBCggAWAEQAIgOAigyIA4hUIgMgHIgEgBIABgEQgBgGAcg1QAcg1BRgoIhjgwQg+gehDgoQhDgogxg1QhVABgrghQgqgjgJgqQgQhJA2gWQAwgLAjAZQAAgTACgRQglirgkhAQgjhAgKgEQgcAIgZAMIgbANIgMAGIAEgMQASg0AeguQAdgtAPgTQgagBgZACIgcADIgKABIAEgIQAxhhAzg4QAyg4ATgNQg9gsg3gdIg8geIgFgCIADgFQAog5AfgQQAggRADACIAEAAIACACIA6BWIA1BNQCfigCrgeQCrgfBUALIBNACQBLAHBJgMQAsgJAjgCIAmgDIASgBIgPAKQhSBAgFAeQDiAtBtBQQBuBQAhBCQAiBDgDAFIADALIgLgFIgUgIIABACQgggMgigHQg4gJgegCQClC0AoCMQAoCMgHAKIACALIgKgGQgqgagmgNQgmgOgSgDIAQAxIANAmIgGABQhxAahDAsQhDArgeAnIAAACQAvgoBDAYQAxAfgdBDQgRApgzAaQgyAbhXgTQg2A5hVAiQhUAhhOAQQA9AlAiBwIABAEIgEACIgQAGQAWA4AgCYQAfAkAaAhQAaAgACARQAAAFgDACQgWAIgqgeQgSAygcAFQgJAAgCgFQgDgGANgbQgVAIgNgHQgHAEgGABQgHBJgNA6IgBADIgDABQgLAEhJAHIAAAQQAdABAOALQAEAEAAAEIAAACQgGAUgKAKQASADAGAPQAAAKgQAKQATAQAJAFQANgJAsgLQAsgMAoAUQAmAegDAsQgEArgEAHIgBACIgCABQgzAMhKADQgxACgrAAIgngBgAB8JvIADgDIgIgaIAFAdg");
	this.shape.setTransform(82.1,113.8);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,164.2,227.7);


(lib.Symbol11 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#14395A").s().p("ADpVzQhTgPgGgDQgmgQAFgUQgGgUAmgTIgBgHQAAggAQgeQAQgeAHgIIgCg1IgKABQicAKh6glQgBAlgGAfQAHAHAMATQAMATADAVIAAAJQAbAPACAVQACAVgCACQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQiVBKh5ADQh4ADhJgXQhIgYgDgEQgZgNgHgbQgFgoATgmQAUgmAFgEQAyhABVgLQBNgHAwAnQAWATAQAYQAggFAigJQAigJAKgPIgCg4QhxgngGgGQgXgMABg2QABg2AKg5QgRgJgMgLIgLgIQgHgHAAgPQACgwAWg2QgSgIgEgNIgCgHQACgVAHgEQARgjAYhAQAYhAASg2IAUg7QANg2ACg6QABg7gEgqIgCgFQgfhMAlhOQAkhMAjgoQgDgVgBgRIgvgMIglgGQhggYhMgmQhigug6gmQg5gmgCgEQgmgtAEhLQAEhLAThAQAQg9ACgEQAPgiAJgoIgCgBIgDgCIAIgZQAKgtADglQAEhggDgKQAEgeAGgaIgKAJQgFABgJgVQgIgUA1gwQAuh5A1gtQA2gtAMAAQAHgIBHgkQBIgkB6gTQB4gTChAqQBIAUBOAnQACAAAmAYQAlAYAuAzQAXAYAUAeIgCgaQgBgCAIgIQANgIAdAHIADABIABAeIACBHQANAKAOANIAQhDIAIgeIADgBQAlgDAEATIAAABIgKAjIgZBQQAoAuAXA/QAXA/gSBPQgBAFgeA4QgdA3g4A1IACBXIABAkIgbgLIgGhaQgxAjhAgGQgvA/hDAoQgUBFgnA/QgmA/gqAyQAUA1gOAwIACABIAFAFQArAgAaApIAYAgQA+BIAuB4QAdBJALBWIgKCUQgIBqgQBeQgFCxgKB6IABABIABAEIgLBqIgCAFIgCACQgkAOgkAIIgPADQABAdAAAPQBCAVAxAAIAMgRQAxgwA+ADQA/ADAwAnQBGBDgHAtQgGAtgHACIgBACQhnA7h0AHQgkACghAAQhKAAg6gKg");
	this.shape.setTransform(66.9,140.4);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,-0.1,133.9,281.1);


(lib.Symbol10 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#14395A").s().p("AgcAmQgEgmANgWQAOgVADgBIACgDIACACQAeAagCAJIAAADIgDACQgMAHgPASIgUAUIgHAIg");
	this.shape.setTransform(3,4.9);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-0.1,0,6.1,9.7);


(lib.Symbol9 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#14395A").s().p("AhtUbIgDAAIgBgEQgCgEACgcIgEAAIgEgVIgMASIgCABQgEAChCAMQhCAMhggIIgEAAIgBgEQgBgDABgWQABgXASgYQAcgjBDAAQBpADAaAGIAIgcIgLgDIgEgCIABgDIAEhCIAIh9QAEhBAAgTQABgYAJhHIARh6Qh9gZgoguQhBgvAHgLQgHgGAGhrQgLABgPgEQAFAcgIAbIgBAAIAAABQgDAKgHAHQAUAUAGASIAAABQAFALgaAmQgSASgigCQgIADgSgfQgIAIgGAEQgZAOgXgMIgEgDIgCgBIgCgCIgBgBIgCgCIgBAAIgCgDQgHgOAFgRIACgMIgFAAQgKAJAAAgQABAgAMBJQAXB8AODHQAFCagMBCQgMBBgDAAIgBACIgBAAIgUANQgPAJgMADQghAFgegYIgCgCIABgDQAGgGAdh+QAdh/gJjDQgPiXgThMQgUhKALgcQAEgLAJgJQgggvAAgVQAGgTAwgnQAwgnAYgIQAUgDAWAGQACgXAMgQQAQgTAbgCQAYgBAbAQQAwhLAbhYQAahXAPhJQALgxAKgkQgEgIAAgEQADgSAGgPQgTgMgHgWQAFgYATgkQhdgnhlhGQhmhFhGhUQhHhUAAhSQAGhLApg3QAog2AzgnIADgJQgGgGgFgHQgFgGADgHQAEgFAJABQAMACAJgHQAJgKgHgeQgBgOAHgFQAXgNAsALQAQg9AfgtQAfgtAjgCQASAAAPAOQA2g0BHglQBHglBUABQALgIBzAtQB0AsB3C8QAVgEBKAHQBKAIA/A7IgIAlQgIAhgMAVQAHAQANAnQANAmACAdQAAATgMAHQgMAEgPgKIgXgQQgDAVgNArQgNArgeAWIgCABQgKCJheBJQhMA5hjAoQASAegBBBIAAAAIAAABQAAACgJALQAmAfAjAzQA5BdAPCSQAPCUgFB7QgFB7gDAQIAAACIgCABQgBAEgcASQgXAqhtAtIgSBkQgLBCgFA7QANAIAFANIAAABQAAAEgDADQgIAHgIgBIAAADIAAACIAAACIABAIIAAALIAAAAIAIBnQAFA/AJAyIABALIACAHIAAAAIACAHIABAFIgFABIgIACQATAbAEBOIAAAEIgEABIgZAFQgYADgeABIgEAAIgEgVIgMASIgCABQgDAChCAMQgoAHgyAAQghAAgmgDgACBS1IAIgeIgWgFIgEgBIAAgDIAAgYIABhYIAAgBIAAgQIAAgCIAAgQIAAgDIAAgnIAAgCIAAgSIABgFIAAgPIAAgGIAAgPIAAgGIAAgPIABgFIAAgVIAAAAIAAgVIABgFIAAgPIAAgHIABgNIAAgIIAAgMIABgIIAAgMIAAgHIABgSIAAgBIABgRIAAgGIABgMIAAgGIABgKIAAgHIABgJIAAgGIABgHQhGAKhGgGQgIAngLA6QgLA6gDAkQAMgBAIAGIADAHQgEAPgOAHIAHBgQAGBKAAA9QAAAWgBAOIgBAEIgEAAIgKABQAGAOAGAWQAQgDAUAAQBoADAZAGg");
	this.shape.setTransform(63.2,131);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,-0.1,126.5,262.2);


(lib.Symbol8 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#14395A").s().p("ACzPaQhZgWgqgVQgqgWgBgCIgCgCIAAgCQgBgGAAgpQAAgoAMgoQgPgEgGgEIgCgDQAJAlAAAmIgBAsIgBACIgBABQgCADgpATQgpAUhXAVQhXARgsgHQgsgIgBgDIgBAAIAAAAQgdgbgBg2QAAgzAjgcQAXgRAagHQACgEADABIACABQAlgIAdgBQAXgBAJgDIAzgaQgNgGgGgMQgCgEAAgFQAAgFACgGQAHgMAOgHIgHAAIgCgBQgQAYgWADQgcABgRgXQgDgGAAgHQAAgQAPgVQgSgOgIg3QgOgJgMgKIgBgCIAAgCIAIg1QAHguANhEQgBgaAAgcQgBg+ALg4QgRgIgOgOIgBgCIAAgCQgBgFAQgwQAQgwArgrQiAgghLg7QhKg7gDgIIAAgBQgHgTABgzQAAgsABgbQgKAQgFAgQgEAhAAAcQAAABAAABQgBAAAAABQAAAAgBABQAAAAgBAAQAAABgBAAQgBAAAAAAQgBAAAAAAQgBAAgBgBQhehKgEhCQgEhCAHgFQBPkXCEiQQCDiQBbgjQBagmA+ANQA8AMAkAdQAjAdAKANQA0gpBkAUQBjAUBeA9QBvBnAOBZQAOBYgHAGIgWgUQgTgSgLgHQAKAlAAApQgICQg5B2QgGAmgPAmQACAKg0BNQg0BNiKAzIAMBLQAHAtADAcIAAACIgBABQAAAFgbAUQAHAwAPBPIALAyQAFASAEALQAQAfAVAWQAcAbABAbQgFAcgZAlQgaAlgZAGQgKABgKgDIgCABQg+ABgYgWIgCgDIgcAGIAABMQAjAFARAbQACAGAAAFQAAAFgCAGQgHAKgNAFIAzAdQAIADAXACQA3gCA9AoQAfAdABA0QgCA4gaAcIgBAAIAAABQgCADgqAIQgOADgTAAQgmAAg5gLgAgNLRIAVAUIAMgKQgOgCgJgKIgKACgAgiKgQAcAGANAOQAQgKAWgEQABgogBgcQgoAEgmgBIgBA7gAhuKdIAEgBIAAgCIgEADg");
	this.shape.setTransform(60.4,99.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-0.1,0,121.2,199.6);


(lib.mother = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 7
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CEAA84").s().p("AgwAVIAAgBIACgCIAGgBQAOgFACgCQABABgGAEIAAABIgLAEIgHABIgBAAgAg6AUIAAgBIABgCQADAAAFgEIAHgEQAAACgDADQgGAGgFAAIgCAAgAgdATIAFgEIAGgBQAIgCAEgGIADgGQAiAAAPgJIANgKQgSATgUACQgVAEgBgBIgFAFQgEAFgIADIgJABIgCAAgAg1gTIABgBIAAAAIAHAIIADAEQgIgFgDgGg");
	this.shape.setTransform(-40.7,17.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E2C19A").s().p("AgxAWIAAgBQAEgEABgDIgCAAQgIAJgFgCIAAAAQABgFAGgGIAGgKIAEgFIAAgBIgBgBQgIgEgDgGIAAgCQACgBALACQALACANAFQAgAFATgFQATgEAHgGQgSAVgWAEQgUAEgCgBIgBAAIAAAAIgFAFQgEAFgIACQgIACgCgBQAGgDABgCIgCgBQgCACgOAGIgHAAIgBAAg");
	this.shape_1.setTransform(-40.6,17.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("Ag2AaIAAgBQgFACgDgBQAAAAgBgBQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAgBQAAgDAIgIQAGgJADgEIgHgFQgEgEgBgDIAAgBIABgDQAEgDAOAEIAUAHQAuAGASgKQAUgLgBgCIACACQgTAbgXAFQgWAFgFgCIgFAGQgDAEgHADQgMACgCgCIgKAEIgGABQgDAAgCgCg");
	this.shape_2.setTransform(-40.3,16.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#5B2802").s().p("AgYAAQAIABAOgBQAMAAAPgLQgCAHgDAJQgPgBgFADIgKAFIgOgMg");
	this.shape_3.setTransform(-53,-4.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#720B00").s().p("AgOAAIAKgEQAGgDANAAQgFAOgKABQgFgBgJgHg");
	this.shape_4.setTransform(-52.5,-2.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgOAKIgMgNIgEgEIAFACQABACASAAQAPAAATgRIADgDIgCANQgCAKgFALQgGALgLACQgHgCgMgMg");
	this.shape_5.setTransform(-53.2,-4.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AAAANIgIgKQgCgCABgBQACgFAHgFIAJgFQAAAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIgJAGQgGAFgCADIABABQAKANADgBQABAAAAABQAAAAAAAAQABAAAAABQAAAAAAAAIgDABQgCAAgEgDg");
	this.shape_6.setTransform(-55.3,-8.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#E2C19A").s().p("AgHACQgDgEAKgGIAJgGIgBAcIgBABQgGAAgIgNg");
	this.shape_7.setTransform(-55.3,-8.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#D1B18F").s().p("AgMgIQAFgNAHgCQAJgBAKAMQgPAEgIALQgKANgEAJQAAgVAGgMg");
	this.shape_8.setTransform(-58.8,-17.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgVAZQgBgUAGgPQAGgQAKgDQAKgBAMAQIABABIgEABQgRAFgJAPIgLATIgBADg");
	this.shape_9.setTransform(-58.8,-16.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#D1B18F").s().p("AAAACQgKgCgGABQAIgOAIAAQALABAGAaQgJgKgIgCg");
	this.shape_10.setTransform(-50.6,-18.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgCADQgMgCgEABIgCABIABgDQAJgRAKAAQAPACAGAgIgCABQgLgOgKgBg");
	this.shape_11.setTransform(-50.6,-18.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgCAAIgCgDQADADACABIADAAIABADQgFgBgCgDg");
	this.shape_12.setTransform(-61.6,-15.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgBAAIgCgFQACAFABABIAEABIAAAEQgEgDgBgDg");
	this.shape_13.setTransform(-61.4,-15.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgEABQACADAIgHIgDADQgDADgFABg");
	this.shape_14.setTransform(-48,-17.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgDADIADgCQACgBACgFIgCAFQgBADgEADg");
	this.shape_15.setTransform(-48.2,-17.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FDFDFD").s().p("AgBAAQAAAAABAAQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAAAAAAAQABABAAAAQAAABAAAAQABAAAAAAQAAAAgBABQAAABAAAAQAAABgBAAQAAAAAAAAQAAAAAAAAQAAAAAAgBQAAAAAAgBQgBgBAAAAg");
	this.shape_16.setTransform(-57.2,-9.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgFAAQABgGAEgBQAFAAABAHQgBAHgFABQgEAAgBgIg");
	this.shape_17.setTransform(-57.3,-9.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FDFDFD").s().p("AgBAAQAAAAAAAAQABAAAAgBQAAAAAAAAQAAgBAAAAQAAAAAAABQABAAAAAAQAAABAAAAQABAAAAAAQAAAAgBABQAAABAAAAQAAAAgBABQAAAAAAAAQAAAAAAAAQAAgBAAAAQAAAAAAgBQgBgBAAAAg");
	this.shape_18.setTransform(-50.5,-10.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgFAAQABgGAEgBQAFABAAAGQAAAHgFABQgEgBgBgHg");
	this.shape_19.setTransform(-50.6,-10.1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FDFDFD").s().p("AgHA4QgPgZADgfQADghAQgXIAAAAQAJABAGATQAGASgBAXQgBAYgIAOQgIAOgIAAIgCgBg");
	this.shape_20.setTransform(-50.7,-14.6);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FCF3ED").s().p("AgIApQgFgPABgWQACgXAIgSQAFgRAKgCQgOAYgEAgQgDAfAOAaQgIgCgGgOg");
	this.shape_21.setTransform(-52.1,-14.6);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FDFDFD").s().p("AgSApQgGgOABgXQACgXAIgTQAIgRAIgBQAKABAGATQAGASgBAXQgCAYgHAOQgIAOgJAAQgKgBgGgPg");
	this.shape_22.setTransform(-51,-14.6);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgVAsQgGgPABgZQACgXAIgUQAJgTAKgBQAMACAGAVQAHATgCAXQgBAYgJAPQgIAOgKAAQgMAAgHgPg");
	this.shape_23.setTransform(-51,-14.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AAAAAIgEgBIABgDQAEAAADAIIgCAAQgBgEgBAAg");
	this.shape_24.setTransform(-64.4,-14.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#E2C19A").s().p("AAAAGQgEgEgBgCIACgFQADgDABAAQABAAAAAAQABAAABAAQAAAAABABQAAAAAAAAIgBAHIgCAJIgCgDg");
	this.shape_25.setTransform(-64.5,-14.8);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AACALQgBgDgCgDQgDgDgCgCQgCgEADgFQAEgFACAAQAGACABACIAAAAIgEAZg");
	this.shape_26.setTransform(-64.5,-14.6);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FDFDFD").s().p("AAAA4QgVgSgDgfQgDgdAIgcQAEgEAEgBQAGgBAFAEQAHAHAIAPQAHAQADAQQADAWgGAPQgGAOgMADIgCAAIgCAAg");
	this.shape_27.setTransform(-57.7,-14);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FCF3ED").s().p("AAEAxQgNgLgEgdQgDgRADgQQACgRAHgKIABgBQgIAcADAcQADAfAVATQgHgBgFgEg");
	this.shape_28.setTransform(-59.3,-13.7);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FDFDFD").s().p("AgHA0QgPgMgEgdQgDgQADgRQACgRAHgJQAEgGAGgBQAFgBADAEQAJAHAIAPQAHAQADAQQADAWgGAPQgGAOgMADIgEAAQgEAAgGgEg");
	this.shape_29.setTransform(-58,-14);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgJA2QgPgMgFgeQgCgRACgRQADgSAHgKQAFgHAGgBQAHgBAEAFQAKAHAHAQQAIAQACARQAEAXgHAQQgGAPgOACIgEABQgFAAgHgFg");
	this.shape_30.setTransform(-58,-14);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgHARIACgCQAFAAAFgHQAHgHACgGQACgHgHgCQgFgCgEACQgGAEgDAGIgDAEIgCAEIgBADIAAgFIABgEIADgFQAEgFAHgEQAEgCAGACQAIADgCAJQgCAGgHAIQgHAHgFABIgCgBg");
	this.shape_31.setTransform(-42.7,-15.3);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#E2C19A").s().p("AgPAIQAAgDAHgLQAIgMAKACQALAHgKALQgKANgIACg");
	this.shape_32.setTransform(-42.8,-15.2);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#D1AD86").s().p("AghBUQgWgcgIgcQgIgcABgBIgBgNQABgiAKgaQAKgaAIgMQgLAiAAAlQABAkAPAdQANAgAYAXQAZAWAvAGQgSAGgVAAQgrgBgXgcg");
	this.shape_33.setTransform(-56.7,-11.3);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#E2C19A").s().p("Ag/BXQgXgcgIgcIgHgfIgBgMQACgnAMgdQANgdAFgGQAGAEAXALQAYAMAfAKQAiAKAigBIAAADQAAAIADAOQAEAOAMAKQABADAAAQQABAQgGAZQgFAYgQAVQgaAfgwAAQgrgBgWgcg");
	this.shape_34.setTransform(-53.6,-11.6);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AhBBZQgXgcgIgdQgIgcABgDQgDgeAIgbQAIgbAJgRIAKgRQAAgBAAAAQAAAAABAAQAAAAAAAAQAAAAABAAIAZAOQAXAMAhALQAjALAlgBIABAAIAAABIACATQACARAOAMIABABIABAUQABAQgGAaQgFAZgRAVQgaAggyAAQgsgBgXgdg");
	this.shape_35.setTransform(-53.7,-11.6);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#E2C19A").s().p("AgMAIIgBgHIAAgGQADABAJgBQAGAAAIgEIABANQgCACgIADIgFABQgGAAgFgCg");
	this.shape_36.setTransform(-52.2,0.7);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgOALIgBAAIgCgSIACAAIAMABQAIABAIgGIACgBIAAACIABAIIABAIIAAABIgBAAQAAACgLADIgGABQgGAAgHgCg");
	this.shape_37.setTransform(-52.2,0.6);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#7C4D29").s().p("ABaAFQgPgjgsgHQADgBACgDQADgDACABQghgTgmABQgoACgnAMQACgCAOgMQAOgMAZgJQAYgIAhAFQAkAGAqAkIgGACIgBABIAAAAIAAABQACAAAQAWQAPATADAtIgCAXIgDASQABgugQglg");
	this.shape_38.setTransform(-48.7,-24.8);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#4C280F").s().p("AARBtQgggegYgqQgYgnADgrQACgrAtgmQgCBEAPA/QASBBArAxQgQAFgVADQgBgLgGgHg");
	this.shape_39.setTransform(-59.7,-10.7);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#6B411B").s().p("AhUCtQAGgDAEgJIAAgDQAAgHgHgHIgHgGQgLgLgRgTQgQgTgOgcQgNgbgBgiQAAgXAIgaQASgzAWgSQAVgTAQgBQARgCABABIABAAQAAgBAPgMQAOgMAagJQAVgJAjAGQAjAFArAkIgHACIgBABIAAABIABABQACAAAQAVQAPAWACAtIgBAXQgGAmgPAjQgPAjgNAXQgMAWAAAGQAAAJAGAEQAFAFADABIgDAHQgDAFgHAAIgFAAIgggCQgUgCgWgEIAAAAIgVAHQgVAGgYADIgLAAQgSAAgKgGg");
	this.shape_40.setTransform(-54,-15.7);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AhYCtIgBgBIABgBIAEgDQAEgDACgFQABgHgHgHIgHgHQgPgMgVgbQgWgagLgmQgMglAPgxQASgxAVgTQAVgTARgDQARgDAFACQACgEAPgLQAOgLAZgJQAWgJAlAGQAlAGAtAmIAAABIAAAAIgBABIgHACQAHAFANAWQANAWACAoIgCAXQgGAmgPAjQgPAjgNAXIgLASQgEAHgBADQABAJAIAEIAJAEIAAABIAAAAQABABgEAHQgDAHgKAAIgFAAIgggCQgVgBgWgFQgEACgUAGQgWAGgZACIgJABQgTAAgKgJg");
	this.shape_41.setTransform(-53.8,-15.6);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#AF1291").s().p("AgeAPQgFgCABgFQABgHAKgFQAKgIANgBIAMAAQAMAAAHAHQAFADAAADQgBAEgDADQgGACgLgEQgLgEgEgBIgBgBIAAABIgJAIQgIAHgJAAIgDAAg");
	this.shape_42.setTransform(-52.3,1.3);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("AgfAQQgGgBAAgGQABgIALgGQALgJAOgBIANAAQANABAIAGQAEAFgBAFQAAAEgEACQgHADgMgEQgLgDgDgDQgCAEgJAGQgGAGgJAAIgFgBg");
	this.shape_43.setTransform(-52.4,1.2);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFE3FA").s().p("AgjAVQgJgCABgKQAAgJALgJQAKgKAUgBQACgBAPABQARABAKAPQAFAHgHAFQgGAGgNgBQgMAAgLgIIgBgBIAAABIgJAKQgHAHgLAAIgFgBg");
	this.shape_44.setTransform(-52,1.5);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#AF1291").s().p("AgNAVQADgIADgDIAFgCQACgDABgDIABgPIAAgFIAAgBIABgCIAHAEQACAAACAYIgBAJIgLAEQgDACgHAAIgFgBg");
	this.shape_45.setTransform(-52.7,4.6);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#000000").s().p("AgWAnIgCAAIABgCIADgHQACgFACgCQAIgDACgDQABgDAAgHIAAgKQgEADgIAFQgIAFgKgCQgLgCAAgKQABgLALgLQALgLAVgBQACgBARABQARACAKAPQAGALgIAHQgFADgLAAQgKAAgLgCQADAGAAAeIgJADQgGACgIAAIgHAAg");
	this.shape_46.setTransform(-52,3);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#000000").s().p("AgUBAQgTgGgBgCIgBAAIAAgBQABgIAIgWQAHgVAKgUQAKgWAHgKQAOgNAMgDIAMgBQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAAAAAQgBAAAAAAQAAAAgBAAIgMACQgMACgMANQgGAKgKAVIgSAoQgHAVgCAIQAFADASAFQAQAFAZgJIgBgSIgBgVIAAAAQAAgBABAAQAAAAAAAAQAAAAAAAAQABAAAAAAIABABIABAYIABAQIAAABIgBAAQgSAGgNAAQgIAAgIgCg");
	this.shape_47.setTransform(-59.9,7.9);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFE3FA").s().p("AACAEQgIAAgEAEQgFgHgGgBIgIgCIAAAAIACgIIABABIAHABQAFACAEAGIAAABIACgBQAAAAAIgCQAFgBAGAEIABABIABgBIAFgBQAFgDAGADIABAAIAAAHQgGgDgFADQgFACgCACQgFgGgFgBg");
	this.shape_48.setTransform(-60.3,11.7);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#F490DD").s().p("AgLALQgTgFgCgDQAAgDAEgNIABABIAHABQAHADADAIIABAAIABAAIAEgDQAEgCAEAAQAFABAEAEIAAACIACgBQAAgBAFgBQAFgEAGADIACAAIAAAJQgRAHgOAAQgGAAgHgDg");
	this.shape_49.setTransform(-60.6,13);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#F490DD").s().p("AgLAtQgHABgCADQgFgHgGgCQgGgDgBABQAIgVAKgTQAKgVAJgKQALgNAMgCIAOgCQADACgBAIQAAAMgEARIgKAdIgFAPIABAPQgGgDgFACQgFACgCACQgGgGgHAAg");
	this.shape_50.setTransform(-59.1,6.5);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#000000").s().p("AgUA/QgTgGgCgCQABgJAIgVQAHgVAKgTQAKgWAHgKQANgNALgCIANgCQADACAAAIQAAAMgFARIgJAdIgFAPIABAWIABARQgSAHgMAAQgIAAgHgCg");
	this.shape_51.setTransform(-59.7,7.9);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#D1AD86").s().p("AArApIgGgBQgHgBgGgEIgEgDQgSgHgQgSQgUgQgNgfQAIACATACQANAkAOAOQAQARAZAKIgFAAg");
	this.shape_52.setTransform(-58.3,17.9);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#E2C19A").s().p("AAeApIgGgBQgHgBgGgEIgEgDQgQgHgSgSQgUgQgNgfQAHACARACQAQABAOgFIALARQALAPAPAaIAAAAIABAAIAKACIACACQAHAEAFAAIAFAAIgHAIQgFAFgEACIgIAAIgHAAg");
	this.shape_53.setTransform(-57,17.9);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#000000").s().p("AAeAsIgGgBQgHgBgHgFIgFgCQgcgPgRgUQgRgWgGgTIgBgDIACABIAVAEQASADARgGIABAAIAAAAIAKAPQAMAPAQAcQAEAAAGACIACACQAHADAFABIAHABIABAAIgBACIgGAIQgGAGgGADIgJABIgHgBg");
	this.shape_54.setTransform(-57.1,17.9);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#000000").s().p("Ah4BwQgKAAgGgDQgHgDgFgHQgGgHgBgIQAAgHAFgEQAFgDACAAIACAAQADACAFgIIAIgJIAIgKQATgYAegYQAegZAmACIAVgYIAAgIQAAgIADgFQAIgJAHAAIAIgBIAPgCIAJgFIADgBIABgBIACAAQAJgDAGABIAEACIACAAQAAgIAHgIQAIgHAPADIAGABIgEAFIgEAHIAFgEIADgBIADAGIgCACQgBgBgEANQAWAMAEAiIAAAKQABAWgJATQgJAVgTAOQggASgdAFQgeAEgIgBQgEAEgNAIQgLAIgWACQgWAAgMADQgMADgCACQgEAFgKABIgKAAIgTAAgAiTBNQgDACAAAFQAEANAMAHQAFADAKAAIASAAIALAAQAHgBACgEIABAAIAAAAQABgCANgDQAMgDAZgCQAVgBALgIQAMgIADgDIABgBIABAAQAGABAdgEQAegEAggTQASgMAIgUQAIgSAAgVIAAgJQgEghgVgKIgBgBIAAgCIACgKIgCAEIgDAJIgCgNQABgKAEgEQgLgCgFAEQgHAJABAHIgBAEIgIgCIgBgBIgCgBQgFgBgIADIgBAAIgEACQgFACgEADIAAAAIgBAAIgQACIgHABQgGAAgGAGQgEAHADANIAAABIgBABIgUAXQgEAEgBgBIAAAAQglgCgdAXQgeAYgSAYIgJAKIgHAJQgHAKgFgCIgBAAIgBAAIgEACg");
	this.shape_55.setTransform(-47.7,11);

	this.instance = new lib.Symbol16("synched",0);
	this.instance.setTransform(-63.1,0,0.257,0.257);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(50));

	// mother
	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#E27DCF").s().p("AAPADQgOgFgIACIgJAAQAAAAAKgCQAHgDAQAGIAAACIgBABIgBgBg");
	this.shape_56.setTransform(-47.6,25.9);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#E27DCF").s().p("AgWARIgBgCQABgCAOgNQALgNAUgDQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAABQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAQgSADgMAMIgOAQIgBAAIAAAAg");
	this.shape_57.setTransform(-48.9,26.1);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#FFB3F1").s().p("ABLCVQABgngDgtQgEgugFgfIgFgkIAAgBIALghIgIAbIAAAAIAGAkQAGAfAFAuQAHAugBAmIAAAKIgKAFIAAgIgABLhoIAAgDIgPgPIgMgMQgfgQgbgCQgegCgCABQgVAAgMANQgGAGgEAHQAEgIAGgHQAMgNAUAAQACgBAeABQAcABAfAOIAMAMIAPAOIABADIgCAKIABgDg");
	this.shape_58.setTransform(-48.1,16.1);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#E27DCF").s().p("AhIBGIACgkIAHg+IAHg3QAAAsAQAnQAPAhAeASQAfARAlACQggAKgpADIgKABQghAAgdgOg");
	this.shape_59.setTransform(-51.7,26.2);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#F490DD").s().p("AhhCdIAEgnIAGhDQAEgjADgQIABgOIgBgbIgBgnQgBgWAEgUQAEgVALgMQAMgNAUgBQADgBAcABQAeABAeAOIANAMIAPAOIAAADQAAAGgEAQQgEAQgGASIAAABIAHAjQAFAhAGAsQAGAuAAAnIAAAKQgGADghAMQghAMgqAEIgRABQgiAAgegOg");
	this.shape_60.setTransform(-49.3,17.4);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#000000").s().p("AhiChIgCgBIAAgBIAEgjIAHhGQADgmADgRQACgOgCgbQgCgeACghQACgiAQgUQANgOAVgBQADgBAcABQAeABAgAPIAAABIAMALIAQAPIABAFQgBAKgFATIgIAcIAGAmQAGAgAFAtQAGAtABAnIAAALIAAABIgBAAQgCACgiAMQgiANgsAFIgUABQgiAAgegOg");
	this.shape_61.setTransform(-49.3,17.5);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#FFE3FA").s().p("AgXAIQgagEgNgHIABgHQAOALAfADQAcAEAVgCQAagFAEgGIgBAFQAAAAgHAFQgIAEgVACIgKAAQgSAAgVgDg");
	this.shape_62.setTransform(-56.7,40.1);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#FFF8FE").s().p("AgDAWQgSgDgKgHQAWAKAaADQABgFAAgRQgBgRgOgMQAXAHADATQAEAVgBAGQgTgBgQgEg");
	this.shape_63.setTransform(-59.3,37.8);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#FFE3FA").s().p("AgFAWQgUgFgIgIQACgIAEgHQADgJAHgGQAJgHAJACQARADAHAMQAHALABAMIAAAPQgVAAgRgFg");
	this.shape_64.setTransform(-59.4,37.7);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#C19A70").s().p("AgQAdIgBgIQAHABALgBQANgBALgIIAAgBQAAgEgCgHQAGAMgBAHIAAACQgMAJgPAAQgNAAgEgBgAgbgGIABgBIADAHIgEgGgAALgTIgBAAIAEgKIAGABIgFAOIgEgFg");
	this.shape_65.setTransform(-54,36.7);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#E2C19A").s().p("AgQAeQAAgIgCgKQgDgKgGgHQAKgGALgBIALgBIABAAIACgHIABgKIAGACIAFABIgDAKIgDAHIABABQAJAIACAIQADAJgBAEIAAACQgMAJgPAAIgHAAIgKgBg");
	this.shape_66.setTransform(-54,36.6);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#EAC5E4").s().p("AgaAHIABgGQAFACAPgBQANAAANgIQADgBADACQAAACgHADQgHAEgOACIgSABIgHAAg");
	this.shape_67.setTransform(-53,39.8);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#000000").s().p("AgYAmQgbgFgOgJIAAAAIAAgBIABgKIABgBQABgIAEgHQAEgJAIgHQAJgHANABQANACAIAJQAHgGALgCQALgBAEAAIABgJIACgHIAAgBIARAEIgEAJIgDAJQAJAJACAJQADAIAAAEIAAACQAFgBADADQABACAAAEIgCAGQABABgIAFQgIAGgXABIgJAAQgTAAgWgDg");
	this.shape_68.setTransform(-56.6,37.3);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#FFE3FA").s().p("AgZALQgVgBgHgFQgIgFAAAAIgBgFQAEAGAaAFQAVACAdgEQAegDAOgLIABAHQgNAHgaAEQgVADgSAAIgKAAg");
	this.shape_69.setTransform(-41.8,40.1);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#EAC5E4").s().p("AACAGQgOgCgGgEQgIgDAAgCQADgCAEABQANAIANAAQAOABAGgCIAAAGIgHAAIgSgBg");
	this.shape_70.setTransform(-45.3,39.8);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#C19A70").s().p("AgbAVIAAgCQgBgIAHgNQgDAJAAAFIAAACQALAIANABQALABAHgCIgBAHQgEABgNAAQgOAAgNgJgAAcgHIAAABIgCADIACgEgAgOgNIgDgJIgCgGIAFgBIACAKQAAAGgBAAIgBAAg");
	this.shape_71.setTransform(-44.4,36.7);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#E2C19A").s().p("AAAAfQgOAAgNgJIAAgCQgBgEADgJQACgHAJgJIABgBIgDgHIgDgKIAFgBIAGgCIACAKIABAHIABAAIALABQAMABAJAGQgGAHgCAKQgDAKAAAIIgKABIgHAAg");
	this.shape_72.setTransform(-44.4,36.6);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#E2C19A").s().p("AAAAfQgOAAgNgJIAAgCQgBgEADgJQACgHAJgJIABgBIgDgHIgDgKIAFgBIAGgCIACAKIABAHIABAAIALABQAMABAJAGQgGAHgCAKQgDAKAAAIIgKABIgHAAg");
	this.shape_73.setTransform(-44.4,36.6);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#FFF8FE").s().p("AAMgFQgIgHgKABQgSADgGAMQAEgSAXgFQAKgBAIAHQAIAGADAHIAFAQIgEAEQgDgQgMgJg");
	this.shape_74.setTransform(-38.7,37);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#FFE3FA").s().p("AggAMQABgMAHgLQAHgMAQgDQAKgCAIAHQAHAGAEAJIAGAPQgIAIgUAFQgRAFgVAAIAAgPg");
	this.shape_75.setTransform(-39,37.7);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#000000").s().p("AgZApQgXgBgIgGQgIgFAAgBIgBgGQgBgEACgCQADgDAFABIAAgCQAAgEACgIQADgJAJgJIgEgJIgDgJIARgEIABAIIACAJQAEAAALABQALACAHAGQAHgJAOgCQANgBAJAHQAHAHAEAJQAFAHABAIIAAABIACAKIAAABIgBAAQgNAJgbAFQgWADgTAAIgJAAg");
	this.shape_76.setTransform(-41.8,37.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56}]}).wait(50));

	// Layer 2
	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#000000").s().p("AAWBJQgHgCgZgBIgJABIgCABIgBgDIgDgJIgCgCIAGgBIAAgIIgBgkIgDgWIAAgBIACgBIADgEIAAgBIgDAAIgDAAIAAgDIAEgYIAFgZIAAgDIADAAQARACARgDIAEgBIgBAEIAAADIAAAEIAAAFIgBAEIAAAFIAAAEIAAADIAAADIAAADIgBAEIAAAIIAAAEIAAAEIAAAFIAAAGIAAAEIAAALIgBAEIAAAGIAAAIIAAACIAAAXIAAAFIAEABIADAAIgDAOgAAUBEIABgDIgEgBIgCgBIAAgFIAAgEIAAgXIAAgFIAAgEIAAgGIAAgFIAAgDIAAgCIAAgDIAAgDIAAgBIAAgCIAAgGIAAgHIAAgCIAAgDIAAgCIABgDIAAgSIAAgEIABgHIAAgCIAAgFIAAgCIAAgCQgPACgOgBIgFAWQgDANAAAKQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAIAAAAIACADIAAAAQAAAEgFAEIACAXIABAiIgBAKIAAACIgCABIABAEIAIAAQAVAAAJACg");
	this.shape_77.setTransform(78.6,29.6);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#000000").s().p("AgcFYIgCgBIgBgCIAAgFIAAgCIgBAAIAAgBIAAAAIgBABIgTADQgRAEgagCIgDgBIAAgDIgBgHQABgHAFgHQAIgKATAAQAXABAJABIABgCIgBAAIgCgBIAAgDIABgTIACggIABgVIACgXIAFggQgggGgKgMQgOgJgBgGQgBAFgFAGQgGAGgKgBIAAAAQgCAAgFgGIgCACQgIAEgHgEIgBgBIgBgBIgBAAIAAgBIAAAAIAAAAIADAYQAGAhADA0IABAUQAAAegDANQgDAMgBABIAAABIgBAAQgFAEgIADQgJACgKgIIgCgBIABgDIAIgbQAGgaABgqIgBgWQgDgngGgUQgDgOAAgHIABgHIADgFQgIgLAAgGQACgHAOgLQANgKAGgCQAEgBAGABQABgFACgEQAFgFAIgBQAGgBAHAEQAMgTAGgWQAHgWAEgRIAFgWIgBgDQAAgDACgFQgGgFAAgEQgCAAAHgPQgZgLgagSQgagSgSgWQgRgVgBgVIAAgCQABgVAMgPQALgPAMgJIAAAAIgCgDIgBgDIAAgCQADgEADABIAEAAQABAAgBgJQgBgFADgCQAEgEANACQAEgMAGgLQAHgKAHgEIAAgDQgBgLAEgGQAEgHABAAIACgCIACACQAJAHAAADIAAADIgCABIgLALQAFAAADADQAkghAkABQADgCAfALQAeAMAgAxQAIgBATACQASADAQAPIABABIgBABIgCAKQgBAIgEAGIAGAOQADAKAAAIQAAAHgEACQgHABgGgFQgBAHgDAKQgEAJgHAFQgDAkgZAUQgSAOgaAKQAEAHAAANIAAAEIAAABIgCACQAKAJAIALQANAVAFAfQAEAhAAAfQAAAWgBAPIgBARIAAABIgBABIgIAGQgGALgcAMIgEAZQgDAQgBAPQAEADAAADIAAABQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAIgEACIAAAFIADAbQABAQACANIAAADIABABIAAACIABAEIgDABQAFAIABARIAAADIgEABIgHABIgOABIgDAAIAAgBIgBAAIgBABIgSAEQgLACgLAAIgUgBgAgcFEIABAFIACAAIgBADIAAAEIAAADQAXABAOgCQARgDACgBIAEgFIADgEIAAAEIABAFIASgCQgBgSgFgHIgBgDIAEgBIAAgBIgBgCIAAgCIgEgeIgCgbIAAgDIAAgGIACgBIADAAIgEgEIgBgBIAAgBIAEghIAFgaIABgCIABAAQAbgMAGgKIAAgBIABAAIAHgFIABgRIABgkQAAgfgEggQgEgegNgUQgIgMgLgJIgCgBIAEgFIAAgDQgBgOgEgGIgBgDIADgBQAagKATgPQAXgSADgjIAAgBIACgBQAHgFADgKIAEgPIABgGIAFAEQAFAEAEAAQAAAAAAgBQABAAAAgBQAAAAAAgBQAAgBAAAAQAAgHgDgKIgGgOIAAgCIAAgBQADgDACgHIACgLQgQgOgSgCQgTgCgEABIgCABIgBgCQgegwgegLQgdgMgDACQgigBgkAhIgCACIgCgCQgDgDgDAAQgDAAgDACIgBAAQgNAKgHAaIgBACIgCAAQgQgCAAACIAAACQACAJgDAEQgEADgEgBIgBAAIABABIACADIABABIgBAEIgBABQgMAIgKAOQgLAOgCAUIAAACQABAUASAVQARAVAaARQAaASAYAKIADACIgBACQgHAOABABQAAABAGAFIABACIAAABIgDAIIABACIAAABIAAABIgFAWQgEARgHAYQgHAXgNAUIgBACIgCgBQgIgEgEAAQgGAAgEAFQgCADgBAFIAAADIgDAAQgGgCgEABQgFACgMAJQgLAKgDAEQAAAEAIAMIABACIgBABIgDAFIgBAFIAEAUQAFAUAEAnIAAAXQAAAngGAaQgGAagDAFQAHAFAHgBIALgGIADgNQACgMABgbIgBgVQgDg0gGggIgEgcQAAgJAEgDIABgBIAFAAIgBAGQgBAEABACIAAABIABAAIABABIABABQAEACAGgDIADgDIADgDIABAEQADAGACAAQAHAAAEgEQAGgHgBgDQgBgEgFgFIgCgBIACgCIACgEQABgEAAgFIAAgEIgBgEIAEABIAGABIADgBIAAADQgCAcACABQgCACAQALIABABQAJALAgAHIACAAIAAACIgHA5IgBATIgBAfIgCAVIACAAIACABIgDAMIgCAAQgHgCgbgBQgQAAgHAJQgFAHAAAGIABACQAWACARgDIATgDIADgFIADgFIABAFgAhUCDIAAgJIAAgMIgBAAIABACQAAAGgCAFIgCADIAEAFIAAAAgAhLk/IAAABIAKgKQAAgDgEgDQgFADgBAMg");
	this.shape_78.setTransform(77.5,5.2);

	this.instance_1 = new lib.Symbol10("synched",0);
	this.instance_1.setTransform(69.6,-28.7,0.261,0.261);
	this.instance_1.alpha = 0.699;

	this.instance_2 = new lib.Symbol9("synched",0);
	this.instance_2.setTransform(61,-29,0.261,0.261);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#000000").s().p("AgIgFIgBgCIAEAAQAEgBABgBIAEgCIAEACIgGgOIAHgDIAAAEIgEAxIgFAAQgFgWgDgKgAgCgDIACAQIACgLIABgGIgFABg");
	this.shape_79.setTransform(-87,9.4);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#000000").s().p("AhnGbIgDAAIgCgGIgDADIgCAAQgIgDgGgDIgCgDIABgCIAGgJIAMgPIgFgEIgCgCIABgDIASgaQAPgWAQgQQgCgDgBgDQAAgDACgCIAEgDIgBgUIgCgiIAAgXQgFACgEAAIgFgCIgBgBQgEACgGgCQgFgEgCgGIgCgJQgIAAgIgNQgFgHAAgGIABgEQADgGACAAIABgBIgQgkQgIgSgCgLIAAAAIABgEQgMgLAAgGIABgCQABgEAEAAQgCgDAAgEQAAgGADgCQAEgDAGAAIAOABIALgcIAJgUQAEgIAGgFIgGgEIgDgBIAAgEIAGgLQAFgKAFgGIAEgCQgPgQgPgaQgQgZgJgkQgdgMACgRIAAgEQACgIAHgFQgDgVAAgVQAAgPAFgOIgFgEIgEgDIAAgDQACgNAFgCIADgCIABACIAGAJQAXgpArgSQAogOAbAAIAJgBQANgBAKgEQAogSAPgNIALgHIABgBIABAAIAHABQAFADAHAFQAKAIACAZIgBANQgEASgTAPQACAHAAAMIgBAYIgBADIAAAFIABAHIAAADQAKAGAGAGIAHAHIAAABIAAABIABAKQgBAjgGAOQgFAOgBAAIgBABIgCAAIgFAAIABAGIAFAQQAFAQABAMQAAAGgCAGQgGAUgYAPQgYAQglAHIgKADQACADAAADQAAAEgDAIIgCALIgBAFIACACIAEAIIAKAYQAGAMAGAJQAIgDAFADQAGAFAAAIQAGgBAFACQACACAAADIAAABIAAADIASAAIARAAIAQgQIARgOQAGgDAIADQAIACAFADIACABIgJARIgBAAIgHAEIAEAHQAHAJACAIQAAACgDADQgFADgIgCQgHgDgHgEQgFAFgQgBIgXADIgjACIgDAEQgGAFgFABQADAPAAAMQAAAMgDAKIAAAEQgBAOgEACQgCAIgJAIIAOAvQAHAaADAQQAEATABAaIAAAkIAAACQANAFAGABQACgIANgCQAIgBAFAFQAGAGAAAJIAAACIgBACIgCABIgQAGQgQAGgVABIgCABIgDAAQgCACgNgBIgEAAIAAgEIABgHQAAgHACgJQgHgBgEgDIgBgCIAAgCIAFgtIADgbQgFgCgBgGQABgFAFgDIgPgsQgGgWgEgHQgGABgTAAIgEAaIgEAoIgDAiIAAABIgBABIgJAPIgRAfIgNAaIgCACIgDAAIgEgBIABAAIAFABIAEABQAGgFAOACQAHADACAHQADAJgEAJIgBABIgCAAIgNADIgTABIgRgBgAhoGQIACAGQAoAAAGgDQACgDAAgEIAAgFQgCgFgFgCQgFgBgFABIgGADIgBAAIgNgCIAAAAQgDgCgCgGIgBgEIAFABIAHACIAOgZIARgeIAJgRIADglIAFgqIADgXIAAgDIADAAQAXABAFgCIACAAIABABQACAGAGASIAMAjIAGAUIABACIgCABQgGAEABAAQAAABABAAQAAAAAAABQABAAAAABQABAAABAAIABABIABABIAAACIgDAeIgFArQAEADAGAAIADAAIgBADQgDARABAHQAIAAADgBIABgGIAAgFIADAFIADAFQATgBAOgFIARgGIAAgBQAAgHgEgEQgDgEgGABQgKADgBAFIgBACIgCAAQgKgBgOgFIgGgDIAFgCIAAgCIgBgkQAAgZgEgTQgDgQgIgbIgOgvIAAgCIABgBQAKgHACgIIAAgBIAAAAQACAAACgNIAAgEIAAgBQADgJAAgMQAAgMgEgRIgBgDIAEAAQAEABAGgGIAFgFIABAAIAkgCIAXgDIAAAAQAQAAAEgEIABgBIABABQASAKAFgDIAAgCQgBgGgGgHQgGgIAAgCQADgGAIgCIAFgKQgMgHgIADIgOAMIgSARIAAABIgCAAIgUAAIgUAAIgEAAIACgDIABgFIAAgBQgDgCgHABIgDABIAAgDQABgGgFgGQgFgBgEADIgCABIgCgCQgGgJgHgOIgLgZIgFgLIgBAAIABgGIACgMIADgLIgEgHIgDgDIATgEQAjgHAXgOQAYgPAFgSQACgJgBgIQgBgJgEgLIgDgJIgCgIIgDgNIAEABIAHAAQACgCAEgNQAFgOAAgeIAAgJIgGgHQgGgGgLgGIgEgCIAEgCIAAgCIgBgGIgBgBIACgJIABgXQAAgPgCgEIgBgCIACgCIAAAAQATgNACgQIACgNQAAgPgIgKQgMgMgFAAIgLAHQgQAOgoASQgLAEgOABIgJABQgaAAgnANQgqASgXAqIgCAEIgCgCIgIgKIgCAJIAEAEIADADIACABIgBABQgFAPAAAPQAAAWADAUIABACIgCABQgGAEgCAHIAAADQgBAOAaAKIABABIABABQAJAmAQAaQARAaAPAQIADADIgKADQgEAEgEAIIgGAMIAJAFIADACIgDACQgHAGgEAIIgKAVIgLAdIgBACIgCAAQgSgDgDADQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAABIACAGIADAFIgGABIgCABIAAAAQAAAEAKAKIADADIgCACIgBACQAEAQAXAxIABADIgDABIgDACIgCADIAAACQAAAEAEAHQAHALAGgBIACAAIABADIACAJQACAFADADQADAAADgBIAAgBIABAAQABAAAAAAQABAAAAABQABAAAAAAQAAABAAAAIAAABIAEABIAGgCIAGgFIAEBaIgBABIgEADIAAABQAAABADADIACACIgCACQgPAOgPAVIgUAdIAHAEIAEABIgDADQgGAFgGAIIgIALQADACAIACIAEgEIADgEIABAGg");
	this.shape_80.setTransform(-76.4,-0.4);

	this.instance_3 = new lib.Symbol13("synched",0);
	this.instance_3.setTransform(-92.5,-41.4,0.261,0.261);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#000000").s().p("AA8FvIgXgFQgMgEABgHIAAgBIAAgBQgBgFAJgGIAAgBQABgIADgHIAGgLIAAgKQghADgkgJIgBANQAGAGACAMIAAABQAJAHgBAHIAAAEIgCACQgoAUggABQggAAgTgGQgTgGgBgBQgIgEgCgIQgBgMAFgKIAHgMQAOgSAXgCQAVgCAOAKIAJALQAWgEADgEIAAgFIAAgHQgbgJgDgCQgCAAgCgEQgDgEAAgNQAAgJACgRIgGgFIgDgCQgDgDAAgEIAAgBIAAgBQABgMAFgMQgDgCgCgEIgBgDIAAgBQABgFACgCIALgZIALgfIAFgPQAEgTAAgSIgBgSIAAAAQgFgJAAgJQABgRAIgNQAIgPAHgIIAAgHIgHgCIgEgBIgFgBIgFgBQgXgFgWgLQgagMgPgKIgQgLQgKgMAAgTQABgVAFgTIAFgRIAGgRIgBgBIACgIIAEgVIAAgQIAAgLIAAgBIABgJIAAgBQgDgBgCgGIAAgBQAAgIAMgLQAMgfAOgMQAOgMAEAAQADgDATgJQATgKAggEQAegFAqALQAUAFAUAKQABAAAKAHQAKAGAMANIAGAIIADgDQAEgDAJACIADABIAAANIABAOIACADIAEgOIACgJIACgBQANgBABAHIABABIgFAOIgFAQQAUAXAAAbQAAAIgCAJIgIAPQgIAPgOAOIAAASIABARIgNgFIAAgIIgBgNQgNAHgNgBQgNARgQAJQgJAegaAhQACAGAAAHIgBALIABABQAKAIAIAMIADAEIADAEQATAWAKAcQAIAVADAVIgBAIIgDAnQgCAYgDAUQgCAwgCAeIAAABIgCAcIgBACIgBABIABAAIgCABQgJAEgKACIgBAAIgBAAIAAAGIAAACQAPAEALAAIADgDQANgNASAAQARABANALIAAAAQAUATgCANQgCANgCAAIgBABQgcAQgeACIgSAAQgUAAgQgCgAAyE5IgBABIgFAJQgFAHAAAIIABADIgCABQgHADAAAFIAAAAQgCACAJAFIAXAFQAWADAdgBQAegCAbgPQABgBACgKQABgKgRgRQgMgKgPAAQgQgBgLAMIgEAFIgCAAQgMAAgTgGIgBAAIAAgCIAAgEIgBgHIAAgDIAGgBIABAAQAJgCAIgEIACgNIABgOIAAAAIAAgBIAEhOIAAgBQADgUACgYIADgmIAAgEIAAgEQgCgUgIgVQgJgagTgWIgGgIQgIgMgJgHIgCgBIgCgBIABgCIABgMQAAgHgDgFIgBgCIACgBQAbgiAJgdIAAgBIABgBQAPgJAOgRIABgBIABAAQAOACAOgJIAEgDIAAAMIABAOIACABIAAgRIAAgMIAAgBQAPgOAHgOIAIgPQACgIAAgIQAAgYgTgXIgBgBIAEgPIAFgPQAAgDgHAAIgDANIgCALIgCAEIgLgJIAAgMIAAgOQgHgBgBABIgBABIABAIIAAAIIgFgIIgLgOQgMgNgJgGIgKgGQgUgKgTgFQgqgLgdAFQggAFgSAJQgTAJgBACIAAAAIgBAAQgDABgNALQgOALgLAfIAAAAIgBABQgMALABAEIAAAAIABADIAEgEIADgDIgBAIIgDAOIAAABIAAALIAAAQIgEAWIgBAFIABAAIgBACQgCAMgEAIIgFARQgFAQgBAWQAAARAIAKIAQAKQAPAKAZAMQAWALAXAFIAEABIAFABIAOAEIABABIABAKIAAABIgBABQgHAIgIAOQgIANAAAQQAAAIADAHIABACIAAABIABASQAAATgEATIgGAQIgLAfIgKAaIgBAAIgBAEIAAACQABACAEACIACABIgBACQgGAQAAAJIAAABIAAAEIADACIAHAFIACABIAAACQgDASAAAKQAAAOAEABIAfAMIACAAIAAASIAAAAQgDAFgJACIgTAEIgBAAIgBgBQgFgGgEgEQgMgKgTACQgVACgNAQIgGAKQgFAKACAKQABAFAGADQAAABATAGQASAGAfgBQAfAAAmgTIAAgCQABgFgHgFIgCgBIAAgDQgBgJgHgHIgBgBIAAgBIACgSIAAgDIADABQAlAKAigDIAFgBg");
	this.shape_81.setTransform(41,5.2);

	this.instance_4 = new lib.Symbol11("synched",0);
	this.instance_4.setTransform(23.6,-31.4,0.261,0.261);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#000000").s().p("AgGErIgSAAIgDAAIgBgEIgBgQQAAgLACgFQgDgCgBgDIAAgCQABgEACgDQgDgCAAgDIABgDQABgFALgEIAAAAIgIgCIgCAAIAAABIgDAAIgNABQALAEABAFIABADQAAADgDADQACACABAEIAAACQgBADgDACQACAFAAALIgBAQIgBAEIgDAAIgSAAIgjAAQgTgBgOgDIgCgBIAAgBQgCgCAAgNQgBgMALgJQAKgFAMACQALADAFACIADgCQgCgCgBgDQABgFAEgCQgCgCAAgDIAAgBIABgEQADgDAGgBIgLgBIgDAAIAAgDIgDgPQgCgPAAgQIAAgBIgEgCIgCgBIAAgCIAEgRIAIggIgMAQIgGAJIAAAHQAAANgHAGIACAJQAAAGgDAEQgDAFgEAAQgEAAgGgNQgDALgFAEQgDACgDgBQgFgBgBgLIADgLQgPAIgHgEIgBgEIAAgBQACgHALgJQgJgGgCgLIAAgBQABgHADgBQADgCAHAEQAFADAJABQAPgHAGAAIALgQIANgTIgBAAIgCgCIAAgDQAAgBAGgNQAHgOATgLIgIgEIgNgGQgQgIgRgKQgSgLgNgNQgWAAgMgIQgLgJgDgMQgFgWARgGQAKgDAKAFIAAgFQgIglgIgRQgHgSgGgFIgMAFIgHADIgJAFIADgJQAEgMAHgKIALgRIgPABIgIABIADgHQAMgXAMgOQAMgOAHgGQgPgKgOgHIgOgHIgEgCIACgEQALgQAJgEQAJgEABAAIACAAIACACIANAUIAOAUQArgqAtgHQAsgIAVADIASABQAUACASgDIAVgEIAKAAIAPgBIgNAIQgQAMgEAIQA3AMAdAUQAcAUAKARQAKASAAAEIADAJIgEgCIgEgCIAAABIgGgDIgRgEIgPgDQAlAqALAiQALAigBAJIACAJIgIgFQgSgKgMgDIAEANIADAJIgEAAQgsALgSASQAKgCAKAEQAOAJgIATQgFALgOAIQgNAHgXgFQgOAOgUAIQgUAJgUAEQAPANAHAYIABADIgDACIgCAAQAFAQAIAkIAFAGQARATAAAHQAAABAAABQAAAAAAABQAAAAgBABQAAAAAAAAQgEAEgOgIQgFAMgIABQgDAAgCgCIgBgCIACgFQgDABgCgBIgBAAQgCASgDAPIgBADIgCAAIgRADQAGAAACADIABAEIAAABQAAADgCADQAEABABAFQAAADgDACIADACQAFgCALgDQAMgCAKAFQALAJgBAMQAAANgCACIAAABIgCABQgOADgTABIgZABIgIgBgAgZDQIABAIIAAAJIAJACIADAAIAAAJIgCABQgLADgBADIAAABIADACIAEADIgEADIgDAEIAAAAQAAABABAAQAAABAAAAQABABAAAAQABAAABAAIACACIgBACQgCADgBANIABAPIAiAAQAbAAAUgEIABgLQABgLgIgGQgKgFgMADIgNAFIgBAAIgBAAIgIgGIgDgCIADgCIADgDIgDgCIgFgCIADgDQACgCABgEIAAgBQABgBgJgBIgDAAIAAgJIADAAIATgDQADgPACgSIAAgCIACAAIADgBIACgBIABABIAEgBIAIgBIgDAFIgCAGQAFgBAFgLIAAgEIAEACQANAIAAgCQAAgDgFgHIgLgNIgGgGIAAgBQgJgogFgOIgBgDIAFgCQgGgYgRgMIgFgDIAGgCQAUgEAWgIQAWgJANgPIABgBIACABQAVAEAMgGQANgGAEgKQAHgPgLgGQgMgGgPAKIgEADIAAgHIABAAQAIgLASgLQARgMAdgHIgEgOIgEgKIAFABQALACAXAMQAAgMgMgiQgMghglgoIgFgFIAHAAIAWADIAMAEIAAgBIAEABIAFACQgBgMgagcQgbgdhMgQIgDgBIABgDQACgHASgQQgKABgQADQgTADgUgCIgTgBQgUgCgsAHQgtAIgqAqIgCACIgCgDIgNgTIgPgXQgGgBgTAWIATAJQANAHAOAKIACACIgCACQgGAEgMAOQgMAOgNAXIATgBIAFAAIgDAFIgKAPQgIALgFAMQAIgEALgDIACgBIABACQATATAMA9IAAAAIgBAPIgDgDQgKgGgKADQgMAEAEARQACALALAIQALAHAUAAIABAAIABABQANANARAKQARAKARAIIAeAPIgFADQgSAIgHAMQgIAMAAAFIAEACIgBACIgPAXIgLAQIgBABIgBAAQgHAAgPAHIAAABIgBAAIgJgCIgIgEQgBAAgBgBQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAAAABQgBAAAAABQAAAAAAAAQAAABAAAAIAAABQADAKAJAEIAEACIgFADQgNALAAAEIAAAAQAAADAUgLIAHgDIgDAJQgDAHAAAGQgBAFADACIACgBQACgBABgGIADgJIADgLIAEAKIADAIIAEAGIACgCQACgDAAgEQAAgEgCgEIgBgCIACgCQAHgEAAgMIAAgGIgBgCIAdgoIAFADIgLAlIgFAYIAFACIAAACIAAAEQAAANACANIADARIAIABIAGABIADAAIAAAJIgDAAQgLABABABIAAABIADAEIADAEIgDACIgFADIADADIADACIgDACIgIAGIgBAAIgBAAIgNgFQgLgDgKAFQgJAHABAKIABALQAUAEAbAAIAkAAIABgPQgBgNgCgDIgBgCIACgCQABAAABAAQAAAAABgBQAAAAAAgBQABAAAAgBIAAAAQAAgBgBAAQAAgBAAAAQAAAAgBgBQAAAAgBgBIgDgCIADgDIADgDIAAgBQgBgDgKgDIgDgBIAAgJIADAAIAOgBIACgKIABgIgAC6i4IAAAAIAAAAgAC6i4IAAAAIAAAAg");
	this.shape_82.setTransform(12.2,10.6);

	this.instance_5 = new lib.Symbol12("synched",0);
	this.instance_5.setTransform(-9.2,-19.1,0.261,0.261);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#000000").s().p("AgJgCIAJgDIAAACIAEACIAGABIgJAFg");
	this.shape_83.setTransform(-20.3,35.4);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#000000").s().p("AAAAMQAAgCgKgDIgCAAIABgSIACAAIATgBIADAAIAAACIAAAQIAAACIgCABQgGABgDACIgCABgAgGgGIAAAJQAFABACADIAGgDIABgFIAAgGIgOABg");
	this.shape_84.setTransform(-20.2,33.3);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#000000").s().p("AAuEEQgYgGgLgGQgLgFAAgBIAAgBIgBgCIAAgBQgGAGglAKQgXAEgMgCIgNgDIAAAAIgBAAQgIgIAAgPQAAgPAKgIQAFgEAIgDQAAAAABAAQAAAAABgBQAAAAAAAAQABAAAAABQAKgDAHAAIAIgBIAJgEIgCgDIgBgDIgEABQgJAAgFgIIgBgEQAAgEAEgGQgFgEgCgMIgGgFIgBgBIAAgCIACgOIAGgeIgBgHIAAgHQAAgRACgMIgGgFIgCgCIABgCQgBgBAEgLQAEgMAJgLQgggKgTgNQgSgPgBgCIAAgBIgCgIIgBACQgBAAAAAAQgBABAAAAQgBAAAAgBQgBAAgBAAQgZgVgBgSQgBgSACgBQAUhIAigmQAjgnAZgKQAsgUAhAiQAQgKAaAGQAaAGAXAPIAAAAQAdAbAEAYQAFAYgDADIgCADIgCgCIgIgHIACAOQgBASgFATQgFASgHAOQgBAKgEAKQABACgOAUQgNAUgkANIADAUIACARIAAABIAAABIgHAHIAFAfIACAHIABAGIADAHQADAIAGAFQAIAIAAAJQgBAHgHALQgHAKgJACIgFAAIgBAAIgNgBQgHgBgEgEIgDABIAAAIIAAAHQAKADADAHIABAEIgBAEIgCACIAJAGIAHABQAPgBARALQAJAJAAAOIAAABQAAAPgIAIIAAAAIAAABIgBAAQgBABgLACIgIABQgKAAgQgDgAAEDLIADABIgBADQgEAMAAALIABAIQACAFAqAMQAVAEAKgCIAMgDQAGgGAAgNIAAgBQAAgMgHgHQgPgJgOAAIgJgCIgSgKIAFgCQABgBAAAAQABAAAAgBQABAAAAAAQAAgBAAAAIABgBIgBgCQgEgGgHgBIgCgBIAAgYIALgCIABACQAEAEAQABIABgBIABABIAEAAQAFgCAGgIQAHgJABgHIAAgBQgBgFgGgGQgGgGgEgJIgDgIIgBgGIgCgHIgFghIgBgCIACgBQAFgDABgCIgDgTIgDgTIAAgCIACgBQAjgMANgTQAOgUgBgCQAEgJACgLIAAAAQAGgOAFgRQAFgSAAgSQAAgKgCgKIgCgGIAGADIAKAIIAAgBQAAgJgGgTQgGgSgWgUQgagQgYgFQgZgEgMAJIgCACIgDgDQgFgIgSgJQgQgJggANQgYAJgiAmQgiAmgTBHQgBABgBAJQAAAHAFALQAEALAOALIACgPQABgIADgEIAFgHIgBAbQABARABAAQABADATAOQATAPAgAHIAFABIgEADQgKAKgEALIgEAOIAHAFIABABIAAACQgDANAAARIABAPIgFAcIgDAPIAGAEIABABIAAABQACANAFADIABACIgBACQgEAFAAADIABACQADAEAGAAQACABAGgHIABgBIACABIABgBIACAFQgDACgBACIgBACIAAABQABACADACIAEACIgRAJIgJACQgIAAgJACIgBAAIgBAAQgHACgFAEQgIAHAAAMQAAAMAHAHQABABAKABQALACAWgFQAogLADgEIABgLQAAgJgDgJIAEgDIAEACg");
	this.shape_85.setTransform(-20.3,16.2);

	this.instance_6 = new lib.Symbol8("synched",0);
	this.instance_6.setTransform(-36.1,-9.8,0.261,0.261);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_6},{t:this.shape_85},{t:this.shape_84},{t:this.shape_83},{t:this.instance_5},{t:this.shape_82},{t:this.instance_4},{t:this.shape_81},{t:this.instance_3},{t:this.shape_80},{t:this.shape_79},{t:this.instance_2},{t:this.instance_1},{t:this.shape_78},{t:this.shape_77}]}).wait(50));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-92.8,-41.6,187.1,84.2);


// stage content:
(lib.motherCJS = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.mother();
	this.instance.setTransform(100,100.8);

	// Layer 8
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,255,255,0)").s().p("AvnPnIAA/OIfOAAIAAfOg");
	this.shape.setTransform(100,100);

	this.addChild(this.shape,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(100,100,200,200);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;