(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 200,
	height: 200,
	fps: 12,
	color: "#FFFFFF",
	manifest: []
};



// symbols:



(lib.Symbol13 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#14395A").s().p("AmMYeIgDAAIgEgOIgHgVIgTAWIgDgBIgYgIQgSgHgIgGIgCgDIACgDIAagoQAYgiAbgaQgRgIgNgLIgEgDIADgDQAIgPA9hZQA+hYA+g5QgMgKgDgQIAAgBQAAgGAEgEQALgLAGgCIgDhFIgGiIIgFhxQgFAEgHAEQgQAIgMAAQgLgCgGgEIgHgIQgHAJgcgGQgOgMgIgXQgHgYgBgKIgBgFQgYAGgkgxQgWgkAHgWQAJgRAGgBIAOgHQgghAgghKQgghKgKgqQgCgCAJgOIgEgDQgrgqABgTIAAgGQAHgIAUgBQgJgPgFgVQAAgOAJgJQAKgHAaAAQAaAAAcAEQATgzAYg6QAYg6APgeQAUgnAYgRQgSgNgTgJIgEgCIABgEQACgGATgkQASglASgTQAHgGAWgEQg8g9g/hmQg/hmgkiRQh3gvARhFQAIgfAbgSQgMhNAAhXQAChDARgxIgSgPIgPgLIAAgDIAEgZQAEgTAKgIIAEgCIAOAUQANASAHAIQAKgcA7hKQA7hLB+g7QBWgjBLgIQBKgJA0gDQA8gFAmgOQBvgxA7grQA8grAZgPIABgBIABAAQAKgFA1AmQA0AmgMCCQgOBEhHAzIgEACQATAdgPCMIgEAfQAIATgDAVIgEACQArAYAXAXQAYAXADAFIAAAAIABACIAAABQACCYgVA8QgWA8gFAAIgCABIgCABQgRABgPgCIAJAiQAXBOALAsQAMAsgNAuQgTBFhYA6QhYA6iSAeIgyAKIgDABQAPARAAAOQgBAPgHAaQgHAagDAVIgDAVIAGAMIAPAiQATAuAYA0QAYA0AaAiQAYgRAVAJQAYAbgDAaQAVgFAWAIQAGAEAAAGQABAHgHATIBLAAQAtAAAigCIA6g4QAsgqAXgRQAXgKAgAMQAgAMAIAGIgbAzQgfAKgGAPQADALAQAVQAQAUAJATQAKATgKALQgTALgggNQghgNgNgJQgQARhCgCIhaAKQhMAIg8ADIgPAQQgZAYgWgCQAcB4gZBLIAAABQgDBIgNgBQgHAigpAfQAXBJAeBoQAfBoANA+QAKA2AEBKQAEBKAAA6IABA9IgBAEIgBAAQAUAIAaAHQAZAIARACQADgJAMgOQANgOAYgDQAagCARARQAUAVgCAiIAAADIgCABQgEAEg6AUQg7AVhQAGIgDAAIgLgRIgCAUIgDABQgFAEg0gCIgEAAIAAgFIABgeQACgdAHgmQgYgBgVgOIgCgCIABgDIAUitQALhZAAgVIAAgBIgFgDQgOgFgEgOIAAgBQAAgMAYgOQgYhNgihgQghhfgPgeQgXAIhZgDIgMBfIgSCeQgJBVgEA4IAAABIAAABIgjA8IhDB3QgkBBgPAgIgCADIgEAAQgEAAgfgIQAEAQAKAJIAWAEIAXADQAFgEAUgHQAVgGAYAHQAVAIAJAWQAJAegPAdIgBACIgDABQgBABgxAHQggAEgvAAIg4gBgAmKFXQgOAFgUACQAKAyAaBNIAOiSQgFAJgLADgAl8EdIAFAMIABgNIAAgCIgGADg");
	this.shape.setTransform(61.3,156.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-0.2,0,123.1,313.5);


(lib.Symbol12 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#14395A").s().p("AgeRxIhEgCIgEAAIAAgEQgLhpARgXQgOgHgDgLIgBgGQAFgQANgIQgNgHgFgOIABgGQAEgTAugMIAAgSQgVgBgSgFIgEgBIgCgiIgDgoIgBAAIgGAqIgFAkIgEABQgCABg5ACIAAARQAuAMAEATIACAGQgGAPgNAIQANAGAFAQIAAAGQgDALgPAHQARAXgLBpIAAAEIgEAAIhEACQg7AChKgDQhKgDgzgMIgCgBIgBgCQgEgHgEgsQgDgrAmgeQApgUArAMQAsALANAJQAJgFATgQQgPgKgBgKQAHgRATgFQgLgHgHgTIAAgCQAAgEAEgEQAOgLAfgBIAAgQQgcgCgggEIgEAAIgBgEIgKhBQgJg9ABg8IgSgJIgDgBIAThUQARhIAbhXIhDBcIgqA4QADAKgBAgQgBAhgdAYQAIATABARQgBAUgIANQgIAOgKAAQgJgCgLgYQgMgYgIgWQgEASgIAbQgIAbgNAJQgHAFgHgDQgRgIABgaQAFgkALgdQgVANgdANQgdANgMgJQgDgCAAgGIAAgBQADgQAVgUIAjgfQgpgSgKgsIAAgDQAAgRAJgFQALgGASAMQAJAFATAGQATAGAMACQBCggAWAEQAIgOAigyIA4hUIgMgHIgEgBIABgEQgBgGAcg1QAcg1BRgoIhjgwQg+gehDgoQhDgogxg1QhVABgrghQgqgjgJgqQgQhJA2gWQAwgLAjAZQAAgTACgRQglirgkhAQgjhAgKgEQgcAIgZAMIgbANIgMAGIAEgMQASg0AeguQAdgtAPgTQgagBgZACIgcADIgKABIAEgIQAxhhAzg4QAyg4ATgNQg9gsg3gdIg8geIgFgCIADgFQAog5AfgQQAggRADACIAEAAIACACIA6BWIA1BNQCfigCrgeQCrgfBUALIBNACQBLAHBJgMQAsgJAjgCIAmgDIASgBIgPAKQhSBAgFAeQDiAtBtBQQBuBQAhBCQAiBDgDAFIADALIgLgFIgUgIIABACQgggMgigHQg4gJgegCQClC0AoCMQAoCMgHAKIACALIgKgGQgqgagmgNQgmgOgSgDIAQAxIANAmIgGABQhxAahDAsQhDArgeAnIAAACQAvgoBDAYQAxAfgdBDQgRApgzAaQgyAbhXgTQg2A5hVAiQhUAhhOAQQA9AlAiBwIABAEIgEACIgQAGQAWA4AgCYQAfAkAaAhQAaAgACARQAAAFgDACQgWAIgqgeQgSAygcAFQgJAAgCgFQgDgGANgbQgVAIgNgHQgHAEgGABQgHBJgNA6IgBADIgDABQgLAEhJAHIAAAQQAdABAOALQAEAEAAAEIAAACQgGAUgKAKQASADAGAPQAAAKgQAKQATAQAJAFQANgJAsgLQAsgMAoAUQAmAegDAsQgEArgEAHIgBACIgCABQgzAMhKADQgxACgrAAIgngBgAB8JvIADgDIgIgaIAFAdg");
	this.shape.setTransform(82.1,113.8);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,164.2,227.7);


(lib.Symbol11 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#14395A").s().p("ADpVzQhTgPgGgDQgmgQAFgUQgGgUAmgTIgBgHQAAggAQgeQAQgeAHgIIgCg1IgKABQicAKh6glQgBAlgGAfQAHAHAMATQAMATADAVIAAAJQAbAPACAVQACAVgCACQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQiVBKh5ADQh4ADhJgXQhIgYgDgEQgZgNgHgbQgFgoATgmQAUgmAFgEQAyhABVgLQBNgHAwAnQAWATAQAYQAggFAigJQAigJAKgPIgCg4QhxgngGgGQgXgMABg2QABg2AKg5QgRgJgMgLIgLgIQgHgHAAgPQACgwAWg2QgSgIgEgNIgCgHQACgVAHgEQARgjAYhAQAYhAASg2IAUg7QANg2ACg6QABg7gEgqIgCgFQgfhMAlhOQAkhMAjgoQgDgVgBgRIgvgMIglgGQhggYhMgmQhigug6gmQg5gmgCgEQgmgtAEhLQAEhLAThAQAQg9ACgEQAPgiAJgoIgCgBIgDgCIAIgZQAKgtADglQAEhggDgKQAEgeAGgaIgKAJQgFABgJgVQgIgUA1gwQAuh5A1gtQA2gtAMAAQAHgIBHgkQBIgkB6gTQB4gTChAqQBIAUBOAnQACAAAmAYQAlAYAuAzQAXAYAUAeIgCgaQgBgCAIgIQANgIAdAHIADABIABAeIACBHQANAKAOANIAQhDIAIgeIADgBQAlgDAEATIAAABIgKAjIgZBQQAoAuAXA/QAXA/gSBPQgBAFgeA4QgdA3g4A1IACBXIABAkIgbgLIgGhaQgxAjhAgGQgvA/hDAoQgUBFgnA/QgmA/gqAyQAUA1gOAwIACABIAFAFQArAgAaApIAYAgQA+BIAuB4QAdBJALBWIgKCUQgIBqgQBeQgFCxgKB6IABABIABAEIgLBqIgCAFIgCACQgkAOgkAIIgPADQABAdAAAPQBCAVAxAAIAMgRQAxgwA+ADQA/ADAwAnQBGBDgHAtQgGAtgHACIgBACQhnA7h0AHQgkACghAAQhKAAg6gKg");
	this.shape.setTransform(66.9,140.4);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,-0.1,133.9,281.1);


(lib.Symbol10 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#14395A").s().p("AgcAmQgEgmANgWQAOgVADgBIACgDIACACQAeAagCAJIAAADIgDACQgMAHgPASIgUAUIgHAIg");
	this.shape.setTransform(3,4.9);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-0.1,0,6.1,9.7);


(lib.Symbol9 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#14395A").s().p("AhtUbIgDAAIgBgEQgCgEACgcIgEAAIgEgVIgMASIgCABQgEAChCAMQhCAMhggIIgEAAIgBgEQgBgDABgWQABgXASgYQAcgjBDAAQBpADAaAGIAIgcIgLgDIgEgCIABgDIAEhCIAIh9QAEhBAAgTQABgYAJhHIARh6Qh9gZgoguQhBgvAHgLQgHgGAGhrQgLABgPgEQAFAcgIAbIgBAAIAAABQgDAKgHAHQAUAUAGASIAAABQAFALgaAmQgSASgigCQgIADgSgfQgIAIgGAEQgZAOgXgMIgEgDIgCgBIgCgCIgBgBIgCgCIgBAAIgCgDQgHgOAFgRIACgMIgFAAQgKAJAAAgQABAgAMBJQAXB8AODHQAFCagMBCQgMBBgDAAIgBACIgBAAIgUANQgPAJgMADQghAFgegYIgCgCIABgDQAGgGAdh+QAdh/gJjDQgPiXgThMQgUhKALgcQAEgLAJgJQgggvAAgVQAGgTAwgnQAwgnAYgIQAUgDAWAGQACgXAMgQQAQgTAbgCQAYgBAbAQQAwhLAbhYQAahXAPhJQALgxAKgkQgEgIAAgEQADgSAGgPQgTgMgHgWQAFgYATgkQhdgnhlhGQhmhFhGhUQhHhUAAhSQAGhLApg3QAog2AzgnIADgJQgGgGgFgHQgFgGADgHQAEgFAJABQAMACAJgHQAJgKgHgeQgBgOAHgFQAXgNAsALQAQg9AfgtQAfgtAjgCQASAAAPAOQA2g0BHglQBHglBUABQALgIBzAtQB0AsB3C8QAVgEBKAHQBKAIA/A7IgIAlQgIAhgMAVQAHAQANAnQANAmACAdQAAATgMAHQgMAEgPgKIgXgQQgDAVgNArQgNArgeAWIgCABQgKCJheBJQhMA5hjAoQASAegBBBIAAAAIAAABQAAACgJALQAmAfAjAzQA5BdAPCSQAPCUgFB7QgFB7gDAQIAAACIgCABQgBAEgcASQgXAqhtAtIgSBkQgLBCgFA7QANAIAFANIAAABQAAAEgDADQgIAHgIgBIAAADIAAACIAAACIABAIIAAALIAAAAIAIBnQAFA/AJAyIABALIACAHIAAAAIACAHIABAFIgFABIgIACQATAbAEBOIAAAEIgEABIgZAFQgYADgeABIgEAAIgEgVIgMASIgCABQgDAChCAMQgoAHgyAAQghAAgmgDgACBS1IAIgeIgWgFIgEgBIAAgDIAAgYIABhYIAAgBIAAgQIAAgCIAAgQIAAgDIAAgnIAAgCIAAgSIABgFIAAgPIAAgGIAAgPIAAgGIAAgPIABgFIAAgVIAAAAIAAgVIABgFIAAgPIAAgHIABgNIAAgIIAAgMIABgIIAAgMIAAgHIABgSIAAgBIABgRIAAgGIABgMIAAgGIABgKIAAgHIABgJIAAgGIABgHQhGAKhGgGQgIAngLA6QgLA6gDAkQAMgBAIAGIADAHQgEAPgOAHIAHBgQAGBKAAA9QAAAWgBAOIgBAEIgEAAIgKABQAGAOAGAWQAQgDAUAAQBoADAZAGg");
	this.shape.setTransform(63.2,131);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,-0.1,126.5,262.2);


(lib.Symbol7 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#14395A").s().p("AEFWhQhXgGgfgUQgegUABgEIAAgBIgBAAIgEgUQgDgPAFgKQAOgNASAEIAAgEQgBgTAKgjQAKgjAigiIgRgvQhmAZhuAFIgGARQAjAiAIAjQAKAjgBATIAAAEQASgEANANQAFAKgCAPIgFAUIAAAAIAAABQABAEgfAUQgcAUhXAGQhgAEhngRQhogQg0gkIgCgBIAAgDIAGgmIABgEQAGgeAQgjQAPgjAdgZQAjgdAwAFQA2AIAcAhQAygdA1gDQhmgHhYgtIgDgCIABgDIAMiSQAMiGAQiWQghABgjgBQgigCgVgJQg0gegOg6QgCgYARgNQAOgJAKABQAHABALgCQALgDAPgWQg9hOgahHQgYgLgBgCIgDgBIABgDQADggAchRQAdhRAmhTQAmhUAjgmIAPgPQhZAGgvgkQgBgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAgBABAAQAAgBAAAAQABAAABgBIARgMQAPgLAFgVQAFgZgbgdIgagYQg4gxhShkQhShkgsiTQgsiTA5i+QBCi5BRhKQBRhLBCgKQBBgKARAGQAKgNA4grQA3grBdghQBegiCLAXQCNAWCsCPQAAABABAAQAAABAAAAQAAABAAAAQABABAAAAIAAABQgBADgDABIgcAJQAbATAyBTQAyBUAHCZQAAApgGAvQgYCbg6CGQg6CGgxBYQgWAngSAcQgTAdgBALQAEAgAdAQQAdAPAEAAQADABAAADIAAABQABADgIATQgIATgWAMIAvAtIATgDQAOgMAWgJIALgFIAEgCIAFgBQAjgLAWAFQAJADAFAFQAJABAJACIABAAQgFgfAfgmQAcgYAzAMIAIABIgFAGQgBABgKARQgKARgBAXIABAJQAFgTAhgUIABAAIAAgBIAFAJQgJgEgRBBQBWAqAQCEQAGA/gPBGQgQBGgpA7IABABQg+BhhLAaQhKAZgqgEQASB2AMB/QANCAABBtIgBAqIAAADIgDABIg+AbQg8AZhfAcIAHAqQAPgBAqAGQAqAGAjAWQAcghA2gIQAvgFAkAdQAdAZAPAjQAQAjAGAeIAAAEQAHAhgBAFIABADIgDABQgzAkhoAQQhUAOhPAAIgkgBg");
	this.shape.setTransform(73.3,144.2);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-0.3,0,147.2,288.6);


(lib.girl = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// girl
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B77602").s().p("AgBAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAgBAAAAQAAABABAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAQgBABAAAAQAAgBAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAg");
	this.shape.setTransform(-18.8,30.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFCC73").s().p("AgCACQAAgCACgBQAAAAAAAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAAAQABAAAAAAQAAAAgBAAQAAABgBAAIgBABIgCAAg");
	this.shape_1.setTransform(-18.4,29.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFCC73").s().p("AgBAAQAAAAAAAAQAAgBAAAAQABAAAAAAQAAgBAAAAQAAAAAAAAQABAAAAAAQAAAAAAABQABAAAAABQAAABgBACQgBgBgBgCg");
	this.shape_2.setTransform(-19,29.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFCC73").s().p("AgCAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAgBABAAQACAAABABQgBACgCAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAg");
	this.shape_3.setTransform(-19.2,30.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFCC73").s().p("AgBABQABgCAAgBQAAAAABABQAAAAAAABQABAAAAAAQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAQAAAAAAAAQAAAAAAgBQAAAAgBAAQAAgBAAAAg");
	this.shape_4.setTransform(-18.9,30.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFCC73").s().p("AAAACQgBgBgBgBQACgCABABQABABAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAQAAABAAAAQgBAAAAABQAAAAAAAAQgBAAAAAAIgBAAg");
	this.shape_5.setTransform(-18.5,30.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#B77602").s().p("AgBAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAgBQAAAAAAABQABAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAAAABQgBAAAAAAQAAAAgBABQAAAAAAgBQAAAAAAAAQAAAAgBAAQAAgBAAAAg");
	this.shape_6.setTransform(-14.6,27.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFCC73").s().p("AgBACQgBgCACgBQAAAAAAAAQAAgBAAAAQAAAAABABQAAAAAAAAQABABAAAAQAAAAAAAAQABAAgBAAQAAAAAAABIgCACIgBgBg");
	this.shape_7.setTransform(-14.3,27);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFCC73").s().p("AgBAAQAAAAAAAAQAAAAAAgBQAAAAABAAQAAAAAAgBQAAAAAAAAQAAAAAAAAQABAAAAABQAAAAABAAQABACgCACQgBAAgBgDg");
	this.shape_8.setTransform(-14.9,27.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFCC73").s().p("AgCAAQAAAAAAAAQAAAAAAAAQAAAAABAAQAAgBABAAQACAAABABQgBABgCABIAAAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAgBAAAAg");
	this.shape_9.setTransform(-15.1,27.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFCC73").s().p("AgBABQAAgCABgBQABAAABACQAAABAAABQAAAAAAAAQgBABAAAAQgBAAAAAAIAAAAQAAAAAAAAQAAAAAAAAQAAgBAAAAQgBgBAAAAg");
	this.shape_10.setTransform(-14.6,27.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFCC73").s().p("AgCAAQABgBACAAQABAAAAAAQAAABABAAQAAAAAAAAQAAAAAAAAQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAgBAAQgBAAgBgCg");
	this.shape_11.setTransform(-14.2,27.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#B77602").s().p("AAAAAQAAAAAAAAQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAAAAAAAQAAAAAAABQABAAAAAAQAAAAAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAQAAABAAAAQAAAAAAgBQAAAAAAAAQAAAAAAgBQAAAAAAAAg");
	this.shape_12.setTransform(-23.6,18.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFCC73").s().p("AAAAAQgBAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAgBAAAAQAAAAAAAAQAAAAAAAAQAAAAABABQAAAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIgBAAQgBAAAAAAQAAAAAAAAQAAgBAAAAQAAAAAAgBg");
	this.shape_13.setTransform(-23.9,18.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFCC73").s().p("AgBAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAABAAQAAgBAAAAQAAAAABABQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAgBAAQAAABgBAAQAAAAAAABQAAAAAAgBQAAAAgBAAQAAAAAAAAQAAgBAAAAg");
	this.shape_14.setTransform(-23.8,18.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFCC73").s().p("AAAACQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAgBgBAAQAAgBABAAQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAAAQAAAAABABQAAAAAAAAQAAAAABABQAAAAgBAAQAAABAAAAQAAAAAAAAQAAAAgBAAIAAAAg");
	this.shape_15.setTransform(-23.5,18.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFCC73").s().p("AgBAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAABAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAABAAAAQAAAAAAAAQgBAAAAAAQgBAAAAAAQAAAAAAAAQAAAAgBgBQAAAAAAAAg");
	this.shape_16.setTransform(-23.3,18.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFCC73").s().p("AAAAAQAAAAAAgBQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAQABAAAAAAQgBAAAAAAQAAABgBAAQAAABAAAAQAAAAAAAAQAAAAAAAAQAAgBAAAAQgBgBAAAAQAAAAABAAg");
	this.shape_17.setTransform(-23.4,18.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#B77602").s().p("AAAAAQAAAAAAAAQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAAAAAAAQAAAAABABQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAQAAABAAAAQAAAAAAgBQAAAAAAAAQAAAAAAgBQAAAAAAAAg");
	this.shape_18.setTransform(-26.1,20.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFCC73").s().p("AAAAAQgBAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAgBAAAAQAAAAAAAAQAAAAAAAAQAAAAABABQAAAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIgBAAQgBAAAAAAQAAAAAAAAQAAgBAAAAQAAAAAAgBg");
	this.shape_19.setTransform(-26.4,20.1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFCC73").s().p("AgBAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAABAAQAAgBAAAAQAAAAABABQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAgBAAQAAABgBAAQAAAAAAABQAAAAAAgBQAAAAgBAAQAAAAAAAAQAAgBAAAAg");
	this.shape_20.setTransform(-26.4,20.5);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFCC73").s().p("AAAACQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAgBgBAAQAAgBABAAQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAABABQAAAAgBAAQAAABAAAAQAAAAAAAAQAAAAgBAAIAAAAg");
	this.shape_21.setTransform(-26,20.8);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFCC73").s().p("AgBAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAABAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAABAAAAQAAAAAAAAQgBAAAAAAQgBAAAAAAQAAAAAAAAQAAAAgBgBQAAAAAAAAg");
	this.shape_22.setTransform(-25.8,20.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFCC73").s().p("AAAAAQAAAAAAgBQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAQABAAAAAAQgBAAAAAAQAAABgBAAQAAABAAAAQAAAAAAAAQAAAAAAAAQAAgBAAAAQgBgBAAAAQAAAAABAAg");
	this.shape_23.setTransform(-26,20.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#B77602").s().p("AAAAAQAAAAAAAAQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAAAQAAABABAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAQAAABAAAAQAAAAAAgBQAAAAAAAAQAAAAAAgBQAAAAAAAAg");
	this.shape_24.setTransform(-22.4,22.9);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFCC73").s().p("AAAAAQgBAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAgBAAAAQAAAAAAAAQAAAAAAAAQAAAAABABQAAAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIgBAAQgBAAAAAAQAAAAAAAAQAAgBAAAAQAAAAAAgBg");
	this.shape_25.setTransform(-22.8,22.5);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFCC73").s().p("AgBAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAABAAQAAgBAAAAQAAAAABABQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAgBAAQAAABgBAAQAAAAAAABQAAAAAAgBQAAAAgBAAQAAAAAAAAQAAgBAAAAg");
	this.shape_26.setTransform(-22.7,23);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFCC73").s().p("AAAACQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAgBgBAAQAAgBABAAQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAABABQAAAAgBAAQAAABAAAAQAAAAAAAAQAAAAgBAAIAAAAg");
	this.shape_27.setTransform(-22.3,23.2);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFCC73").s().p("AgBAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAABAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAABAAAAQAAAAAAAAQgBAAAAAAQgBAAAAAAQAAAAAAAAQAAAAgBgBQAAAAAAAAg");
	this.shape_28.setTransform(-22.1,23);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFCC73").s().p("AAAAAQAAAAAAgBQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAQABAAAAAAQgBAAAAAAQAAABgBAAQAAABAAAAQAAAAAAAAQAAAAAAAAQAAgBAAAAQgBgBAAAAQAAAAABAAg");
	this.shape_29.setTransform(-22.3,22.6);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#B77602").s().p("AgBACQAAgBAAAAQgBgBAAAAQABAAAAAAQAAAAABAAQAAgBAAAAQAAAAAAgBQAAAAABAAQAAABABAAQAAAAAAABQABAAAAAAQAAAAgBAAQAAABAAAAIgCACIgBgBg");
	this.shape_30.setTransform(-16.5,22);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFCC73").s().p("AgCAAQAAgBABgBQAAAAAAgBQABAAAAAAQAAAAAAAAQABAAAAAAQABAAAAABQAAAAABABQAAAAAAABQgBADgCABQgCgBAAgDg");
	this.shape_31.setTransform(-16.5,21.4);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFCC73").s().p("AgBACQgBgBAAAAQgBgBAAAAQAAAAAAAAQAAAAABAAQAAgBABAAQAAgBAAAAQABAAAAAAQAAAAAAAAQAEACAAACIgDABIgCgBg");
	this.shape_32.setTransform(-17,21.9);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFCC73").s().p("AgBACQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAAAAAAAQACgEADABQABADgDACIgBACIgBgCg");
	this.shape_33.setTransform(-16.9,22.6);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFCC73").s().p("AAAADQgDgDABgCQACgBADADQAAAAAAAAQABAAAAAAQAAABgBAAQAAABAAAAIgDABIAAAAg");
	this.shape_34.setTransform(-16.2,22.5);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFCC73").s().p("AgDADQAAgDADgCQAAAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQAAABABAAQAAAAAAAAQAAAAgBAAQAAABgBAAQgCACgBAAIgCAAg");
	this.shape_35.setTransform(-16,21.8);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#B77602").s().p("AgCAAQAAgDACAAQADAAAAADQAAAEgDAAQgCAAAAgEg");
	this.shape_36.setTransform(-22.9,27.6);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFCC73").s().p("AgDABQgCgCADgCQACgDACADQAEAEgCAEIgBAAQgDAAgDgEg");
	this.shape_37.setTransform(-23.5,26.9);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFCC73").s().p("AgFAAQgBgBAEgCQAFgBADADQgBADgFACIgBAAQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBgBgBg");
	this.shape_38.setTransform(-23.4,27.9);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFCC73").s().p("AgDACQAAgFADgCQADACABAFQAAAEgEAAIAAAAQgBAAAAAAQgBgBAAAAQAAgBgBAAQAAgBAAgBg");
	this.shape_39.setTransform(-22.6,28.4);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFCC73").s().p("AgFAAQACgDAFAAQAEAAAAADQABAEgFAAQgFAAgCgEg");
	this.shape_40.setTransform(-22.1,27.7);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFCC73").s().p("AgDgCQACgEABABQAFAAgBAFQgCAFgCABQgEgDABgFg");
	this.shape_41.setTransform(-22.5,27);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AAEAJQAFgFAAgEQgCgFgHgEIgLgEQAAgBAIACQADACAFADQAGAEABADQAAAGgGAEIgHAEIAFgFg");
	this.shape_42.setTransform(-11.6,7.1);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("AgMAHQgBgBAFgGQAFgFAOgCQABgBAAABQABAAAAAAQAAAAAAABQAAABAAABQgBABgFAAQgIABgEACQgEADgBADIgCADQAAgBAAAAQAAAAAAAAQAAAAAAgBQAAAAAAAAg");
	this.shape_43.setTransform(-17.1,4.8);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#000000").s().p("AALAGQgHgGgEgBIgGgBQgIAAACgBQgBgDAIAAIAFACQAGACAHAHIAAACIgCgBg");
	this.shape_44.setTransform(-10.2,4.2);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#870000").s().p("AgNANQgJgEgLgSQANgGASAAQASgBASAOQgSASgSAAIAAAAIgBAAIgKgDg");
	this.shape_45.setTransform(-15.6,14.4);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#000000").s().p("AgNAOQgKgDgMgTIAAgBIABgBQAMgFAUgBQASgBAUAOIAAABIAAABQgTATgTgBIgBAAIgKgDg");
	this.shape_46.setTransform(-15.6,14.4);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#562301").s().p("AgYAaQgMgEgMgYQAWgMAagHQAXgGAZgCQgGASgPATQgPAVgYABIgBAAQgCAAgJgEg");
	this.shape_47.setTransform(-14.6,12.9);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#662C01").s().p("AgSAmQgKgDgKgSQgLgRgGgoQAIAJAdAKQAbAKAvgSQgCAIgIARQgIAPgOAPQgOAOgSABIgBAAIgJgDg");
	this.shape_48.setTransform(-15,11.9);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#000000").s().p("AgOAsQgFgBgIgFQgJgGgJgTQgJgSgEgmIABgBIABAAIAOAKQAOAIAZAEQAYAEAlgNIABAAIAAABIgIAVQgHASgQARQgPATgVAAIgBAAIgFgBg");
	this.shape_49.setTransform(-15,11.9);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#F9BE93").s().p("AAMAOQANgqgWhAQAIALAMAZQALAZABAfQAAASgHASQABADgOAVQgNAUgkANQAigjAMgsg");
	this.shape_50.setTransform(-11.3,7.5);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#F2B481").s().p("AgzBfQgEgDgKgWQgJgVgCghQgBgZARgiQADABAOgDQANgEATgVQgDAIAAAHQAAAEACACQAEAEAKgFIATgPQAQgOAGgQQAGAIANAaQANAbACAiQAAARgHATQAAACgKAQQgKARgbAPQgTAKgfAAIgYgBg");
	this.shape_51.setTransform(-15.5,7.6);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#000000").s().p("Ag3BjIAAAAQgCgBgKgTQgKgTgDghQgDgeAUgqIACAAQABACAPgEQAPgDAYgcIACAAIAAABIgGAOQgCAJACAEQADADAIgEQADgBARgPQARgOAEgRIABgBQAAgBAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIAOAWQAMAUAIAgQAIAdgMAiQABACgLARQgLASgdAPQgVALgfAAIgbgCg");
	this.shape_52.setTransform(-15.4,7.5);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#633D01").s().p("AgBAWQgIgGgCgKIATgcQgEALAAALQABAMAHAIQgEADgFAAIgEgBg");
	this.shape_53.setTransform(-16.1,0.8);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#633D01").s().p("AgeBGQgGgmAIgkQAHgmAVgdQADAjAGAiQAHAgASAhIgOAFQgQAEgNAAQgLAAgKgCg");
	this.shape_54.setTransform(-22,10);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#663F01").s().p("AiYBNQASg5AagfQAZghATgOQAUgOABAAQAXgLARADQAPADAKAHQAKAIAAABIABAAIABAAQAMgKAUAEQATAEAQAIIARAJQAYAVAGARQAGAQAAAHIgKgFQgVgggggSQghgSgmAMQgJgKgKgGQgJgHgPAGQgqAUgeAiQgeAhgRArQgDAHgIAIIABgFg");
	this.shape_55.setTransform(-20.4,-0.8);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#663F01").s().p("AgVg+QAiAaAKAmQgIAkgNAYQABhBgYg7g");
	this.shape_56.setTransform(-8.3,4);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#4C3100").s().p("Ag5B/QgcgKgQgNQgRgOgBgCQgBgEAAgNIAAgVIAAgBIgBAAQgGACgBALIgCAQQgOgLgFgKQgFgLABgIQAAgJABgBQATg3AZghQAZgiAUgOQATgOACAAQAWgLARADQAQAEAKAHQAKAHAAABIABABIABgBQAMgKATAFQATAEAQAHIARAJQAYAVAGASQAHARgBAHIgGgDIgEgCIgCAAIAAABIAAAAQADALAAALQgCAhgNAdQgOAegDAFIgdAMIgzAWIgcALQgQAFgPAAQgRAAgOgFg");
	this.shape_57.setTransform(-20.5,4.1);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#000000").s().p("Ag8CCQgdgKgQgOQgRgNAAgCIAAAAQgCgFAAgOIAAgSQgCAEgCAIIgBAQIAAABIgCAAQgYgTgBgRQgBgRACgCQAUhHAjglQAigmAYgJQAXgKAQADQAPAEAJAHQAJAIADADQANgKAaAFQAaAFAZAQQAdAbADAXQAEAXgCABIgFgFIgIgGQACAKAAAKQgBAigOAeQgOAegEAEIAAAAIhtAuQgQAEgPAAQgSAAgPgFg");
	this.shape_58.setTransform(-20.3,4);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#000000").s().p("AAAAcQgMAAgMgKIAAgBIAAgBIADgMQAEgJAJgLQAIgLAQgBQABAAAAABQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAQgBABAAAAQAAAAAAAAQAAAAgBAAQgUACgIARQgJAQAAAGQAKAIALABQAKABAEgBQABgJADgMIAFgLIACgBQAAAAAAAAQAAAAAAABQAAAAAAAAQAAABAAAAIgEALQgEANgBAIIAAABIgBABIgIABIgHgBg");
	this.shape_59.setTransform(-24.8,19.3);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#E5A423").s().p("AAAAbQgMgBgLgJIADgNQAEgIAJgLQAHgKAQgBIAEADQAEADAAAHIgBAGIgEAMQgEAMgBAJIgIABIgGAAg");
	this.shape_60.setTransform(-24.7,19.3);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#CE8C17").s().p("AAQAEQgLgHgJABQgKAAgBABIgCgBQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAAAAAQACgBALAAQAJABALAFIABACIgBABIgBgBg");
	this.shape_61.setTransform(-19.1,24.3);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#CE8C17").s().p("AgXAGQgBAAAAAAQAAAAAAgBQAAAAAAAAQAAAAABgBQAAgCAMgEQALgHAYAFIABACQAAAAAAABQAAAAgBAAQAAAAAAAAQAAAAgBAAQgXgHgLAHQgLAFABACIgBABIgBgBg");
	this.shape_62.setTransform(-19.4,24.1);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#000000").s().p("AgDAAIAAAAIABgBIAAAAIABAAQABABAEACIAAAAIAAAAIgHgCg");
	this.shape_63.setTransform(-25.5,33.2);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#DB9967").s().p("AgKA8IgBgDQAAgDAEgFIABgBIgBgBIgDgEQgDgGgBgHQAAgGAEgHIAAgBIgCgQIgCggQAAgQADgPIAEAAQgDAPAAAQIACAgIACAOIAAACQgEAHAAAGQAAAIADAEQADAFABAAIAAABIAAABQgEAFAAAEIAAACQADAEAEABIgBAAQgGAAgDgEgAAMA2IAAgBIABgBQAAgBAAAAQAAAAABAAQAAAAAAAAQAAAAABAAIAAABIAAABIgCADIAAAAIgEABIADgDg");
	this.shape_64.setTransform(-25,28.2);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#F2B481").s().p("AgPA8IAAgDQAAgDAEgFIAAgBIAAgBIgEgEQgDgFAAgIQgBgGAFgHIAAgBIgCgQIgCggQAAgQADgPIAIABIgBAcQgBAVAFASIAAAAIAAABIAIAHQAJAHAFALIACAIQAAAGgEAFQgFAHgGAAIACgDIAAgBIAAgBIgCAAIgFAHQgCAFgDAAQgHAAgDgEg");
	this.shape_65.setTransform(-24.5,28.2);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#000000").s().p("AgRA+IgBgEQAAgEAEgGQgFgDgCgPQAAgGAEgIIgCgQIgCggQAAgRADgQIAAgBIANACIAAABIgBAJIAAAUQAAAVAEARIAJAIQAJAHAEALQACAFAAAEQAAAHgEAGQgGAIgJAAIgBAAQgCAGgGABQgHAAgEgFg");
	this.shape_66.setTransform(-24.5,28.1);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#EFB245").s().p("AACAqQAEgdgGgbQgFgcAFgbIAAAbQABAQAEARQAJAZAAAWQABAMgFAIQgEAHgTAGQANgNACgQg");
	this.shape_67.setTransform(-14.9,24.6);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#CE8C17").s().p("AgEBIQgagDgPgNIAFghQAFgYAIgdQAIgdAKgNQgLArALAoQAJAqAuARQgPADgQAAIgTgBg");
	this.shape_68.setTransform(-22.5,24.8);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#E5A423").s().p("AgZBNQgbgDgQgMIAGgkQAFgaAJgeQAJgeALgKQALgHARAAQAQgBAQACIAUAEIAAABIABAaQABAUAFATQAJAZAAAWQABAMgFAIQgGAJgfAGQgQACgOAAIgWgBg");
	this.shape_69.setTransform(-20.3,24.3);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#000000").s().p("AgZBQQgcgDgQgNIgBgBIAAgBIAGghQAFgdAJgeQAJgfAMgLQAMgIASAAQATgBAQADIARADIABABIAAABIABAXQABAVAFAWQAQAugKAXQgEAGgLAEQgMAEgMADQgRACgOAAIgWgBg");
	this.shape_70.setTransform(-20.4,24.3);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f().s("#000000").ss(1,1,1,3,true).p("AAugEQgBABgEAEQgFAGgHABQgIAAgHgHQgIgEAAgBQAAABgGAGQgEAIgMAAQgLgBgJgFQgJgFAAAAQABAAARgEQAQgEAUgCQAVgBAQAHg");
	this.shape_71.setTransform(-19.4,17.1);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#F2B481").s().p("AgHAOIABgOIAAgLIAGgCIAIgBIAAAEIAAANIAAAKQgHACgDAAQgDAAgCgBg");
	this.shape_72.setTransform(-18.2,33.4);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#000000").s().p("AgCASIgGgCIAAgBIAAgBIABgPIgBgLIAAgBIARgEIAAABIAAAQIAAAOIAAABIAAAAQgGADgDAAIgCAAg");
	this.shape_73.setTransform(-18.2,33.4);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#E5AA4A").s().p("AgFABIACgBQACAAAHAAIAAAAQAAAAgKABg");
	this.shape_74.setTransform(-22.9,35.8);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#F2B481").s().p("AgHALIAAgLIABgLQAGgCAHABIAAAQIAAAIQAAAAgBAAQAAABgBAAQAAAAgBAAQgBAAgBAAQgCAAgHgCg");
	this.shape_75.setTransform(-22.2,33.4);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#000000").s().p("AgIANIAAAAIAAgBIAAgLIAAgNIAAgBIABAAIAHgBQAEgBAEABIABAAIAAABIAAALIAAAPIAAABIgBAAIgFACIgDAAQgCAAgGgDg");
	this.shape_76.setTransform(-22.2,33.4);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#E5A423").s().p("AgDAGIgCgXIAAgDQAAgBAAgBQAAgBABAAQAAgBAAAAQABgBAAAAQADAAAAADIADATIADAWQgBADgHAEIgBgUg");
	this.shape_77.setTransform(-14.5,18.9);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#000000").s().p("AgFAbIgCgWQgBgQAAgKQABgGADgBQAEABACACIAAABIAAAAIADASIAEAZIAAAAIgBAAIgDAEQgDAEgFABIgCABg");
	this.shape_78.setTransform(-14.5,19);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#F2B481").s().p("AgGAAIAAAAQADgDAEABQABACAEACIABABQgLgBgCgCg");
	this.shape_79.setTransform(-15.5,32);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#000000").s().p("AgEAJQgDgBgBgFIAAgEQAAAAAAgBQAAAAAAAAQAAAAABAAQAAAAAAAAIABABQAAAGACACIACAAQACgCABgEIADgFIADgEQAAAAAAgBQAAAAABAAQAAAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABQAAAAAAAAIgDAEIgDAFQgBAFgDACIgBABIgCgBg");
	this.shape_80.setTransform(-13.2,30.4);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#F2B481").s().p("AgLAzQgEgDAAgDQAAgCAEgDQAHgFADgMIAAgDQAAgJgCgOIgFgfIgEgSIABgBIAGAcQADATACAHQADAJAHAGQAFAGABAGIAAAAQgBAHgGAJQgHAJgDABIgBAAQgFAAgEgDg");
	this.shape_81.setTransform(-13.4,26.9);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#000000").s().p("AAAA5IAAABQgQAAgHgGQAAAAAAAAQAAgBgBAAQAAgBAAAAQAAgBABAAQAFgFAGABQABgDAEgCQAHgFABgLQAAgHgBgRIgFgiIgDgRIAAgBIAFgFIABACIACANIACAZQADAOACAFQAEAIAGAGQAHAHABAHQgCAHgGAKQgHAJgHACIgCAAIgBgBg");
	this.shape_82.setTransform(-14,26.8);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#FFCC73").s().p("AgLALQgCAAADgFIABgCIgCAAIgDgCQgEgCgBgBQAAAAgBgBQAAAAAAAAQAAgBAAAAQABgBAAAAQACgFAHgCQAGgCAEABIAKACQAGACADADIAAABIAAABQgDADgCAAIgEAAIADAAQAGAFACAFIgBABQgDABgMABIgFAAQgHAAgEgCg");
	this.shape_83.setTransform(-22.2,35.3);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#000000").s().p("AgNAMIgCgDIACgEQgFgBgEgEIAAgCIAAgDQAFgGAIgBQAIgCACABIAJABQAHACAEAEIABADIAAABQgDACgEAAQAGADACAGQAAAAAAAAQAAABAAAAQAAAAgBABQAAAAAAAAQgEADgOABIgDAAQgJAAgFgDg");
	this.shape_84.setTransform(-22.2,35.3);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#EFBA73").s().p("AgbAVQgLgCgBgBQgGgFgBgNQAAgMAIgHIACgBQgEAGgBAJQABANAGAFQABABALABQAMACATgEQAcgIAKgFIgBACQgCAEgpAMQgOADgKAAIgGAAg");
	this.shape_85.setTransform(-25.3,39.6);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#DD9E43").s().p("AgbAfQgLgCgBgBQgGgFgBgOQAAgLAIgGQAGgFAHgCQAFABAKAIQAKAGAFAVIABABIABAAIAOgDQAMgCAJgGIABAAIAAgBQAAgCgHgLQgHgNgQgJIAGgEQANgEAKAMQAFAKAAAMIgBALQgCAFgpALQgNADgKAAIgHAAg");
	this.shape_86.setTransform(-25.3,38.5);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#CC881B").s().p("AgHgGQgJgIgGgCIAEgBQAOAGALAaIAPgEIABAEIgRADQgGgRgHgHg");
	this.shape_87.setTransform(-25.1,38.6);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#CC881B").s().p("AgFgEQgJgJgFgCIABgBIADgBIANAMQAGAHAFAMQAGgBAEgDIABADQgGADgHACQgFgPgHgHg");
	this.shape_88.setTransform(-23.3,38.2);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#BA7B0C").s().p("AgHgFQgJgJgGgCIANgCIAFAAIABAAQACABAJAIQALAJAEAPIgRAEQgGgRgHgHg");
	this.shape_89.setTransform(-25.1,38.6);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#BA7B0C").s().p("AgFgCQgJgJgFgCIABgBIAKgFQAPAHAGAMQAGAKABAFIgNAFQgFgPgHgHg");
	this.shape_90.setTransform(-23.3,38);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f("#000000").s().p("AgdAgQgLgBAAgBQgIgHAAgPQAAgLAJgHQAGgFAGgBIACgBIAAAAQAKgCAHAAIAIgBIASgKQAOgFALANQAHAJAAANIgBANIAAAAIAAABIgMAFQgLAFgWAGQgOADgKAAIgJgBg");
	this.shape_91.setTransform(-25.3,38.5);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#E5AA4A").s().p("AAFACQgKgCAAAAIABgBQAGABACAAIACACg");
	this.shape_92.setTransform(-17.6,36.1);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f("#FFCC73").s().p("AgEAOQgMgBgEgCIAAgBQACgGAGgEIADgBIgEAAQgCABgDgEIAAgBIAAgCQADgDAGgBIAJgCQAFAAAHACQAGACADAEQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQgCABgDACIgGACIABACQAEAFgDAAQgEADgIAAIgEAAg");
	this.shape_93.setTransform(-18.3,35.6);

	this.shape_94 = new cjs.Shape();
	this.shape_94.graphics.f("#000000").s().p("AgEAPQgNAAgFgDIgBgDIAAAAQADgGAGgDQgFAAgCgDIAAgBIABgDQAEgEAIgCIAIgBIAAAAQACgBAJACQAIABAEAHIABADIgBACQgEADgFABIACAFQAAAAAAABQAAAAgBABQAAAAAAABQAAAAgBAAQgFADgJAAIgEAAg");
	this.shape_94.setTransform(-18.2,35.6);

	this.shape_95 = new cjs.Shape();
	this.shape_95.graphics.f("#CC881B").s().p("AgTAOIAAgCIAKAEQAFgPAGgHQAJgJAFgDIADACIABAAQgFADgIAJQgIAIgGAPIgMgFg");
	this.shape_95.setTransform(-17.2,38.6);

	this.shape_96 = new cjs.Shape();
	this.shape_96.graphics.f("#CC881B").s().p("AgWAQIABgDIAOADQALgcANgGIAGABQgFACgJAJQgJAHgFASIgRgDg");
	this.shape_96.setTransform(-15.4,39.1);

	this.shape_97 = new cjs.Shape();
	this.shape_97.graphics.f("#BA7B0C").s().p("AgTAPQABgFAIgKQAHgNANgHIAJAFIABABQgFADgIAJQgIAHgGAQQgHgCgFgEg");
	this.shape_97.setTransform(-17.2,38.5);

	this.shape_98 = new cjs.Shape();
	this.shape_98.graphics.f("#EFBA73").s().p("AgBASQgVgFgLgFQgKgFgCgCIAAgBQAJAFAfAIQATAEAKgCQALgBABgCQAFgFABgNQAAgIgDgGQAHAHAAAMQgBANgFAGQgBABgLABIgIABQgJAAgMgDg");
	this.shape_98.setTransform(-15.4,40.2);

	this.shape_99 = new cjs.Shape();
	this.shape_99.graphics.f("#DD9E43").s().p("AgBAeQgVgFgLgFQgKgFgCgCIAAgIIABgOQABgJAEgFQAKgNANAGIAIAEQgRAJgIAOIgIAOIAAAAIAAABQAKAGANADIAPACQAAgCAFgQQAIgOARgGQAGACAGAFQAHAHAAAKQgBAPgFAGQgBABgLABIgIABQgJAAgMgDg");
	this.shape_99.setTransform(-15.4,38.9);

	this.shape_100 = new cjs.Shape();
	this.shape_100.graphics.f("#BA7B0C").s().p("AgWAQQAFgQALgJQAKgJABAAIAAgBIAFABIANACQgFACgJAIQgJAHgFATIgRgEg");
	this.shape_100.setTransform(-15.4,39.1);

	this.shape_101 = new cjs.Shape();
	this.shape_101.graphics.f("#000000").s().p("AgCAgQgXgGgLgFIgLgHIgBAAIAAgBIAAgOQABgOAGgJQAMgOAOAGIARALIAIABQAPgBAPALQAJAHAAAMQgBAPgHAHIAAAAQAAABgLACIgIABQgKAAgOgDg");
	this.shape_101.setTransform(-15.3,39);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_101},{t:this.shape_100},{t:this.shape_99},{t:this.shape_98},{t:this.shape_97},{t:this.shape_96},{t:this.shape_95},{t:this.shape_94},{t:this.shape_93},{t:this.shape_92},{t:this.shape_91},{t:this.shape_90},{t:this.shape_89},{t:this.shape_88},{t:this.shape_87},{t:this.shape_86},{t:this.shape_85},{t:this.shape_84},{t:this.shape_83},{t:this.shape_82},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(50));

	// Layer 2
	this.shape_102 = new cjs.Shape();
	this.shape_102.graphics.f("#000000").s().p("AgIgFIgBgCIAEAAQAEgBABgBIAEgCIAEACIgGgOIAHgDIAAAEIgEAxIgFAAQgFgWgDgKgAgCgDIACAQIACgLIABgGIgFABg");
	this.shape_102.setTransform(-87,9.4);

	this.shape_103 = new cjs.Shape();
	this.shape_103.graphics.f("#000000").s().p("AhnGbIgDAAIgCgGIgDADIgCAAQgIgDgGgDIgCgDIABgCIAGgJIAMgPIgFgEIgCgCIABgDIASgaQAPgWAQgQQgCgDgBgDQAAgDACgCIAEgDIgBgUIgCgiIAAgXQgFACgEAAIgFgCIgBgBQgEACgGgCQgFgEgCgGIgCgJQgIAAgIgNQgFgHAAgGIABgEQADgGACAAIABgBIgQgkQgIgSgCgLIAAAAIABgEQgMgLAAgGIABgCQABgEAEAAQgCgDAAgEQAAgGADgCQAEgDAGAAIAOABIALgcIAJgUQAEgIAGgFIgGgEIgDgBIAAgEIAGgLQAFgKAFgGIAEgCQgPgQgPgaQgQgZgJgkQgdgMACgRIAAgEQACgIAHgFQgDgVAAgVQAAgPAFgOIgFgEIgEgDIAAgDQACgNAFgCIADgCIABACIAGAJQAXgpArgSQAogOAbAAIAJgBQANgBAKgEQAogSAPgNIALgHIABgBIABAAIAHABQAFADAHAFQAKAIACAZIgBANQgEASgTAPQACAHAAAMIgBAYIgBADIAAAFIABAHIAAADQAKAGAGAGIAHAHIAAABIAAABIABAKQgBAjgGAOQgFAOgBAAIgBABIgCAAIgFAAIABAGIAFAQQAFAQABAMQAAAGgCAGQgGAUgYAPQgYAQglAHIgKADQACADAAADQAAAEgDAIIgCALIgBAFIACACIAEAIIAKAYQAGAMAGAJQAIgDAFADQAGAFAAAIQAGgBAFACQACACAAADIAAABIAAADIASAAIARAAIAQgQIARgOQAGgDAIADQAIACAFADIACABIgJARIgBAAIgHAEIAEAHQAHAJACAIQAAACgDADQgFADgIgCQgHgDgHgEQgFAFgQgBIgXADIgjACIgDAEQgGAFgFABQADAPAAAMQAAAMgDAKIAAAEQgBAOgEACQgCAIgJAIIAOAvQAHAaADAQQAEATABAaIAAAkIAAACQANAFAGABQACgIANgCQAIgBAFAFQAGAGAAAJIAAACIgBACIgCABIgQAGQgQAGgVABIgCABIgDAAQgCACgNgBIgEAAIAAgEIABgHQAAgHACgJQgHgBgEgDIgBgCIAAgCIAFgtIADgbQgFgCgBgGQABgFAFgDIgPgsQgGgWgEgHQgGABgTAAIgEAaIgEAoIgDAiIAAABIgBABIgJAPIgRAfIgNAaIgCACIgDAAIgEgBIABAAIAFABIAEABQAGgFAOACQAHADACAHQADAJgEAJIgBABIgCAAIgNADIgTABIgRgBgAhoGQIACAGQAoAAAGgDQACgDAAgEIAAgFQgCgFgFgCQgFgBgFABIgGADIgBAAIgNgCIAAAAQgDgCgCgGIgBgEIAFABIAHACIAOgZIARgeIAJgRIADglIAFgqIADgXIAAgDIADAAQAXABAFgCIACAAIABABQACAGAGASIAMAjIAGAUIABACIgCABQgGAEABAAQAAABABAAQAAAAAAABQABAAAAABQABAAABAAIABABIABABIAAACIgDAeIgFArQAEADAGAAIADAAIgBADQgDARABAHQAIAAADgBIABgGIAAgFIADAFIADAFQATgBAOgFIARgGIAAgBQAAgHgEgEQgDgEgGABQgKADgBAFIgBACIgCAAQgKgBgOgFIgGgDIAFgCIAAgCIgBgkQAAgZgEgTQgDgQgIgbIgOgvIAAgCIABgBQAKgHACgIIAAgBIAAAAQACAAACgNIAAgEIAAgBQADgJAAgMQAAgMgEgRIgBgDIAEAAQAEABAGgGIAFgFIABAAIAkgCIAXgDIAAAAQAQAAAEgEIABgBIABABQASAKAFgDIAAgCQgBgGgGgHQgGgIAAgCQADgGAIgCIAFgKQgMgHgIADIgOAMIgSARIAAABIgCAAIgUAAIgUAAIgEAAIACgDIABgFIAAgBQgDgCgHABIgDABIAAgDQABgGgFgGQgFgBgEADIgCABIgCgCQgGgJgHgOIgLgZIgFgLIgBAAIABgGIACgMIADgLIgEgHIgDgDIATgEQAjgHAXgOQAYgPAFgSQACgJgBgIQgBgJgEgLIgDgJIgCgIIgDgNIAEABIAHAAQACgCAEgNQAFgOAAgeIAAgJIgGgHQgGgGgLgGIgEgCIAEgCIAAgCIgBgGIgBgBIACgJIABgXQAAgPgCgEIgBgCIACgCIAAAAQATgNACgQIACgNQAAgPgIgKQgMgMgFAAIgLAHQgQAOgoASQgLAEgOABIgJABQgaAAgnANQgqASgXAqIgCAEIgCgCIgIgKIgCAJIAEAEIADADIACABIgBABQgFAPAAAPQAAAWADAUIABACIgCABQgGAEgCAHIAAADQgBAOAaAKIABABIABABQAJAmAQAaQARAaAPAQIADADIgKADQgEAEgEAIIgGAMIAJAFIADACIgDACQgHAGgEAIIgKAVIgLAdIgBACIgCAAQgSgDgDADQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAABIACAGIADAFIgGABIgCABIAAAAQAAAEAKAKIADADIgCACIgBACQAEAQAXAxIABADIgDABIgDACIgCADIAAACQAAAEAEAHQAHALAGgBIACAAIABADIACAJQACAFADADQADAAADgBIAAgBIABAAQABAAAAAAQABAAAAABQABAAAAAAQAAABAAAAIAAABIAEABIAGgCIAGgFIAEBaIgBABIgEADIAAABQAAABADADIACACIgCACQgPAOgPAVIgUAdIAHAEIAEABIgDADQgGAFgGAIIgIALQADACAIACIAEgEIADgEIABAGg");
	this.shape_103.setTransform(-76.4,-0.4);

	this.instance = new lib.Symbol13("synched",0);
	this.instance.setTransform(-92.5,-41.4,0.261,0.261);

	this.shape_104 = new cjs.Shape();
	this.shape_104.graphics.f("#000000").s().p("AAWBJQgHgCgZgBIgJABIgCABIgBgDIgDgJIgCgCIAGgBIAAgIIgBgkIgDgWIAAgBIACgBIADgEIAAgBIgDAAIgDAAIAAgDIAEgYIAFgZIAAgDIADAAQARACARgDIAEgBIgBAEIAAADIAAAEIAAAFIgBAEIAAAFIAAAEIAAADIAAADIAAADIgBAEIAAAIIAAAEIAAAEIAAAFIAAAGIAAAEIAAALIgBAEIAAAGIAAAIIAAACIAAAXIAAAFIAEABIADAAIgDAOgAAUBEIABgDIgEgBIgCgBIAAgFIAAgEIAAgXIAAgFIAAgEIAAgGIAAgFIAAgDIAAgCIAAgDIAAgDIAAgBIAAgCIAAgGIAAgHIAAgCIAAgDIAAgCIABgDIAAgSIAAgEIABgHIAAgCIAAgFIAAgCIAAgCQgPACgOgBIgFAWQgDANAAAKQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAIAAAAIACADIAAAAQAAAEgFAEIACAXIABAiIgBAKIAAACIgCABIABAEIAIAAQAVAAAJACg");
	this.shape_104.setTransform(78.6,29.6);

	this.shape_105 = new cjs.Shape();
	this.shape_105.graphics.f("#000000").s().p("AgcFYIgCgBIgBgCIAAgFIAAgCIgBAAIAAgBIAAAAIgBABIgTADQgRAEgagCIgDgBIAAgDIgBgHQABgHAFgHQAIgKATAAQAXABAJABIABgCIgBAAIgCgBIAAgDIABgTIACggIABgVIACgXIAFggQgggGgKgMQgOgJgBgGQgBAFgFAGQgGAGgKgBIAAAAQgCAAgFgGIgCACQgIAEgHgEIgBgBIgBgBIgBAAIAAgBIAAAAIAAAAIADAYQAGAhADA0IABAUQAAAegDANQgDAMgBABIAAABIgBAAQgFAEgIADQgJACgKgIIgCgBIABgDIAIgbQAGgaABgqIgBgWQgDgngGgUQgDgOAAgHIABgHIADgFQgIgLAAgGQACgHAOgLQANgKAGgCQAEgBAGABQABgFACgEQAFgFAIgBQAGgBAHAEQAMgTAGgWQAHgWAEgRIAFgWIgBgDQAAgDACgFQgGgFAAgEQgCAAAHgPQgZgLgagSQgagSgSgWQgRgVgBgVIAAgCQABgVAMgPQALgPAMgJIAAAAIgCgDIgBgDIAAgCQADgEADABIAEAAQABAAgBgJQgBgFADgCQAEgEANACQAEgMAGgLQAHgKAHgEIAAgDQgBgLAEgGQAEgHABAAIACgCIACACQAJAHAAADIAAADIgCABIgLALQAFAAADADQAkghAkABQADgCAfALQAeAMAgAxQAIgBATACQASADAQAPIABABIgBABIgCAKQgBAIgEAGIAGAOQADAKAAAIQAAAHgEACQgHABgGgFQgBAHgDAKQgEAJgHAFQgDAkgZAUQgSAOgaAKQAEAHAAANIAAAEIAAABIgCACQAKAJAIALQANAVAFAfQAEAhAAAfQAAAWgBAPIgBARIAAABIgBABIgIAGQgGALgcAMIgEAZQgDAQgBAPQAEADAAADIAAABQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAIgEACIAAAFIADAbQABAQACANIAAADIABABIAAACIABAEIgDABQAFAIABARIAAADIgEABIgHABIgOABIgDAAIAAgBIgBAAIgBABIgSAEQgLACgLAAIgUgBgAgcFEIABAFIACAAIgBADIAAAEIAAADQAXABAOgCQARgDACgBIAEgFIADgEIAAAEIABAFIASgCQgBgSgFgHIgBgDIAEgBIAAgBIgBgCIAAgCIgEgeIgCgbIAAgDIAAgGIACgBIADAAIgEgEIgBgBIAAgBIAEghIAFgaIABgCIABAAQAbgMAGgKIAAgBIABAAIAHgFIABgRIABgkQAAgfgEggQgEgegNgUQgIgMgLgJIgCgBIAEgFIAAgDQgBgOgEgGIgBgDIADgBQAagKATgPQAXgSADgjIAAgBIACgBQAHgFADgKIAEgPIABgGIAFAEQAFAEAEAAQAAAAAAgBQABAAAAgBQAAAAAAgBQAAgBAAAAQAAgHgDgKIgGgOIAAgCIAAgBQADgDACgHIACgLQgQgOgSgCQgTgCgEABIgCABIgBgCQgegwgegLQgdgMgDACQgigBgkAhIgCACIgCgCQgDgDgDAAQgDAAgDACIgBAAQgNAKgHAaIgBACIgCAAQgQgCAAACIAAACQACAJgDAEQgEADgEgBIgBAAIABABIACADIABABIgBAEIgBABQgMAIgKAOQgLAOgCAUIAAACQABAUASAVQARAVAaARQAaASAYAKIADACIgBACQgHAOABABQAAABAGAFIABACIAAABIgDAIIABACIAAABIAAABIgFAWQgEARgHAYQgHAXgNAUIgBACIgCgBQgIgEgEAAQgGAAgEAFQgCADgBAFIAAADIgDAAQgGgCgEABQgFACgMAJQgLAKgDAEQAAAEAIAMIABACIgBABIgDAFIgBAFIAEAUQAFAUAEAnIAAAXQAAAngGAaQgGAagDAFQAHAFAHgBIALgGIADgNQACgMABgbIgBgVQgDg0gGggIgEgcQAAgJAEgDIABgBIAFAAIgBAGQgBAEABACIAAABIABAAIABABIABABQAEACAGgDIADgDIADgDIABAEQADAGACAAQAHAAAEgEQAGgHgBgDQgBgEgFgFIgCgBIACgCIACgEQABgEAAgFIAAgEIgBgEIAEABIAGABIADgBIAAADQgCAcACABQgCACAQALIABABQAJALAgAHIACAAIAAACIgHA5IgBATIgBAfIgCAVIACAAIACABIgDAMIgCAAQgHgCgbgBQgQAAgHAJQgFAHAAAGIABACQAWACARgDIATgDIADgFIADgFIABAFgAhUCDIAAgJIAAgMIgBAAIABACQAAAGgCAFIgCADIAEAFIAAAAgAhLk/IAAABIAKgKQAAgDgEgDQgFADgBAMg");
	this.shape_105.setTransform(77.5,5.2);

	this.instance_1 = new lib.Symbol10("synched",0);
	this.instance_1.setTransform(69.6,-28.7,0.261,0.261);
	this.instance_1.alpha = 0.699;

	this.instance_2 = new lib.Symbol9("synched",0);
	this.instance_2.setTransform(61,-29,0.261,0.261);

	this.shape_106 = new cjs.Shape();
	this.shape_106.graphics.f("#000000").s().p("AA8FvIgXgFQgMgEABgHIAAgBIAAgBQgBgFAJgGIAAgBQABgIADgHIAGgLIAAgKQghADgkgJIgBANQAGAGACAMIAAABQAJAHgBAHIAAAEIgCACQgoAUggABQggAAgTgGQgTgGgBgBQgIgEgCgIQgBgMAFgKIAHgMQAOgSAXgCQAVgCAOAKIAJALQAWgEADgEIAAgFIAAgHQgbgJgDgCQgCAAgCgEQgDgEAAgNQAAgJACgRIgGgFIgDgCQgDgDAAgEIAAgBIAAgBQABgMAFgMQgDgCgCgEIgBgDIAAgBQABgFACgCIALgZIALgfIAFgPQAEgTAAgSIgBgSIAAAAQgFgJAAgJQABgRAIgNQAIgPAHgIIAAgHIgHgCIgEgBIgFgBIgFgBQgXgFgWgLQgagMgPgKIgQgLQgKgMAAgTQABgVAFgTIAFgRIAGgRIgBgBIACgIIAEgVIAAgQIAAgLIAAgBIABgJIAAgBQgDgBgCgGIAAgBQAAgIAMgLQAMgfAOgMQAOgMAEAAQADgDATgJQATgKAggEQAegFAqALQAUAFAUAKQABAAAKAHQAKAGAMANIAGAIIADgDQAEgDAJACIADABIAAANIABAOIACADIAEgOIACgJIACgBQANgBABAHIABABIgFAOIgFAQQAUAXAAAbQAAAIgCAJIgIAPQgIAPgOAOIAAASIABARIgNgFIAAgIIgBgNQgNAHgNgBQgNARgQAJQgJAegaAhQACAGAAAHIgBALIABABQAKAIAIAMIADAEIADAEQATAWAKAcQAIAVADAVIgBAIIgDAnQgCAYgDAUQgCAwgCAeIAAABIgCAcIgBACIgBABIABAAIgCABQgJAEgKACIgBAAIgBAAIAAAGIAAACQAPAEALAAIADgDQANgNASAAQARABANALIAAAAQAUATgCANQgCANgCAAIgBABQgcAQgeACIgSAAQgUAAgQgCgAAyE5IgBABIgFAJQgFAHAAAIIABADIgCABQgHADAAAFIAAAAQgCACAJAFIAXAFQAWADAdgBQAegCAbgPQABgBACgKQABgKgRgRQgMgKgPAAQgQgBgLAMIgEAFIgCAAQgMAAgTgGIgBAAIAAgCIAAgEIgBgHIAAgDIAGgBIABAAQAJgCAIgEIACgNIABgOIAAAAIAAgBIAEhOIAAgBQADgUACgYIADgmIAAgEIAAgEQgCgUgIgVQgJgagTgWIgGgIQgIgMgJgHIgCgBIgCgBIABgCIABgMQAAgHgDgFIgBgCIACgBQAbgiAJgdIAAgBIABgBQAPgJAOgRIABgBIABAAQAOACAOgJIAEgDIAAAMIABAOIACABIAAgRIAAgMIAAgBQAPgOAHgOIAIgPQACgIAAgIQAAgYgTgXIgBgBIAEgPIAFgPQAAgDgHAAIgDANIgCALIgCAEIgLgJIAAgMIAAgOQgHgBgBABIgBABIABAIIAAAIIgFgIIgLgOQgMgNgJgGIgKgGQgUgKgTgFQgqgLgdAFQggAFgSAJQgTAJgBACIAAAAIgBAAQgDABgNALQgOALgLAfIAAAAIgBABQgMALABAEIAAAAIABADIAEgEIADgDIgBAIIgDAOIAAABIAAALIAAAQIgEAWIgBAFIABAAIgBACQgCAMgEAIIgFARQgFAQgBAWQAAARAIAKIAQAKQAPAKAZAMQAWALAXAFIAEABIAFABIAOAEIABABIABAKIAAABIgBABQgHAIgIAOQgIANAAAQQAAAIADAHIABACIAAABIABASQAAATgEATIgGAQIgLAfIgKAaIgBAAIgBAEIAAACQABACAEACIACABIgBACQgGAQAAAJIAAABIAAAEIADACIAHAFIACABIAAACQgDASAAAKQAAAOAEABIAfAMIACAAIAAASIAAAAQgDAFgJACIgTAEIgBAAIgBgBQgFgGgEgEQgMgKgTACQgVACgNAQIgGAKQgFAKACAKQABAFAGADQAAABATAGQASAGAfgBQAfAAAmgTIAAgCQABgFgHgFIgCgBIAAgDQgBgJgHgHIgBgBIAAgBIACgSIAAgDIADABQAlAKAigDIAFgBg");
	this.shape_106.setTransform(41,5.2);

	this.instance_3 = new lib.Symbol11("synched",0);
	this.instance_3.setTransform(23.6,-31.4,0.261,0.261);

	this.shape_107 = new cjs.Shape();
	this.shape_107.graphics.f("#000000").s().p("ABEF7QgYgCgIgFQgJgGAAgCIAAgBIgCgIQAAgDACgCQACgEAFAAQgBgMAPgTIgDgJQgcAHgXABIAAABQANATgBAMQAFAAACAEQACACAAADIgCAJIAAAAIAAAAQAAACgJAGQgGAFgYACQgZABgcgFQgbgEgOgKIgCgBIAAgCIACgKIAAABIABgDIgBABQACgJAEgJQAFgKAHgHQALgIANACQANABAJAJQAEgDAGgCQgTgDgQgJIgCgBIAAgCIADglIAHhJQgSABgMgEQgGgEgGgGQgFgIgCgHQAAgIAFgEQAFgDADAAIABAAQADABAEgFQgNgRgIgUIgGgDIgCgBIAAgDQABgIAHgVQAIgVAKgWQAKgWAJgJQgVAAgKgJQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAgBIACgDIAEgCQADgDABgEIABgCQAAgEgGgGIgGgGQgMgLgSgTQgRgUgOgcQgNgdgBgkQgBgYAJgbQARgwAVgUQAVgUASgDQARgEAGACQAEgFAOgLQAPgKAXgIQAZgKAkAGQAlAGAuAmIABADIAAABQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAIgDABQAJAIALAWQAMAVABAkIAAABIgCAXQgGApgPAjQgQAjgNAXIgJAQIgGALQABAHAGADIAJAEQAAAAABAAQAAABABAAQAAABAAAAQAAABAAABIAAAAIgBAFQgCAFgFAEIAJAJIADgBIAJgFIAEgCIABAAIACgBIgBAAQAKgDAGACIAFACIABAAQAAgIAIgJQAIgHAPADIAGACIgEAFIgEAGIAFgDIACgBIAEAGIgCABQgCAAgDANQAWALAEAiIAAAKQABAcgRAeIAAAAIgBACQgPAYgSAIQgTAIgOgBQALBNAAAuIAAAGIAAAGIAAACIgCABIgQAHQgPAGgYAHIABAHIAPABQAJACAJAFQAIgJANgBQAOgCAKAIQAIAHAEAKQAEAJACAJIgBgBIABADIAAgBIACAKIAAACIgCABQgOAKgbAEQgXAEgVAAIgJAAgAAfFgIAAADIABAHQAAABAHAFQAIAEAVACQAYABAbgEQAagFANgIIgBgJIAAgBQgDgSgOgOQgIgGgLABQgMABgIAJIgCABIgCgBQgIgFgLgCIgOgBIgCAAIgDgQIACAAQAXgHAPgGIASgIIAAgFIAAgFQAAgugLhPIgBgDIADAAQANABASgHQARgHAPgVIgBgBIACgCQASgdgBgcIAAgJQgEgigVgIIgCgBIAAgCIADgKIgCADIgEAJIgCgMQABgKAEgFQgKgCgGAFQgHAJABAHIAAADIgJgBIgBgBIgCgBQgFgBgIACIgBABIgBAAIgDABIgJAGIgBAAIgHABIgQgPIAEgCQAHgFABgGQgEgBgHgEQgGgFgBgIQAAgEAHgKIAJgPQANgXAPgjQAPgjAGgoIACgWIAAgBQgCgmgNgWQgMgVgIgFIgDgDIAEgBIAGgCQgsgkgkgFQghgGgYAJQgYAIgOALIgRAOIgBABIgCAAQgDgCgRADQgQADgVATQgVATgRAvQgIAbAAAXQABAjANAcQAOAbARATQARAUALAKIAHAGQAHAHAAAHIAAADQgEAJgGADQAKAHAWgBIAHAAIgEAEIgFAFQgIAIgKAVQgJAVgIAVQgHAUgCAJIAHADIAAABQAJAVAOARIABACIgBABQgHAKgGgCIgBAAIgEACQgEADABAEQADAOAMAHQAGADAJAAIAQAAIADAAIAAADIgHBGIgEApQAVALAbACIAAAFQgNABgMAHIgCABIgCgBQgIgIgMgCQgLgBgIAGQgOAOgDASIAAABIgBAJQANAIAbAFQAaAEAYgBQAVgCAFgEQAIgFAAgBIABgHIAAgDQgBgBgFAAIgDABIAAgEQABgFgBgIQgCgJgJgJIgBgBIADgHIACAAQAXgBAegHIACgBIAGAQIgBABQgJAJgCAJQgDAIABAFIAAAEIgDgBIgCAAQgBAAgBAAQAAAAgBAAQAAABgBAAQAAAAAAAAg");
	this.shape_107.setTransform(-51.2,3.6);

	this.instance_4 = new lib.Symbol7("synched",0);
	this.instance_4.setTransform(-70.4,-34.1,0.261,0.261);

	this.shape_108 = new cjs.Shape();
	this.shape_108.graphics.f("#000000").s().p("AgGErIgSAAIgDAAIgBgEIgBgQQAAgLACgFQgDgCgBgDIAAgCQABgEACgDQgDgCAAgDIABgDQABgFALgEIAAAAIgIgCIgCAAIAAABIgDAAIgNABQALAEABAFIABADQAAADgDADQACACABAEIAAACQgBADgDACQACAFAAALIgBAQIgBAEIgDAAIgSAAIgjAAQgTgBgOgDIgCgBIAAgBQgCgCAAgNQgBgMALgJQAKgFAMACQALADAFACIADgCQgCgCgBgDQABgFAEgCQgCgCAAgDIAAgBIABgEQADgDAGgBIgLgBIgDAAIAAgDIgDgPQgCgPAAgQIAAgBIgEgCIgCgBIAAgCIAEgRIAIggIgMAQIgGAJIAAAHQAAANgHAGIACAJQAAAGgDAEQgDAFgEAAQgEAAgGgNQgDALgFAEQgDACgDgBQgFgBgBgLIADgLQgPAIgHgEIgBgEIAAgBQACgHALgJQgJgGgCgLIAAgBQABgHADgBQADgCAHAEQAFADAJABQAPgHAGAAIALgQIANgTIgBAAIgCgCIAAgDQAAgBAGgNQAHgOATgLIgIgEIgNgGQgQgIgRgKQgSgLgNgNQgWAAgMgIQgLgJgDgMQgFgWARgGQAKgDAKAFIAAgFQgIglgIgRQgHgSgGgFIgMAFIgHADIgJAFIADgJQAEgMAHgKIALgRIgPABIgIABIADgHQAMgXAMgOQAMgOAHgGQgPgKgOgHIgOgHIgEgCIACgEQALgQAJgEQAJgEABAAIACAAIACACIANAUIAOAUQArgqAtgHQAsgIAVADIASABQAUACASgDIAVgEIAKAAIAPgBIgNAIQgQAMgEAIQA3AMAdAUQAcAUAKARQAKASAAAEIADAJIgEgCIgEgCIAAABIgGgDIgRgEIgPgDQAlAqALAiQALAigBAJIACAJIgIgFQgSgKgMgDIAEANIADAJIgEAAQgsALgSASQAKgCAKAEQAOAJgIATQgFALgOAIQgNAHgXgFQgOAOgUAIQgUAJgUAEQAPANAHAYIABADIgDACIgCAAQAFAQAIAkIAFAGQARATAAAHQAAABAAABQAAAAAAABQAAAAgBABQAAAAAAAAQgEAEgOgIQgFAMgIABQgDAAgCgCIgBgCIACgFQgDABgCgBIgBAAQgCASgDAPIgBADIgCAAIgRADQAGAAACADIABAEIAAABQAAADgCADQAEABABAFQAAADgDACIADACQAFgCALgDQAMgCAKAFQALAJgBAMQAAANgCACIAAABIgCABQgOADgTABIgZABIgIgBgAgZDQIABAIIAAAJIAJACIADAAIAAAJIgCABQgLADgBADIAAABIADACIAEADIgEADIgDAEIAAAAQAAABABAAQAAABAAAAQABABAAAAQABAAABAAIACACIgBACQgCADgBANIABAPIAiAAQAbAAAUgEIABgLQABgLgIgGQgKgFgMADIgNAFIgBAAIgBAAIgIgGIgDgCIADgCIADgDIgDgCIgFgCIADgDQACgCABgEIAAgBQABgBgJgBIgDAAIAAgJIADAAIATgDQADgPACgSIAAgCIACAAIADgBIACgBIABABIAEgBIAIgBIgDAFIgCAGQAFgBAFgLIAAgEIAEACQANAIAAgCQAAgDgFgHIgLgNIgGgGIAAgBQgJgogFgOIgBgDIAFgCQgGgYgRgMIgFgDIAGgCQAUgEAWgIQAWgJANgPIABgBIACABQAVAEAMgGQANgGAEgKQAHgPgLgGQgMgGgPAKIgEADIAAgHIABAAQAIgLASgLQARgMAdgHIgEgOIgEgKIAFABQALACAXAMQAAgMgMgiQgMghglgoIgFgFIAHAAIAWADIAMAEIAAgBIAEABIAFACQgBgMgagcQgbgdhMgQIgDgBIABgDQACgHASgQQgKABgQADQgTADgUgCIgTgBQgUgCgsAHQgtAIgqAqIgCACIgCgDIgNgTIgPgXQgGgBgTAWIATAJQANAHAOAKIACACIgCACQgGAEgMAOQgMAOgNAXIATgBIAFAAIgDAFIgKAPQgIALgFAMQAIgEALgDIACgBIABACQATATAMA9IAAAAIgBAPIgDgDQgKgGgKADQgMAEAEARQACALALAIQALAHAUAAIABAAIABABQANANARAKQARAKARAIIAeAPIgFADQgSAIgHAMQgIAMAAAFIAEACIgBACIgPAXIgLAQIgBABIgBAAQgHAAgPAHIAAABIgBAAIgJgCIgIgEQgBAAgBgBQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAAAABQgBAAAAABQAAAAAAAAQAAABAAAAIAAABQADAKAJAEIAEACIgFADQgNALAAAEIAAAAQAAADAUgLIAHgDIgDAJQgDAHAAAGQgBAFADACIACgBQACgBABgGIADgJIADgLIAEAKIADAIIAEAGIACgCQACgDAAgEQAAgEgCgEIgBgCIACgCQAHgEAAgMIAAgGIgBgCIAdgoIAFADIgLAlIgFAYIAFACIAAACIAAAEQAAANACANIADARIAIABIAGABIADAAIAAAJIgDAAQgLABABABIAAABIADAEIADAEIgDACIgFADIADADIADACIgDACIgIAGIgBAAIgBAAIgNgFQgLgDgKAFQgJAHABAKIABALQAUAEAbAAIAkAAIABgPQgBgNgCgDIgBgCIACgCQABAAABAAQAAAAABgBQAAAAAAgBQABAAAAgBIAAAAQAAgBgBAAQAAgBAAAAQAAAAgBgBQAAAAgBgBIgDgCIADgDIADgDIAAgBQgBgDgKgDIgDgBIAAgJIADAAIAOgBIACgKIABgIgAC6i4IAAAAIAAAAgAC6i4IAAAAIAAAAg");
	this.shape_108.setTransform(12.2,10.6);

	this.instance_5 = new lib.Symbol12("synched",0);
	this.instance_5.setTransform(-9.2,-19.1,0.261,0.261);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_5},{t:this.shape_108},{t:this.instance_4},{t:this.shape_107},{t:this.instance_3},{t:this.shape_106},{t:this.instance_2},{t:this.instance_1},{t:this.shape_105},{t:this.shape_104},{t:this.instance},{t:this.shape_103},{t:this.shape_102}]}).wait(50));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-92.8,-41.6,187.1,84.1);


// stage content:
(lib.sisterCJS = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.girl();
	this.instance.setTransform(100,100.8);

	// Layer 8
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,255,255,0)").s().p("AvnPnIAA/OIfOAAIAAfOg");
	this.shape.setTransform(100,100);

	this.addChild(this.shape,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(100,100,200,200);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;