(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 550,
	height: 400,
	fps: 12,
	color: "#FFFFFF",
	manifest: []
};



// symbols:



(lib.flower = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("Al+IEQgagQAxhCIA8h/QAVgwB6hbIACABIAmADQBAgFAngIQgKAlAAAxIgBAYQAABfhkA/QhPAyhNAcQgwARgcAAQgRAAgJgGgAC+GJIgFgDQgOgIgHAAQgEAAgZgXIgJgHQgggdgIgOQgBAAAAAAQAAgBgBAAQAAAAgBAAQAAAAgBAAQgOgdgHgVQgHgUAAgLQAAgMgKgXQgKgXAAgaIAbgMIABABIAXgNIAsgWQASgIASgQQAZADAZAJQAyAQBFAeQCbBEAAA6QAABVh2AqQglAOg0AJIgGABQhFgEgRgLgArqFRQgMgzA9gnQA9gnANgKIAOgLQBAg3BKAAQAPAABngPQBYgNAggCIAAAAIgBAPQAAAMAPASQAIAJAIAFQgeAggeAUIhbA7QgRAbhRAgQhPAfhmANQgVACgRAAQhCAAgJgogAHwBoQhsgTgTgNQgSgNgrgLQgsgKgUgDIgegDIgOgBQAYgzAAgQQAXgBAzgMQAxgMA5gKQA0gPCXAAQCJAAAFApQAEAphKA+Qg5AyhOAAQgXAAgZgEgAmKAxQijAAg1gNIgigKIgcgIQgZgIgLgOQgMgQgGgkQgGglAngqQAmgoBWgKIAJgBIAVgDIBxATQBPAaBbBCQBMA2ATALQgEADgDAEIgDADIgLAMIgNATIgKASIAAAAIgBACIAAAAIgBABgAh3g4QiviYAAhnQAAg5AZgSQAVgPA+AAQBBAAAlBVQAeBFACA1IAEBvQgZAKgXANIgRAKIgGgGgACphWIgNgFIgCgBQAwhFArgrQAbgbBhhVQBbh4CTAAQAlAAAjAPQAoARAAAZQAAApg7A7QguAugZAMIixBJQgwAThJAaQg+AUgfAMQgMgIgRgHgAAJjxQAFgXAAgMQAFgPAAgFIAAgDQAAhBA3hNQA5hQA4AAQAZAAAPAQQAOAQAMAsQAEAxhECXQgvBogZAnQgVgEgTAAQglAAgjAHIAEiOg");
	this.shape.setTransform(75,52.3);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,150,104.5);


// stage content:
(lib.flower1CJS = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFF00").s().p("AixAxQCHi4DuA4QkABBhSBIQgnAjgKAAQgMAAAagsg");
	this.shape.setTransform(379.1,110.5);

	this.colorMe = new lib.flower();
	this.colorMe.setTransform(380.6,108.4,1,1,0,0,0,75,52.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FFFF00").ss(1,1,1).p("ACahcQAwhFArgrQAbgbBhhVQBbh4CTAAQAlAAAjAPQAoARAAAZQAAApg7A7QguAugZAMQh0Awg9AZQgwAThJAaQg+AUgfAMQgMgIgRgHQgGgDgHgCQgBAAgBgBgAhxgyQgDgDgDgDQiviYAAhnQAAg5AZgSQAVgPA+AAQBBAAAlBVQAeBFACA1QABA2ADA5QgZAKgXANQgIAFgJAFgAjPAxIi7AAQijAAg1gNQgSgEgQgGQgDAAgZgIQgZgIgLgOQgMgQgGgkQgGglAngqQAmgoBWgKQAEgBAFAAQAKgBALgCIBxATQBPAaBbBCQBMA2ATALQgEADgDAEQgBABgBACAAFhjQAEiCAAgMQAFgXAAgMQAFgPAAgFQAAgBAAgCQAAhBA3hNQA5hQA4AAQAZAAAPAQQAOAQAMAsQAEAxhECXQgvBogZAnQgVgEgTAAQglAAgjAHgADggkQAXgBAzgMQAxgMA5gKQA0gPCXAAQCJAAAFApQAEAphKA+QhKBBhtgTQhsgTgTgNQgSgNgrgLQgsgKgUgDQgSgCgMgBQgJgBgFAAQAYgzAAgQgAClBJQAZADAZAJQAyAQBFAeQCbBEAAA6QAABVh2AqQglAOg0AJQgDABgCAAQhGgEgRgLQgDgCgCgBQgOgIgHAAQgEAAgZgXQgEgDgFgEQgggdgIgOQgBgBgDAAQgOgdgHgVQgHgUAAgLQAAgMgKgXQgKgXAAgaIARgHIAKgFIABABIAXgNQAHgEAlgSQASgIASgQgAgNCfQgKAlAAAxQgBAMAAAMQAABfhkA/QhPAyhNAcQhNAbgZgQQgagQAxhCQA6h9ACgCQAVgwB6hbQABABABAAQAPABAXACQBAgFAngIgAikgKQgDADgDADQAAABAAAAQgGAEgGAIQgHAIgGALQgBABAAABAjNAuQgBABAAABIAAAAIgBABAjLChQgeAggeAUQg2AjglAYQgRAbhRAgQhPAfhmANQhmANgLgzQgMgzA9gnQA9gnANgKQAMgJACgCQBAg3BKAAQAPAABngPQBYgNAggCIAAAAQgBALAAAEQAAAMAPASQAIAJAIAFgAjbBGQAHgLAFgK");
	this.shape_1.setTransform(380.7,108.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFCC00").s().p("AiVCIIgCAAIgcgCQgKAAgJgFQgIgFgHgKQgQgRABgMIAAgPIAAAAIADgKIAEgHIAGgNIABgCIANgVIAAgCIABgBIAAgBIADgEIAGgJIABgCIANgUIAEgFIAEgDIAFgGIABgDIAFgEIADgCIAZgVIAWgQIARgKQAYgOAYgJQAbgLAagGQAjgGAlAAQATAAAVADQASAEATAHIACAAIAOAGQARAHALAHQAbARgBASQABAQgZA1QgRAXgSARQgRAQgTAJIgrAWIgjAQIgQAIIgBAAQgGAEgJADQgNAFgTAEQgnAIhAAFIgmgEgAikgkIAGgHIgGAHg");
	this.shape_2.setTransform(380.2,111.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#FFFF00").ss(1,1,1).p("AjeBnIAAgBQgHgKAAgHQAAgEACgLIAAAAQABgFABgFQADgEABgCQADgIADgGQABgCABgCQAeg8A1gqIAAAAQALgIAMgIQAIgFAJgFQAXgOAYgJQAbgLAagFQAjgIAlAAQATAAAVAFQASADAUAHQAAAAABAAQAHADAHACQARAIALAHQARALAGALQAEAHAAAGQAAABAAABADihSQACAIACAHQgBAKgIAWAA9BlIgHADAAVB3QgMAEgRAEQgnAIhAAFQgWgDgQgBQgBAAgBAAQgUgBgIAAQgKAAgJgGQgIgFgIgJQgFgHgDgFAjJCKQgPgZgGgK");
	this.shape_3.setTransform(380,111.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006600").s().p("AgyJAQhxiaAejQQAejQAkhSQAkhUAfhnQAfhoAAg6QAAg6gJgaQgJgbgygEQg0gDg5gSQg4gSgWgkIgegwIAJAMQAIAJAHAFQAFADAFABQAFACAFAAIAcABIACAAIAmAEQBAgFAmgIQAVgEANgFIAIgEIAGgDIAAAAIAbgMIAAAAIABABIAFgEIASgJIAsgWQASgJARgQQASgRARgYIADgFQAEA0gIAbQgMAlgPAfQgPAegZAUQgYAUANBBQAOBCgiBnQgjBogYA6Ig2CJQggBNgOBBQgNBCgDB1QgDB1BbCYQBZCYCygUIgGAIQgWAcgKAZIgCAEIgBAEQiYgrhviag");
	this.shape_4.setTransform(381.9,188.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#044103").s().p("AhfJ9QhbiYADh1QADh2AOhBQAOhCAfhOIA4iHQAYg6AjhoQAhhngOhCQgNhCAXgTQAZgUAPgeQAPgfAMgmQAIgagEg1QAVguABgQIAEAbQAHBEgKAfQgMAmgPAfQgOAegZAUQgZATAPBBQAOBBgaBbQgaBbgcBIIg+CUQggBOgOBCQgOBBgGB2QgFB1BYCPQBWCPCcgTQAYAAgXAgQgVACgUAAQiSAAhRiGg");
	this.shape_5.setTransform(390,182.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFCC00").s().p("AiVCIIgCAAIgbgCQgLAAgJgFQgIgFgHgKIgJgLIAAgBQgHgKAAgHIABgPIAAAAIADgLIAEgGIAGgNIACgEQAeg8A1gqIAAAAIAXgQIAQgKQAYgOAYgJQAbgLAagFQAjgIAlABQATAAAVADQASAEATAHIACABIANAEQASAIALAHQARALAGALQAEAHgBAHIAAABIgDgPIADAPQAAAKgJAWIgDgbQgBAQgVAuIgDAEQgRAYgSARQgRAQgSAJIgsAWIgSAJIgGADIAAgBIgbANIAAAAIgGADQgMAEgRAEQgnAIhAAFIgmgEg");
	this.shape_6.setTransform(380,111.6);

	this.addChild(this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.colorMe,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(579.8,254.9,152,211.4);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;