(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 200,
	height: 200,
	fps: 12,
	color: "#FFFFFF",
	manifest: []
};



// symbols:



(lib.Symbol2 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AHtH3QgOgDgJACQgKABgFgBQgGgCglABQgmABg/gSQg/gSgigRQghgQgjghQgighgNgRIgmgvQgagggFgQQgGgPgKgKQAygxAFgXQABgFAAgJQANAkBBBhQBABiC6ArQgPAVA+ApQAaAJAWAOgAkMh8IgGgHQgSgYgNgbQh5iTgqhKQgeg2AHgiIAEgMQgPBQBwBtQCbBmgDALQgDALBqBLIgEAJIAAAjQAAAZADAaQhWgwgug4g");
	this.shape.setTransform(49.4,50.4);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,98.8,100.8);


(lib.frog = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(1,1,1).p("AXhHMQh8hzg4gQQg5gQhsgRQhsgQghAAAs1z1QAaAXAhAzQAcAuApAKQAPAEBWAcQAeAKAaAGQAZAHAUADQAGACAHAAQBLALCpAKQCyAKBFAJQDTAaEGBBQEvBKCRBLQCQBLCxCjQC0CnCcDLQCoDZBhDRQBrDoAAC3QAAAWAIAmQABAEACAGIABAAQAABOAKCEQAAAlgIApQggAugMAQQgMAQgTAIQgSAIhZAIQgMABhWATAFUSVQAMAEANADQAbAHAfAGQBMARBhAKQC1AUD9AAQCNAAAUgCQAfgECPgYQACgBADAAQAagEAdgIQACAAASgHQADgBAEgBQAJgCAIgDQAQgDAPgDQBEgSAcgHQAfgHAdgHQAWgEATgEIAmgFQBjA3gdAKQhVBRleA2QhVANhRAJQAAAAgBAAQjCAXipAAQhBAAiBAUQi+AcgLACIgtAKQhkAegtAAQgRAAgXgUQA8gfBxgaQA0gMBlgUQAZgGAdgFIgKgKIhkAAQgoAFggAEQgdADgXADQgRACgPACQgCAAgDABQgzAGgmACQgjACgZAAQhRgDg6AaQg8AmgmATIgUAAQAmhoCZghQAvgJBMgJQAmgEAugEQASgCATgCQAZgCAbgBQgdgFgZgDQgUgDgRgCQgZgDgTgCQgZgCgPAAIAPAAQAAgEgLgCQgBAAAAAAQgBAAgBAAQgCAAgCAAQgBAAgBAAIgBAAQgJAAgPAAQgtADhZANIj4AtApcsPQAiAWBPAjQBqAwC8BHQFnCrBqBMQBqBNDGCbQDHCbCFCiQA7BIA4ATAQpEeQgUAEgagKQl8ANkmCdQheAyhEA7QgoAigeAlQhXBpAABuQAACfCRBeAyxxEQAPgFAOABQAFAAAGAAQAUgBATgBQAOgBANAAQA6ABBYAzQA3AhAmAnQAUAVAPAWQACACABACQAsBDApgBIAAAAQBlA8AXAOQgBgBgCAAQAEADAEADAs1z1QALAWAGATA0j0iQAfgXBMg+QBTg8A6AAQB2AAA/BCQAnApAaBTAphsUQADABACAEA+0yHIBaAAQApAGD5A5QD4A5AagUQAZgTA5gJQASgDARgCQAUgCAUgCA0j0iQAIACAFADIAKAAA0W0dIgUAAQADgCAEgDA+0yHQAGgNAKgLQBChUC6gBQC5AABqghQBEgUAeAHA+8xsQADgOAFgNA+8xsQAaCBH2E6AyNgzQjFhuhqiAQgHgIgHgKQgrg3gcg9QkWlQhgiqQhHh9AShOAtSkrQACAFACAFQAkBnA7DdQBHESgLAzQgLA0hzByQg4A3hSA+QhUA/hhA8QgoAZgZAOQiQBTgMBvQgNBvgrB2IgHACQgIADAAAHQgYgeAEgwQADgxAIhtQALhLg7gRQhHAWhbAgQhcAgidApQAAgEgIgEQgHgEAAgRQgBgeCqg9QDbhOAEgCQhXgPhxhEQifguAMgxQAegIBCAPQBCAOBKAlQBJAlA9AAQAxAADKiOQAVgPAXgQQBWhQB7h7QhSgtg1i6QgchkgKhhQAAgBAAgCQgHg7AAg7IAAhQAtKkrQgIgLgJgMQAEALAFAMQAEAAAEAAQAKAAAKAAAtnlTQAEAGAEAFQACAEACACAtKkrQBfCBBlBwQF4GhHFDIQAMAGAMAFAEZSBIAAAAQghgIgVAEQgWADgNgDQgNgEhVACQhWACiPgpQiRgohNgnQhNgmhPhMQhPhMgeglQgeglg6hJQg6hJgNgjQgNgkgXgWAi0UZQhEAigagBQgbgBgVgIQgWgIAWgfQBEgqDpgqQCKgZBNgIQAGgBAGAAQAGgBAFAAQABAAACAAQARgBANAAQAGAAAQAAQADAAAEAAQABAAAAAAQALABAOAAQgMgKgMgIIAAAAQAcALAfAJQgUgBgPgBAEZSBQg/gYgvgfQA8AWAyAhg");
	this.shape.setTransform(198.5,146);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#CCCCCC").s().p("AL8SEQghgHgVADQgWADgNgDQgNgEhVACQhWACiRgoQiRgphNgmQhNgnhNhMQhPhMgeglIhYhuQg6hJgNgjQgNgjgXgXQBzhyALgzQALgzhIkSQg6jeglhmIgDgKQi1huiDCCIgKAeIAABQQAAA7AGA7QjFhvhph/IgOgSQgrg3gcg9QkWlRhgiqQhHh8ARhPQAbCCH2E6Qn2k6gbiCQADgOAGgMIBaAAQApAFD5A5QD4A5AagTQAZgTA5gKIAjgFIAogEIAngCIAbAAQA6AABYA0QA3AhAmAnQAUAUAPAXIADADQArBDAqgBIAAAAIB8BKIgDAAIAIAFQAiAWBPAkQBoAvC8BIQFpCqBqBMQBpBNDHCcQDGCaCGCiQA6BIA5AUQl8AMkmCdQhfAzhEA7QnHjJl1mgQhlhxhfiAIAUAAIgUAAIgRgXIAJAXIAIAAQBfCABlBxQF1GgHHDJQgnAhgeAlQhXBpAABuQAACfCRBeQAvAfA/AYIAAAAgAl8lEIAEAGIgEgGIgIgLIAIALg");
	this.shape_1.setTransform(150.2,145.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#999999").s().p("ADRWfQA8geBxgaQA0gMBlgVIA2gLIgKgJIhkAAIhIAJIg0AGIggAEIgFABQgzAGgmACQgjACgZgBQhRgCg6AaQg8AmgmASIgUAAQAmhnCZghQAugJBMgJIBVgIIAlgDIA0gFIg2gHIglgFIgtgFIgngDIAPAAQAAgDgMgCIAAAAIgCAAIgEAAIgDAAIAAAAIgYAAQgtADhZANIj4AsQgWAFgEAGQgEAFAggQQhEAjgagBQgbgBgWgIQgVgIAWgfQBEgpDpgrQCKgZBNgIIAMgBIAKgBIAEAAIAegCIAWABIAHAAIABAAIAZABIAjACIAZAHQAbAHAeAHQBNAQBhAKQC1AUD9AAQCNgBAUgBQAfgECOgYIAGgBQAagEAdgIIAUgHIAHgCIARgEIAfgHIgWAGQBjgTATgMIA8gNIApgJIAmgGQBjA4gdAJQhVBRleA2QhVAOhRAJIgBAAQjCAWipAAQhBAAiBAVIjJAeIgtAJQhkAegtAAQgRABgXgVgA2vSJIAMidQALhLg7gRQhHAWhbAgQhcAgieApQABgEgIgEQgIgEABgSQgBgdCqg9QDbhOAEgDQhXgOhxhEQifguAMgwQAegJBCAOQBCAPBKAlQBJAlA9AAQAxAADKiPIAsgeQBWhQB7h8QhSgsg1i6QgchkgKhhIAAgDQgHg7AAg7IAAhQIAKgeQCDiBC1BuIADAJQAlBnA7DdQBHESgLAzQgLA0hzByQg4A3hSA+QhUA/hhA8IhBAnQiQBTgMBvQgNBvgrB2IgIACQgHADAAAHQgYgeADgxgAQATYQj9AAi1gUQhhgKhNgQQgegHgbgHIgZgHQgfgJgcgLQgyghg8gWQiRheAAigQAAhtBXhpQAeglAogiQBDg7BfgyQEmidF8gNQAaAKAUgEIBfAKQhsgQghAAQg5gTg6hIQiFiijHiaQjHichphNQhqhMlniqQi8hIhqgwQhPgjgigWQgCgEgDgBIh8hKIAAAAQgpABgshDIgDgEQgPgWgUgUQgmgog3ggQhYg0g6gBIgbABIgnACIgLAAQgOgBgPAFIgjAFQg5AJgZATQgaAUj4g5Qj5g5gpgGIhaAAQAGgNAKgLQBChUC6gBQC5AABqggQBEgVAeAHQAfgXBMg9QBTg9A6AAQB2AAA/BCQAnApAaBTQAaAXAgAzQAdAuApALQAPADBWAcIA4AQQAZAHAUADIAMACQBMAMCpAKQCyAJBFAKQDTAZEGBBQEvBLCQBKQCRBMCxCjQC0ClCcDMQCoDaBhDPQBrDpAAC2QAAAXAIAlIADAKIABAAQAABPAKCEQAAAlgIApIgsA+QgMAQgTAIQgSAIhZAIQgMABhWATIgpAJIg8ANIhgAZIgfAHIgRAEIgHACIgUAHQgdAIgaAEIgGABQiOAYgfAEQgUABiNABIAAAAgADJI6IgYgLIAYALgAUnFJQA4AQB8ByQh8hyg4gQQg5gQhsgRQBsARA5AQgArGwJQAAABgBAAQAAAAAAABQgBAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABABAAQAAABAAAAQAAAAABABQAAAAABAAQAAAAABAAIBiAWIAhAIIBOASQAUAFgCAGQB6AcBMAdQFHBdEFCDQH+DXFmFfQENDLC9EeIgJAGIAJgGIADACQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAgBQAAAAABAAQAAgBAAAAQABgBAAAAQAAAAAAgBQAAgBAAAAQAAAAAAgBQAAAAAAgBQAAAAgBgBQmYporTmBQnFjUoniJIhDgQIiPghIgBAAIgDABgAsqzMQgGgTgLgWQALAWAGATgA0w0cIAUAAIAKAAIgKAAQgFgEgIgCIgHAGg");
	this.shape_2.setTransform(199.1,146);

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-1,-1,399.1,294);


// stage content:
(lib.frogCJS = function() {
	this.initialize();

	// Layer 4
	this.instance = new lib.Symbol2("synched",0);
	this.instance.setTransform(63.7,89,1,1,0,0,0,49.4,50.4);
	this.instance.alpha = 0.379;

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(2.8,1,1).p("ABIACQhTgrg8A6");
	this.shape.setTransform(53.6,45.7,0.436,0.436);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgiBYQg3gXgdgpQgegnAPglQAPglAxgKQAygKA2AXQA3AWAeApQAdAogPAkQgPAlgxAKQgQADgQAAQgkAAgkgPg");
	this.shape_1.setTransform(54.5,47.1,0.436,0.436);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#FFFFFF").ss(2.8,1,1).p("AgngFQAWgEAMAAQAPAAAGAFQANAJALAG");
	this.shape_2.setTransform(54.9,46.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#333333").ss(0.3,1,1).p("AACAAIgDAA");
	this.shape_3.setTransform(51.7,41.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#333333").ss(1,1,1).p("AgYhBQAcgCApAVQAAABAEADQAFADAJAGQAJAGAHAFQAGAFADAEQABAAAAABQAQAdgHALQgHAKgMAKQgLAKgWAHQgVAGg8gdQg9gdgDgaQgCgbAOgKQAPgLAHgBQAGgCANgBQAMAAAFAA");
	this.shape_4.setTransform(54.5,47.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgjAqQg9gdgDgZQgCgcAOgKQAPgLAHgBQAGgCANAAIARgBIAFAAQAcgCApAVIAEAEIAOAJIAQALQAGAFADAEIABABQAQAdgHALQgHALgMAKQgLAJgWAHIgJABQgXAAgxgYgAAUgWQANALALAGQgLgGgNgLQgGgFgPAAQgMAAgWAEQAWgEAMAAQAPAAAGAFg");
	this.shape_5.setTransform(54.5,47.8);

	this.colorMe = new lib.frog();
	this.colorMe.setTransform(100.8,89.1,0.436,0.436,0,0,0,198.5,146);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#666666").ss(1,1,1).p("AhBgYQAJgBAIAAQAGgBAGAAQAZAAAkAXQAZANAQAR");
	this.shape_6.setTransform(56.4,43.9);

	this.addChild(this.shape_6,this.colorMe,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(114.1,125.3,173.4,127.7);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;